### ISSUE TITLE
[MouseButton] Chain do_action, open_url fail

### ISSUE THREAD

**Issue by biopsin** [dunst-project/dunst#1001]
### Issue description
In v.1.6.1 the "do_action" handles both notifications containing one "url" or "-A",
```
  dunstify "Site" "<a href=\"https://somesite\"></a>\nsome"
or
  ... && [ dunstify -A Y,"Load" "Data" = Y ] && ...
```
In v.1.7.x the "open_url" is added, however its not possible to chain 
`= do_action, open_url` (or other way around) on a mouse button, and
handle both notifications in a random order. (Also related  to #1000 )
My liver suspect commit https://github.com/dunst-project/dunst/commit/0dfc4ed738c319daf8f35ba31a778dca1dae3705 skip on chainlogic ,but wait 
where did I put my head

### Installation info

- Version: `<!-- [1.7.3] -->`
- Install type: `<!-- [package|...] -->`
- Window manager / Desktop environment: `<!-- [Pekwm] -->`

<details>
<summary>Minimal dunstrc</summary>

```ini
    mouse_left_click = do_action, open_url, close_current
or
    mouse_left_click = open_url, do_action, close_current
    #1000  Bug https://github.com/dunst-project/dunst/issues/1000
```
</details>

**Comment by imsamuka** [comment]
I assume the following is the intended behavior (`do_action` from v.1.6.1):
* With 0 action and 0 urls: Nothing
* With 0 action and 1 urls: Open url
* With 1 action and 0 urls: Execute action
* Else: Open context


Chaining `open_url` and `do_action` (in the current version), would never have the same behavior: if we click a notification with 1 url and 1 action (e.g. `dunstify -A return,name Summary '<a href="/tmp"/>Body'`), the chained option execute **BOTH action and url**, and not open a context menu.

Also, currently (1.7.3-1 arch-community), chaining right now kinda works, but VERY badly:
* With x action and 0 urls: #1000
* With 0 action and 1 urls: Open url :+1: 
* **With 1 action and 1 urls: Open url AND execute action**
* With 1 action and 2 urls: The action is executed instantly, and the context menu opens showing the 3 entries. (the action entry does nothing)
* With 2 action and 1 urls: The url opens instantly, and the context menu opens showing the 3 entries (and we can open the url a second time).
* With 2 action and 2 urls: The context menu opens 1 time (dunst outputs `WARNING: Context menu already running, refusing to rerun`)

I think the only solution is to create another option, to do the intended behavior after all. Maybe `act_url`, `do_both`, `run_both`, or something like that.

**Comment by fwsmit** [comment]
I don't think we should mess with chaining `open_url` and `do_action`, since that would complicate the logic in dunst. 

So I gather from this that you want an option that doesn't differentiate between actions and URL's. It shouldn't be too hard to add, but I think the name is pretty important, since by that time we have 4 options for interacting with url's and actions. I would prefer the longer name `action_or_url`.
It would also be possible to add an option to modify one of the existing actions like `do_action` to make it do either the current behaviour or the suggested behaviour (which is apperently the old behaviour?).

**Comment by imsamuka** [comment]
> I don't think we should mess with chaining open_url and do_action, since that would complicate the logic in dunst.

Exactly, also if someone chain these together, `open url AND execute action` should be the intended behavior. But also think the logic for (actions x urls) in (1x2, 2x1, 2x2), should be fixed some time. (i hope this syntax makes sense :smiley:)

> It would also be possible to add an option to modify one of the existing actions like do_action to make it do either the current behaviour or the suggested behaviour (which is apperently the old behaviour?).

I think this would add unnecessary complexity, and be less useful than a new option.

I like the name `action_or_url` very much, it's intuitive and not so long. The ones I suggested are very imprecise in comparison.

**Comment by biopsin** [comment]
Switching from 1.6.1 to 1.9.0 and after the open_url fix, seems doing the following 
`mouse_left_click = open_url, do_action, close_current`
at any random notification with either 1 url or 1 action work fine for me now.

Im closing this issue, please reopen if otherwise.
Anyways thank you for the splendid work!
