### ISSUE TITLE
Escape key does not close active notifications

### ISSUE THREAD

**Issue by wgmayer0** [dunst-project/dunst#1005]
### Issue description
I am not able to use the escape key to close active notifications.

### Installation info

- Version: `<!-- output of dunst -v -->`
`$ dunst -v`
`Dunst - A customizable and lightweight notification-daemon 1.7.3 (2021-12-08)`

- Install type: `<!-- [package|manually|...] -->`
pacman

- Window manager / Desktop environment: `<!--  -->`
xmonad

<details>
<summary>Minimal dunstrc</summary>

```ini
# Dunstrc here
[global]

monitor = 0
follow = mouse
geometry = "500x200-30+20"
indicate_hidden = no
shrink = no
transparency = 0
notification_height = 0
separator_height = 2
padding = 8
horizontal_padding = 8
frame_width = 0
frame_color = "#000000"
separator_color = frame
sort = no
idle_threshold = 0
font = DejaVu 24
line_height = 0
markup = no
format = "<b>%s</b>\n%b"
alignment = left
show_age_threshold = -1
word_wrap = yes
ellipsize = middle
ignore_newline = no
stack_duplicates = false
hide_duplicate_count = false
show_indicators = yes
icon_position = off
max_icon_size = 32
icon_path = /usr/share/icons/gnome/16x16/status/:/usr/share/icons/gnome/16x16/devices/
sticky_history = no
history_length = 0
always_run_script = true
title = Dunst
class = Dunst
startup_notification = false
verbosity = mesg
mouse_left_click = close_current
mouse_middle_click = do_action
mouse_right_click = close_all

[urgency_low]
background = "#000000"
foreground = "#ffffff"
timeout = 0

[urgency_normal]
background = "#000000"
foreground = "#ffffff"
timeout = 0

[urgency_critical]
background = "#000000"
foreground = "#ffffff"
timeout = 0
```
</details>

**Comment by Narrat** [comment]
For various reasons global shortcuts got removed with `dunst 1.7.0` and can be replaced with the dunstctl cli.
See the `Removed` section for more information https://github.com/dunst-project/dunst/releases/tag/v1.7.0

**Comment by wgmayer0** [comment]
Ok what is the alternative. The nice thing about the escape key is that it only closed a notification if there was a notification present. If there wasn't, the escape key would function normally depending on which application was currently capturing input from the keyboard. I have looked all over online and it appears as if no one has found a solution to this problem. What was the purpose for disabling the escape key in dunst? I am not sure how to solve this...

**Comment by fwsmit** [comment]
You can combine the dunstctl call with a check to see if notifications are available. See #978.
