### ISSUE TITLE
Progressbar size not working

### ISSUE THREAD

**Issue by JosefLitos** [dunst-project/dunst#1006]
### Issue description
Minimum progressbar width doesn't make the notification wider when the message is shorter than the minimum, it just resizes to match the text.

Also, a feature request, would it be possible for us to change the color of the progressbar to sth else than the default? The shades really don't match my scheme.

**Comment by fwsmit** [comment]
> Minimum progressbar width doesn't make the notification wider when the message is shorter than the minimum, it just resizes to match the text.

Ok I'll take a look at it later.

> Also, a feature request, would it be possible for us to change the color of the progressbar to sth else than the default? The shades really don't match my scheme.

That's possible with the `highlight` option.

**Comment by fwsmit** [comment]
The min width is never used in the code currently. I implemented it now :)
