### ISSUE TITLE
Allow to build without dependency on X11, i.e. Wayland-only build

### ISSUE THREAD

**Issue by jirutka** [dunst-project/dunst#1008]
Currently, dunst can be built without Wayland support, but not the opposite – without X11. It’d be nice to provide this option.

**Comment by fwsmit** [comment]
Yeah that'd be cool. Shouldn't be too hard to do, I think. We already split the x11-specific code in it's own directory.

**Comment by LeCodingWolfie** [comment]
> Yeah that'd be cool.

Indeed. That should also get rid of X11 issues within Wayland. I've had [this issue](Issue) — for example, in which dunst was expecting an X11 display and completely crashed the daemon. It would evidently reduce _bloat_ of X11 when you're just using Wayland.

**Comment by bynect** [comment]
I dont think we are there yet, but maybe this can be added to the milestone @fwsmit

**Comment by bynect** [comment]
I made a pr making X11 optional. If someone with wayland could test if everything works (it should work) it would be great
