### ISSUE TITLE
Margin / spacing / gaps between notifications?

### ISSUE THREAD

**Issue by Octelly** [dunst-project/dunst#1011]
Is it possible to add some spacing between notifications?
I tried producing the desired effect with ``separator_color = "#00000000"``, but that doesn't quite achieve what I want.
![image](https://user-images.githubusercontent.com/29976879/148532990-a70aa024-1422-4b17-a278-8b9a13097a65.png)
``wired-notify`` supports this via a gap config setting if I recall correctly. It is also a popular feature among different tiling window managers such as AwesomeWM (``beautiful.useless_gap = 5``) or QTile (layout property ``margin=5``).

**Comment by fwsmit** [comment]
Needs #1018 before this can be implemented correctly.

**Comment by paddyw2** [comment]
I have implemented this feature for myself quickly, you can view the commit/diff here: https://github.com/paddyw2/dunst/commit/436613f0975a5686bdc028f6b46bb61247af036b 

It allows me to set these values in the config file:

```
[global]
    gaps = true
    gap_size = 10
```

Happy to clean it up and submit a PR, but it sounds like there's some code base refactoring planned first. So in the meantime you might want to try out the edits above and just build and install locally.

**Comment by fwsmit** [comment]
> 



> I have implemented this feature for myself quickly, you can view the commit/diff here: [paddyw2@436613f](https://github.com/paddyw2/dunst/commit/436613f0975a5686bdc028f6b46bb61247af036b)
> 
> It allows me to set these values in the config file:
> 
> ```
> [global]
>     gaps = true
>     gap_size = 10
> ```
> 
> Happy to clean it up and submit a PR, but it sounds like there's some code base refactoring planned first. So in the meantime you might want to try out the edits above and just build and install locally.

Cool. I'd be happy to accept it as a PR. It's a pretty small patch and when we implement multiple windows, it can be replaced in a backward compatible way. So I see no issues with adding it to master :)

**Comment by fwsmit** [comment]
What's good to think about for the PR is mouse clicking. I suspect that clicks in between the notifications are getting picked up by dunst. On top of that, the notification height calculation might be off, leading to the wrong notification being closed on click. This calculation should be fixed and it's probably best to ignore clicks that are in between notifications, since that can only really be fixed by multiple windows AFAIK.

**Comment by bynect** [comment]
I think this has been solved with the gaps option
