### ISSUE TITLE
Support regex matching in rules

### ISSUE THREAD

**Issue by levouh** [dunst-project/dunst#1013]
Is there a better way to ignore things based on `summary` for a given `appname` (yes I am aware that I should use `desktop_entry` instead) than:

```ini
[kdec_pushover_ignore]
    appname = "KDE Connect"
    summary = "Pushover"
    format = ""

[kdec_gmail_ignore]
    appname = "KDE Connect"
    summary = "Gmail"
    format = ""

[kdec_cal_ignore]
    appname = "KDE Connect"
    summary = "Calendar"
    format = ""

[kdec_ov_ignore]
    appname = "KDE Connect"
    summary = "Okta Verify"
    format = ""
```

For example, using a script based on the `appname` that just modifies the `format` like:

```ini
[kdec_ignore]
    appname = "KDE Connect"
    summary = "*"
    script = ignore.sh
```

where the script can use "better" pattern matching (basically just a bunch of `|` statements) and "return" `format = ""` (to ignore the notification) manually?

**Comment by fwsmit** [comment]
You cannot use a script to do this, but you should be able to do it the way you suggest inside of dunst. Dunst uses [`fnmatch(3)`](https://man.archlinux.org/man/fnmatch.3) for pattern matching a list of patterns. The pattern: `summary = @(one|two|three)"`  matches any string that contains "one", "two" or "three".

This should probably get documented better.

**Comment by levouh** [comment]
Definitely does, thanks.

**Comment by levouh** [comment]
@fwsmit Given that my notifications are coming through as:

```
appname=KDE Connect
summary=Gmail
```

which is captured using a script to just log every notification (skipping something like running `dunst` with `-print` mostly just to check the rule is happening), my rule is:
```
[kdec_ignore]
    appname = "KDE Connect"
    summary = "@(Pushover|Gmail|Calendar)"
    format = ""
```

and things are not being ignored as I would expect. Is the format there correct? I will modify the "logging" to check trailing whitespace, but I would expect these to be ignored?

I run `dunst` as a user service, and am restarting it to reload the configuration via `systemctl --user restart dunst`. I have also verified that once I kill it, there are no other instances running (and it is loading my other configuration so I know the configuration file is being read).

**Comment by fwsmit** [comment]
Whoops, read the fnmatch documentation incorrectly. Dunst calls fnmatch without flags, but you need the FNM_EXTMATCH flag to have the behavior. It's a gnu extension, so I'll have to look to see how we can enable it on certain platforms.

**Comment by fwsmit** [comment]
Looking into this, I found this PR: https://github.com/dunst-project/dunst/pull/659, which implements said feature, but it was decided it was not the right solution. Regex was deemed as the more correct solution. I'll look into how that could be implemented right now. I'll make a tracking issue to consolidate the different issues about this.

**Comment by levouh** [comment]
Sounds good, want me to close this one?

For what its worth, being able to filter using a script (perhaps return an exit code) could also be relatively agnostic to how the user wants to do it. Could be (potentially) less work on the `dunst` side?

**Comment by fwsmit** [comment]
> Sounds good, want me to close this one?

No, you can keep this open. I'll close it when regex is implemented.

 
> For what its worth, being able to filter using a script (perhaps return an exit code) could also be relatively agnostic to how the user wants to do it. Could be (potentially) less work on the `dunst` side?

That's a possibility, but it would be easier for the user to use regex of course. For more advanced use cases which will never be supported by dunst this would be an option.

**Comment by fwsmit** [comment]
@levouh I've implemented regex in #1017. Would you mind testing it?

**Comment by levouh** [comment]
Will do!

**Comment by levouh** [comment]
It would look something like:

```
[kdec_ignore]
    appname = "KDE Connect"
    summary = "Gmail|Slack"
    format = ""
```

and not:

```
[kdec_ignore]
    appname = "KDE Connect"
    summary = "Gmail\|Slack"
    format = ""
```

right?

**Comment by levouh** [comment]
Actually looks like the commit has docs, let me read those.

**Comment by fwsmit** [comment]
> @fwsmit it would look something like:
> 
> ```
> [kdec_ignore]
>     appname = "KDE Connect"
>     summary = "Gmail|Slack"
>     format = ""
> ```
> 
> and not:
> 
> ```
> [kdec_ignore]
>     appname = "KDE Connect"
>     summary = "Gmail\|Slack"
>     format = ""
> ```
> 
> right?

yes



> Actually looks like the commit has docs, let me read those.

also yes :)

**Comment by fwsmit** [comment]
I opted for the extended syntax, as I don't think you will often need to match the special characters literally.

**Comment by levouh** [comment]
Works perfectly for me, tried a handful of regex things like `[]`, `[^]`, `.*`, etc.

Also verified that the old syntax for `*` replaced with `.*` works as intended.

Thanks for the feature!

**Comment by fwsmit** [comment]
> Works perfectly for me, tried a handful of regex things like `[]`, `[^]`, `.*`, etc.
> 
> Also verified that the old syntax for `*` replaced with `.*` works as intended.
> 
> Thanks for the feature!

Cool. I'll add error messages for incorrect regex patterns and then I'll merge it.

**Comment by fwsmit** [comment]
Merged!
