### ISSUE TITLE
Is it possible to prevent a program from sending notifications ?

### ISSUE THREAD

**Issue by ThomasTraineau** [dunst-project/dunst#1024]
Some programs send notifications and we don't necessarily have access to their configuration, would it be possible to make dunst block those notifications ?

**Comment by fwsmit** [comment]
Yes, you can use skip_display (and skip_history) for that

**Comment by ThomasTraineau** [comment]
Thanks for your answer ! How can I use skip_display if I want to hide the notifications from firefox for example ?

**Comment by fwsmit** [comment]
You'll need to make a rule to match that application. You can take a look at the man page `dunst(5)` and the example dunstrc for more information. If you have any questions afterwards, I'm happy to help.

**Comment by ThomasTraineau** [comment]
Yea I had a look but I can't find a configuration example, that's why I asked :)

**Comment by ThomasTraineau** [comment]
Yea I had a look and couldn't find any example, that's why I'm asking :)

**Comment by fwsmit** [comment]
We are indeed missing some documentation with examples regarding rules. It would be nice if you added some on the wiki once you understand it yourself

**Comment by ThomasTraineau** [comment]
Thanks for the explanation !
