### ISSUE TITLE
`show_age_threshold` defaults to wrong value

### ISSUE THREAD

**Issue by fabionatali** [dunst-project/dunst#1029]
The value of `show_age_threshold` is documented as defaulting to `-1` (e.g. see [here](https://github.com/dunst-project/dunst/blob/master/docs/dunst.5.pod)) but it seems to me that it's actually set to `60` (e.g. see [here](https://github.com/dunst-project/dunst/blob/1c3876b16e36c830fe6d194a9ed4484d2a40c5e8/src/settings_data.h#L847)).

**Comment by fwsmit** [comment]
Thanks, I've fixed it. I've also fixed it for some other settings.
