### ISSUE TITLE
Pushover Image Attachment

### ISSUE THREAD

**Issue by mattyrc** [dunst-project/dunst#1050]
### Issue description

I use pushover to send me a notification from my security cameras at home.  The notification contains a snapshot from the camera that is sent via pushover as an attachment.

 Is it possible to display these attachment images in Dunst? 

On android, the attachment displays just below the body.

Thanks

### Installation info

- Version: `v1.8.1`
- Install type: `pacman -s dunst`
- Window manager / Desktop environment: `Arch`

<details>
<summary>Minimal dunstrc</summary>

```ini
# Dunstrc here
```
</details>

**Comment by fwsmit** [comment]
The answer is probably yes. To help you further I need some more information. Please send the output of `dunst -print` from when pushover sends a notification. This way I can see how the icon is sent to dunst (if at all). You might need to `pkill dunst` before running another instance.

**Comment by mattyrc** [comment]
Sure thing.

Output of 'dunst --print':

```
{
	appname: 'qutebrowser'
	summary: 'Porch - Motion!'
	body: '<a href="https://client.pushover.net/">https://client.pushover.net/</a>

Motion detected on the Porch.'
	icon: '(null)'
	raw_icon set: true
	icon_id: 'fc82ec95c9690cf654bf5d2e191b0cb4'
	desktop_entry: 'org.qutebrowser.qutebrowser'
	category: 
	timeout: 10000
	urgency: NORMAL
	transient: 0
	formatted: '<span size='large' foreground='#cfa58e' weight='ultrabold'>Porch - Motion!</span>
<b>https://client.pushover.net/

Motion detected on the Porch.</b>'
	fg: #f6ffff
	bg: #051319
	highlight: #cfa58e
	frame: #051319
	fullscreen: show
	format: <span size='large' foreground='#cfa58e' weight='ultrabold'>%s</span>\n<b>%b</b>
	progress: -1
	stack_tag: 
	id: 3
	urls:
	{
		[https://client.pushover.net/] https://client.pushover.net/		
https://client.pushover.net/
	}
	actions: {
		"default": "Activate"
	}
	script_count: 1
	scripts: '/home/matt/.scripts/dunst/dunst-sound.sh' 
} 
```
I'm using Qutebrowser with the client.pushover.net tab open for the notifications.

The icon that is being displayed is a png that was uploaded as the app icon in the pushover dashboard.

The 'dunst-sound.sh' script that I'm using is only to play an audio notification sound.

**Comment by mattyrc** [comment]
For reference, here is what the notifications look like:
Dunst:
![dunst_pushover](https://user-images.githubusercontent.com/3344929/158887986-cf2c3fea-7d90-4962-829f-dcecbd542391.png)

Android:
<img src="https://user-images.githubusercontent.com/3344929/158888032-2cf16810-9e6f-414a-ba31-64c23b85f84f.png" width=50% height=50%>

**Comment by fwsmit** [comment]
It seems like only the house icon is sent to dunst. You'll need to make sure the website sends a different icon then. Note that dunst can only show one icon currently, so it will have to replace the house.

**Comment by fwsmit** [comment]
@mattyrc Have you found a satisfactory solution. If so, would you like to share it so others can benifit?

**Comment by mattyrc** [comment]
Unfortunately I haven't found a solution. It was my understanding from the reply that this would need to be handled by the Pushover service and not Dunst.

**Comment by progandy** [comment]
> Unfortunately I haven't found a solution. It was my understanding from the reply that this would need to be handled by the Pushover service and not Dunst.

They do allow for custom clients with their "Open Client API", so you could write your own to replace the official one. There are some clients and libraries available on e.g. github as a starting point.
