### ISSUE TITLE
Bug with action_name ?

### ISSUE THREAD

**Issue by PiCkLeS76** [dunst-project/dunst#1051]
### Issue description

I have this configured in dunstrc :

//--cut-//

 mouse_left_click = do_action
 mouse_middle_click = close_all
 mouse_right_click = close_current

//--cut--//

[niclas_test] # Test rule for action_name
    summary = "\*test\*"
    action_name = "no"

//--end--//

And if I run something like this:

dunstify --action="yes,YesAnswer" --action="no,NoAnswer" "Response test notification"

.. and I add format = "" to that rule I can see that the rule itself works fine, it hooks into that dunstify-test-notification correctly. Ie, it wont show. Also, if I left-click on the notification, I get the default behaviour of do_action in that it doesnt have a default action and it has more then one, so the context menu opens. (I have dmenu correctly setup so I get the context-menu correctly). 

Now. If I define action_name = "no" as above, I thought that the behaviour would be to use the action defined as --action="no,NoAnswer" on the left-click of the mouse but it does'nt. 

Furthermore I get this when starting dunst manually in a console:

WARNING: Setting action_name in section niclas_test doesn't exist

Is this a bug or am I just stupidly misunderstanding how this works or how it should be correctly defined in dunstrc? I have read the man pages and all the dunstrc's I can find to no avail.

Thank you,

Niclas

### Installation info

- Version: Dunst - A customizable and lightweight notification-daemon v1.8.1-10-g96cfb2f
- Install type: manually (github clone + make install)
- Window manager / Desktop environment: i3wm

<details>
<summary>Minimal dunstrc</summary>
 mouse_left_click = do_action
 mouse_middle_click = close_all
 mouse_right_click = close_current

//--cut--//

[niclas_test] # Test rule for action_name
    summary = "*test*"
    action_name = "no"

```ini
# Dunstrc here

[global]

    monitor = 0

    follow = mouse

    width = (300, 600)

    height = 300

    origin = top-right

    offset = 30x30

    scale = 0

    notification_limit = 0

    progress_bar = true

    progress_bar_height = 10

    progress_bar_frame_width = 1

    progress_bar_min_width = 150

    progress_bar_max_width = 300

    indicate_hidden = yes

    transparency = 0

    separator_height = 2

    padding = 8

    horizontal_padding = 8

    text_icon_padding = 0

    frame_width = 2

    frame_color = "#f1800e"

    separator_color = frame

    sort = yes

    idle_threshold = 0

    font = Monospace 12

    line_height = 2

    markup = full

    format = "<b>%s</b>\n<i>%b</i>\n\n%p___\n"

    alignment = left

    vertical_alignment = center

    show_age_threshold = -1

    ellipsize = middle

    ignore_newline = no

    stack_duplicates = true

    hide_duplicate_count = false

    show_indicators = no

    icon_position = left

    min_icon_size = 0

    max_icon_size = 32

    icon_path = /usr/share/icons/Adwaita/16x16/status/:/usr/share/icons/Adwaita/16x16/devices/:/usr/share/icons/hicolor/22x22/apps/:/usr/share/icons/Adwaita/16x16/legacy/:/usr/share/icons/hicolor/22x22/legacy/

    sticky_history = yes

    history_length = 20

    dmenu = /usr/bin/rofi -dmenu -p dunst:

    browser = /usr/bin/google-chrome-beta

    always_run_script = true

    title = Dunst

    class = Dunst

    corner_radius = 20

    ignore_dbusclose = false

    force_xwayland = false

    force_xinerama = false

    mouse_left_click = do_action
    mouse_middle_click = close_all
    mouse_right_click = close_current

[experimental]
    per_monitor_dpi = false


[urgency_low]
  background = "#43464B"
    foreground = "#ffffff"

[urgency_normal]
   background = "#43464B"
    foreground = "#ffffff"
    timeout = 30

[urgency_critical]
   background = "#900000"
    foreground = "#ffffff"
    frame_color = "#ff0000"
    timeout = 120

[niclas_test]    
    summary = "*test*"
    action_name = "no"
    
[ignore_bt1]
    appname = "*Bluetooth Authentication*"
    format = ""

[ignore_bt2]
    summary = "*Galaxy*"
    format = ""

[ignore_bt3]
    summary = "*PulseEffects*"
    format = ""

[ignore_wifi]
    summary = "*Connection Established*"
    format = ""

[history-ignore]
    summary = "*Volume*"
    history_ignore = yes
    summary = "*Brightness*"
    history_ignore = yes
</details>

**Comment by fwsmit** [comment]
It seems that `action_name` has been accidentally dropped, so it's not working at all. I've added it back in in the commit linked above. Could you see if it works now as expected?

It's been implemented and discussed in: #848

**Comment by PiCkLeS76** [comment]
Ah, well that would do it. I thought I was stupid - it did'nt even occur to me to check the source. Sorry about that.

Thank you for the quick response - I can confirm that everything is not working as expected.

//N

**Comment by fwsmit** [comment]
Great, thank you for testing
