### ISSUE TITLE
Feature request: allow command\script execution on mouse click

### ISSUE THREAD

**Issue by purpleleaf** [dunst-project/dunst#1056]
Mouse click can activate "Actions", why not allow also script execution?
For example, i have a notification that shows available package update, and on arch also 2 or 3 days can lead to hundred of updates.
Obviously not all the update can fit in the notification window.
With a configurable mouse click it should be possible open the notification body in another applications.
This particular problem should be solved with a scrollable notification (i read in another issue that scrollabars are not a viable solutions, may be only scrolling with arrows or mouse wheel could be used).
Anyway i think that opening the notifications builtin variables  on request (not for every notification that match a rules) could be an interesting feature.

**Comment by fwsmit** [comment]
See the events proposal #879. I think that would suit your needs
