### ISSUE TITLE
Dunst reporting wrong xbox-controller battery value

### ISSUE THREAD

**Issue by Chr1s70ph** [dunst-project/dunst#1059]
### Issue description

Connecting my Xbox-Controller via Bluetooth displays a notification, that my controller is connected, and displays the current battery status. I posted this issue originally to XPADNEO-Issues ([#342](https://github.com/atar-axis/xpadneo/issues/342)), but I was told to report the issue here.
TLDR: Connecting the controller without loading the module `hid_xpadneo`, the correct value is displayed. But connecting a second time, it shows 50% again. In my `dmesg` logs however, there is no indication, that `xpadneo` is reporting battery events. 
> I'd say dunst-notification is to consider first, it may change behavior of what modules are loaded and what devices match.

### Installation info

- Version: Dunst - A customizable and lightweight notification-daemon 1.8.1 (2022-03-02)
- Install type: Installed over manjaro community repository
- Window manager / Desktop environment: i3wm

<details>
<summary>Minimal dunstrc</summary>

```ini
[global]
font = Iosevka Term 11
corner_radius = 5
markup = yes
format = "%s %p\n%b"
sort = no
indicate_hidden = yes
alignment = center
bounce_freq = 0
show_age_threshold = -1
word_wrap = yes
ignore_newline = no
stack_duplicates = yes
hide_duplicate_count = yes

shrink = yes
idle_threshold = 0
monitor = 0
follow = none
sticky_history = yes
history_length = 15
show_indicators = no

dmenu = /usr/bin/dmenu -p dunst:
# Browser for opening urls in context menu.
browser = /usr/bin/firefox -new-tab

icon_position = left
max_icon_size = 80
icon_path = /usr/share/icons/Colloid-dark/devices/16/:/usr/share/icons/Colloid-Dark/status/16/
```
</details>

**Comment by fwsmit** [comment]
Sorry, dunst just displays the notification. You'll have to figure out which program sends the notification. Maybe a `dunst -print` will give you more information about which program sent the notification if you take a look at the appid.

**Comment by Chr1s70ph** [comment]
Thanks, I have narrowed it down to `blueman` and opened an [Issue](https://github.com/blueman-project/blueman/issues/1696) there aswell.
