### ISSUE TITLE
NO DOCUMENTATION 

### ISSUE THREAD

**Issue by RedDofamine** [dunst-project/dunst#1063]
I have not seen the worst documentation.
I am a beginner in Linux and for me important examples of the use of certain flags to display information (it is incomplete in the documentation).
The main page of the project states that the application is very customized and you can really see some great examples, but it is unknown how to implement them, what knowledge is needed for this - it is unknown.
Let's take a situation where we want to display notifications in a certain part of the screen and for this we have an origin and an offset, whether it is possible to use different values ​​for certain programs is unknown. Even if you can do it, the documentation will show you - nothing.
In my opinion, the shortcomings described above simply kill this project for beginners.

**Comment by pvonmoradi** [comment]
Have you seen `man dunst` and `man 5 dunst` and [this guide](https://github.com/dunst-project/dunst/wiki/Guides) ?

**Comment by fwsmit** [comment]
@RedDofamine is the above mentioned documentation sufficient?

**Comment by RedDofamine** [comment]
> @fwsmit I'm still where I was.

**Comment by fwsmit** [comment]
You should take another look at the man page. All settings are described there. All settings in the global section, like origin, are not configurable per notification.
