### ISSUE TITLE
Summary is always treated as plain text

### ISSUE THREAD

**Issue by imsamuka** [dunst-project/dunst#1068]
### Issue description

Unlike the __body__, notification summaries appears to always be treated as plain text.

### Installation info

- Version: `1.8.1 (2022-03-02)`
- Install: `pacman -S community/dunst`
- Window manager: `openbox 3.6.1`

### Example

```ini

$ cat ~/.config/dunst/dunstrc 
[global] 
    markup = full 
    format = "%s\n%b" 
$ dunstify "<span color='#FF0000'>In Summary, don't</span>" "<span color='#FF0000'>Span in Body works</span>"
```

![image](https://user-images.githubusercontent.com/62220318/164735351-4e00e2ef-9557-4831-b003-b428b2ef4e51.png)

### Static Summary Format

As you can see, using a __<span>__ statically inside the __format__ configuration works. It also works with multiple levels (nested spans). I don't know if there's a reason why __summary__ is treated differently from __body__, but I think it shouldn't, and is very limiting.

```ini

$ cat ~/.config/dunst/dunstrc 
[global] 
    markup = full
    format = "<span color='#FF0000'>%s</span>\n%b" 
$ dunstify "Static Span in Summary works" "<span color='#FF0000'>Span in Body works</span>"
```

![image](https://user-images.githubusercontent.com/62220318/164736292-0095d995-1438-49b5-8e8e-f98b0dd2fe42.png)

**Comment by fwsmit** [comment]
This is expected behaviour as described by [the notification spec](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html):
" Body text may contain markup". It is not mentioned that the summary may contain markup.

You can use `format` in rules instead.
