### ISSUE TITLE
WARNING: Could not find theme breeze-dark | Even though icon_theme is set

### ISSUE THREAD

**Issue by Fxzzi** [dunst-project/dunst#1074]
### Issue description

Even though icon_theme has been set, the warning `WARNING: Could not find theme breeze-dark` shows up when running dunst.

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon v1.8.1-56-g6c9f83b`
- Install type: `dunst-git from AUR`
- Window manager / Desktop environment: `BSPWM`

<details>
<summary>Minimal dunstrc</summary>

```ini
[global]
icon_theme = Papirus-Dark
```
</details>

**Comment by fwsmit** [comment]
Does this cause any issues other than emitting a warning?

**Comment by bynect** [comment]
I will close as this seems expected behavior
