### ISSUE TITLE
Can't pair bluetooth device

### ISSUE THREAD

**Issue by d3im** [dunst-project/dunst#1079]
### Issue description
When pairing device with blueman over applet it uses notification to display and accept pair code.
Dunst only displays message and I have no clue how to accept it.

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.8.1 (2022-03-02)`
- Install type: `package`
- Window manager / Desktop environment: `Openbox`

**Comment by fwsmit** [comment]
Could you show a screenshot of the message?

**Comment by fwsmit** [comment]
You can bind that command to a hotkey if you want.
(edited your message for type, progandy)

**Comment by izmyname** [comment]
> Install dmenu, then try `dunstctl context` to open the menu with the actions. https://github.com/dunst-project/dunst/blob/master/docs/dunstctl.pod

Sorry for necrobumping but this doesn't work. Context menu won't popup
