### ISSUE TITLE
External images are not scaled correctly with experimental configurations.

### ISSUE THREAD

**Issue by kenielf** [dunst-project/dunst#1084]
### Issue description
Dunst does not seem to be resizing images according to configuration with the experimental flags enabled.
```
DEBUG: [     set_setting:0380] [global] Trying to set min_icon_size to 0
DEBUG: [     set_setting:0380] [global] Trying to set max_icon_size to 32
DEBUG: [   save_settings:0450] Adding rule 'ellipsize = middle' to special section global
DEBUG: [     set_setting:0380] [global] Trying to set min_icon_size to 64
DEBUG: [     set_setting:0380] [global] Trying to set max_icon_size to 64
DEBUG: [   save_settings:0450] Adding rule 'icon_size = 64' to special section global
WARNING: Could not find theme elementary
WARNING: Could not find theme gnome
DEBUG: [icon_pixbuf_scale_to_size:0186] Scaling to a size of 32x32
DEBUG: [icon_pixbuf_scale_to_size:0187] While the icon size and scale are 32x1.000000
```
The regular icons are displayed correctly, with proper scaling while images (eg.: from discord, telegram or whatsapp) are not:
![image](https://user-images.githubusercontent.com/61657416/173120859-31ed449d-526c-4241-8023-1daa0aa432ce.png)

### Installation info

- Version: `1.8.1`
- Install type: `Arch Linux Package`
- Window manager / Desktop environment: `i3wm`

<details>
<summary>Minimal dunstrc</summary>

```ini
###--- Dunstrc here ---###
[global]
    # Normal
    min_icon_size = 64
    max_icon_size = 64
    # Experimental
    enable_recursive_icon_lookup = true
    icon_theme = Flat-Remix-Blue-Dark
    icon_size = 64
```
</details>

**Comment by fwsmit** [comment]
This might already be fixed in master. Could you try running the latest git version?

**Comment by kenielf** [comment]
I can confirm, in the current master branch `min_icon_size` and `max_icon_size` works perfectly fine. Setting `icon_size` alone doesn't seem to have an effect. otherwise, to have a constant size I can just set the min and max to the same value and it works.

I'll be closing this now as the master branch is working perfectly fine, the package in the distro repository just needs to be updated.
