### ISSUE TITLE
How to properly set font (Correct Font Description) in dunstrc

### ISSUE THREAD

**Issue by TheJollyDuck** [dunst-project/dunst#1085]
### Issue description

Hello, I'm not sure if this is the correct place to ask but I've been having problems trying to use the bitmap [Tamsyn](http://www.fial.com/~scott/tamsyn-font/) as the font in dunst. I've been trying to get it to work but I can seem to get the font to change, only the font size. I have tried different ways of putting it into the dunstrc, also trying to conform it to the [Pango Font Description](https://docs.gtk.org/Pango/pango_markup.html), but to no avail. The font came from the AUR but using `fc-list | grep Tamsyn`, I get the output:

```
/usr/share/fonts/misc/Tamsyn8x15r.pcf: Misc Tamsyn:style=Regular
/usr/share/fonts/misc/Tamsyn8x16r.pcf: Misc Tamsyn:style=Regular
/usr/share/fonts/misc/Tamsyn7x13r.pcf: Misc Tamsyn:style=Regular
/usr/share/fonts/misc/Tamsyn7x14r.pcf: Misc Tamsyn:style=Regular
/usr/share/fonts/misc/Tamsyn5x9r.pcf: Misc Tamsyn:style=Regular
/usr/share/fonts/misc/Tamsyn6x12r.pcf: Misc Tamsyn:style=Regular
/usr/share/fonts/misc/Tamsyn10x20b.pcf: Misc Tamsyn:style=Bold
/usr/share/fonts/misc/Tamsyn10x20r.pcf: Misc Tamsyn:style=Regular
/usr/share/fonts/misc/Tamsyn5x9b.pcf: Misc Tamsyn:style=Bold
/usr/share/fonts/misc/Tamsyn6x12b.pcf: Misc Tamsyn:style=Bold
/usr/share/fonts/misc/Tamsyn7x13b.pcf: Misc Tamsyn:style=Bold
/usr/share/fonts/misc/Tamsyn7x14b.pcf: Misc Tamsyn:style=Bold
/usr/share/fonts/misc/Tamsyn8x16b.pcf: Misc Tamsyn:style=Bold
/usr/share/fonts/misc/Tamsyn8x15b.pcf: Misc Tamsyn:style=Bold

```
In the minimal dunstrc part are the different variations I've tried to get it working. Consequently, I've also had problems making it the default font for the editor in VS code as well, but not for dwm.

### Installation info

- Version: `Dunst 1.8.1 (2022-03-02)`
- Install type: `sudo pacman -S dunst`
- Window manager / Desktop environment: `dwm`

<details>
<summary>Minimal dunstrc</summary>

```ini
font = Misc Tamsyn Regular 9
font = Misc Tamsyn 9
font = Misc_Tamsyn 9
font = Tamsyn 9
font = MiscTamsyn 9
font = "Misc Tamsyn 9"
font = "Misc Tamsyn" 9
font = Misc Tamsyn 10
font = "Misc Tamsyn:style=Regular" 9
font = Hack 10 # Also did not work
```
</details>

**Comment by progandy** [comment]
Pango (and therefore dunst) does not support PCF fonts anymore. You'd have to use the OTB version (for arch linux there is ```tamsyn-font-otb``` in the AUR.

**Comment by TheJollyDuck** [comment]
Ah okay. Thanks for the info and the pointer. I'll close the issue then.
