### ISSUE TITLE
window class and title are unset despite being configured

### ISSUE THREAD

**Issue by PhoenixClank** [dunst-project/dunst#1089]
### Issue description
My dunstrc specifies a window class and title, but when a notification is on screen, inspecting it with the window manager reveals that it has no class or title set.

### Installation info
- Version: 1.9.0 (2022-06-27)
- Install type: package
- Window manager / Desktop environment: Qtile, as a Wayland compositor

<details>
<summary>Minimal dunstrc</summary>

```ini
title=dunst
class=dunst
```
</details>

Also here's the info qtile shell prints on the dunst window:
```python
 {'height': 54,
  'id': 6,
  'name': '<no name>',
  'width': 309,
  'wm_class': None,
  'x': 1601,
  'y': 50}
```
</details>

**Comment by bynect** [comment]
did you solve this?

**Comment by PhoenixClank** [comment]
Nope, just checked, this behavior still shows. But by now I forgot what I needed this for XD

I think I wanted to apply transparency to all non-focused windows, but not to the notifications (or other popups). I now check this in qtile with `isinstance(the_window, LayerStatic)`.

**Comment by bynect** [comment]
does this still occur if you use force_xwayland? or if you use another compositor?

**Comment by PhoenixClank** [comment]
qtile doesn't print any attributes for the xwayland window except its position and size, so I don't know if this still occurs. And unfortunately, I'm not familiar with any other compositor that I could just install and try this in.

**Comment by bynect** [comment]
> qtile doesn't print any attributes for the xwayland window except its position and size, so I don't know if this still occurs

Good to know

I think that this is a wayland problem since on x11 it should work ok. I'll try looking into it

**Comment by bynect** [comment]
Turns out, this feature was completely unimplemented in wayland... @alebastr do you know if there is a protocol to specify the window title/class?

**Comment by alebastr** [comment]
No, that's not a part of the `wlr-layer-shell` protocol dunst uses. It's available in the regular desktop `xdg-shell`, but you cannot use both shells for the same surface and `xdg-shell` doesn't allow positioning windows.

There's a `namespace` property that just happen to be used as `app_id` everywhere nowadays (the planned replacement for wlr-layer-shell even [renamed namespace to app_id](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28/diffs#0f7d62083cb06bea09093cc4019184cc26dda1da_0_315)). Dunst currently sets it to a rather generic string "notifications", and Qtile doesn't seem to use the property at all.

**Comment by bynect** [comment]
> No, that's not a part of the `wlr-layer-shell` protocol dunst uses. It's available in the regular desktop `xdg-shell`, but you cannot use both shells for the same surface and `xdg-shell` doesn't allow positioning windows.
> 
> There's a `namespace` property that just happen to be used as `app_id` everywhere nowadays (the planned replacement for wlr-layer-shell even [renamed namespace to app_id](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28/diffs#0f7d62083cb06bea09093cc4019184cc26dda1da_0_315)). Dunst currently sets it to a rather generic string "notifications", and Qtile doesn't seem to use the property at all.

Thanks. So the title and class options are not implementable using the current protocols and we should update the documentation.

Partially unrelated question: can we implement multiple windows (on different screens even) using the layer shell? Or should we move to the xdg-shell? Because I wanted to start implementing multiple windows for x11 in the next releases

**Comment by alebastr** [comment]
> Partially unrelated question: can we implement multiple windows (on different screens even) using the layer shell? Or should we move to the xdg-shell? Because I wanted to start implementing multiple windows for x11 in the next releases

There's no problem with having multiple layer-shell windows. Might take a bit of refactoring in wl.c though.
