### ISSUE TITLE
Question: How to investigate push notification instigator?

### ISSUE THREAD

**Issue by shmup** [dunst-project/dunst#1093]
I've figured out _what_ was pushing the notification, but only by thinking about which of my apps could have sent something like it. 

I'd still like to be able to definitively tell, though. In this case the notification didn't carry any extra data, just a simple string. No icon, for example.

I used `dunstctl history-pop` to get a reminder of what the notification said.

Is there a way to uncover what triggered it, what process?

Thanks

**Comment by fwsmit** [comment]
You can take a look at the output of `dunstctl history`. Or you can run dunst with `dunst -print`.

**Comment by shmup** [comment]
Oh that's perfect, shame on me not trying that first heh. Thank you!
