### ISSUE TITLE
What does the value of timestamp in dunstctl history represent?

### ISSUE THREAD

**Issue by Meta502** [dunst-project/dunst#1096]
### Issue description
Hello, i'm currently trying to make a script that parses the notification history returned by dunstctl history and displays it in a window opened by rofi.

I would like to ask what value does the timestamp object in notification entries represent? I expected it to be a value that represents the number of miliseconds after UNIX epoch, but that doesn't seem to be the case.

In my case i am trying to get and parse the notification push times from dunstctl history so i can render it on my rofi window, but i've been having issues due to the timestamp seemingly not representing a UNIX date. 

Any help would be appreciated, thank you!

For context:
```
{
    ...
    "timestamp" : {
	    "type" : "x",
    	    "data" : 470080808378
    }
   ...
}
```

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.9.0 (2022-06-27)`
- Install type: `Package`
- Window manager / Desktop environment: `i3 version 4.20.1-98-ga70b89a7 © 2009 Michael Stapelberg and contributors`

**Comment by vichle** [comment]
@Meta502 Do you mind sharing the answer if you figured it out? I have the exact same problem.

**Comment by vichle** [comment]
I found this script: https://github.com/dunst-project/dunst/blob/master/contrib/notification-history.sh that implies that the timestamp field from `dunstctl history` contains the uptime of the system at the time the notification was sent. This means that you can use the below script to get the time. See `man date` for details on how to format the output.

```sh
system_timestamp=$(cat /proc/uptime|cut -d'.' -f1)
how_long_ago=$((system_timestamp - notification_timestamp / 1000000))
notification_time=$(date +%X -d "$(date) - $how_long_ago seconds")
```

**Comment by bebehei** [comment]
IIRC, I was the one who implemented this.

Found the commit: ac4a0becd2b1ed61312d8ce63afe6af37573c74a

It mainly counts the monotonic time (which progresses during sleep) and uses it in a milli-second resolution.

As far as I remember, this may not be aligned with `1970-01-01T00:00:00` and boot time might start at some random timestamp. The only premise, which holds true: The difference between the boot timestamp and the current timestamp is the same as the local time difference. So to make it accurate, you should subtract the difference from the current timestamp.

---

Whoever has written this script, should have received an [award](https://porkmail.org/era/unix/award#cat). Also the double use of `date` command is quite hinderous.

```
system_timestamp="$(cut -d'.' -f1 /proc/uptime)"
how_long_ago=$((system_timestamp - notification_timestamp / 1000000))
notification_time="$(date +%X -d "$how_long_ago seconds ago")"
```
