### ISSUE TITLE
Idea: dunstify should support the option -r for ID as string instead integer

### ISSUE THREAD

**Issue by Zesko** [dunst-project/dunst#1098]
### Issue description

It is not about the issue, but a new feature:

Currently ID is only integer, but it is hard for human to remember to avoid conflict of many IDs of `dunstify` when he creates many different systemd services, each service has an ID of `dunstify` and each ID must be different. 

For example: 
A service1 starts and a notification ID as String:
```
$ dunstify -u "critical" "Service1 is running" -r "Service1"
```

This notification will be closed when the service is done.
```
$ dunstify -C "Service1"
```

Idea: the ID "Service1" would be converted to hash like ID

**Comment by bynect** [comment]
Unfortunately the  Desktop Notifications Specification specifies that ids are integers (https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html).

Also, you should not use -r ID for new notifications but only to replace old notifications. Using -r ID when ID is not already existing is wrong according to the spec (see #1317)
