### ISSUE TITLE
Dunstify close ID does not work in Gnome 42 Wayland, but it works in KDE X11.

### ISSUE THREAD

**Issue by Zesko** [dunst-project/dunst#1103]
### Issue description

the notification starts with ID 11
```
dunstify "test" -u crit -r 11
```
It displays in the Gnome desktop 42.4 Wayland,

then close the notification with the same ID via CLI
```
dunstify -C 11
```
But it does not work in Gnome. It works fine in KDE.

### Installation info

- Version: `1.9.0 (2022-06-27)`
- Install type: `in Arch/Manjaro repos` -> `sudo pacman -S dunst`
- Window manager / Desktop environment: `Gnome wayland 42.4 from Manjaro repo`

**Comment by fwsmit** [comment]
Dunstify is meant to control Dunst. It's lucky that you can control the kde notification daemon with it
