### ISSUE TITLE
[Question] is it possible to override origin per notification type

### ISSUE THREAD

**Issue by motorto** [dunst-project/dunst#1106]
Not an issue more of a question, I couldn't found references on the man-page so I am assuming that answer is no, 

but would be possible to override the "origin" parameter in the scripting session (for example)

I currently have notifications spanning on the `origin=top-center` , I would like for example that some specific notifications to be on the top-right for example.  It this currently possible ?

Another question, is it possible that instead of a script I pass a program (on the script parameter) ??

Cheers

**Comment by fwsmit** [comment]
It's not possible. You need multiple windows for that and that has yet to be implemented.

You can pass any executable path for the script

**Comment by motorto** [comment]
Thanks for the reply !!!
