### ISSUE TITLE
Allays return "2", never "1"

### ISSUE THREAD

**Issue by surfzoid** [dunst-project/dunst#1109]
### Issue description
Hi,
I'm using dunstify in the following bash script : 
https://github.com/surfzoid/QtVsPlayer/blob/master/classicnotify.sh
When the notif popup i got the button "ouvrir" and clic on it , dunstify return correctly "open", then i can do an action.
But, if either there is more than one notif, nor i took too much time to read, the notif go to the list of gnome notif and so there isn't anymore the button.
At this point, i can clic on the text of the notif or close it with the cross or use "del all" button, all those cases return "2", so i cannot do action.

### Installation info

dunst -v
Dunst - A customizable and lightweight notification-daemon 1.5.0 (2020-07-23)
gnome-shell --version
GNOME Shell 3.38.3
uname -a
Linux SurfzoidPC 5.15.62-desktop-1.mga8 #1 SMP Sun Aug 21 16:48:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
RPM Mageia 8

I thank you

**Comment by surfzoid** [comment]
pkill dunst; dunst
WARNING: No dunstrc found.
CRITICAL: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'gnome-shell' with PID '7480'.

**Comment by surfzoid** [comment]
woooo i discover dunstify  -a QtVsPlayer start my app by clicking on the text area, but cannot add path argument to it

**Comment by fwsmit** [comment]
Dunstify isn't necessarily made to work with gnome's notification daemon. Not all features will work. I don't think it's possible to run Dunst on a gnome environment

**Comment by surfzoid** [comment]
> Dunstify isn't necessarily made to work with gnome's notification daemon. Not all features will work. I don't think it's possible to run Dunst on a gnome environment

well gnome notif work with Dunstify/libnotify , i did a partial and dirty workarround : https://github.com/surfzoid/QtVsPlayer/blob/master/classicnotify.sh
