### ISSUE TITLE
Feature Request: Option to display notifications bottom-up instead of top-down

### ISSUE THREAD

**Issue by ExperiBass** [dunst-project/dunst#1113]
Currently, dunst displays newer notifications below older ones, but it doesn't seem to have a option to reverse the order. I have my notifications display in the top center, and having notifs come in from the top would fit better.

**Comment by bynect** [comment]
does #845 solve this?

**Comment by ExperiBass** [comment]
Sorting by `update` solves this, thanks @duarm :3
