### ISSUE TITLE
Dunst doesn't accept keyboard shortcuts if ibus is enabled.

### ISSUE THREAD

**Issue by AmandaCameron** [dunst-project/dunst#112]
Title pretty much says it all. I've recently enabled ibus so I can type in other languages, but it appears to have completely FUBAR'd dunst's keybindings, which is a real big problem when one's missing a mouse.

Thanks for all the hard work so far, and please keep it up! :)

**Comment by tsipinakis** [comment]
You should now use `dunstctl` to perform the operations previously done by keyboard shortcuts (I intend to deprecate the latter).

In either case, this is solved with #651 .
