### ISSUE TITLE
How to configure appearence on the fly ?

### ISSUE THREAD

**Issue by ghost** [dunst-project/dunst#1120]
### Issue description
I've set everything on dunstrc config to show on top left for all notifications. But I need volume level notifications to be exactly in the middle of the screen. Is it possible ?

Currently I'm using these bindings:
```
set $showvol notify-send -t 1500 'VOLUME' -h int:value:$(pulsemixer --get-volume | awk '{print $1}')
bindsym XF86AudioRaiseVolume $run pactl set-sink-volume @DEFAULT_SINK@ +10% && $showvol
bindsym XF86AudioLowerVolume $run pactl set-sink-volume @DEFAULT_SINK@ -10% && $showvol
```
But they show at the configured position. I wanna set it to middle of the screen on the fly, unlike the rest of the notifications that appear at the corner.
### Installation info

- Version: `1.9.0`
- Install type: `pacman -S dunst`
- Window manager / Desktop environment: `i3-gaps`

<details>
<summary>Minimal dunstrc</summary>

```ini
# Dunstrc here
```
</details>

**Comment by wael444** [comment]
https://github.com/dunst-project/dunst/blob/53a2ff19728aa3584784b0cb313212a1ed3ef801/dunstrc#L346

Unfortunately doesn't seem you can set `origin` here.

**Comment by ismay** [comment]
I was just wondering about the exact same thing. Allowing a different origin and offset for certain notifications would be great. It feels much more natural to me to have volume, microphone and brightness notifications at bottom center.

**Comment by apprehensions** [comment]
@voguelike , that feature is for Xresources configuration.

**Comment by apprehensions** [comment]
It reloads Xresources configuration and not the configuration file...

**Comment by apprehensions** [comment]
https://github.com/FT-Labs/phyOS-dunst/commit/018d965231de67ce45b3b767baa299dc84e8c56d

**Comment by bynect** [comment]
for future reference now dunst supports hot reloading #1350
