### ISSUE TITLE
libXScrnSaver and libnotify disabled at build time

### ISSUE THREAD

**Issue by apprehensions** [dunst-project/dunst#1122]
IMO, libXScrnSaver and libnotify should be disabled at build time via `IDLE=0` and `DUNSTIFY=0`, for dunstify it can be added to Makefile rule dunstify to check for libnotify. but for libxscrnsaver i haven't got very far.

**Comment by wael444** [comment]
@fwsmit why is libXScrnSaver needed? i was hoping for an answer.

**Comment by bebehei** [comment]
AFAIK is libXScrnSaver used for X11 when to detect if we're idling.

**Comment by wael444** [comment]
yeah that must be a optional feature at build time... but couldnt figure it out due to a segmentation fault.

**Comment by bebehei** [comment]
If I remember this correctly - can be changed by @fwsmit in the meantime - the X11-Codeparts are not yet optional, so neither libXScrnSaver. But take this with a grain of salt, it might be FUD.

**Comment by fwsmit** [comment]
The X11 code part is not yet optional. You'll have to #ifdef it out, just like I've done with the wayland code. I would go straight for all the X11 code, not just libXscreensaver

**Comment by wael444** [comment]
i'd still want libXScrnSaver disabled at build time, since it's practically a useless dependency when the feature its used for isn't used.

**Comment by fwsmit** [comment]
So I understand correctly you are using X11? 
You can also just ifdef out the X11 Screensaver part of you want. But I don't see many people wanting to only get rid of the Screensaver part, so I don't think that should be merged upstream

**Comment by wael444** [comment]
> You can also just ifdef out the X11 Screensaver part of you want.

technically thats the same as removing it, which for me ended up in a segmentation fault.

**Comment by fwsmit** [comment]
Yeah, you'll also have to make sure it's not used anywhere

**Comment by bynect** [comment]
I think that this is no longer relevant thanks to #1290.

**Comment by apprehensions** [comment]
This issue was made at a different stage when I was growing up, when I cared about minimalism and dependencies in my system. At that time I hadn't known X was designed for a different time and had protocols/extensions ontop of Xorg, which is why we have XScrnSaver.

Personally, I understand the need for idle detection and I can definitely find use to it, but not everyone will find these features useful - especially those who care about dependencies. I asked for a re-opening so I can close the issue properly as I am the OP.

**Comment by bynect** [comment]
I totally understand, I also hate bloat and pursue minimalism (that's why I ended up here in the first place). However the xscrnsaver extension has become a stable part of the xorg ecosystem and is on almost on every server (like xinerama and randr). So since everyone will have it installed we might as well take advantage of it. This same reasoning goes for libglib which is used by cairo.
