### ISSUE TITLE
Support for light font?

### ISSUE THREAD

**Issue by GRR3ED** [dunst-project/dunst#1130]
So I tried setting the font to ubuntu light as I don't like how dunst shows the notifications in bold as shown below but it just changes the font size but not the font weight to light? Or am I missing something?

### Installation info

- Version: `1.9.0`
- Install type: `pacman`
- Window manager / Desktop environment: `BSPWM`

<details>
<summary>Minimal dunstrc</summary>

```ini
[global]
width = (0, 400)
height = 100
font = Ubuntu Light 11
```
</details>

**Comment by bebehei** [comment]
Have you checked out `format`? [It's default value is `<b>%s</b>\n%b`](https://github.com/dunst-project/dunst/blob/943d1e99e1d03cb67046c6b9a829b1a815bb2173/src/settings_data.h#L537), so the summary is bold by default. You might be able to change it to `%s\n%b`, which might serve your use case.
