### ISSUE TITLE
Wayland: Monitor number makes it difficult to consistently choose the correct display

### ISSUE THREAD

**Issue by lbatalha** [dunst-project/dunst#1132]
### Issue description

dunst only allows choosing a monitor based on its "number"
This number can change on boot and also with display hotplugging
It would be ideal to be able to define an output by its name

### Installation info

- Window manager / Desktop environment: `sway`
- Nvidia proprietary drivers

### Details

dunst [seems to](https://github.com/dunst-project/dunst/blob/58206fe50ff3ef97bc12f49caf830e82e10c08a6/src/wayland/wl.c#L376) get a list of wayland output numbers on start, but this list appears to be dynamic, adding or removing a new display messes with the order, and changes the output dunst displays on silently. (I guess because it follows the wayland client example implementation)

The ideal solution imo would be to be able to supply an output name _a la_ sway, ie: `"Ancor Communications Inc ASUS PB278 C9LMTF278905"` or the short output port name `HDMI-A-1` (these can be found with `swaymsg -t get_outputs`).
They should be available in `wl_output::name` according to the docs.

Ideally both formats would be supported (maybe it just works with common libraries?) because each potentially has advantages for different users (desktop vs laptop vs whatever, depending on how stuff is handled).

I think this solution should probably replace the current output number behavior for wayland, though I dont know how other compositors and desktop environments manage this, and I dont know if that would be an annoyance for people that want to use X and Wayland concurrently or want to migrate between them seamlessly.

Adding a second option like `monitor_name` doesn't seem to be too bad for the end user at least.

Implementing this myself is a bit over my head unfortunately.

**Comment by evolozzy** [comment]
> but this list appears to be dynamic

It feels like list is in some kind of order (I suspect it to be reverse alphabetical order for the serial number, I need to test it with more monitors to make sure but I don't have more monitors).  In my case I have 3 monitors I plug in and out, and every time the monitor I wanted my notifications was the highest number for dunst. So I resolved the issue using a simple script that I wrote. I run it every time I plug a monitor. While waiting for this feature, feel free to change it and use it for your needs. I hope this workaround helps.

```
#!/bin/bash

killall dunst

MONITORCOUNT=`swaymsg -t get_outputs | grep type | wc -l `
NEWINDEX=$(( $MONITORCOUNT - 1 ))

sed -i -r "s/(monitor =).*/\1 $NEWINDEX/"  ~/.config/dunst/dunstrc

dunst &  
```

**Comment by fwsmit** [comment]
There is a PR posted #1250 that should fix this issue. More testing of this, especially on some more uncommon wayland compositors would be appreciated.
