### ISSUE TITLE
Critical error on startup

### ISSUE THREAD

**Issue by Pound-Hash** [dunst-project/dunst#1142]
### Issue description
On startup, I receive this critical error message:

`[dbus_cb_name_lost:1044] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '599'.
`
### Installation info

- Version: `1.9.0`
- Install type: `package`
- Window manager / Desktop environment: `river`
- Distro: `Arch`

**Comment by bebehei** [comment]
Please see the FAQs for this: https://dunst-project.org/faq/#cannot-acquire-orgfreedesktopnotifications

Dunst ist probably already running.
