### ISSUE TITLE
Notification Hook Feature

### ISSUE THREAD

**Issue by samuelzxu** [dunst-project/dunst#1146]
I'd like some pointers on how I would go about implementing a notification hook feature, where every dunst notification is hooked into a bash script. My intended use case is to send notifications from my desktop to my phone via email, and I plan to write a python script with notify-send that performs the email function. Is this something feasible and reasonable to implement as a feature of this library?

**Comment by fwsmit** [comment]
There is an option to run a script when a notification is received. This script could send an email with the notification's contents. Take a look at the man page for documentation

**Comment by samuelzxu** [comment]
Got it, thanks! That's enough for the functionality I want.
