### ISSUE TITLE
Close the daemon when a notification is received

### ISSUE THREAD

**Issue by tupo2** [dunst-project/dunst#1153]
Not really an issue, but more a question:
Is there a clean way to close the daemon when a notification is received and after being displayed?

**Comment by biopsin** [comment]
You mean dbus-daemon? then the answer is no, how you gonna recieve new notifications if you kill the dbus.
If your looking for dbus free notifications you might like https://github.com/phillbush/xnotify

**Comment by tupo2** [comment]
> You mean dbus-daemon? then the answer is no, how you gonna recieve new notifications if you kill the dbus. 

I'm talking about the dunst daemon.

> If your looking for dbus free notifications you might like https://github.com/phillbush/xnotify

Thanks, I didn't know xnotify.

**Comment by tupo2** [comment]
> What would be the use case for this? I would mean a startup delay for every notification and your history would not be preserved

Preserve resources and I don't need history.

**Comment by fwsmit** [comment]
Dunst is already very lightweight, so I don't think this feature is necessary. I will close this as not planned
