### ISSUE TITLE
Permanent notifications

### ISSUE THREAD

**Issue by 1stepback** [dunst-project/dunst#1160]
Big n00b here. Does anyone have any clue how I might stop notifications from disappearing (unless clicked by user)

**Comment by 1stepback** [comment]
Actually i'm not even sure I managed to get dunst running. Please ignore.

**Comment by bebehei** [comment]
Ok, we'll ignore it. If you've got further questions, do not hesistate to ask or consult

- FAQ: https://dunst-project.org/faq/
- configuration file manpage `man 5 dunst`
- dunst process manpage: `man 1 dunst`
