### ISSUE TITLE
unable to edit dunst using config file

### ISSUE THREAD

**Issue by 1stepback** [dunst-project/dunst#1161]
I've tried editing 2 different config files. 
1. /~/dunst/dunstrc
2. /etc/xdg/dunst/dunstrc

I tried changing all urgency level notifications to the critical urgency red colour, & changing timeout settings. Neither did anything. 

I'm a complete noob at Linux, so i'm just trying to find out which file will allow me to customise my Dunst notification daemon. 
I checked: config.mk    
And it lists /etc/xdg/ as the SYSCONFDIR. Should that not be the location of the config file being read by Dunst? I tried editing the dunstrc at that location using sudo -e, and nothing. 

I'm on Raspberry Pi OS (Debian based), and I installed Dunst from the repository, if that makes a difference. 

If anyone can point me in a direction, I would greatly appreciate it. Sorry for posting twice in 24 hours, but I've been reading so much and i'm only sinking deeper into terms and commands I don't understand.

**Comment by 1stepback** [comment]
After many hours of throwing myself at a wall (usually what happens with me and programming), I finally found the correct dunstrc file. I did not think to look for a hidden .config directory, and believed I didnt have one. In the end it was there.

**Comment by ClassickTech** [comment]
Hello, I have been having the same EXACT PROBLEM. Where exactly did you find it?

**Comment by bynect** [comment]
> It will be owned by root so edit in nano, vim, etc:
> sudo nano duntsrc
> 

You should chown the file to yourself

sudo chown user:user dunstrc

**Comment by ClassickTech** [comment]
I just did that. Thanks!
