### ISSUE TITLE
XDG_CONFIG_DIRS fallback

### ISSUE THREAD

**Issue by akinokonomi** [dunst-project/dunst#1176]
### Issue description

Dunst manual page reads:
```
       $XDG_CONFIG_DIRS
               This, like $PATH for instance, is a :-separated list of base directories in descending order of importance.  (/etc if unset or empty)
```

While https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables says:
```
If $XDG_CONFIG_DIRS is either not set or empty, a value equal to /etc/xdg should be used.
```

So, shouldn't system `/etc/dunst/dunstrc` actually be `/etc/xdg/dunst/dunstrc`, too?

Thanks!

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.9.2 (2023-04-20)`
- Install type: `package`
- Window manager / Desktop environment: `<!--  -->`
- Distro: `Arch Linux`

Reproducible with the default Dunst config.

EDIT: Made it more comprehensible. Sorry about the mess.

**Comment by fwsmit** [comment]
Yeah, that's true. But in my experience not many programs actually conform to this spec, since it's an extra directory to type. We've chosen not to do that for dunst either.
