### ISSUE TITLE
Incorrect documentation of corner_radius

### ISSUE THREAD

**Issue by n3oney** [dunst-project/dunst#1177]
### Issue description
The corner_radius option is not documented correctly.
"[If you have multiple notifications, the whole window is shaped, not every single notification.](https://github.com/dunst-project/dunst/blob/dfab9f057f89702ade5725c8247a520ab51026f4/docs/dunst.5.pod?plain=1#L505)"
This does not seem to be true:
![image](https://user-images.githubusercontent.com/30625554/236707061-194c52ee-ad86-42f1-a29a-e9f526d4580c.png)

### Installation info

- Version: `1.9.2`
- Install type: `package`
- Window manager / Desktop environment: `Hyprland`
- Distro: `NixOS`

<details>
<summary>Minimal dunstrc</summary>

```ini
[global]
corner_radius=5
gap_size=20
```
</details>

**Comment by fwsmit** [comment]
Feel free to submit a PR editing the docs

**Comment by bynect** [comment]
that is true only if the gaps option is not used
