### ISSUE TITLE
progress_bar_corner_radius not working correctly 

### ISSUE THREAD

**Issue by ikz87** [dunst-project/dunst#1178]
### Issue description
These are like 3 issues in one:

1- When setting `progress_bar_corner_radius` to a negative value, dunst runs without problems but seems to add that value to the overall size of the bar which wouldn't seem like the expected behavior to me.

2- If the window has a low progress value (like 0) the corners get "inverted". To replicate, simply run: `dunstify "bar radius test" -h int:value:0`
![image](https://github.com/dunst-project/dunst/assets/98569017/a61bef23-1d0c-4a4c-87a4-83751b94de22)

3- The `progress_bar_frame_width` property doesn't play well with the corner radius. Using both at the same time results in the inner part of the bar being offset vertically a bit:
![image](https://github.com/dunst-project/dunst/assets/98569017/35f3bf59-ba8f-4416-ba42-701b086c361c)

### Installation info

- Version: `v1.9.2`
- Install type: `manually`
- Window manager / Desktop environment: `BSPWM`
- Distro: `Arch Linux`

<details>
<summary>Minimal dunstrc</summary>

```ini 
    progress_bar = true       
    progress_bar_height = 20                                                               
    progress_bar_frame_width = 5    
    progress_bar_min_width = 0       
    progress_bar_max_width = 380       
    progress_bar_corner_radius = 7    
```
</details>

**Comment by fwsmit** [comment]
This should be fixed by #1227
