### ISSUE TITLE
stop timeout on right click

### ISSUE THREAD

**Issue by jackffmm** [dunst-project/dunst#1202]
I set the timeout that is ok for 90% of the notifications.
On left click the notification goes away, and thats ok.

But there can be a notification that is longer and / or i want to read carefully, so the right or middle click should stop the timeout.
maybe its already possible to do that ? It could be the default anyway.

**Comment by jackffmm** [comment]
what could I do as a workaround ? how do i read a closed notification ?

**Comment by fwsmit** [comment]
Yeah, you can use dunstctl history pop function. There is a proposal of an event rule that would be an exact match for your issue: #879. But there has been no work on that yet.
