### ISSUE TITLE
actions are invalidated in case of closeNotification message

### ISSUE THREAD

**Issue by dmitry-j-mikhin** [dunst-project/dunst#1219]
Dunst documentation has the following statement:

```
Actions are invalidated once the notification is closed, so you cannot execute that action when you bring back a notification from history.
```

It looks like actions are also invalidated in case of a closeNotification message. I have `ignore_dbusclose = true` in dunstrc so notifications don't close in case of a closeNotification message, but I can't take action on them once the message is received. I think actions should not be invalidated in the case of `ignore_dbusclose = true` or there should be a separate option to control invalidation of actions.

P.S.
```
$ dunst -v
Dunst - A customizable and lightweight notification-daemon 1.9.2
```

**Comment by bynect** [comment]
This is actually the expected behavior because ignore_dbusclose is only a thing made by dunst. To remain compliant with the notification protocol dunst "lies" to the program by saying that it closed the notification (even if it didn't).

**Comment by dmitry-j-mikhin** [comment]
@bynect thanks for the explanation. Can I ask one more thing: how do actions actually work? Is there an action (such as a URL) in the notification that I can use later. Or the action is something that I need to double-check against the notification protocol from the sender before executing it. Sorry for the stupid questions.

**Comment by bynect** [comment]
> @bynect thanks for the explanation. Can I ask one more thing: how do actions actually work? Is there an action (such as a URL) in the notification that I can use later. Or the action is something that I need to double-check against the notification protocol from the sender before executing it. Sorry for the stupid questions.

As far as I know, actions are "synchronous" in the sense that if a notification is dismissed by either the program or the user, they can no longer be used. At least for dunstify, waiting for actions if blocking. for other programs it isn't, but it still does expire when the notification goes away.

Maybe you can do what you want with some scripting being run on a notification?
