### ISSUE TITLE
Move to scdoc

### ISSUE THREAD

**Issue by apprehensions** [dunst-project/dunst#1225]
Currently, dunst uses doxygen/pod2man, which is pretty bloated.

scdoc is a very simple man page generator with a much readable markdown format than pod.

 I am willing to rewrite the docs in markdown, which itself isnt that hard anyway.

**Comment by apprehensions** [comment]
https://git.sr.ht/~sircmpwn/scdoc 

many simple projects such as dunst use scdoc or manually written man pages.

**Comment by fwsmit** [comment]
I don't think the pod format is too hard to read, but I'm not against replacing it either.

**Comment by apprehensions** [comment]
scdoc is easier to package as it is a small C program. Pod on the other hand requires a whole new language, and its own formatting language instead of Markdown.

**Comment by apprehensions** [comment]
Alongside this change, the docs for the dunst website may have to be redone.

Please consider having a simple suckless website such as https://soju.im/ https://soju.im/doc/soju.1.html

**Comment by bebehei** [comment]
A few years ago, I would have supported this to 150%. But especially in the last year, I have learned that docs mostly aren't as simple as markdown is. I acknowledge, that the pod package is bloated, but on the other side, the pod format matured over years and is a perfect fit for man pages.

Just keep this in mind. I don't want to prevent you from any good actions.

**Comment by apprehensions** [comment]
Technically speaking, scdoc is a very very similar format to markdown and could easily be converted back to markdown.

I believe for the time being it should be POD to retain Hugo compatibility up until the build system changes.

**Comment by fwsmit** [comment]
I'll close this issue, as we are currently not planning to switch.

**Comment by apprehensions** [comment]
Just as a reminder, sway uses scdoc, so i think dunst should too! (also reduces some meson complexity.), i can work on it after the meson PR has been merged.
