### ISSUE TITLE
Trigger notification actions from the command line w/ `dunstctl`

### ISSUE THREAD

**Issue by mageowl** [dunst-project/dunst#1236]
### Issue description
It would be nice to be able to trigger an action on a keyboard shortcut using sxhkd, however currently that is impossible due to the fact that it is impossible to trigger a notification action via `dunstctl`.

Could we have a command like: `dunstctl action 0 default` that would trigger the `default` action for the first notification, and `dunstctl action 0` to list all actions for a notification?

### Installation info

- Version: `v1.9.2-6-ga8b2650`
- Install type: `manually`
- Window manager / Desktop environment: `bspwm 0.9.10`
- Distro: `linux mint 21.1`

**Comment by mageowl** [comment]
Oh, whoops! I didn't see this in the man pages. Thanks so much!

**Comment by sakarimov** [comment]
> e. g. `dunstctl action`, `dunstctl action 0` or `dunstctl action 0 default` 

it's still not working for me, i have no custom action i just want to use the default action when the the notification has `URL` it should open the browser, i tried all three method and none of those opening the url to browser, when i try to open it by middle click it works perfectly

Installation info

- Version: v1.11.0
- Install type: AUR `dunst`
- Window manager / Desktop environment: qtile 0.25.1.dev0+g005da458.d20240413
- Distro: Archlinux
