### ISSUE TITLE
How exactly to disable any notification for a specific program

### ISSUE THREAD

**Issue by c02y** [dunst-project/dunst#1239]
### Issue description
I need to disable any notification for a specific program (fcitx5), but I don't know how, the `doc` or `man` doesn't show any useful info

### Installation info

- Version: `1.9.2-1`
- Install type: `Archlinux repo`
- Window manager / Desktop environment: `i3wm`
- Distro: `Archlinux`

<details>
<summary>Minimal dunstrc</summary>

All the same as `/etc/dunst/dunstrc` except for the following 
```ini
[ignore]
   desktop_entry = "org.fcitx.Fcitx5"
   skip_display = true
```

</details>

BTW:
```
$ dunst -print
CRITICAL: [dbus_cb_name_lost:1152] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '205305'.
```

**Comment by bynect** [comment]
There was a very similar question here #1024

**Comment by c02y** [comment]
Yes, I searched before this issue, 


> You can use dunst -print to see what app name or other matching rules you can use.


BUT
```
$ dunst -print
CRITICAL: [dbus_cb_name_lost:1152] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '205305'.
```

**Comment by maxz** [comment]
Kill your running dunst process first and then start a new one with `dunst -print`.

**Comment by c02y** [comment]
@maxz thanks, every time I modify my dunstrc, I will kill dunst and start new dunst session (since dunst doesn't have a auto reload rc feature), but `dunst -print` always outputs the similiar error message.

**Comment by maxz** [comment]
You try to start dunst twice. Do what I wrote, e. g. use `dunst -config /home/chz/.config/i3/dunstrc -print` in your case to start it.

**Comment by c02y** [comment]
OK, thanks, didn't know `dunst -print` is to start dunst session, the following doc may be incorrect.
```
# NOTE: It might be helpful to run dunst -print in a terminal in order
# to find fitting options for rules.
```

So back to the original question, what should I do to disable any notification for a specific program?

**Comment by c02y** [comment]
`desktop_entry` I got is from Goggle, it is said to be the name of desktop file in the system.

But I noticed that `desktop_entry` entry in the `dunst -print` result for the program I need is empty.

Anyway, thank you.
