### ISSUE TITLE
Feature: Color gradient

### ISSUE THREAD

**Issue by bynect** [dunst-project/dunst#1273]
Hello, I was fiddling around and implementing a color gradient feature.
It is still unfinished though and I would like to hear your ideas.

I wanted to add the option to have a gradient to the background and progress bar.
Basically we have a list a colors that are put in a `cairo_pattern_t`.
If there is only one color the behavior is the same as it is now.

For the syntax of I was thinking of one of the following
```ini
# separate
background = whatever # ignored
background_gradient = 0xffaa22,0xfaf2a
```

or 

```ini
background = red, green, blue
```

Example:
![img-1706811365](https://github.com/dunst-project/dunst/assets/68197565/d701da6d-0102-4484-962a-df3d0200d504)

**Comment by fwsmit** [comment]
I'm just seeing this now. If you want me to react, you can tag me.
The gradient looks cool. Currently the color of the progress bar is called the highlight color. You can expand that one to also accept a list.

**Comment by bynect** [comment]
> I'm just seeing this now. If you want me to react, you can tag me.
> The gradient looks cool. Currently the color of the progress bar is called the highlight color. You can expand that one to also accept a list. 

Ok so I'll go with the list ruote 👍

I'll present a pr when I'm done
