### ISSUE TITLE
suggestion: optional FIFO

### ISSUE THREAD

**Issue by dicktyr** [dunst-project/dunst#1309]
please consider an option to create a FIFO at a specified path which dunst continuously reads, displaying notifications as they arrive

for example, a script might redirect stderr (rather than trying to capture it separately from stdout and then calling notify-send, &c.)

`command 2> ~/.config/dunst/dunst.fifo`

probably best to allow multiple fifos so different rules may be applied to each as need be

**Comment by bynect** [comment]
can't you create a script that monitors the fifo and calls notify-send?

**Comment by dicktyr** [comment]
of course, but I think a significant portion of dunst users might find it useful (not to mention avoiding yet another resident process...)

**Comment by zappolowski** [comment]
I don't consider avoidance of a resident process a compelling argument for adding this feature. Also, writing a script which uses standard tools like `notify-send` (or even some binding to the DBus) seems to be preferred as it would work with other notification daemons besides `dunst`.
