### ISSUE TITLE
Dunstify with hint -h int:value:$VALUE is not printing

### ISSUE THREAD

**Issue by sonalys** [dunst-project/dunst#1310]
### Issue description

I don't receive any notification when using `-h int:value:{0 to 100}`

Example command:
```bash
dunstify \
        -h string:bgcolor:"#343434" \
        -h string:hlcolor:"#e44138" \
        --urgency=critical \
        -r 2593 \
        -h int:value:50 \
        -h string:x-canonical-private-synchronous:volume \
        "Volume"
```

I tried downgrading until 1.9.1, and it still doesn't work.

### Installation info

- Version: `1.10.0`
- Install type: `arch\yay`
- Window manager / Desktop environment: `i3wm`
- Distro: `manjaro`

<details>
<summary>Minimal dunstrc</summary>
It won't run in with any dunstrc, even without one.

</details>

**Comment by zappolowski** [comment]
I can't reproduce the issue here. 

Could you please run dunst with `-verbosity debug`, issue your command and post the output here.

**Comment by sonalys** [comment]
My bad, I double-checked, and I had `vim /usr/share/dbus-1/services/org.freedesktop.Notifications.service` set to `notify-osd`
Some update probably broke it, I set back to dunst, and it's working.

It's just weird that dunstify is not using dunst, but the default notification service

**Comment by zappolowski** [comment]
> It's just weird that dunstify is not using dunst, but the default notification service

That's not weird, but working as intended. There can be one and only one notification daemon running at a time ... `notify-send` and `dunstify` as well don't communicate with a notification service directly but with a DBus interface (that's where the restriction of a single service comes from).

**Comment by sonalys** [comment]
I just assumed dunstify would alert me that dunst is not running by default or something.

would be pretty nice

**Comment by zappolowski** [comment]
`dunstify --serverinfo` already provides information about the running server (so, you could already check it before sending your notification).

I'm not sure whether it is really beneficial to add a new check for a "compatible" (whatever this means in this context) notification server before sending any notification ... especially doing this by default. This use case seems to be rather niche.
