### ISSUE TITLE
other notification daemons wont work after uninstalling dunst

### ISSUE THREAD

**Issue by xienuss** [dunst-project/dunst#1313]
if i try to do `notify-send` after uninstalling dunst it says `GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: startup job failed.`, also mako dont auto starts but i can start it from terminal (im using arch&hyprland system)

**Comment by bynect** [comment]
is the file `org.knopwob.dunst.service` present in the dbus service folder?

**Comment by xienuss** [comment]
yes, do i need to delete it?

**Comment by xienuss** [comment]
so, i deleted it and mako started working, thanks!

**Comment by xienuss** [comment]
i used `pacman -R dunst` to uninstall it, also the daemon is still im my /usr/local/bin after i uninstalled it

**Comment by bynect** [comment]
> i used `pacman -R dunst` to uninstall it, also the daemon is still im my /usr/local/bin after i uninstalled it

I am not too familiar with pacman, is there a purge option? Anyway, maybe you could tell the arch package maintainer about it?

**Comment by xienuss** [comment]
yeah -R means -Remove, i think i'll report it tomorrow

**Comment by Narrat** [comment]
The Arch package doesn't install into `/usr/local/`
https://archlinux.org/packages/extra/x86_64/dunst/files/
And even if it did, the files are tracked and if the package gets uninstalled it would be removed.
So whatever happened it isn't an Arch packaging problem (aka nothing to report to them)
