### ISSUE TITLE
HOw to get rid of (A) in notifications

### ISSUE THREAD

**Issue by mrgreen3** [dunst-project/dunst#1320]
Not so much of an issue as a question. 

How do I get rid of the (A) in notifications?

Currently running version 1.10.0

Dunstrc looks like this:

`[global]
font = Sans 8
format = "%s"
timeout = 5
frame_width = 1
icon_theme = elementary
enable_recursive_icon_lookup = true

frame_color = "#889600"
background = "#131c26"
foreground = "#FFFFFF"
width = 200`

I have tried searching the web but have found any real solution.

**Comment by bynect** [comment]
```
 # Display indicators for URLs (U) and actions (A).
    show_indicators = no
```

**Comment by mrgreen3** [comment]
*Kev*

**Comment by mrgreen3** [comment]
That did the trick, thank you very much ;-)
