### ISSUE TITLE
Ubuntu 22.04 - help for compilation

### ISSUE THREAD

**Issue by e1kfL0ck** [dunst-project/dunst#1321]
### Issue description

Hello, 

I'm quiet new to Linux, and I'm bit scared of compiling my own applications. I could use the default apt version, but it's version 1.5.0 from 2020-07-03 (which does not support progress bar). 

I have seen the [wiki/Dependencies](https://github.com/dunst-project/dunst/wiki/Dependencies), but I'm not sure about what packages I need. As I'm a bit scared of installing wrong packages that may break some stuff. Some help or a walktrough would be very much of a spine out of my feet.

Thank you in advance for any help or guidance you can provide!

### Installation info

- Window manager / Desktop environment: `x11 + i3wm`
- Distro: `Ubuntu 22.04`

**Comment by bynect** [comment]
Hello, are you trying to build the latest version tag or the main branch?

Anyway, the dependencies written in the wiki should cover most of what's needed, however I can't confirm if every package is exact since I don't have a debian at hand.

As said in the wiki you will need both the libraries and developer version of the libraries:

``` sudo apt install libdbus-1-dev libx11-dev libxinerama-dev libxrandr-dev libxss-dev libglib2.0-dev libpango1.0-dev libgtk-3-dev libxdg-basedir-dev libgdk-pixbuf-2.0-dev
```

Note: if you are compiling the latest branch you can decide to build only wayland/xorg support (this means less package to install). 

The process should be something along the lines of

```
git clone dunst-link...
cd dunst
make all
sudo make install
```

If you need explanation about some of the steps don't be afraid to ask 👍

**Comment by e1kfL0ck** [comment]
Hello, 

Thanks for your answer. I decided to build the latest version tag as it's a release I feel safer. 
Is it really true ? What are the pros and cons ?  

You were right about the libraries to install, the command was just missing `libnotify-dev`. 

For the compilation and installation I followed the [wiki/Installation](https://github.com/dunst-project/dunst/wiki/Installation) and used :

```bash
make
sudo PREFIX=/usr checkinstall
```

And it did the trick !  It less scary now that it went perfectly smoothly. 

Thanks again :smiley:

**Comment by bynect** [comment]
> Hello, 
> 
> Thanks for your answer. I decided to build the latest version tag as it's a release I feel safer. 
> Is it really true ? What are the pros and cons ?  
> 
> You were right about the libraries to install, the command was just missing `libnotify-dev`. 
> 
> For the compilation and installation I followed the [wiki/Installation](https://github.com/dunst-project/dunst/wiki/Installation) and used :
> 
> ```bash
> make
> sudo PREFIX=/usr checkinstall
> ```
> 
> And it did the trick !  It less scary now that it went perfectly smoothly. 
> 
> Thanks again :smiley: 

Yes, the version tag should be a little more tested.

Libnotify is needed for dunstify (you can build dunst without it if you want)

I forgot that on debian you have to use checkinstall :o

Anyway I am glad that everything went smoothly

**Comment by e1kfL0ck** [comment]
I'm still in the configuration, and I have used the default config file in `/etc/xdg/dunst/dunstrc` by copying it to `.config/dunst/dunstrc`

However when running `dusnt -print`, I have the following errors :

```
WARNING: Setting geometry in section global doesn't exist
WARNING: Setting notification_height in section global doesn't exist
WARNING: Setting startup_notification in section global doesn't exist
WARNING: Setting verbosity in section global doesn't exist
```

Where can I find a default file to work with ?

**Comment by bynect** [comment]
It seems like the file was outdated. You can try the dunstrc file on github

**Comment by e1kfL0ck** [comment]
I can't find the file on github even with the research bar, can tell me where I can find it ? Thanks

**Comment by bynect** [comment]
> I can't find the file on github even with the research bar, can tell me where I can find it ? Thanks

It is on the toplevel of the repository and it is called dunstrc

**Comment by e1kfL0ck** [comment]
Found it, thanks. So strange I couldn't find it. Is it possible to use rules to modify the geometry of a notification ?

**Comment by bynect** [comment]
> Found it, thanks. So strange I couldn't find it. Is it possible to use rules to modify the geometry of a notification ?

As of now you can't unfortunately. We expect to add that in a future version (there is an issue tracking this feature)

**Comment by bynect** [comment]
I'll close this. If you need further help let me know
