### ISSUE TITLE
Dunst wakes or stops my computer from sleeping suspending

### ISSUE THREAD

**Issue by WorldsEndless** [dunst-project/dunst#1338]
I love Dunst, and for the most part it works great for me. One issue that I have with it is wmhen I press my sleep button on my laptop, though: Dunst will fire notifications that my wifi has gone offline and this interupts or supercedes the sleep operation, which then happily reports, "hey, we're awake and back online again!" This reminds me of my light-sleeping children&#x2026;

This probably isn't technically a Dunst issue, but this seems like the best place to find others who have confronted the same issue. How can I get my machine to just sleep/suspend without Dunst waking it immediately?

```sh
$> dunst -v
Dunst - A customizable and lightweight notification-daemon 1.10.0 (2024-02-19)
```

**Comment by bynect** [comment]
Maybe you could try pausing the notifications when the pc goes into sleep and unpausing them later. Depending on what you use for sleep you should have a way to attach scripts before and after

**Comment by WorldsEndless** [comment]
What's the easiest way to pause Dunst? I'm sure  this is a RTFM thing; maybe I can script it...

**Comment by bynect** [comment]
```dunstctl set-paused true``` should do the trick

For more information see `man dunstctl` 👍🏻

**Comment by WorldsEndless** [comment]
that'll do it, I'm sure! Hopefully someone here benefits from this, as I had searched around everywhere
