### ISSUE TITLE
All notifications get closed together

### ISSUE THREAD

**Issue by lordofscripts** [dunst-project/dunst#1355]
I am using `esiqveland/notify` for notifications. I am on a Raspberry π which has the `dunst` notification daemon.

The daemon is configured as default:
- different colors for urgency
- full markup
- actions supported
- `dmenu` is installed. I noticed it is supposedly invoked for actions.

In my app I setup 3 notifications with Low, Normal & Critical urgency and then fire them one by one in succession.

But:
- all notifications get the same background/foreground colors regardless of urgency. An (U) is prepended for urgent only but nothing for Low urgency.
- The 3 notifications pop up with separators BUT **left clicking** on ONE closes ALL three rather than the one I clicked on.
- Despite the Cancel & Open actions being setup in each of them there is no visual in the notification body. When I **middle click** (interact with actions), no context menu appear and all 3 get closed.

The global config has these mouse settings:

`
mouse_left_click= close_current
mouse_middle_click= do_action,close_current
mouse_right_click= close_all
`

**Comment by bynect** [comment]
Please include a log from 

dunst -verbosity debug

**Comment by lordofscripts** [comment]
I was thinking about it during my sleep and woke up with a hypothesis.

In my code I open a SINGLE session and with it I fire all 3 notifications. When I click on ONE then ALL get closed.

My hypothesis is that perhaps for every notification I must do an Open/Closein other words, connect, compose & send ONE, wait for actions/closing, and then terminate the connection. That as opposed to using the same connection to send multiple.

I am refactoring to verify my hypothesis.

**Comment by lordofscripts** [comment]
My nightly enlightenment was correct, _for every notification one must do open/close._ Otherwise they get bundled as a group and close as a group.
