### ISSUE TITLE
Remove progress bar label (number between brackets)

### ISSUE THREAD

**Issue by reassuringgreet** [dunst-project/dunst#1363]
Hi! I'm trying to set up the volume slider for dunst, and I can't figure out how to change the label of the progress bar. I have my notification set up like this:

dunstify -a "changeVolume" -u low -i GIBRISHICON -h string:x-dunst-stack-tag:myvolume -h int:value:"$volume" "  Volume: ${volume}%"

which produces this:
![image](https://github.com/dunst-project/dunst/assets/8457771/d4122f37-1136-4297-8895-f3932d89184f)

As you can see, the volume is followed by the progress bar number between brackets. I'd like to remove that number, but removing the -h int:value:"$volume" removes the progress bar. Is there anyway not to print this value?

![image](https://github.com/dunst-project/dunst/assets/8457771/6b0ea596-d21e-40f3-90eb-3672bfe79944)

**Comment by bynect** [comment]
Hello, does your format string contain a %p? That's the format specifier for `[n%]`

**Comment by reassuringgreet** [comment]
Thanks a lot, that fixed it, I hadn't seen the definition on the dunstrc file.
