### ISSUE TITLE
WARNING: no icon found in path: 'dialog-information' is making journalctl hard to use.

### ISSUE THREAD

**Issue by misterhackerman** [dunst-project/dunst#1364]
### Issue description

<details>
<summary>journalctl log</summary>
Jun 25 11:21:21 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:31 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:36 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:37 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:37 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:37 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:37 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:37 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:37 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:37 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:38 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:39 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:39 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:40 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:41 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:54 M4CH1N3 pipewire-pulse[31099]: mod.protocol-pulse: client 0x5571a9022cb0 [PulseAudio Volume Control]: ERROR command:104 (SEND_OBJECT_MESSAGE) tag:3241 error:3 (Invalid argument)<br>
Jun 25 11:21:54 M4CH1N3 pipewire-pulse[31099]: mod.protocol-pulse: client 0x5571a9022cb0 [PulseAudio Volume Control]: ERROR command:104 (SEND_OBJECT_MESSAGE) tag:3242 error:3 (Invalid argument)<br>
Jun 25 11:21:56 M4CH1N3 bluetoothd[51705]: /org/bluez/hci0/dev_AC_12_2F_F0_12_B3/sep2/fd0: fd(31) ready<br>
Jun 25 11:21:57 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:58 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:58 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:21:59 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:22:00 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:22:00 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:22:00 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:22:00 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:22:00 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
Jun 25 11:22:00 M4CH1N3 dunst[31192]: WARNING: No icon found in path: 'dialog-information'<br>
</details>

### Installation info

- Version: `1.11.0 (2024-04-15)`
- Install type: `pacman`
- Window manager / Desktop environment: `dwm`
- Distro: `arch`

happens with default dunstrc, and even without the dunstrc file.

to reproduce easily start dunst in a terminal, and run `notify-send "test"`

**Comment by bynect** [comment]
This has to do with a icon being predefined by default in the settings. I will probably change this next release

**Comment by misterhackerman** [comment]
Thanks alot.
