### ISSUE TITLE
Is there any way to add animations in dunst?

### ISSUE THREAD

**Issue by nekupaw** [dunst-project/dunst#1366]
Hi, I hope this is the right place here.

Is there any simple way to add some kind of slide animation to entry?
As if the notification would slide right to the left side of the screen to its normal position.

I am looking forward to answers :3

### Installation info

- Version: `1.11.0 (2024-04-15)`
- Install type: `pacman`
- Window manager / Desktop environment: `hyprland`
- Distro: `Manjaro`

**Comment by bynect** [comment]
at the moment dunst does not have any animations. Maybe you can see if there are other programs that make a slide in animation

**Comment by kingdomkind** [comment]
For anyone in future on hyprland (as this person was), you can add a slide animation to dunst via the following line in your configuration:
layerrule = animation slide, notifications
