### ISSUE TITLE
Notifications with same text but different urgency (or other hints) still stack

### ISSUE THREAD

**Issue by anko** [dunst-project/dunst#137]
If I do...

```
$ notify-send what
$ notify-send --urgency critical what
```

... then `dunst` shows `(1) what` in the _normal_ urgency colour. As in, it stacks the messages by **text content**, disregarding the **differing urgencies**.

If I `notify-send` in the opposite order, the same text `(1) what` is displayed, but in the _critical_ urgency colour.

In the benign case, this is confusing. In the worst case, it could lead to urgent messages going unnoticed.

---

I think notification stacking should be toggleable, if not removed altogether.

Here's why I think it's bad: There are innumerable properties that might differentiate notifications, such as the background colour specified in `notify-send`'s hints (or indeed any other arbitrary contents of any other passed hints), the requested icon, urgency level, et cetera. Trying to hash these together to determine whether two notifications are "equal" (for some utopian _global_ definition of "equal") opens a whole other can of worms.

Maybe it has a place in the override rules section of the config file? Rules could specify how they want notifications' equality to be determined.

**Comment by tsipinakis** [comment]
Fixed in 6c9de72c7d3b74abb6d34767d854776c63203ba8.
