### ISSUE TITLE
Resolve `~` or `$HOME` in `icon_path`

### ISSUE THREAD

**Issue by danielwerg** [dunst-project/dunst#1371]
### Issue description

dunst doesn't resolve `~` or `$HOME` in `icon_path`. It was [claimed](https://github.com/dunst-project/dunst/issues/350#issuecomment-477550687) to be fixed in `1.4` by @tsipinakis and [here](https://github.com/dunst-project/dunst/issues/520#issuecomment-398317087) by @bebehei  so I'm little puzzled.

### Installation info

- Version: `1.11.0 (2024-04-15)`
- Install type: `package`
- Window manager / Desktop environment: `Hyprland`
- Distro: `Artix`

<details>
<summary>Minimal dunstrc</summary>

```ini
enable_recursive_icon_lookup = false
# doesn't work
icon_path = ~/.config/dunst/icons/
# also doesn't work
#icon_path = $HOME/.config/dunst/icons/
# works
#icon_path = /home/<USER>/.config/dunst/icons/
```
</details>

Related: #350 #520

**Comment by bebehei** [comment]
Is this a regression?

**Comment by danielwerg** [comment]
> Is this a regression?

I haven't edited dunst config before so not sure.

**Comment by bynect** [comment]
I'm not sure if this is a regression. the problem seems to lie here https://github.com/dunst-project/dunst/blob/844167abe1f7845bfe7c81797da36be28362e7b9/src/icon.c#L241

I will try to add the recognition of ~

**Comment by zappolowski** [comment]
@danielwerg could you try #1383?
