### ISSUE TITLE
[Q] invoke dmenu revers order

### ISSUE THREAD

**Issue by biopsin** [dunst-project/dunst#1375]
![2024-08-27-195254_3840x2160_scrot](https://github.com/user-attachments/assets/5f6c0160-db27-4f52-ac05-a3a259b5db5a)

### Issue description
Hi, i need to revers the order dmenu outputs open notifications, the order in picture is "dmenu top" = "bottom notification" I would like to align it equal top to bottom?

### Installation info

- Version: `1.11`
- Install type: `pkg`
- Window manager / Desktop environment: `cwm`
- Distro: `void`

<details>
<summary>Minimal dunstrc</summary>

```ini
dmenu = /usr/local/bin/dmenu

#####dmenu bin
/usr/bin/dmenu -i -l 9 -x 1560 -w 720 -fn "Dejavu Sans:style=Book:pixelsize=16" \
	-nb "#FDF6E3" -nf "#555555" -sb "#657B83" -sf "#FFFFFF"

```
</details>

**Comment by bynect** [comment]
could it be that dmenu automatically orders entry by alphabetical order?

**Comment by biopsin** [comment]
no the dmenu entries are ordered but in reverse order

**Comment by bynect** [comment]
I'm looking at this. could it be that you are using a particular notification ordering? or are you using the default one (last arrived at the top)?

also what did you do to open that notification menu? exact command

**Comment by biopsin** [comment]
Yes default; last is top. Default binary location as in `dunstrc` but its a symlink to local/bin with extra dmenu config settings, nothing that would order on a custom level. 
I guess it would also make sense to order/group in a mixed action nonaction condition all action notifications are stacked above all nonaction notifications.

**Comment by bynect** [comment]
what did you do to pop up that menu exactly?

**Comment by biopsin** [comment]
bind-key 4M-space	- "dunstctl context" or is there something else you are thinking of?

**Comment by bynect** [comment]
just wanted to be sure. I think the problem lies in this function here https://github.com/dunst-project/dunst/blob/d2faa87081329a31726082837d5197199be53f50/src/menu.c#L296

I will try to fix the order in some time

**Comment by bynect** [comment]
Hello, I successfully reproduced this problem and it turns out it was just a linked list being reversed.

**Comment by biopsin** [comment]
@bynect Hi, thank you for looking into it, will test the patch later today both for vertical and horisontal dmenu context.
