### ISSUE TITLE
WARNING: Offset has two values, separated by an 'x'

### ISSUE THREAD

**Issue by xienuss** [dunst-project/dunst#1388]
### Issue description
as written in [here](https://github.com/dunst-project/dunst/blob/master/docs/dunst.5.pod) offset's variable is `offset = (horizontal, vertical)` _example: offset = (10, 300)_. However, when i write it in config and then starting `dunst` it gives the warning from title of this issue and ignores the offset line
(sorry if something unclear here)

### Installation info

- Version: `1.11.0 (2024-04-15)`
- Install type: `package`
- Window manager / Desktop environment: `Hyprland`
- Distro: `Arch Linux`

<details>
<summary>Minimal dunstrc</summary>

```ini
    offset = (10, 10)
```
</details>

EDIT:nvm im stupid, the warning litteraly is the answer, it starter working with `offset = 10x10`

**Comment by bynect** [comment]
> ### Issue description
> as written in [here](https://github.com/dunst-project/dunst/blob/master/docs/dunst.5.pod) offset's variable is `offset = (horizontal, vertical)` _example: offset = (10, 300)_. However, when i write it in config and then starting `dunst` it gives the warning from title of this issue and ignores the offset line
> (sorry if something unclear here)
> 
> ### Installation info
> 
> - Version: `1.11.0 (2024-04-15)`
> - Install type: `package`
> - Window manager / Desktop environment: `Hyprland`
> - Distro: `Arch Linux`
> 
> <details>
> <summary>Minimal dunstrc</summary>
> 
> 
> ```ini
>     offset = (10, 10)
> ```
> </details>
> 
> EDIT:nvm im stupid, the warning litteraly is the answer, it started working with `offset = 10x10`

This (a,b) syntax will be used from the new version onwards
