### ISSUE TITLE
Recent builds have missing icons and weird window dimensions

### ISSUE THREAD

**Issue by Samueru-sama** [dunst-project/dunst#1392]
### Issue description

Here is how the notifications used to look on my system using the last stable build of dunst (upper right corner): 

![image](https://github.com/user-attachments/assets/66588eac-254c-4063-a4ee-b707f8990050)

Here is how the look using dunst-git ([and also happens with this appimage build from the master branch](https://github.com/Samueru-sama/dunst/actions/runs/11643737551))

![image](https://github.com/user-attachments/assets/e8a0e5bf-894a-4f09-bb7f-b6da40eff436)

Icons are gone and the notifications have weird window dimensions. 

I noticed dunst gave me this warning: **MESSAGE: Using legacy offset syntax NxN, you should switch to the new syntax (N, N)** so what my config is now obsolete? so I tested removing it and launching dunst with defaults.

![image](https://github.com/user-attachments/assets/e26c56e6-7325-4547-870e-fc0d5073d4b9)

Also when my music player sends notifications I get this error: 

![image](https://github.com/user-attachments/assets/6d58ff71-a103-4cbf-ad0c-c965d9260767)

So it seems the issue is just the icons and the window size is that I need to update my config, because with default settings this is how the stable build looks (has working icons): 

![image](https://github.com/user-attachments/assets/d1d4757f-6266-4abc-918b-21e68af3ea41)

### Installation info

- Version: `v1.11.0-92-g9d3c91a`
- Install type: `Dunst-git aur package (and also happens with an appimage that I make when built on the master branch)`
- Window manager / Desktop environment: `i3-wm`
- Distro: `Artix`

# [Dunstrc here](https://github.com/Samueru-sama/dotfiles/blob/main/Local/config/dunst/dunstrc)

</details>

**Comment by bynect** [comment]
Hello.

The icons and size are actually correct. This is yet to be properly documented (it is testing). But if you have any suggestions on how to make it painless to switch and document it would be great.

Rationale for not including icons in the backed in config: some systems don't have the icons requested and you have to do extra steps to remove the icon. This way if you want them you can easily add to dunstrc, otherwise they will be without icon


The height issue is due to dynamic height. Now the height can be variable between (min, max) just like the width. If you provide a single height it will be read as a fixed height (min=max). This means that you can fix your problem by doing
size = ( , oldsize)

The last thing about missing icons messages. I don't know if it is normal. Are the deadbeef icons present in the themes? 
If the icons is not found by dunst this logging seems right though

**Comment by Samueru-sama** [comment]
> Hello.
> 
> The icons and size are actually correct. This is yet to be properly documented (it is testing). But if you have any suggestions on how to make it painless to switch and document it would be great.
> 
> Rationale for not including icons in the backed in config: some systems don't have the icons requested and you have to do extra steps to remove the icon. This way if you want them you can easily add to dunstrc, otherwise they will be without icon
> 
> The height issue is due to dynamic height. Now the height can be variable between (min, max) just like the width. If you provide a single height it will be read as a fixed height (min=max). This means that you can fix your problem by doing `height = (0 , oldheight)`

Thanks, I was able to fix the height issue.

> The last thing about missing icons messages. I don't know if it is normal. Are the deadbeef icons present in the themes? If the icons is not found by dunst this logging seems right though

The icon of deadbeef is not in the Adwaita icon theme, however I have `enable_recursive_icon_lookup` enabled which means it should still try to find it right? 

With that said, I don't remember ever seeing the deadbeef icon on my notification and it still shows the album art of the current playing track, so maybe that's normal? however the error about the missing icon does not happen with the stable release.

And also the default icons I used to get, which is that light bulb and a warning sign for critical notifications are gone.

**Comment by bynect** [comment]
you should be able to add to
```
[urgency_normal]
default_icon = dialog-information
...
```

**Comment by bynect** [comment]
I will add this to the default dunstrc to keep backward compatibility of the config

**Comment by bynect** [comment]
> The icon of deadbeef is not in the Adwaita icon theme, however I have `enable_recursive_icon_lookup` enabled which means it should still try to find it right?
> 
> With that said, I don't remember ever seeing the deadbeef icon on my notification and it still shows the album art of the current playing track, so maybe that's normal? however the error about the missing icon does not happen with the stable release.

if it is in any of the themes you have installed it should find it. however that error means that it doesn't find anywhere. so it is provided by an actual theme you have installed? The changes to icon lookup where made in #1365 btw

**Comment by bynect** [comment]
for the problem of icon error that you found. it is true and it is actually an error. the only change I made is that I before it was an INFO message (so it was hidden). Now it is a warning.
but I think there is something wrong with the theme search. Further work is required. Thanks for reporting 👍🏻 
In the meantime you can check the dunstrc in #1393

**Comment by Samueru-sama** [comment]
> you should be able to add to
> 
> ```
> [urgency_normal]
> default_icon = dialog-information
> ...
> ```

Oh now I get the icons back, but that's odd, with the old dunst I still had `#default_icon = /path/to/icon` and somehow it still showed those  icons? Anyways now it works which is the important part!

> if it is in any of the themes you have installed it should find it. however that error means that it doesn't find anywhere. so it is provided by an actual theme you have installed? The changes to icon lookup where made in https://github.com/dunst-project/dunst/pull/1365 btw

I'm very sorry, it seems I don't have a deadbeef icon in my themes, I'm actually surprised because I have the Papirus icon theme and that one usually has everything.

I don't remember ever seeing the DeaDBeeF icon in my notifications, it instead sends the album art for display, so the only difference between before and now is that **now the warning works** and not that the icon can't be find 😅

>for the problem of icon error that you found. it is true and it is actually an error. the only change I made is that I before it was an INFO message (so it was hidden). Now it is a warning.

Yeah it was this.

I think this issue can be closed now right?

**Comment by bynect** [comment]
> Oh now I get the icons back, but that's odd, with the old dunst I still had `#default_icon = /path/to/icon` and somehow it still showed those icons? Anyways now it works which is the important part!

because before the icon names were hardcoded in dunst source code. now they can easily be specified in the dunstrc if needed.


> I think this issue can be closed now right?

👍🏻

**Comment by bynect** [comment]
For future reference, read the RELEASE_NOTES for 1.12 on how to fix the height change
