### ISSUE TITLE
1.12.0 fails to render body on notifications when there are tall Unicode characters only in title

### ISSUE THREAD

**Issue by Architector4** [dunst-project/dunst#1406]
### Issue description

My test case is this command:

    dunstify "⛧" "hi"

On Dunst 1.11.0, this shows two lines perfectly:

![image](https://github.com/user-attachments/assets/5f4ba47e-fa82-48b5-b533-b2db3870edab)

On Dunst 1.12.0, this breaks:

![image](https://github.com/user-attachments/assets/a72a7da6-5a7d-488a-86ad-f0d68a1b3943)

The extra line can still be shown if the minimum/constant height is set to a big enough value, but that's obviously suboptimal.

It doesn't break if both title and body have such a character, nor if only the body has one, nor if the body text is long enough.

### Installation info

- Version: `1.12.0 (2024-11-30)`
- Install type: `package`
- Window manager / Desktop environment: `i3wm`
- Distro: `Arch Linux`

Two screenshots above are done with no `dunstrc` in place, i.e. on completely default configuration.

**Comment by bynect** [comment]
I guess it has to do with the dynamic height changes.

Does it occur with unicode special chars in general or only with tall ones?

**Comment by Architector4** [comment]
Only with tall ones, it seems. Greek and Cyrillic letters and random arrows and weird spaces go through just fine.

Seems it also breaks with emojis too; a title of just "😁" causes the issue as well.

**Comment by bynect** [comment]
> Only with tall ones, it seems. Greek and Cyrillic letters and random arrows and weird spaces go through just fine.
> 
> Seems it also breaks with emojis too; a title of just "😁" causes the issue as well.

Could you try a few things

* add a minimum height of 1 like height = (1,300)
* test different values of vertical alignment
* try the provided dunstrc

**Comment by Architector4** [comment]
Side note, a usable hack workaround for anyone else experiencing this may be to change `format` string like this:

    format = "<b>%s</b>\n%b\n "

Compared to default setting, this appends a newline and a word joiner (special Unicode character; it's only significance here is that it's rendered invisible, and doesn't get trimmed like a space in its place seemingly does).

This results in one extra line worth of empty space at the end of every notification, but at least it shows all the text now lol

**Comment by bynect** [comment]
I will look into possible solutions as soon as I can

**Comment by bynect** [comment]
I can replicate this. however still no idea why this happened

**Comment by Architector4** [comment]
For reference, I did `git bisect` between v1.11.0 and v1.12.0, observing if the issue is present or not, and it points to commit b72d021fa55a6f4775a24fea926fbe018249c5d5 as the first bad one.

**Comment by bynect** [comment]
yes I guessed so. I will make a pr fix soon

**Comment by bynect** [comment]
@Architector4 could you try this new pr?

**Comment by Architector4** [comment]
> @Architector4 could you try this new pr?

Seems to be working perfectly now.

**Comment by bynect** [comment]
Good, I'll merge then

**Comment by bynect** [comment]
@Architector4 the version with the fix has been released (v1.12.1)
