### ISSUE TITLE
tall unicode/emoji character in title causes word wrap setting to be ignored in body

### ISSUE THREAD

**Issue by 2084x** [dunst-project/dunst#1410]
### Issue description
when a tall unicode/emoji character is present in the notification title, long bodies are shortened with an ellipse instead of word wrapping. 

reproduce with the provided config and this test command: 

`dunstify "💖 test message" "this is a long sentence that will not word wrap"`

other things to note:
- if the title is also long enough to wrap, then the body wraps as expected.
- when using the default config I experience the same issue as https://github.com/dunst-project/dunst/issues/1406 which is presumably related to this one

### Installation info

- Version: `1.12.0 (2024-11-30)`
- Install type: `package`
- Window manager / Desktop environment: `dwm`
- Distro: `arch linux`

<details>
<summary>Minimal dunstrc</summary>

```ini
[global]
    height = (0, 350)
    font = Monospace 12
```
</details>

**Comment by IMythx** [comment]
i got the same issue too....sometimes the body is even hidden entirly but idk how....so i cant replicate it

**Comment by IMythx** [comment]
i have the same issue too....sometimes the body is even hidden entirly but idk how....so i cant replicate it

**Comment by Architector4** [comment]
Sorry, I mistyped my workaround the first time around. It should actually be:

    format = "<b>%s</b>\n%b\n⁠"

There is an invisible WORD JOINER character right before the quotation mark at the end, which is needed for this to work in case of my issue.
