### ISSUE TITLE
[help] How do I ignore notifications with more than one body?

### ISSUE THREAD

**Issue by tripplehelix** [dunst-project/dunst#1414]
I need something like below, where it's ignoring notifications from `xfce4-power-manager` if it contains `*Your Battery is discharging*` or `*Your Battery is charging*`. As I need the other notifications.

```
[ignore]
#    # This notification will not be displayed
	appname = xfce4-power-manager
	body = *Your Battery is discharging* | *Your Battery is charging*
	skip_display = true
```

**Comment by bynect** [comment]
enable extended regular expression.
then this should work
`.*(Your Battery is discharging|Your Battery is charging).*`

**Comment by tripplehelix** [comment]
Ah thanks, that's what I was missing!
