### ISSUE TITLE
block notifications if there is a window in fullscreen mode

### ISSUE THREAD

**Issue by aanatoly** [dunst-project/dunst#142]
Hi 
Can you implement a feature that block notifications if there is a window in fullscreen mode

I wrote simple app to monitor if there is any
https://gist.github.com/aanatoly/9263530

**Comment by TheDoctorsLife** [comment]
I support this.

**Comment by bebehei** [comment]
On [my branch `fullscreen`](https://github.com/dunst-project/dunst/compare/master...bebehei:fullscreen), there are the neccessary changes implemented. "It works".

At the end of the day, it should be configurable by a rule, which notifications get shown during fullscreen.

```
[fs_urgent]
    has_urgency = "critical"
    set_show_on_fs = yes
```

But in terms of cleanyness, I have to improve the commits. I will create a PR, if the code quality is mergeable.

**Comment by bebehei** [comment]
I've reafactored my old branch and have fixed all issues in code.

Is somebody volunteering and will give feedback? I'd love to have some external feedback. All I can say about it, it works for me very well.

```
git clone https://github.com/bebehei/dunst
cd dunst
git checkout fullscreen
make
sudo make install
```

This introduces a rule field `show_on_fs`:
```
# show critical notifications also on fullscreen
[fs_enable_critical]
    msg_urgency = critical
    show_on_fs = yes
```
