### ISSUE TITLE
test_dbus_cb_dunst_RuleList fails on s390x

### ISSUE THREAD

**Issue by dcermak** [dunst-project/dunst#1421]
I have tried bumping the dunst Fedora package from 1.11.0 to 1.12.0 or 1.12.1 and for both version bumps, I get a failure in the test `test_dbus_cb_dunst_RuleList` on s390x **only**:
https://github.com/dunst-project/dunst/blob/e38001ffdeca4ac06ba3e14f9851dcb0889d8319/test/dbus.c#L619

All other architectures (x86_64, aarch64 and ppc64le) are fine.

On s390x, the testsuite outputs:
```
# snip
PASS test_dbus_cb_dunst_RuleEnable:  (4init_second_pass: a 495660997, c 2147483647, state 123915249
init_second_pass: a 495660997, c 2147483647, state 123915249
526 ticks, 0.005 sec)
FAIL test_dbus_cb_dunst_RuleList: boolean (test/dbus.c:649) (3053 ticks, 0.003 sec)
PASS assert_methodlists_sorted:  (86 ticks, 0.000 sec)
# snip
```

You can reproduce it with the following `Dockerfile`:
```Dockerfile
FROM registry.fedoraproject.org/fedora:latest

RUN set -euo pipefail; \
    dnf -y build-dep dunst; \
    dnf -y install git make awk; \
    dnf -y clean all; rm -rf /var/log/

RUN git clone https://github.com/dunst-project/dunst

WORKDIR /dunst

RUN git checkout v1.12.1
RUN make -j$(nproc)
RUN make -j$(nproc) test
```

by running `buildah bud --layers --arch=s390x .` or `docker build --platform=s390x .`
(you need to have a qemu-s390x-static installed, but nowadays podman pulls that in as a dependency).

Any idea what's the issue here? Would it be fine to just skip this test on s390x? (tbh, I have my honest doubts that anyone actually installs dunst on a mainframe, but you never know…)

**Comment by bynect** [comment]
Offending line

https://github.com/dunst-project/dunst/blob/e38001ffdeca4ac06ba3e14f9851dcb0889d8319/test%2Fdbus.c#L649

Could it be that on s390x the boolean values are represented differently? From a quick search it seems it is a big endian architecture.

**Comment by alebastr** [comment]
`bool` and `gboolean` are represented differently on any platform. `gboolean` is a type alias for `gint`, and `bool` is implementation-defined, but commonly implemented as 1 byte.

`g_variant_dict_lookup(&d, "enabled", "b", &boolean)` takes a pointer to a `gboolean` and writes TRUE (0x00000001) in a platform byte order. On a little-endian platform this would write the expected 1 to `bool *` and corrupt the next few bytes.

Similarly, `g_variant_dict_insert(&dict, "enabled", "b", &r->enabled)` will read `sizeof(gint)` bytes from the provided pointer and assume TRUE if any byte is non-zero.

This fixes the immediately greppable offenders, but I haven't looked deeper.
```
diff --git a/src/rules.h b/src/rules.h
index bdeb170..9f99c01 100644
--- a/src/rules.h
+++ b/src/rules.h
@@ -56,7 +56,7 @@ struct rule {
         char *format;
         char *script;
         enum behavior_fullscreen fullscreen;
-        bool enabled;
+        gboolean enabled;
         int progress_bar_alignment;
         char *set_stack_tag; // this has to be the last modifying rule
 };
diff --git a/test/dbus.c b/test/dbus.c
index 77d7d42..66e9e9f 100644
--- a/test/dbus.c
+++ b/test/dbus.c
@@ -639,7 +639,7 @@ TEST test_dbus_cb_dunst_RuleList(void)
         g_variant_dict_init(&d, dict);
 
         char *str;
-        bool boolean;
+        gboolean boolean;
 
         ASSERT(g_variant_dict_lookup(&d, "name", "s", &str));
         ASSERT_STR_EQ("testing RuleList", str);
```

**Comment by bynect** [comment]
> `bool` and `gboolean` are represented differently on any platform. `gboolean` is a type alias for `gint`, and `bool` is implementation-defined, but commonly implemented as 1 byte.
> 
> `g_variant_dict_lookup(&d, "enabled", "b", &boolean)` takes a pointer to a `gboolean` and writes TRUE (0x00000001) in a platform byte order. On a little-endian platform this would write the expected 1 to `bool *` and corrupt the next few bytes.
> 
> Similarly, `g_variant_dict_insert(&dict, "enabled", "b", &r->enabled)` will read `sizeof(gint)` bytes from the provided pointer and assume TRUE if any byte is non-zero.
> 
> This fixes the immediately greppable offenders, but I haven't looked deeper.
> ```
> diff --git a/src/rules.h b/src/rules.h
> index bdeb170..9f99c01 100644
> --- a/src/rules.h
> +++ b/src/rules.h
> @@ -56,7 +56,7 @@ struct rule {
>          char *format;
>          char *script;
>          enum behavior_fullscreen fullscreen;
> -        bool enabled;
> +        gboolean enabled;
>          int progress_bar_alignment;
>          char *set_stack_tag; // this has to be the last modifying rule
>  };
> diff --git a/test/dbus.c b/test/dbus.c
> index 77d7d42..66e9e9f 100644
> --- a/test/dbus.c
> +++ b/test/dbus.c
> @@ -639,7 +639,7 @@ TEST test_dbus_cb_dunst_RuleList(void)
>          g_variant_dict_init(&d, dict);
>  
>          char *str;
> -        bool boolean;
> +        gboolean boolean;
>  
>          ASSERT(g_variant_dict_lookup(&d, "name", "s", &str));
>          ASSERT_STR_EQ("testing RuleList", str);
> ```

Thank you very much for figuring this out

**Comment by bynect** [comment]
Keeping it open because there could be other occurrences of this

**Comment by fossdd** [comment]
Thanks, this commit fixes the tests for s390x, all other tests pass.

**Comment by bynect** [comment]
> Thanks, this commit fixes the tests for s390x, all other tests pass.

can I merge #1423 then?

**Comment by fossdd** [comment]
Yes, SGTM!
