### ISSUE TITLE
add support for more image formats for icons

### ISSUE THREAD

**Issue by knopwob** [dunst-project/dunst#150]
Currently only png is supported for icons.

**Comment by ehasting** [comment]
Any plans for svg?

gettings this in the log:
Could not load icon: '/usr/share/icons/hicolor/scalable/apps/hexchat.svg'

**Comment by Xylemon** [comment]
@ehasting see this PR: https://github.com/knopwob/dunst/pull/223

I don't know why it hasn't been accepted yet but should do what you want.

**Comment by wedens** [comment]
yeah. many modern icon themes use svg

**Comment by bijanebrahimi** [comment]
I Managed to convert my desired Icon sets to PNG format just to make notificationIcons working for now untill [pull#223](https://github.com/knopwob/dunst/pull/223) is accepted.

**Comment by Xylemon** [comment]
I highly recommend checking this patch: https://github.com/buglloc/dunst/commit/b6f56be97ba01d93843b206bbdab63b030e6e450

**Comment by Eizen** [comment]
Fixed in 7ba4c1c
