### ISSUE TITLE
Icon support inline raw image data

### ISSUE THREAD

**Issue by knopwob** [dunst-project/dunst#151]
libnotify allows notifications to include raw image data. Pidgin uses this to display user pictures in notifications.
[An example of how this can be implemented.](https://github.com/GNOME/notification-daemon/blob/11ab2f7949477efaa63db851b3446b4a774ba02a/src/nd-notification.c#L484)

**Comment by Xylemon** [comment]
Any update on this?

**Comment by pmiddend** [comment]
From what I gather, spotify uses this feature, too. Any update on this feature?

**Comment by maximbaz** [comment]
Sadly this repo doesn't seem to be maintained anymore. But for everyone keen for this feature, I've just tried https://github.com/buglloc/dunst where raw images are implemented -- works pretty neat. Send thanks to @buglloc :+1:

**Comment by hobarrera** [comment]
Correct, it's not maintained any more, see #228.

**Comment by Eizen** [comment]
Fixed in a6d9626

**Comment by hobarrera** [comment]
Really glad to see this spinning back to life. Big thanks!
