### ISSUE TITLE
Flickering grey boxes with gnome-screensaver's locked screen (instead of notifications)

### ISSUE THREAD

**Issue by blueyed** [dunst-project/dunst#153]
When using gnome-screensaver to lock the screen, any notifications from dunst cause a grey, flickering area where the notifications would be displayed.

TEST CASE:
1. trigger a notification to be displayed with dunst, e.g. `notify-send -t 0 "foo"`
2. Start gnome-screensaver and lock the screen (e.g. `/usr/bin/gnome-screensaver-command -l`)
3. Press a key to get the unlock dialog

dunst master
gnome-screensaver 3.6.1-0ubuntu7

**Comment by Eizen** [comment]
Since this is old, i'm gonna close it but feel free to reopen or create a new issue if the problem still persists.
