### ISSUE TITLE
Headless Mode

### ISSUE THREAD

**Issue by knopwob** [dunst-project/dunst#155]
Allow dunst to receive notifications without displaying a popup for people only using the script functionality

**Comment by JindrichPilar** [comment]
:+1: 

Spliting the way described by @vivien seems pretty good. Would be nice using ``dunst-core`` with ``tmux`` on server via SSH and` `dunst`-core` ` with ``dunst-draw`` on desktop.

**Comment by fwSmit** [comment]
You can do this now with `skip_display`
