### ISSUE TITLE
Support freedesktop icon theme specification

### ISSUE THREAD

**Issue by progandy** [dunst-project/dunst#157]
I'd like to have support for the xdg icon theme specification so you only have to set a theme name and not twenty directories. Maybe allow one directory to be searched before the icon theme where you can put your own icons if needed.

http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

**Comment by Vladimir-csp** [comment]
Perhaps, you can find some useful code in [here](https://github.com/johanmalm/jgmenu)
jgmenu also supports reading icon theme from xsettings with fallback to GTK config files.

**Comment by bebehei** [comment]
My `icon_path` configuration field is [currently over 2000 chars long](https://github.com/bebehei/df/blob/3b702c47eadfa56c4fee1253803c66a82a76a739/i3/dunst/dunstrc#L41), while it could boil down to less than 20 chars. This is insane.

Current implementations of this are either unmaintained, lack scaling support or are not a common library/package. I'll probably write a fresh one for this algorithm. It'll probably give me some experience in libraries.

**Comment by Vladimir-csp** [comment]
I am keeping an eye on three thematically close independent software projects that work with icons: yours, [tint2](https://gitlab.com/o9000/tint2) and [jgmenu](https://github.com/johanmalm/jgmenu). Lightweight implementation of XDG icon theme spec would benefit many, I see collaboration potential.

**Comment by bebehei** [comment]
Thanks for mentioning tint2. On the first glance, the code for the icon theme looks quite neat, too!

https://gitlab.com/o9000/tint2/blob/master/src/launcher/icon-theme-common.c

**Comment by fwsmit** [comment]
The new implementation has been finished and merged. You can try it out by enabling it in the settings. See the man page for how to do that.
