### ISSUE TITLE
Force icon for messages

### ISSUE THREAD

**Issue by hoschi** [dunst-project/dunst#162]
Is it possible to force an icon for some filtered messages in `dunstrc`? I tried the following:

```
[test]
  summary = "*test*"
  background="#ffffff"
  iconname = weather-storm
```

But "notify-send "test" gives me the changed background font with the standard light bulb icon.

**Comment by hughdavenport** [comment]
Hmm, bug #202 also uses the new_icon, but doesn't get the same error. Could be related, maybe not though. Worth mentioning.

@hoschi, does it still crash on the latest master? Can you give a small test case that reliably reproduces it?

Cheers,

Hugh

**Comment by memeplex** [comment]
Is it possible to disable the icon instead of changing it? `icon_position = off` doesn't seem to have any effect in a rule. My current workaround is to set `new_icon = non-existent-icon`.

**Comment by Eizen** [comment]
@hoschi Would you be able to confirm if this happens with latest master?

**Comment by hoschi** [comment]
I'm not at master anymore, sorry. I switched to Arch some years ago and use the package provided https://www.archlinux.org/packages/community/x86_64/dunst/

**Comment by Eizen** [comment]
Since this is an old issue and i cannot reproduce it in HEAD, i'll close it. Feel free to reopen or create a new issue if need be.
