### ISSUE TITLE
shortcuts not working

### ISSUE THREAD

**Issue by xenogenesi** [dunst-project/dunst#171]
I'm using openbox on Linux, and dunst from about a year now but I never needed shortcuts before, now I would like to handle some url, are only available through shortcuts and dmenu?

**Comment by hughdavenport** [comment]
Hi @xenogenesi,

Have you defined shortcuts in your .dunstrc file? Can you see any error messages when you run dunst manually? `killall dunst; dunst -print`

Would openbox be stealing these keybindings?

Cheers,

Hugh

**Comment by xenogenesi** [comment]
Hi @hughdavenport , thanks and sorry but was some time ago, I still remember what I was trying to do but not details anymore.

I'm using dunst mostly to show incoming emails (*from*, *subject* and a *short abstract*), I was trying to associate a shortcut to directly *open*  (with `mutt`) an email when interesting.

I remember at the time I did some test with common shortcuts expected to work but with no effect, like ignored.

`dunst -print` show no errors.

`.config/dunst/dunstrc` define some shortcut, <kbd>ctrl</kbd>+<kbd>backspace</kbd> for history works just fine, <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>backspace</kbd> for context menu does nothing (the current terminal just *flash* like a visual bell), 
`/usr/bin/dmenu` is an *alternative* (Debian) symbolic link for `/usr/bin/dmenu.default` (`suckless-tools=40-1`) (maybe this *dmenu* implementation is the problem)

Taking a look at `dunstrc` and how *http* URLs are handled (launching the browser) given me the idea that my task would be easier with a *mailto* handler, or better a generic *proto://* (regex?) handler, how do you think?

**Comment by fwSmit** [comment]
Closing, since this is very old. Shortcuts can now be handled by your wm and it should call `dunstctl`. Feel free to reopen if needed
