### ISSUE TITLE
make separator invisible

### ISSUE THREAD

**Issue by Kaligule** [dunst-project/dunst#180]
It would be cool to be able to make the separator invisible.
That way the notifications would be separated not by a line but simply by space.

It could be done by a new Variable separator_transperency or by assigning the value "invisible" to [separator_color](https://github.com/knopwob/dunst/issues/81)

**Comment by hailbreno** [comment]
Oh boy.. I realy want this.

**Comment by lbkvu** [comment]
It's been a very long time. Any update on this?

**Comment by tsipinakis** [comment]
Implemented with #717, now all color strings support transparency.
