### ISSUE TITLE
A bit heavy on the CPU when showing notifications with a timer

### ISSUE THREAD

**Issue by wavexx** [dunst-project/dunst#194]
I noticed dunst was among the top 5 programs by used TIME on my desktop a few days ago, which looked suspicious, considering it was close to Thunderbird (!).

I was able to determine that this happens when there's one or more pending notifications being show (with a counting timer displayed) for a long time.

Not critical, but maybe worthy of being looked into. Displaying notifications shouldn't take that much cpu time.

**Comment by lzap** [comment]
Might be this one FYI: https://bugzilla.redhat.com/show_bug.cgi?id=1179258

**Comment by wavexx** [comment]
On 01/07/2015 09:36 AM, Lukáš Zapletal wrote:
> Might be this one FYI: https://bugzilla.redhat.com/show_bug.cgi?id=1179258

It's unrelated.

dunst takes noticeable cpu time while doing the notification countdown,
but it's noticeable in terms of relative usage. It's still below 1% in
the run queue on my system, but it's above "spectrwm" of total time
taken at the end of a session, and this shouldn't be.

**Comment by hughdavenport** [comment]
Hmm, that doesn't sound optimal.

Is this still an issue for you @wavexx ? Do you know how to reliably reproduce this? I'm guessing send a notification that has a timer (for a long timer)?

Cheers,

Hugh

**Comment by hughdavenport** [comment]
May be fixed in bug #169

**Comment by Eizen** [comment]
@wavexx Can you confirm if this is still an issue in latest master?

**Comment by wavexx** [comment]
CPU usage while showing several counting notifications seems reasonable now, definitely not as severe as when I reported this.
