### ISSUE TITLE
using bold tag doesn't stretch notification window properly

### ISSUE THREAD

**Issue by pale3** [dunst-project/dunst#196]
notification windows isn't displayed properly when using markups,
for example if i use bold tag in subject and new line in the begining of body, notification won't be stretched as expected and body text is cuted by frame.
test pattern: 

> notify-send "PM <b>message from me</b>:" "\nhello"
> ![untitled](https://cloud.githubusercontent.com/assets/3071207/4644551/f424411e-545c-11e4-88a5-a9b055bb189a.png)

bolded text needs o be tagged with bold tags before executing in terminal.
can someone confirm issue?

**Comment by wavexx** [comment]
Humm, I cannot reproduce this issue. Maybe it has some interactions with the icon (that I don't have)?

**Comment by pale3** [comment]
For me is same with or without icon. Did you use bold tags in text, exactly as I specified above?

**Comment by wavexx** [comment]
As in ``notify-send "PM <b>message from me</b>:" "\nhello"`` ?
Could you attach your dunstrc?

**Comment by pale3** [comment]
yes that right!

I found out If i use <code>shrink = no</code> that dunst will respect geometry and thus notification wont get shrinked, so message with tags is displayed correctly. 
Also if i set <code>word_wrap = no</code>, message is displayed correctly.
 
I think this has something to do with shrink and geometry values. In example I gave, message is < 500, so it gets shrinked. If message is >500 notification is displayed correctly. 

Here is my dunstrc

https://gist.github.com/pale3/f4a85ffca440d9cf51cb

**Comment by hughdavenport** [comment]
Hi @pale3,

Is this still an issue for you, or did the `shrink` and `word_wrap` settings solve it for you?

Cheers,

Hugh

**Comment by shioyama** [comment]
For the record, I have the same issue. I've turned `shrink` off which sort of fixes it (not really, but at least it's wrapping correctly).

**Comment by shioyama** [comment]
Also I haven't looked into this in detail, but I found that the wrapping was working until I made some changes to my fontconfig, which perhaps caused some issue.

Here's my fontconfig, in case it helps:

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>FontAwesome</family>
    </prefer>
    <default><family>DejaVu Sans</family></default>
  </alias>
  <match target="font" >
    <edit mode="assign" name="rgba" >
      <const>rgb</const>
    </edit>
  </match>
  <match target="font" >
    <edit mode="assign" name="hinting" >
      <bool>true</bool>
    </edit>
  </match>
  <match target="font" >
    <edit mode="assign" name="hintstyle" >
      <const>hintslight</const>
    </edit>
  </match>
  <match target="font" >
    <edit mode="assign" name="antialias" >
      <bool>true</bool>
    </edit>
  </match>
  <match target="font">
    <edit mode="assign" name="lcdfilter">
      <const>lcddefault</const>
    </edit>
  </match>
</fontconfig>
```

**Comment by pale3** [comment]
I think this is related to font, I cant reproduce it anymore, so this should be closed.
