### ISSUE TITLE
feature request: configurable exclusion from history

### ISSUE THREAD

**Issue by kettlun** [dunst-project/dunst#197]
It'd be nice if it were possible to exclude certain notifications that only have short-term relevance (AC unplugged, etc) from showing up in the history.

Personally, messages I want to see in the history are limited to RSS/email notifications.

**Comment by hughdavenport** [comment]
This would be a pretty cool feature. I could see it being put in a config block with a name such as `history_ignore = yes` and targetting certain strings etc.
