### ISSUE TITLE
Implement text bounce

### ISSUE THREAD

**Issue by kyrias** [dunst-project/dunst#201]
I tried to use the `bounce_freq` option, but it doesn't seem to actually do anything at all for me, just get an ellipsis in the middle of the text.

**Comment by hughdavenport** [comment]
I would like this feature. I'll look into implementing this in the next month or so.

Cheers,

Hugh

**Comment by randomn4me** [comment]
I would love to get this feature implemented

**Comment by tsipinakis** [comment]
Looks like the code that implemented this setting was removed in b2883b213342c912a76329bb8f6c179ea3451ae5. I went ahead and removed it from the code and documentation to avoid further confusion. 

I'll probably attempt to implement it again once I clean up the codebase a bit but I'd welcome it if anyone wants to work on a PR in the meantime. Until then, I'm downgrading this issue to a feature request.

**Comment by fwsmit** [comment]
I'll close this as too vague (and old). Feel free to open a new issue with more details
