### ISSUE TITLE
Wrong indentation when lines begin with a space

### ISSUE THREAD

**Issue by Markus00000** [dunst-project/dunst#208]
To see how dunst changes the indentation, run these examples with:

```
notify-send "$(cat test.txt)"
```

Make sure not to lose the leading spaces when testing!

Input file 1:

```
 x
 x
 x
```

Notification:

```
x
 x
 x
```

Input file 2:

```
 x
x
 x
```

Notification:

```
x
x
 x
```

Input file 3:

```
 x
x
x
```

Notification:

```
x
x
x
```

**Comment by hughdavenport** [comment]
Can reproduce, and can confirm that PR#214 fixes this.

Cheers,

Hugh
