### ISSUE TITLE
Add notification width option

### ISSUE THREAD

**Issue by ewancoder** [dunst-project/dunst#211]
I'd like to setup notification width with notify-send hint option (like bg-color/fg-color). My notifications is wide because I am reading some twitter messages and etc., but when I try to control my volume - it just says "Volume [ 5%]" and the rest of the notification window is blank. This is why I need to shorten it for volume notifications.

![img](http://dl.dropbox.com/u/70091792/Screenshots/January/14-150117.png)

UPD: And another possible request: don't store volume notifications in history, because when I've changed volume several times and then wanna go back to history and see previous twitter messages, whole bunch of volume notifications come rushing back.

**Comment by hughdavenport** [comment]
Hi,

What hint name would you suggest? `width` makes sense I guess.

What about the ignore history? `history=0` or something? That part may be more suited as another bug.

This would be a great feature and would also suit some of my use cases so I'll tackle it.

Cheers,

Hugh

**Comment by hughdavenport** [comment]
The other option is if you have your geometry set to 0xheightetc instead of a set value, the width will auto adjust.

Cheers,

Hugh

**Comment by ewancoder** [comment]
Actually, I kind of used to default width already, it's not a big deal :) So this feature can be implemented just to extend functionality. I don't care would it be `width` or `left-border-to-right-border-length` :) although, I think `width` is more suitable.

**Comment by tsipinakis** [comment]
This is a very old issue so not sure if it's still relevant.

Have you tried the [`shrink`](https://github.com/dunst-project/dunst/blob/master/dunstrc#L80) option? Seems like exactly what you're asking for.

**Comment by ewancoder** [comment]
I kind of switched to Windows 10 after 6 years of Linux experience (strange as it may sound), so yes, this is not relevant anymore.
