### ISSUE TITLE
Allow to check whether dunst is paused

### ISSUE THREAD

**Issue by roomcays** [dunst-project/dunst#216]
I'd like to check if dunst is paused within my Conky script. Something like

```
killall -SIGUSR2 dunst
```

would be OK, if it can print something out to STDOUT, but then command

```
killall -SIGUSR1 dunst
```

should toggle pause/resumed mode.
Alternatively one might use notifications with pre-defined summaries.

**Comment by hughdavenport** [comment]
Hmm,

I think changing the signals may cause a regression in a lot of user scripts.

Sending a message with summary of say DUNST_COMMAND_STATUS should be possible, but it won't return to stdout, but instead show a notification regardless of paused status? What are your thoughts here?

Cheers,

Hugh

**Comment by arnegoeteyn** [comment]
I would also like to check the status of dunst in my lemonbar config. Is there already a way to check check this? Or a dunst toggle would be great as well.
Cheers

**Comment by raspbeguy** [comment]
I think the easiest way that wouldn't cause any regression (and IMHO the most UNIX-compliant one) would be to keep the status written in a file, for instance `/tmp/dunst-status`, with the same idea than what you can find in `/sys` or `/proc`. A single `cat` to this file would give the required information.

**Comment by raspbeguy** [comment]
Or it could throw an info text (easily parseable) when you send a `SIGINFO`. Could be handier.

**Comment by tsipinakis** [comment]
Implemented with #651.
