### ISSUE TITLE
systemd unit for dunst

### ISSUE THREAD

**Issue by Strubbl** [dunst-project/dunst#221]
Hello,
this issue is to discuss a systemd service unit for dunst. I wanted to have one, so i created the file, which i am going to file under contrib/ and add it as pull request to this ticket.
Maybe someone can have a look on this proposal service file w.r.t improvements? 

I would be glad to have this file merged to dunst.

**Comment by hughdavenport** [comment]
Hi,

I would suggest changing this based on @knopwob's comment at https://github.com/Strubbl/dunst/commit/94efb5a5eb6dde7dbb3bad318714807603c72375#commitcomment-10524148

Cheers,

Hugh

**Comment by Strubbl** [comment]
okay, i have used the feedback in commit f5675bccd1cdfaab39baecbc8b48abe63f1411a6

**Comment by Strubbl** [comment]
The systemd service unit in PR #222 can start the dunst daemon. But with `systemctl --user stop org.knopwob.dunst.service` this service keeps running. But systemd thinks it has stopped. 

Is there any specific command/parameter, we can use to stop dunst?

**Comment by Eizen** [comment]
Fixed in f32659a
