### ISSUE TITLE
Find new Maintainer for Dunst

### ISSUE THREAD

**Issue by knopwob** [dunst-project/dunst#228]
Since I don't have the required motivation to properly maintain this project anymore I should seek out for someone else to maintain it.

So If you're reading this and are interested, just leave a comment (or directly email me: dunst@knopwob.de) with a few informations about you.

**Comment by hughdavenport** [comment]
Hah,

I just found a bug, and made a patch and was about to file it when I saw this. I could be interested. What sort of workload?

Cheers,

Hugh

**Comment by knopwob** [comment]
It's only taking care of this repository. So handling open issues and pull requests as well as developing dunst further as far as you desire.

The initial workload might be a little high, because of the backlog of issues that grew over time, but it's normally a pretty quiet project.

I'm willing to get the website up and running again and taking care of that by myself.

I would suggest, if you're interested and okay with that, that you do some work via pull request and after a few weeks when everything is fine I'll give you direct push access to this repository.


On June 4, 2015 5:21:23 AM CEST, Hugh Davenport <notifications@github.com> wrote:
>Hah,
>
>I just found a bug, and made a patch and was about to file it when I
>saw this. I could be interested. What sort of workload?
>
>Cheers,
>
>Hugh
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/knopwob/dunst/issues/228#issuecomment-108702655

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hughdavenport** [comment]
Yeh had a look through the backlog, quite a lot. I'll put in some effort over next few weeks to go and triage and then fix some etc.

**Comment by knopwob** [comment]
Yeah, that's why I'm looking for someone to give this project some care ;) 

And I don't expect from you that you fix all open issues within the near future. Just a little bit more attention than I gave the project in the last few months is fine. 

On June 5, 2015 2:40:08 AM CEST, Hugh Davenport <notifications@github.com> wrote:
>Yeh had a look through the backlog, quite a lot. I'll put in some
>effort over next few weeks to go and triage and then fix some etc.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/knopwob/dunst/issues/228#issuecomment-109105093

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jcf** [comment]
As I said [in this comment](https://github.com/knopwob/dunst/pull/223#issuecomment-259965952), can we give some previous and current contributors write access to this repo so we can start getting some of the great work people have done merged?

Maybe run an unstable `master` branch for a while, get some testing done, and then cut a release when we've had a :+1: from a few members of the community?
