### ISSUE TITLE
Horizontally centered banners (GNOME 3.16+-like)

### ISSUE THREAD

**Issue by sgtpep** [dunst-project/dunst#233]
It would be great to be able to place notifications like GNOME do since 3.16: https://wiki.gnome.org/Design/OS/Notifications.

**Comment by tsipinakis** [comment]
This can be partly achieved with the current `geometry` setting, just set the X to +/- half the width of the display. The window won't expand based on the notification length but it's a start.

**Comment by jzbor** [comment]
It would be nice if this setting where independent from the screen width as it may vary on a laptop with external screen

**Comment by victorz** [comment]
> This can be partly achieved with the current `geometry` setting, just set the X to +/- half the width of the display. The window won't expand based on the notification length but it's a start.

With this method, you'd have to also subtract half of the notification width, so `horiz_offset = (screen_width - notification_width) / 2`. Still, this won't work properly with `shrink = yes`, because that makes the notification width dynamic, and the offset can't be made dynamic.

**Comment by fwSmit** [comment]
This issue is solved with #855 (WIP)

**Comment by WhyNotHugo** [comment]
I believe this can be closed with #855 merged?
