### ISSUE TITLE
Context menu not working for some urls

### ISSUE THREAD

**Issue by marcvs** [dunst-project/dunst#236]
Hi there,

I'm not sure how to exactly use the context menu.  However, urls with a '-' are cut off before the - character. I.e. notify-send "http://ix-pert.de" will ask my browser to open "http://ix".

The context menu also gives me the option to enter something like in dmenu. However, only if I enter nothing, the URL will be opened in the browser. Entering any executable there does not even execute it.

Sorry for filing two issues here, but the latter probably is just my faulty understanding.

**Comment by Narrat** [comment]
The input area is for searching stuff. Like in dmenu, yes.
But just for URLS found in the current displayed notifications. Or specify an url to open.
It doesn't search $PATH to get binary paths. So entering a bin doesn't work.

And the cut off is a bug. Faulty regex at work

**Comment by danlamanna** [comment]
I can reproduce a similar bug:

```
notify-send "https://bugzilla.redhat.com/show_bug.cgi?id=1323610"
```

Action menu sends me to `https://bugzilla.redhat.com/show`.

**Comment by tsipinakis** [comment]
Should be fixed in HEAD, can you confirm?

**Comment by mathstuf** [comment]
The bugzilla one works, but the `ix-pert.de` one does not. It is cut off right before the hyphen.

**Comment by mathstuf** [comment]
Oops, restarted using an older dunst before thinking to test `ix-pert`. `ix-pert.de` works as well on `master`.
