### ISSUE TITLE
dbus dunst only works as root user

### ISSUE THREAD

**Issue by superzanti** [dunst-project/dunst#238]
I was hoping to get the dbus service in 

```
/usr/share/dbus-1/services/org.knopwob.dunst.service
```

working, but it only seems to work as root user. When I do a

```
notify-send "test"
```

it does not work, however if I do a

```
sudo notify-send "test"
```

it works just fine. I should also mention that this only happens with the dbus service. If I start dunst in a terminal, then everything works as expected. However, I would like it to start up automatically with notify-send as needed.

I have a few things that are doing at notify-send on startup. It seems that the very first notify-send as soon as the x-server and i3 get started works just fine displaying a "Display settings changed" message, but it must crash after that because running a

```
ps aux | grep dunst
```

returns nothing. I've been trying to debug this but I'm afraid I've hit a dead end. Even some information on where dunst puts it's error logs might help me.

If I add

```
dunst &
```

to my xinitrc then I witness the same behavior, dunst seems to crash after the first message.

Heres an output of dbus when I try to send something manually:

```
$ dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1441972779.060571 sender=org.freedesktop.DBus -> destination=:1.17 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string ":1.3"
      string "org.a11y.Bus"
      string "org.freedesktop.systemd1"
      string ":1.4"
      string ":1.17"
      string ":1.0"
      string ":1.1"
      string ":1.10"
      string ":1.9"
      string "org.gnome.d-feet"
      string ":1.2"
   ]

$ sudo dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1441973308.870561 sender=org.freedesktop.DBus -> destination=:1.10 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "org.freedesktop.Notifications"
      string ":1.10"
      string ":1.1"
   ]

```

On top of that if I try to use the d-feet tool to debug it (in the AUR) and run it from there, it pops up with an error message:

```
org.freedesktop.Notifications : g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.Notifications exited with status 1 (25)
```

I monitored the dbus

```
$ gdbus monitor  --session --dest org.freedesktop.Notifications
Monitoring signals from all objects owned by org.freedesktop.Notifications
The name org.freedesktop.Notifications does not have an owner
```

I also monitored journalctl and found that every time a notify-send command was called this appeared in the journal:

```
Sep 11 13:07:49 Chell dbus-daemon[621]: Activating service name='org.freedesktop.Notifications'
Sep 11 13:07:49 Chell org.freedesktop.Notifications[621]: cannot open display
Sep 11 13:07:49 Chell dbus-daemon[621]: Activated service 'org.freedesktop.Notifications' failed: Process org.freedesktop.Notifications exited with status 1
```

**Comment by superzanti** [comment]
With these messages I was able to come up with a temporary solution. I made a shell script: /usr/bin/dunst.sh

```
#!/bin/bash

export DISPLAY=:0
/usr/bin/dunst
```

And this works just fine without any crashes or errors when I change the dbus service file to execute this shell script. But what if my display changes? This doesn't seem like the best solution to me. Why isn't dbus giving the proper display to the dbus service?

**Comment by Brottweiler** [comment]
The [AUR package of dunst-git](https://aur.archlinux.org/packages/dunst-git/) got updated the 19th September, and at that time I rebuild it from git.

Today however, I noticed dunst didn't work. I tried as sudo, and that works. But not as normal user.

Is it related to a commit, or this https://www.archlinux.org/news/d-bus-now-launches-user-buses/ ?

**Comment by superzanti** [comment]
I believe it's related to that commit.

I added this to my .xinitrc and everything started working again

    eval $(dbus-launch --sh-syntax --exit-with-session)

The only weird thing was, that I would get the first notify-send message upon startup. Any notify-send after that would not work.

**Comment by mathstuf** [comment]
Probably related: https://github.com/systemd/systemd/issues/892

**Comment by Narrat** [comment]
Maybe the solution from #245 applies here too.

More likely if I look at the "solution"

**Comment by Brottweiler** [comment]
@Narrat yes, this fixed it;

`/etc/X11/xinit/xinitrc` is the default `.xinitrc` file example, which includes, under the comment `# start some nice programs`, this:

```sh
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
```

This just sais this should have been in `~/.xinitrc` from the start, so I copy pasted that into my `~/.xinitrc` and now dunst works again.

**Comment by tsipinakis** [comment]
Is this issue still relevant? A few solutions have been proposed.

**Comment by Brottweiler** [comment]
Not for me. the `~/.xinitrc` file was missing stuff that the arch wiki has in their [example](https://wiki.archlinux.org/index.php/Xinit#xinitrc). So, it's a user problem. 

You should close this.

**Comment by mathstuf** [comment]
It is not actually fixed AFAIK, but it is more a systemd issue anyways.

**Comment by tsipinakis** [comment]
I'll close this then, feel free to reopen or create a new one if it's still a problem.
