### ISSUE TITLE
Unknown tag qt

### ISSUE THREAD

**Issue by sedrubal** [dunst-project/dunst#239]
I'm using Kopete and I always get this error:

`Error parsing markup: Unknown tag 'qt' on line 2 char 6`

Is this a bug, or do I have to configure anything? Can you "implement" this tag?

**Comment by tsipinakis** [comment]
First of all, this is a really old issue is it still relevant?

Can you please post an example notification that causes the error to try and debug it?

**Comment by wavexx** [comment]
This (and similar issues mentioning "Unknown tag <XY>") where fixed along with proper quoting of the input text as part of one of my PR. This is generated by pango trying to parse unescaped text.

**Comment by sedrubal** [comment]
I'm sorry, I can't say. I don't use kopete anymore and currently I don't use dunst... 😉
