### ISSUE TITLE
Add DUNST_COMMAND for shortcut actions

### ISSUE THREAD

**Issue by jeroentbt** [dunst-project/dunst#241]
In stead of defining keybindings in dunst, I would like to use my WM to send commands to dunst to `close`, `close_all` and show `history`.

These could be defined like the pause/resume functuionality by sending a notificatione with a summary of eg `DUNST_COMMAND_CLOSE`, `DUNST_COMMAND_CLOSEALL`, `DUNST_COMMAND_HISTORY`.

My C is non-existant but browsing the code here on github maybe at least the last 2 would be easily implemented?

**Comment by progandy** [comment]
I rather think that these commands should be implemented as dbus methods, maybe in a new interface. They don't belong in the Notify method.

**Comment by jeroentbt** [comment]
Fine by me :), I see why this would be preferable.
I'd just love the opportunity to use them without having to capture key
events with Dunst.

Maybe open a new issue so we can close this one and point to the dbus one?

I rather think that these commands should be implemented as dbus methods,
maybe in a new interface. They don't belong in the Notify method.

—
Reply to this email directly or view it on GitHub
<https://github.com/knopwob/dunst/issues/241#issuecomment-150934111>.

**Comment by FlashYoshi** [comment]
Just seeing this issue, [this](https://github.com/knopwob/dunst/pull/243) PR fixes the close all command.

**Comment by jeroentbt** [comment]
@FlashYoshi nice, just two more to go ;)

**Comment by FlashYoshi** [comment]
@jeroentbt Implemented all the commands this time around, also added a command to replace the text of the last notification. Now the PR just has to be approved but because of #228 this could be quite hard.

**Comment by jeroentbt** [comment]
@FlashYoshi W00t! but yeah, #228 :( , hope someone steps up to keep Dunst going.

**Comment by tsipinakis** [comment]
Implemented via #651.
