### ISSUE TITLE
move notifications out of the way when the mouse is near

### ISSUE THREAD

**Issue by mathstuf** [dunst-project/dunst#242]
Though this might conflict if actions are ever supported. Right now, there's no good corner to place them in where they don't get in the way :/ .

**Comment by blueyed** [comment]
I wanted to suggest keeping notifications open while they are being hovered with the mouse cursor (i.e. the timer for them to timeout stops).
This would conflict with this feature, since you could never hover them in the first place.

**Comment by fwsmit** [comment]
It seems this would conflict too much with other features, like hovering and clicking actions. With that reason I will close this issue.

**Comment by mathstuf** [comment]
Agreed. Back when I opened this, actions weren't supported. Now that they are, clicking is far more important.
