### ISSUE TITLE
Support for multiple font sizes

### ISSUE THREAD

**Issue by agboom** [dunst-project/dunst#250]
I love to use dunst for my notifications. Recently I discovered override rules and use them to add icons per app. It's great that dunst supports multiple fonts, e.g. `font = "Cantarell, Font Awesome 10"`, but it only supports one font size. Is this possible to add support for multiple font sizes, like`font = "Cantarell 10, Font Awesome 12"`?

Another use case for multiple font sizes could be to put the notification body below the summary.

**Comment by batmat** [comment]
Possibly related, not opening a new one seems it seems very close: that would be useful to define a bigger font size for critical messages for example.

**Comment by rogue-ronin** [comment]
The markup in Pango includes <big> and <small> and both <sub> and <sup> -- all of which affect the text size in relation to the current size.  While <sub> and <sup> aren't likely what you need, the other two are useful.  I've played with all four and they work in Dunst.

I haven't looked further, but there is a lot more that can be done via markup.  Take a look at the page linked in the config file: http://developer.gnome.org/pango/stable/PangoMarkupFormat.html

It looks to me like you might be able to do a lot with fonts -- I think the <span> tag is supported, but I haven't checked.

Aloha.

**Comment by ebarriosjr** [comment]
@agboom could you share the config you use to add icons per app? I have been looking for it and can't find anything

**Comment by agboom** [comment]
@ebarriosjr Sure it's right here: https://github.com/agboom/vcsh-xorg/blob/master/.config/dunst/dunstrc#L175

**Comment by Eizen** [comment]
I'll close this since this functionality is already provided by pango markup.
Example:
format = "<span font="Monospace 12">%s</span>\n<span size="13">%b</span>"

For more attributes check out: https://developer.gnome.org/pango/stable/PangoMarkupFormat.html
