### ISSUE TITLE
Dunst using ~7GiB ram

### ISSUE THREAD

**Issue by skraj** [dunst-project/dunst#252]
I have posted a question on stackoverflow on this, thought you should be aware and maybe help me out

http://stackoverflow.com/questions/35081628/i3-usr-bin-dunst-draining-memory

**Comment by Narrat** [comment]
Kinda related to issue #251 as it seems (Just to mention it. Solution isn't there either)

**Comment by Narrat** [comment]
What could propably be tested is locally merging this PR https://github.com/knopwob/dunst/pull/231 and try if that helps

**Comment by WillMoggridge** [comment]
I just got this when I accidentally didn't rename a rule section.

This for example:
```
[section]
    appname = One
[section]
    appname = Two
```

Eats up around 0.2GiB of RAM every second, until I run out of memory.

**Comment by Eizen** [comment]
Fixed
