### ISSUE TITLE
Preventing accidental close of notification

### ISSUE THREAD

**Issue by hahiserw** [dunst-project/dunst#256]
I accidentally closed notification when I was trying to click something in the place notification usually appears. (I know I can just bring this notification by Ctrl+`)

Could you make something to prevent closing of the notification for about 0.5s after it appears (maybe configurable)?

**Comment by krompus** [comment]
I would like this as well. Often, when I'm busy typing things and a notification pops up, it will dismiss immediately, which is annoying.
