### ISSUE TITLE
Please consider tagging a release

### ISSUE THREAD

**Issue by Stebalien** [dunst-project/dunst#263]
There have been quite a few bug fixes since the last release.

**Comment by Stebalien** [comment]
:crying_cat_face:  :pray:

**Comment by dubhater** [comment]
Surely it's not that difficult to type 'git tag -a v2' or whatever?

**Comment by Stebalien** [comment]
To be fair, they're probably waiting to clear the issue backlog.

**Comment by Stebalien** [comment]
Probably the [https://github.com/dunst-project/dunst/milestone/3](2.0 milestone).

**Comment by jplatte** [comment]
Yeah, it's a bit annoying to have to use the -git package just to not have big icons completely mess up the notifications..

**Comment by hobarrera** [comment]
Can we at least have a 1.2?

The missing features an bugs in the last stable is ridiculous, even if the current master has bugs, 1.1 also has so many issues that it's a pain. Be honest: do you ever except to **completely** clean up all GH issues? (no offence intended here, thanks for the cool work! 😗  )

**Comment by tsipinakis** [comment]
> Be honest: do you ever except to completely clean up all GH issues? (no offence intended here, thanks for the cool work! 😗 )

No, the [1.2](https://github.com/dunst-project/dunst/milestone/3)(previously named 2.0) milestone contains the issues that I consider blockers for a new release and I also have a few work-in-progress local branches that I want merged before the next version(doc rework, and a few config file changes/deprecations).

Additionally, I am currently in a month-long hiatus that'll last till the middle of June so I don't currently have the time to do the work needed to prepare a release.

**Comment by tsipinakis** [comment]
Last issue in the 1.2 milestone was closed. Current todo list for the release is the following:

- [ ] Test the `xinerama-flag` branch
- [ ] Merge `xinerama-flag` to master
- [ ] Do a final check to verify full backwards compatibility with 1.1
- [ ] ... release?

**Comment by bebehei** [comment]
Having alltogether ~800 commits on master, while [240 of them have never been released](../compare/v1.1.0...master), I doubt that there is a solution to ensure full backwards compatibility.

What about just releasing 1.2? People who use 1.1 currently will report issues anyway, because so much stuff has changed. And all others, who have depended on a fix compile it either from source or use something like [dunst-git package](https://aur.archlinux.org/packages/dunst-git).

**Comment by tsipinakis** [comment]
> Having alltogether ~800 commits on master, while 240 of them have never been released, I doubt that there is a solution to ensure full backwards compatibility.

Obviously, but scanning the commits and verifying that nothing obvious was missed (and that the changelog is up to date) isn't that bad. That's done now anyway, only the release left to do now.

**Comment by bebehei** [comment]
@tsipinakis Yay! Thank you!

**Comment by tsipinakis** [comment]
Closed via `b069b2dba66082043a60edaab174d80399d57a87`

**Comment by hobarrera** [comment]
Not a big fan of gtk2 being a *new* dependency nowadays, TBH.

**Comment by tsipinakis** [comment]
Well, we're stuck with it now until the next release but luckily we only use a handful of gtk functions for icon scaling so it's trivial to switch to gtk3.
