### ISSUE TITLE
follow=pointer and mouse gestures

### ISSUE THREAD

**Issue by artheus** [dunst-project/dunst#272]
Would be a nice feature to add, a tiny icon with a number that will follow the pointer. Then when you do mouse gestures like ´shake´, ´circle´ or something like that. The notification messages will be shown either using the geometry, like default, relative to screen edges. Or! using the geometry relative to the pointer position.

This feature would help me a lot, since when I am focused I want to just be "snapped out of it" for a second and see that I have notifications pending. Colors, size, position and font for the little icon should be configurable depending on urgency of the notifications, and always let the most urgent win the "styling of the icon"

**Comment by artheus** [comment]
I am a developer myself. Not experienced with C though. I would love to contribute, but I would need an introduction to the project.

**Comment by fwsmit** [comment]
Many of the suggestions in this issue are implemented already, like notification styling being configurable depending on urgency. For this reason I will close this issue. If there are any specific things that you would like to see, feel free to open a new issue.
