### ISSUE TITLE
notifications are considered duplicate even if icons differ

### ISSUE THREAD

**Issue by jwdevel** [dunst-project/dunst#275]
If two notifications come in with the same message contents, but with different icons, dunst shows them as "the message (2)", and keeps whatever the first icon was.

In the case where icons are communicating some useful information (such as success/failure, in my case), this hides information.

I think icon should be considered "part of the message" w/regard to collapsing them down.

Also: is there no configuration for turning off the "collapse duplicates" feature entirely?
I couldn't find one...

**Comment by tsipinakis** [comment]
Fixed in 6c9de72c7d3b74abb6d34767d854776c63203ba8

>Also: is there no configuration for turning off the "collapse duplicates" feature entirely?
I couldn't find one...

There's [`stack_duplicates`](https://github.com/dunst-project/dunst/blob/master/dunstrc#L108)
