### ISSUE TITLE
Duplicates with no icon are not detected

### ISSUE THREAD

**Issue by nioncode** [dunst-project/dunst#280]
Since 6c9de72c7d3b74abb6d34767d854776c63203ba8, dunst does not detect duplicates anymore when I simply issue:
```
notify-send foo
notify-send foo
```

This shows 2 notifications, instead of 1 stacked.

This only applies if I have `icon_position` set to `left` or `right`. Duplicate detection works fine if I have `icon_position` set to `off`.

Duplicate detection also works fine if I include an icon in my notify-send commands:
```
notify-send -i icon foo
notify-send -i icon foo
```

**Comment by tsipinakis** [comment]
Thanks for the report! Fixed in c4a002bc79929a207c7a8b532d19fb868784d8e7.
