### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [dunst-project/dunst#288]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [load_settings](https://github.com/dunst-project/dunst/blob/bfd24224aa5451312a1d20192ca3eb4121baa52a/src/settings.c#L400)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [notification_print](https://github.com/dunst-project/dunst/blob/a3cce0ec2fbf2f66bf5d2d619b4d66ada1bf0546/src/notification.c#L25)

**Comment by tsipinakis** [comment]
I don't think error handling is needed here.
* `fclose` mostly fails when writing to a file, we are opening the config read-only so it's very unlikely for it to fail. And in the case that it does, the error handler can't do much else other than pop a warning. (The only possible consequence here is a leaked file descriptor anyway).

* `printf`, especially in this context which is used as a debug output, what is the error handler even going to do if `printf` fails? Call `printf` again to report an error? That almost certainly won't work.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked  return values") a bit more.
How do you think about to indicate a software failure by a corresponding program exit code?
