### ISSUE TITLE
Transparancy enabled colors

### ISSUE THREAD

**Issue by phuhl** [dunst-project/dunst#289]
Dunst can be set to transparent in the config but this sets the whole window transparent. Many applications are able to use rgba-color-values to display colors accordingly. This has the advantage of being able to display the text non-transparent and the background transparently. That improves readability (vs. everything is transparent).

**Comment by jonathashenriques** [comment]
Would be awesome, also, if we could set an separator to transparent, so we can have multiple and separeted notifications, something like that:

![example](https://user-images.githubusercontent.com/21113681/28444961-4fa0d592-6db0-11e7-9efa-89f4efabf206.png)

**Comment by Sweenu** [comment]
Would this also let us have non-transparent icons/images while having tranpsarent notifications?
That would be a really nice feature!

**Comment by tsipinakis** [comment]
Implemented with #717, not all color strings support transparency.
