### ISSUE TITLE
use milliseconds internally, and don't make rounding errors

### ISSUE THREAD

**Issue by quite** [dunst-project/dunst#291]
Broken out from closed issue #276 

@knopwob wrote:

Eventhough the protocol works with milliseconds, dunst internally uses seconds, so the timeout send by the app will be rounded to the next second.

so notify-send -t 100 "blehp" should timeout after one second. This might get extended to 2 seconds, due to some other rounding stuff.

@quite wrote:

For me, dunst git as of today lets the notification sit around for milliseconds rounded up to whole second(s) plus 1 second. As @knopwob lays it out.

**Comment by tsipinakis** [comment]
Looking back, dunst originally used milliseconds and this was changed in #109.

It doesn't seem any other reasoning was given for the change other than, as said in the PR
> It is not important whether a notification is shown for 9.5 or 10.5 seconds.

Perhaps @knopwob can shed some light on this?

**Comment by LemonBoy** [comment]
As a side note it'd be better to use `g_get_monotonic_time` instead of `time` when computing the timeouts.

**Comment by bebehei** [comment]
Thanks @LemonBoy for mentioning `g_get_monotonic_time`. Dunst now supports monotonic time and timeout in milliseconds!
