### ISSUE TITLE
unable to parse long lines in dunstrc

### ISSUE THREAD

**Issue by seschwar** [dunst-project/dunst#294]
Apparently dunst is unable to parse lines in its configuration file which contain more than 1023 (non-whitespace, non-comment) characters.

``` sh
$ dd if=/dev/zero bs=1023 count=1 2> /dev/null \
    | tr '\0' '.' \
    | sed -e '1s/^/#/' \
    | dunst -config /dev/stdin \
    & sleep 1
Warning: invalid config file at line 2
Missing '='
$ kill $!
```

If we try the same with a smaller input there's no warning.

``` sh
$ dd if=/dev/zero bs=1022 count=1 2> /dev/null \
    | tr '\0' '.' \
    | sed -e '1s/^/#/' \
    | dunst -config /dev/stdin \
    & sleep 1
$ kill $!
```

I hit this when trying to set `icon_folders` to the expansion of `/usr{/,/local/}share/icons/hicolor/32x32/{actions,animations,apps,categories,devices,emblems,emotes,filesystem,intl,mimetypes,places,status,stock}` in order to get dunst to search all 32x32 hicolor icons, since #157 is not implemented yet.

**Comment by tsipinakis** [comment]
This is very interesting, in my system this bug triggers at 8191.

After looking a bit more into it, dunst reads in config lines into a buffer of length `BUFSIZ`, a macro defined by glibc. Any characters after the buffer has been filled are treated as a new config line.
