### ISSUE TITLE
Rule to remove notification from redisplay queue.

### ISSUE THREAD

**Issue by chinarulezzz** [dunst-project/dunst#302]
Hi! Would be good to have option, to match application and remove notification from redisplay queue. At example, I go to the kitchen and back I want to see only important messages (mails, im, system notifications), and not music player notifies.

**Comment by Eizen** [comment]
A new rule has been added recently to master that does what you want, called `history_ignore`. Unless you build from git, you'll have to wait for the next release.

**Comment by chinarulezzz** [comment]
Wow, thank you very much. It would be good to mention this option in dunstrc.

**Comment by tsipinakis** [comment]
Just added an [example](https://github.com/dunst-project/dunst/blob/2126b212f60975aae1064c3562addbcd8022eb2a/dunstrc#L266) to the default dunstrc file.
