### ISSUE TITLE
SystemD unit is not recognized

### ISSUE THREAD

**Issue by Brottweiler** [dunst-project/dunst#304]
Currently the systemd unit file is called `dunst.systemd.service`, but systemctl is unable to recognize it. I believe it needs to be installed as `dunst.service` for it to work as intended.

**Comment by Stebalien** [comment]
That's really a packaging issue. Dunst doesn't actually install the unit file and it's up to the package to put it in the correct location (with the correct name).

**Comment by nmschulte** [comment]
It would be nice if there was a `Makefile` target to install this under the specified `PREFIX`, or at least have the build note that one may want to do so manually.

**Comment by febs** [comment]
I second that

**Comment by bebehei** [comment]
There is a target `install-service` alredy on current master. I guess it's already included in 1.2.0, too.

**Comment by nmschulte** [comment]
Strange.  Looking back at this, I can't determine what I was after that was missing -- I see the `install-service` target (and that `install` deps it). :shrug:

**Comment by febs** [comment]
Well, there is, unfortunately it does not work in my case. See #457
