### ISSUE TITLE
Notifications show icon and path to icon.

### ISSUE THREAD

**Issue by planigan** [dunst-project/dunst#305]
![Image of Yaktocat](http://i.imgur.com/8MW1YSB.png)

I was trying to solve the icon size issue with guard-minitest, as discussed in #158, so I just got a fresh clone of master and built from source. I was hoping this path issue would go away with it.

Ubuntu Gnome 16.04 
i3wm 4.13-1~~xenial1
dunst v1.1.0-191-g1d4a26c

I searched through the issues and didn't find anything about this.

Any help resolving this would be appreciated. Let me know if I can provide any more information.

**Comment by tsipinakis** [comment]
Can you post the output of `dunst -print` when one of those notifications comes  through?

**Comment by planigan** [comment]
```
[1][11:45:07][patrick@figment-PC:~/.config/dunst]
 (master:9b2c35b △ ) λ dunst -print -config dunstrc 
Warning: 'allow_markup' is deprecated, please use 'markup' instead.
{
	appname: 'notify-send'
	summary: 'Minitest results'
	body: '11 tests
21 assertions, 0 failures, 0 errors

43.35 tests/s, 82.76 assertions/s

Finished in 0.2538 seconds'
	icon: '/home/patrick/.rvm/gems/ruby-2.4.0/gems/notiffany-0.1.1/images/success.png'
	raw_icon set: false
	category: 
	timeout: 3
	urgency: 0
	formatted: '/home/patrick/.rvm/gems/ruby-2.4.0/gems/notiffany-0.1.1/images/success.png <b>notify-send: Minitest results</b>
11 tests
21 assertions, 0 failures, 0 errors

43.35 tests/s, 82.76 assertions/s

Finished in 0.2538 seconds'
	fg: #aaaaaa
	bg: #222222
	frame: #000000
	id: 2
	script: (null)
}
{
	appname: 'notify-send'
	summary: 'Minitest results'
	body: 'Running: test/models/user_test.rb'
	icon: '/home/patrick/.rvm/gems/ruby-2.4.0/gems/notiffany-0.1.1/images/success.png'
	raw_icon set: false
	category: 
	timeout: 3
	urgency: 0
	formatted: '/home/patrick/.rvm/gems/ruby-2.4.0/gems/notiffany-0.1.1/images/success.png <b>notify-send: Minitest results</b>
Running: test/models/user_test.rb'
	fg: #aaaaaa
	bg: #222222
	frame: #000000
	id: 3
	script: (null)
```
}

**Comment by planigan** [comment]
I just resolved that deprecation warning with the same results.

**Comment by tsipinakis** [comment]
Is that with the default `dunstrc`? If not can you post the config file you're using?

**Comment by Eizen** [comment]
Also make sure there's no `%i` on the `format` option in the rules associated with guard-minitest.

**Comment by planigan** [comment]
I can try to reproduce with a default config. 

[Here is my config](https://gist.github.com/planigan/3a32568093f30047ddf825671257c038)

**Comment by tsipinakis** [comment]
```
format = "%i <b>%a: %s</b>\n%b"
```
`%i` expands to the icon path, removing it from your format should fix it.

**Comment by planigan** [comment]
Well, whadaya know. I gave up trying to figure this out when I first set up i3wm with dunst.

Thanks so much for the help.
