### ISSUE TITLE
Strange rule matching

### ISSUE THREAD

**Issue by bodqhrohro** [dunst-project/dunst#306]
I've created a config section for Skype notifications:
```
[skype]
    category = "im.received"
    background = "#5db4d5"
```
But this rule applies for notifications with any category. What am I doing wrong?

**Comment by Eizen** [comment]
This was fixed in 94eecd6. Unless you build from git you're better off waiting for the next release. Btw not all applications set the category, it's better to match rules using the appname instead. You can get the information related to a notification by running `dunst -print` from a terminal.
