### ISSUE TITLE
Get the history stack from command line

### ISSUE THREAD

**Issue by ohque** [dunst-project/dunst#307]
Let the users get notification history with something like `dunstcli --get-history` or `dunstcli ls` and then leave it to them to do with the data whatever they want.
One use case that I have in mind specifically is displaying notification count in the panel, as well as some other info based on what kind of notifications are in the history stack at the moment.

This feature request belongs to the general idea of exposing functionality to the command line: #284

**Comment by 11111000000** [comment]
Please, help! How to get history? I lost important notification!

**Comment by tsipinakis** [comment]
@11111000000 If more than 20 notifications have been sent since it's not possible unfortunately. The [history_length](https://github.com/dunst-project/dunst/blob/master/dunstrc#L176-L177) setting controls how many notifications are kept in history, and it's set to 20 by default.

History is never saved anywhere, it's just in memory while dunst is running because it's not meant to handle important data it's there as a "I need a way to see what I missed".

**Comment by snide** [comment]
Just a note because I see this thread pops on google when you search for dunst history. You can run `dunstctl history-pop` to pull the last notification. It can be run multiple times to go back in history.

**Comment by Narrat** [comment]
If that is the case, isn't this issue a candidat for closing?

**Comment by snide** [comment]
I didn't make the original issue and it makes a slightly different request, looking for the data, rather than replaying the notification. I just added it in case people run into a similar need.

**Comment by nikp123** [comment]
Managed to implement it however it has REALLY ugly output. Especially because of unbroken newlines messing with the output. Posting code soon...

**Comment by fwsmit** [comment]
I'm pleased to say that the history command has been added. This issue can be closed :)

**Comment by gchamon** [comment]
For later reference, to print all the messages and their timestamps in readable format in bash:

```bash
dunstctl history |
  jq -cr '.data | flatten(1) | .[] | {"html_text": .message.data, "timestamp": .timestamp.data}' |
  while read -r notification_data; do
    html_text=$(jq -r '.html_text' <<<$notification_data)
    timestamp=$(jq -r '.timestamp' <<<$notification_data)
    rendered=$(html2text <<<$html_text)
    if [[ -n $rendered ]]; then
      # Get the system boot time in seconds + your timestamp converted to seconds
      converted_timestamp=$(bc <<<"$(stat -c %Y /proc/1) + ($timestamp / 1000000)")
      rendered_timestamp=$(date +"%Y-%m-%dT%H:%M:%S%z" -d "@$converted_timestamp")
      echo timestamp: $rendered_timestamp
      echo message: $rendered
      echo ---------------------------------------
    fi
  done
```
