### ISSUE TITLE
Crashes on FreeBSD

### ISSUE THREAD

**Issue by mekanix** [dunst-project/dunst#319]
When I try to start dunst manually, I get "Name Lost. Is Another notification daemon running?" error. If I don't run it manually, it never get's started. Could you please give some pointers on how to debug what's going on? I have C/C++ experience, but if you have any advice as to where to start, I'd love to hear those. Thank you!

**Comment by tsipinakis** [comment]
> Name Lost. Is Another notification daemon running?

This means that dunst can either dbus-daemon is not running, or that another notification daemon has already grabbed the notification address.

Is the `DBUS_SESSION_ADDRESS` environment variable set?

**Comment by mekanix** [comment]
dbus-daemon is running, and there's nothing else that could be notification daemon. I have file in ~/.dbus/session-bus/ that has:
```
DBUS_SESSION_BUS_ADDRESS='unix:path=/tmp/dbus-qS3xxo9Dz2,guid=83b81b1d0a38d89fdb99697158fda41a'
DBUS_SESSION_BUS_PID=1390
DBUS_SESSION_BUS_WINDOWID=18874369
```

PID is good, and the file exists in /tmp. As I'm guessing https://github.com/dunst-project/dunst/blob/f624c42432e87e5a9e07c5a1068398d7119bb21d/src/dbus.c#L479 is the line when it all begins, is there a way to print dbus' listener for "org.freedesktop.Notifications"?

**Comment by tsipinakis** [comment]
> As I'm guessing [snip] is the line when it all begins

Yeah, that's the line when the dbus connection is initialized.

> is there a way to print dbus' listener for "org.freedesktop.Notifications"

```
gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/Dbus --method org.freedesktop.DBus.ListNames
```
lists all the names currently on the bus and 

```
gdbus call --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.GetServerInformation
```
should print the information of the notification server if one is running. Does either of these give any clues on what's going on?

**Comment by mekanix** [comment]
My dbus is buggy and errors on those commands. I'll close this issue and reopen if fixing dbus doesn't fix dunst. Thanx!

**Comment by mekanix** [comment]
Just for a reference if anyone else searches for the similar problem. Mine was that command:
```
gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/Dbus --method org.freedesktop.DBus.ListNames
```
was throwing an error `Error connecting: Cannot spawn a message bus without a machine-id: Unable to load /var/db/dbus/machine-id or /etc/machine-id: Failed to open file '/var/db/dbus/machine-id': No such file or directory`. The fix for me was to generate /etc/machine-id file: `dbus-uuidgen >/etc/machine-id`
