### ISSUE TITLE
Allow stacking with -a or -c using notify-send

### ISSUE THREAD

**Issue by Anachron** [dunst-project/dunst#321]
It would be awesome to allow stacking of notifications using a custom ID. 

There is already `-a` for app and `-c` for category in `notify-send`, which could be used for this.

**Comment by hobarrera** [comment]
Doesn't `dunstify` work for your scenario?

**Comment by Anachron** [comment]
Based on  @tsipinakis dunstify can break my stuff any release and is only meant for debugging.
Plus on the distro I'm on (Void Linux) dunstify isn't compiled.

**Comment by bebehei** [comment]
Stacking is now possible with the stack_tag feature implemented in #552.

Send a hint with `notify-send --hint=string:x-dunst-stack-tag:test SUMMARY BODY`. And all notifications with the stack tag `test` get stacked on top of each other.

You can have whatever stack tags you want. Common stack tags are `volume` and many more.

**Comment by Anachron** [comment]
Thank you so much!
