### ISSUE TITLE
Possibility to specify which server to send messages to (via DISPLAY)

### ISSUE THREAD

**Issue by dkasak** [dunst-project/dunst#323]
Suppose I'm running two Xorg servers at the same time. Is it possible to send a notification so it gets displayed on both servers? Or even send to separate notifications with the same content. I've seen some guides for notification-daemons say to simply set DISPLAY to the correct server temporarily while sending the notification (e.g. via `notify-send`) but I've been unsuccesful to make dunst respect this.

**Comment by tsipinakis** [comment]
Currently we connect to the X server at startup and keep the same connection open so a single instance currently can't use 2 X servers simultaneously. To do that, you'd need to have 2 instances and thus 2 dbus-daemon instances running and thus, you'd have to run notify-send twice to send a notification to both server.

I'll keep this issue open as a feature request to consider later.

**Comment by bebehei** [comment]
This is not possible with dunst. The notification spec does not align with this example.

It's not possible to send a single notification to two sessions. You have to run one dbus sessions with these X-Servers each and have to duplicate the notification manually. (executing `notify-send` with the respective values of `DBUS_SESSION_ADDRESS`).
