### ISSUE TITLE
GDK3 instead of GDK2?

### ISSUE THREAD

**Issue by hobarrera** [dunst-project/dunst#327]
Is is possible to rely on / build using glib and gdk 3, rather than 2? How much work would upgrading compatibility imply?

**Comment by hobarrera** [comment]
Oh, actually, changing `gdk-2.0` to `gdk-3.0` seems to work okay. I'm not sure what's up with `gio` though.

**Comment by tsipinakis** [comment]
Latest stable version of glib and gio is 2.52.2, there is no version 3 as far as I know.

I'll look into switching to gdk 3 thought I'm not sure how beneficial it would be at this point.

**Comment by tsipinakis** [comment]
Closed via 111fcaf5838a61faa2449c6edcdca163da5f287e
