### ISSUE TITLE
colour for individual characters

### ISSUE THREAD

**Issue by lampenhauser** [dunst-project/dunst#329]
Is it possible to change the colour of individual characters?
I tried using ansi escape sequences, but it didn't seem to work.

**Comment by tsipinakis** [comment]
You can use [pango markup](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html) to change the text attributes both in the format and inside notification text. Look for the `allow_markup` setting in the stable version, or simply `markup` if you're  using the git version.

**Comment by lampenhauser** [comment]
Thanks a lot!
