### ISSUE TITLE
max_icon_size not resizing larger icon

### ISSUE THREAD

**Issue by joaokamun** [dunst-project/dunst#331]
I've noticed that Dunst has a setting for max icon height, where he resizes larger icons to specified size, right? One of the applications I use send a large image (200x200), that's not beign resized. I know that 32 is default size and I even typed the setting to 'ensure', but changes nothing. It has something that I'm missing?

OS: Arch Linux

config:
```
[global]
    font = Iosevka 12
    allow_markup = yes
    format = "<b>%s</b>\n%b"
    sort = yes
    indicate_hidden = yes
    alignment = left
    bounce_freq = 0
    show_age_threshold = 60
    word_wrap = yes
    ignore_newline = no
    geometry = "250x5-20+22"
    shrink = yes
    transparency = 0
    idle_threshold = 120
    monitor = 0
    follow = mouse
    sticky_history = yes
    history_length = 20
    show_indicators = yes
    line_height = 0
    separator_height = 2
    padding = 10
    horizontal_padding = 8
    separator_color = frame
    startup_notification = false
    dmenu = /usr/bin/dmenu -p dunst:
    browser = /usr/bin/chromium
    icon_position = left
    icon_folders = /usr/share/icons/Arc/status/16/:/usr/share/icons/Arc/devices/16/
    max_icon_size = 32        
```

dunst print:
```
{
	appname: 'notify-send'
	summary: 'Laravel Elixir'
	body: 'Browserify Compiled!'
	icon: '/home/kamun/Projects/app/node_modules/laravel-elixir/dist/../icons/laravel.png'
	category: 
	urgency: 1
	formatted: '<b>Laravel Elixir</b>
Browserify Compiled!'
	fg: #ffffff
	bg: #2b303b
	id: 3
	script: (null)
}
```

**Comment by tsipinakis** [comment]
What version are you running (Check with `dunst -v`). `max_icon_size` was implemented after the last release so you'll need to be running the git version in order to use it.

**Comment by joaokamun** [comment]
Im running 1.1.0, but not git version. So you can close this I think, Ill test git version and if I got any problem Ill reopen. 
Thanks for the help.

**Comment by tsipinakis** [comment]
By the way, you can close issues you've opened yourself (close button next to the comment one).
