### ISSUE TITLE
Urgency based `frame_color` has no effect

### ISSUE THREAD

**Issue by 0x64746b** [dunst-project/dunst#337]
I'm running v1.1.0 from the Debian repository. The urgency specific frame colors in the [provided config](https://dunst-project.org/static/dunstrc1) have no effect. Setting them through the command line flags doesn't work either. The frame is always greenish. The urgency based foreground and background settings seem to apply just fine.

**Comment by hobarrera** [comment]
Dunst v1.2.0 was recently release, and the configuration format has been updated (especially regarding frame). I'd suggest that you upgrade, since the previous version is several years old, and it's unlikely that there's interest in maintaining that.

**Comment by cirrusUK** [comment]
@0x64746b  running dunst from a terminal will show what needs changing in your dunstrc config.
regards

**Comment by tsipinakis** [comment]
Per-urgency frame color was implemented in 8ee86dc477962e58bd018e5a7430ac78f882ebff, after the 1.1 release, you'll need to update to 1.2 to use them.

**Comment by 0x64746b** [comment]
D'oh. My bad! Didn't realize the command line flags don't even exist -.-
