### ISSUE TITLE
Rule to only allow one notification at a time per application

### ISSUE THREAD

**Issue by bl34k** [dunst-project/dunst#341]
Let's suppose I'm raising the volume from a keybind that both raises the volume and uses notify-send to display the current level. Every time I press the key = new notification. I can match them with "appname = notify-send", but the best I could do afterwards is override the timeout to 1 second. Is there a way to make dunst close the last notification sent by notify-send as soon as a new one spawns? Either by a rule or calling a script?

**Comment by tsipinakis** [comment]
While that's not supported by `notify-send` it's actually accounted for by the notification spec.

If you use a language with a proper implentation of libnotify (C, python etc) when you send a notification dunst returns back an id that can be used to replace or update that notification later.

**Comment by hobarrera** [comment]
Yup, and proper binding can work around this. If you're tying shell scripts together, you can use dunstify (I did this to update a same notification with multiple volume change, as can be seem [here](https://gitlab.com/hobarrera/dotfiles/blob/master/home/.local/bin/volume-notify#L7)).

**Comment by bebehei** [comment]
I'd guess @bl34k is asking for transient notification support. Transient notifications should behave exactly like the given description.

**Comment by jonathashenriques** [comment]
You can use `libnotify-id`, that's what i do. With it everytime a notification send by the same ID, overwrite the last one.

**Comment by bl34k** [comment]
Dunstify did just what I expected, thanks everyone.

**Comment by Deomkan** [comment]
Is it possible to substitute the notification without that glitchy "close-open" effect?

**Comment by tsipinakis** [comment]
See #320, it's a bug.
