### ISSUE TITLE
fail to start dunst via systemd and service

### ISSUE THREAD

**Issue by jduf** [dunst-project/dunst#347]
I run the latest version of dunst on a debian 9 and I can't start dunst properly. I read your documentation and the `make install` command correctly sets all the files required to start dunst via `systemd`. Unfortunately it doesn't work and the command ` journalctl -b -p 7..0` run as root outputs:

    Aug 01 11:52:38 pink-floyd systemd[986]: Starting Dunst notification daemon... 
    Aug 01 11:52:38 pink-floyd systemd[986]: Starting Accessibility services bus...
    Aug 01 11:52:39 pink-floyd dbus-daemon[1107]: Successfully activated service 'org.a11y.Bus' 
    Aug 01 11:52:39 pink-floyd systemd[986]: Started Accessibility services bus.
    Aug 01 11:52:39 pink-floyd dunst[1297]: cannot open display
    Aug 01 11:52:39 pink-floyd systemd[986]: dunst.service: Main process exited, code=exited, status=1/FAILURE
    Aug 01 11:52:39 pink-floyd systemd[986]: Failed to start Dunst notification daemon.
    Aug 01 11:52:39 pink-floyd systemd[986]: dunst.service: Unit entered failed state.
    Aug 01 11:52:39 pink-floyd systemd[986]: dunst.service: Failed with result 'exit-code'.

then a bit later in the same output

    Aug 01 11:58:01 pink-floyd systemd[986]: Starting Dunst notification daemon...
    Aug 01 11:58:01 pink-floyd dunst[4114]: cannot open display
    Aug 01 11:58:01 pink-floyd systemd[986]: dunst.service: Main process exited, code=exited, status=1/FAILURE
    Aug 01 11:58:01 pink-floyd systemd[986]: Failed to start Dunst notification daemon.
    Aug 01 11:58:01 pink-floyd systemd[986]: dunst.service: Unit entered failed state.
    Aug 01 11:58:01 pink-floyd systemd[986]: dunst.service: Failed with result 'exit-code'.
    
Thanks for your help

**Comment by bebehei** [comment]
> ```
> Aug 01 11:58:01 pink-floyd dunst[4114]: cannot open display
> ```

Obviously, the `DISPLAY`-variable is not set. Add in your systemd-service file in the `Service`-Section the line `Environment=DISPLAY=:0`.

But that's just the quickfix.

**Comment by tsipinakis** [comment]
As @bebehei said, the most likely cause is that the `DISPLAY` environment variable is not set within systemd. I just ran a test on a Debian 9 VM with `i3-wm`, `xinit` and `dbus-user-session` installed and the systemd service appears to be working fine.

Can you give some more details on your setup? What desktop environment are you using? How are you starting X?

**Comment by bebehei** [comment]
Related commit: 52b08e4f19e6e2cf4b334f021505cba2244953ae

**Comment by jduf** [comment]
Thanks for your quick response!

I'm using a minimalistic version of debian with dwm for desktop environment. I log on my session via the terminal and then run `xinit` which executes the `~/.xinitrc` containing:

    #!/bin/bash
    exec dwm

**Comment by tsipinakis** [comment]
> xinit which executes the ~/.xinitrc containing:

Ah, there's the problem, xinit is the low level command to initialise X, useful if you want a truly minimal system but it skips the system-wide X intialization which can cause problems. I'd recommend using `startx` instead if possible.

After some digging, looks like that the relevant scripts to properly links dbus, systemd and X11 apps are [20dbus_xdg-runtime](https://sources.debian.net/src/dbus/1.11.16%2Breally1.10.22-1/debian/20dbus_xdg-runtime/) and [95dbus_update-activation-env](https://sources.debian.net/src/dbus/1.11.16%2Breally1.10.22-1/debian/95dbus_update-activation-env/).

**Comment by jduf** [comment]
adding the `Environment=DISPLAY=:0` in ` /usr/local/lib/systemd/user/dunst.service` solved the problem. 

If you find a "long term solution" to this problem, let me know !

thanks again!

**Comment by tsipinakis** [comment]
Glad that worked, though that file may be overwritten on updates.

Some other (possibly better) solutions to this would be
* Use `startx` instead as mentioned above
* Run the scripts mentioned above manually in your `xinitrc` file
* Add `systemctl --user set-environment DISPLAY=:0` to your `xinitrc` file.

**Comment by hobarrera** [comment]
`systemctl --user import-environment DISPLAY` is probably better, since it'll work with wayland/xwayland and non-default DISPLAYs.

**Comment by ericfreese** [comment]
This might not be relevant to many folks, but I was struggling with this for a while and found that I had a script (`50-systemd-user.sh`) in `/etc/X11/xinit/xinitrc.d/` that wasn't being called by anything. When initially setting up my `~/.xinitrc` file, I had removed the final `if` block that runs every script in that dir. Adding it back in fixed the issue. Check the default `xinitrc` file at `/etc/X11/xinit/xinitrc`, and see the note [here](https://wiki.archlinux.org/index.php/Xinit#xinitrc):

> Note: At the very least, ensure that the last if block in `/etc/X11/xinit/xinitrc` is present in your `~/.xinitrc` file to ensure that the scripts in `/etc/X11/xinit/xinitrc.d` are sourced.

**Comment by mpaccione** [comment]
I've added the Environment to the dunst.service file and reloaded the daemons. It still doesn't start. 

I am able to run it in the console by typing dunst however it keeps outtputing : Xlib:  extension "RANDR" missing on display ":0". It tries XINERAMA first. 

I'd really like to have this working. I start a new job on Monday and particularly need notifications. Can someone help me please.

**Comment by fwSmit** [comment]
@mpaccione please try not to clutter other issues to get other people to look at your issue. Just wait patiently for your issue to be answered.
