### ISSUE TITLE
Debian dependency list is missing libgtk-3-dev

### ISSUE THREAD

**Issue by quinnuendo** [dunst-project/dunst#355]
Tried to make the project after installing the recommended list of dependencies from the Wiki (https://github.com/dunst-project/dunst/wiki/Dependencies) for Debian, and got the following error: 

`Package gdk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-3.0' found
config.mk:40: *** "pkg-config failed, see errors above".  Stop.
`
I additionally installed `libgtk-3-dev` and now the make process has ended successfully. I have verified that the package in fact is responsible for the file `gdk-3.0.pc`.

I am running Debian 9 with a very minimal install. I am guessing that this will be true for the Ubuntu dependencies, but have not tried to verify that.

**Comment by tsipinakis** [comment]
I updated the wiki. If I'm not mistaken any github user can edit it so you could have updated it yourself, just FYI.

**Comment by quinnuendo** [comment]
I missed that I can do it myself, will do in the future if I notice something like this.
