### ISSUE TITLE
Issues with large icons

### ISSUE THREAD

**Issue by TARDIS-Maker** [dunst-project/dunst#356]
I'm having issues with some icons being too large, specifically with spotify. They'll end up squishing the text down into a few columns making it all look very messy and unreadible.

It is of course possible to just extend the width, but then you run into issues with it being too large for text only notifications.

Essentially I'd like to see an option to scale icons down to a maximum size. I'd rather not have to to resort to text only notifications.

Here's an example of what I'm seeing:
![2017-08-09-141101_1920x1200_scrot](https://user-images.githubusercontent.com/8764444/29137351-035cd560-7d0e-11e7-9197-d9e93e062718.png)

**Comment by Eizen** [comment]
@TARDIS-Maker There's already such an option called "max_icon_size". By default it's set to 0, that's why it doesn't scale down icons. Check out the dunstrc config file for reference. I'll be closing this now, feel free to comment if the problem persists.

**Comment by TARDIS-Maker** [comment]
Oh, sorry. I had searched on Google quite a bit and didn't find anything, and then I thought that I had searched through the reference config file. I guess I either wasn't thorough enough or didn't use the right keywords.

Thanks for taking the time to respond, and sorry again.

**Comment by Eizen** [comment]
I've updated the wiki faq to reflect this problem. This was introduced in the latest release so the changelog file is a good place to find out about these changes fyi.
