### ISSUE TITLE
Rounded Corners Implementation

### ISSUE THREAD

**Issue by jonathashenriques** [dunst-project/dunst#358]
Would be nice if `Dunst` offers an option to use rounded corners. Is that possible ?

**Comment by dmitryplatonov** [comment]
Yes, that feature would be very useful. Maybe more general way of styling?

**Comment by bebehei** [comment]
Implemented in #420

**Comment by tsipinakis** [comment]
Implemented in 15c252afb051a81de1c86a14c5d839cb34aba5de.
