### ISSUE TITLE
Remove usage of non-portable GNU functions

### ISSUE THREAD

**Issue by tsipinakis** [dunst-project/dunst#359]
By defining `_GNU_SOURCE` in many header files we're enabling the usage of many GNU-specific functions that might not be portable to other OSs as demonstrated in #354. We should:

* [x] Figure out what GNU-specific functions we depend on
* [x] Find a suitable replacement or implement one ourselves if one isn't available
* [x] Remove the `_GNU_SOURCE` macro definition

**Comment by bebehei** [comment]
> Figure out what GNU-specific functions we depend on

I think there is no index for this, right? So I thought I let my computer do the work:

```
# for some reasons, `comm` and `sort` sort the lists differently if on `en_US` locale.
export LANG=C LC_ALL=C
DUNST_REPO=~/code/dunst

# search through every manpage for _GNU_SOURCE and extract the basename of it
find /usr/share/man -type f | xargs zgrep -l _GNU_SOURCE | sed 's%.*/%%;s%\.[0-9]\(\.gz\)\?$%%' |  sort -u > functions_gnu.txt

# search the dunst repo for all called functions
cscope -kL -2 '.*' $DUNST_REPO/src/{,x11/}*.{h,c} | awk -F ' ' '{print $2}' | sort -u > functions_called.txt

# compare both files and only print out used functions, which also have _GNU_SOURCE in the manpage 
comm -12 functions_gnu.txt functions_called.txt
```

So, this is the result. These functions may behave differently, if `_GNU_SOURCE` is defined:

```
basename
dup
getenv
getline
pipe
printf
strchr
strerror
strstr
```

**Comment by bebehei** [comment]
So, I've read manually through the GNU-manpages and searched, if the specific functions are GNU-specific:

- [x] basename
    - ruled out with latest PR #403 
- [ ] dup
    -  dup(), dup2(): POSIX.1-2001, POSIX.1-2008, SVr4, 4.3BSD.
- [x] getenv
    - the GNU one confirms to C99 standard even with `_GNU_SOURCE` defined
- [ ] getline
    - Both  `getline()`  and  `getdelim()`  were  originally  GNU extensions.  They were standardized in POSIX.1-2008.
- [ ] pipe
    - Confirming to: pipe(): POSIX.1-2001, POSIX.1-2008.
- [x] printf
    - the GNU one confirms to C99 standard even with `_GNU_SOURCE` defined
- [x] strchr
    - the GNU one confirms to C99 standard even with `_GNU_SOURCE` defined
- [x] strerror
    - the GNU one confirms to C99 standard even with `_GNU_SOURCE` defined
- [x] strstr
    - the GNU one confirms to C99 standard even with `_GNU_SOURCE` defined

So, how can we require `POSIX.1-2008`? If that's done, we can safely remove the `_GNU_SOURCE` stuff.

**Comment by tsipinakis** [comment]
Outstanding work as usual, I'll admit automating searching through the code and manpages to find the  relevant functions never really crossed my mind.

On to the current issue:

* `dup`, `pipe`: Looks like `_GNU_SOURCE_` only affects `dup3` and `pipe2` respectively if my reading of the synopsis on the man-page so no need to do anything there
* `getline`: I'm not sure we can do much more than checking the glibc version to verify the POSIX version but that would break compatibility with glibc alternatives like musl - Does dunst even work on these libraries and if so is anyone using them?

**Comment by bebehei** [comment]
>  Does dunst even work on these libraries and if so is anyone using them?

Let's compile it on alpine! I'll check it. Docker hast to be there for a reason ;-)

**Comment by bebehei** [comment]
Ha, it works on alpine like a charm: https://gist.github.com/bebehei/0a677b8179db695d67168c63af02580a
