### ISSUE TITLE
Additional logging & handling logging during tests

### ISSUE THREAD

**Issue by tsipinakis** [dunst-project/dunst#368]
I've wanted for a while to look into adding more detailed logging into dunst. Currently we have `fprintf` statements scattered around the codebase which makes the logging behaviour hard to control.

We should look into implement a more centralised logging solution that can be set to multiple levels from `error`, `warn` which are the messages we display now but it should also be able to be set to `debug` which would print step-by-step info on what dunst is doing to make debugging a bit easier.

A rough tasklist for that is as follows (will be expanded as needed):
- [ ] Decide on the logging API and its behaviour during testing
- [ ] Implement logging functionality
- [ ] Add more detailed logging calls to the code

---

I was prompted to create this issue while reviewing #365 in which a bug was encountered in the handling of an error condition which creates a problem with the current logging system since we can't implement a regression test without having errors in the test report.

The main question for now is: How we should distinguish expected and unexpected errors during testing? We can obviously simply disable them altogether but that would also disable logging unexpected errors that we DO want to be notified for.

**Comment by bebehei** [comment]
>  Decide on the logging API and its behaviour during testing

By accident, I found the glib logging functions. See: https://developer.gnome.org/glib/stable/glib-Message-Logging.html

- no extra deps
- works
- [easy to implement](https://github.com/bebehei/dunst/commit/19ad7c568a7d124459deeacfaf68ed3005cb5e2b)

**Comment by bebehei** [comment]
As #428 has to test for faulty values, I've sat down on this again. I'm working currently on this [at my logging branch](https://github.com/dunst-project/dunst/compare/master...bebehei:logging).

>  Decide on the logging API and its behaviour during testing

The decision to specify, which *external* logging API we should use, is actually quite easy. The [GLib logging methods](https://developer.gnome.org/glib/stable/glib-Message-Logging.html) work easy, fully suffice the needs and do not increase our footprint. To not make the race, there has to be another framework, which is exceptionally good. But there isn't. All other frameworks have their specialities. GLib does simple general Purpose logging. That's what we need.

Alternatively, we could assemble our own small header files, which do not have to be big to be powerful.

>  Add more detailed logging calls to the code

I also miss some some calls by default in dunst. When debugging some issues, I mostly have to write all my logging calls from scratch. But in relation to this PR, I wouldn't make this a goal of it. I think it's more effective to introduce logging calls when you really need them. I think we should give here a rough guideline, when it's neccessary/ok to introduce new calls with new code.

> The main question for now is: How we should distinguish expected and unexpected errors during testing? We can obviously simply disable them altogether but that would also disable logging unexpected errors that we DO want to be notified for.

Unit testing has its purpose to feed the program with faulty input. And the program spits out warning, when fed with faulty input. Our tests should not cover the warnings. These should check, that the returnvalues are still sanitized. Their purpose is not to check for warnings.

Anyways, when we're feeding the program with faulty input, it's expected to print warnings. So when testing with enabled logging, you have to go through every message manually.

---

I would also add another point: Logging guidlines

I would in general add some logging guidlines written down (maybe in Contributing.md or somewhere else), which are covering the following questions.

1. What to log?
1. When to log?
1. What's which level?
1. Message formatting

**Comment by bebehei** [comment]
I'm finished with it. Actually I'd like to give it into review now and get feedback. But i'd like to get #428 at least approved first.

**Comment by bebehei** [comment]
We may want to use structured logging, too. This is really neat in combination with systemd. https://www.youtube.com/watch?v=I_elueI6JY0

**Comment by bebehei** [comment]
Idea: print the notification as log message with structured logging enabled. Then with `verbosity = info`, all messages get logged and also put into systemd. As systemd knows how to handle structured log messages, you can save your notifications forever!!11elf
