### ISSUE TITLE
dunst does not respect config when waking up from suspend

### ISSUE THREAD

**Issue by amituttam** [dunst-project/dunst#373]
Compiled and installed dunst from source and it works well in general with the config I have in .config/dunst. However, when waking up from sleep the user that launches dunst is `lightdm` but the settings used are the default ones.

I changed `/usr/local/share/dbus-1/services/org.knopwob.dunst.service` and changed the `Exec=` command to `Exec=/usr/local/bin/dunst -conf /home/amituttam/.config/dunst/dunstrc1`.

Thus, now when the system wakes up from sleep/suspend `ps aux` shows:

```
lightdm   2285  0.0  0.0 455056 15544 ?        Sl   17:39   0:00 /usr/local/bin/dunst -conf /home/amituttam/.config/dunst/dunstrc1
```

But the settings are still not respected. What is the best way to resolve this issue?

**Comment by bebehei** [comment]
Just for the technical aspect:

> I changed /usr/local/share/dbus-1/services/org.knopwob.dunst.service and changed the Exec= command to Exec=/usr/local/bin/dunst -conf /home/amituttam/.config/dunst/dunstrc1.

<del>

Well, the exec-line in your dbus service file won't get respected, if you have set `SystemdService=dunst.service`.

You have to modify your `dunst.service` file from systemd and **not from dbus**.

But actually, that's not your problem. The problem is somewhere else:

</del>

Oh, I see. Dbus actually runs dunst with your option. So you have to run another init daemon than systemd. right?

---

> Compiled and installed dunst from source and it works well in general with the config I have in .config/dunst. However, when waking up from sleep the user that launches dunst is lightdm but the settings used are the default ones.

There is something going south. When your dbus session starts, it should start every process as the actual user. The fact, that dunst is launched as the lightdm user, it indicates, there is a bug or a misconfiguration in lightdm's session handling.

Check, that dbus is running right and check your logfiles for errors indicating any configuration mistake.

If lightdm/dbus is starting the session wrong, this is clearly not dunst's fault.

**Comment by amituttam** [comment]
Thanks for the reply. I finally got around to debugging this further. So here is what I am doing:

Verify that dunst is not running:

```
$ ps aux | grep dunst
amitutt+ 22441  0.0  0.0  12784   952 pts/0    S+   17:10   0:00 grep --color=auto dunst
```

`dunst.service` is enabled in as a user service in systemd but does not start:

```
$ systemctl --user status dunst.service
● dunst.service - Dunst notification daemon
   Loaded: loaded (/etc/systemd/user/dunst.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-10-07 14:51:31 PDT; 1 day 2h ago
     Docs: man:dunst(1)
  Process: 1917 ExecStart=/usr/local/bin/dunst (code=exited, status=1/FAILURE)
 Main PID: 1917 (code=exited, status=1/FAILURE)
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

Starting it manually:

```
$ systemctl --user start dunst.service
Failed to start dunst.service: Unit dbus.socket not found.
```

Looks like all the env variables are set correctly:

```
$ env | grep -e 'DBUS' -e 'DISPLAY'
DISPLAY=:0
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-m0G4AYNXjM,guid=2fee97cd023991ca33d934de59d94c64
```

Then, when I manually do `notify-send 'this is a test message'`, it works as expected:

```
$ notify-send 'this is a test message`
# This displays the notification correctly with the proper settings in my ~/.config/dunst/dunstrc
$ ps aux | grep dunst
amitutt+ 25244  0.0  0.0 446880 16048 ?        Sl   17:34   0:00 /usr/local/bin/dunst
$ ps -o ppid= -p 25244
    1
```

Now, looking at `dbus` stuff in systemd, it looks OK:

```
$ systemctl | grep dbus
  dbus.service                                                                              loaded active running   D-Bus System Message Bus
  dbus.socket                                                                               loaded active running   D-Bus System Message Bus Socket
```

So at this point, `dunst` is running, spawned somehow by my user. I close the lid of the laptop and open it again, at this point `lightdm` seems to be the one spawning dunst:

``` 
$ ps aux | grep dunst
amitutt+ 26730  0.0  0.0 446884 15560 ?        Sl   17:41   0:00 /usr/local/bin/dunst
lightdm  27046  0.5  0.0 447032 15464 ?        Sl   17:43   0:00 /usr/local/bin/dunst

$ ps -o ppid= -p 27046
    1
```

I completely agree it is definitely some weird issue with the setup I have (debian + bspwm). But can't figure out what the issue could be. Hope this helps clarify what I'm seeing and you maybe able to suggest a fix. And we can potentially add it in the FAQ if this can be resolved.

**Comment by bebehei** [comment]
> ```
> $ systemctl --user status dunst.service
> ● dunst.service - Dunst notification daemon
>    Loaded: loaded (/etc/systemd/user/dunst.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Sat 2017-10-07 14:51:31 PDT; 1 day 2h ago
>      Docs: man:dunst(1)
>   Process: 1917 ExecStart=/usr/local/bin/dunst (code=exited, status=1/FAILURE)
>  Main PID: 1917 (code=exited, status=1/FAILURE)
> Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable
> ```

This is the most important error message (which is not there). Please get this error message!

>So at this point, dunst is running, spawned somehow by my user. I close the lid of the laptop and open it again, at this point lightdm seems to be the one spawning dunst:

Here the same: Please give the (valid) output of `systemctl --user status dunst`.

---

What version of dunst do you use?

**Comment by WhyNotHugo** [comment]
> Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable

This means that journald rotate the logs. That's far beyond dunst's control, and because of your local settings.

**Comment by bebehei** [comment]
@amituttam Do you have any resolution on this?
