### ISSUE TITLE
Missing /usr/lib/systemd/user/dunst.service in v1.1.0 (Debian)

### ISSUE THREAD

**Issue by pylipp** [dunst-project/dunst#377]
I had an issue with dunst v1.1.0-2+b1 that I could fix myself. 

I'm on Debian buster/sid using i3 (started by startx) and installed dunst v1.1.0-2+b1 via `sudo apt-get install dunst`. In my i3 config I have `exec --no-startup-id dunst`. However running notify-send does not show any notifications. Grepping `ps aux` for `dunst` or `noti` didn't give any hits. Running `dunst` in terminal shows `Name Lost. Is Another notification daemon running?`. 

Taking a look at the dunst Makefile, I see that the `install-service` target copies the `dunst.service` file to `/usr/lib/systemd/user/`, however it was missing on my system. I manually added the file based on the template in the dunst project directory, `chown root:root`ed it, logged out and in and notify-send displayed stuff. 

HTH!

**Comment by bebehei** [comment]
Albeit version `v1.1.0-2+b1` is the latest on debian, it's heavily outdated, [see the changelog](http://metadata.ftp-master.debian.org/changelogs/main/d/dunst/dunst_1.1.0-2_changelog).

Version `1.2.0` of dunst got released in july and there are >2 years development work in between. You may want to ask [the maintainer](https://qa.debian.org/developer.php?login=stapelberg%40debian.org) to update dunst to the current version and then let it run through testing/unstable/sid to land in the next release.

If it's still an issue on master (or 1.2.0), everyone would be happy to receive a PR.

**Comment by pylipp** [comment]
Alright, thanks for the update! I installed dunst from master and the issue is gone. I will inform the maintainer.
