### ISSUE TITLE
Enable actions to send text to the parent application

### ISSUE THREAD

**Issue by kauron** [dunst-project/dunst#383]
Some notifications (telegram desktop for example) send a notification with a Reply to action. I would like to be able to respond from the dmenu

**Comment by tsipinakis** [comment]
Sending back text is not listed anywhere in the [notification spec](https://developer.gnome.org/notification-spec/) so I don't see how that could be added unless telegram is using some unofficial interface.

I wouldn't expect this to work with any notification daemons.

**Comment by bebehei** [comment]
Telegram is using its own notification window only if the Linux native notification daemon is not usable. There you can hit reply. Telegram knows how to process the replied text. This is not a use case of the Freedesktop Notification Spec and therefore there is no handling of such a reply button.

If you really want to have a reply button, it's currently only possible to manually disable native notifications in telegram settings.

**Comment by kauron** [comment]
Thanks for the reply
