### ISSUE TITLE
Support hide_duplicate_count in rules

### ISSUE THREAD

**Issue by nvllsvm** [dunst-project/dunst#384]
The hide_duplicate_count attribute should be supported in notification rules. I would like to set this attribute only for my volume and backlight notifications.

**Comment by bebehei** [comment]
@nvllsvm It's a rather small fix inside of dunst. But this actually indicates other problems in the client software. Please look forward to support the replace option in the software, which is actually the correct option.

**Comment by tsipinakis** [comment]
#552 Was just merged which satisfies the use case mentioned so I'll close this. If `hide_duplicate_count` is still needed for some reason feel free to comment here and I'll re-open it.
