### ISSUE TITLE
Notifications with --replace never disappear

### ISSUE THREAD

**Issue by josduj** [dunst-project/dunst#398]
To reproduce, run:
```bash
r=0; for i in {1..5} ; do r=$(dunstify --replace=$r --timeout=2 --printid "Hi $r - $RANDOM") ; sleep 1 ; done
```

Could be related with https://github.com/dunst-project/dunst/pull/391

**Comment by tsipinakis** [comment]
Confirmed here, apparently my review wasn't as thorough (it's also why we need better tests -.-).

Random theory but I think that this is because the new notification skips the queue and goes straight to the displayed list and hence `n->start` isn't initialized.

**Comment by bebehei** [comment]
> Random theory but I think that this is because the new notification skips the queue and goes straight to the displayed list and hence n->start isn't initialized.

Yes, this is the problem. Shall I push a patch?

**Comment by tsipinakis** [comment]
> Shall I push a patch?

Sure, go ahead if you want. But we should also check what else gets skipped, just looking at that function looks like `notification_run_script` isn't being called either when it should be.
