### ISSUE TITLE
dunst doesn't work well with Thunderbird

### ISSUE THREAD

**Issue by paride** [dunst-project/dunst#399]
When using dunst with Thunderbird (and the GNotifier add-on) the following happens:
- Every time there is a notification, dunst outputs this error kind: `Error parsing markup: Error on line 1 char 59: 'xxxxxx.yyyyyyyy@gmail.com' is not a valid name: '@`. This happens even if I specify `allow_markup = no` in my `dunstrc` configuration file.
- For some reason notifications from Thunderbird begin with an `(A)`, even if `format = "[%a] %s\n"`. Instead of notifications like `[Thunderbird] ...`, I'm getting notifications like `(A) [Thunderbird] ...` .

```
$ dunst --version
Dunst - A customizable and lightweight notification-daemon 1.1.0
```

**Comment by tsipinakis** [comment]
Can you post the output of `dbus-monitor` while one of the broken notifications comes through?

**Comment by tsipinakis** [comment]
> For some reason notifications from Thunderbird begin with an (A), even if format = "[%a] %s\n". Instead of notifications like [Thunderbird] ..., I'm getting notifications like (A) [Thunderbird] ... .

`(A)` means that thunderbird has set some actions that you can perform on the notification (look into the `ACTIONS` section of the documentation). Alternatively you can disable it entirely with `show_indicators = false`.

**Comment by paride** [comment]
Thanks for the clarification, the parsing problem remains. Here is the output of `dbus-monitor`:
```
method call time=1507220812.644327 sender=:1.23 -> destination=:1.158 serial=45 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Thunderbird"
   uint32 0
   string "thunderbird"
   string "Xxxxxx Yyyyyyyy <xxxxxx.yyyyyyyy@gmail.com>"
   string "aaaa"
   array [
      string "default"
      string "Open"
      string "gnotifier_139802508533648"
      string "Mark as read"
      string "gnotifier_139802511576272"
      string "Delete"
      string "gnotifier_139802542293936"
      string "Archive"
   ]
   array [
   ]
   int32 -1
method return time=1507220812.645422 sender=:1.158 -> destination=:1.23 serial=19 reply_serial=45
   uint32 9
```
I realized I'm not using the latest available version of `dunst`, I'm not sure if that matters in this case.

**Comment by tsipinakis** [comment]
I'm not sure what
```
'xxxxxx.yyyyyy@gmail.com' is not a valid name: '@'
```
means (it's probably trying to parse it as a tag?) but then it shouldn't error when `allow_markup = no`.

Anyway, I have confirmed that it's indeed fixed in the latest version with `markup = no`.

**Comment by paride** [comment]
Fine, I'm closing this for now and try the latest version. Thank you.

**Comment by bebehei** [comment]
@paride I had the same problem but it wasn't worth for me spending time yet. Now, I reported a bug. There is also a possible workaround: See mkiol/GNotifier#192
