### ISSUE TITLE
Inconsistency with duplicate check and replacing notifications in-place

### ISSUE THREAD

**Issue by tsipinakis** [dunst-project/dunst#404]
Currently `stack_duplicates` is enabled and a notification is sent to replace an existing one the following happens

* Scenario 1:

    If the notification is identical to another notification the duplicate count of the other notification is increased leaving the notification it's meant to replace untouched - Obviously wrong behaviour, correct one would be to either
    - Replace the notification and leave 2 identical notifications up
    - Merge the two notifications (and their duplicate counts) together

    In my opinion option 2 would be the sane option but it's also the harder one to implement currently

* Scenario 2:

    If a notification is sent to replace an existing one but it turns out to be identical the duplicate count of the existing one is increased. This is probably a very rare case but in my opinion identical replace calls shouldn't count as a "duplicate" notification.

This is obviously due to the way `notification_init` is structured and a clean-up is very much needed there.

**Comment by bebehei** [comment]
This is what I'm also targeting in the queue-refactoring. See https://github.com/bebehei/dunst/commit/7a1a1ed70aed5b3cf66d1b2193d25981320c838d#diff-4a78fe4a1e47fe57fc0581a862ffabd2R437
