### ISSUE TITLE
Default icon names invalid?

### ISSUE THREAD

**Issue by krayon** [dunst-project/dunst#405]
The default icon names appear to be based on urgency and are currently:

    char *icons[] = { "info", "info", "emblem-important" }; /* low, normal, critical */

For me, this causes an error for each notification generated for each urgency level:

    Could not load icon: 'info'
    Could not load icon: 'info'
    Could not load icon: 'emblem-important'

Reading through https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html should these not be something like:

    char *icons[] = { "dialog-information", "dialog-information", "dialog-warning" }; /* low, normal, critical */

**Comment by bebehei** [comment]
On my system, the `info` icon is linked to the `dialog-information` icon. So there is evidence, that the `info` icon is not the right one. On some other systems, these links might not exist.

Also the `emblem-important` icon looks quite out of style on my system:
![screenshot from 2017-10-07 12-06-15](https://user-images.githubusercontent.com/2073458/31306835-f9dd57da-ab57-11e7-8454-afe4c0d9e361.png)

**Comment by krayon** [comment]
@bebehei I noticed the emblem icon being from a different set also. Thanks @bebehei and @tsipinakis for the rapid fix! I would have created a PR but was afraid I didn't know what I was talking about :P
