### ISSUE TITLE
Productivity feature: buffering notifications

### ISSUE THREAD

**Issue by alem0lars** [dunst-project/dunst#408]
Some studies and productivity books clearly state that social interactions and notifications kill productivity because they distract and make the person lose focus in what he was doing.

A possible way to prevent that and still not lose notifications is to (maybe with a hotkey or something else) se a time delay which notifications will be buffered and not triggered.

Then, when person releases the buffer (maybe with another hotkey or something else) all notifications are prompted to the user, possibly with timestamp of when the notifications has been received by dunst.

This allows a person to focus on a particular task by temporarly turning off notifications and then get all notifications when task is finished.

Thanks,
Alessandro

**Comment by bebehei** [comment]
There is some undocumented workaround already there:

To pause dunst (and not show any message):
```
notify-send DUNST_COMMAND_PAUSE
```

To make dunst work again:
```
notify-send DUNST_COMMAND_RESUME
```

Combined with a small bash script it, it may work.

These commands are somewhat hacky and get replaced in a future release with a proper `dunstcmd` tool.

**Comment by alem0lars** [comment]
Thanks very much :+1: 

I'm going to close the issue since there is already a working way to achieve that.

However, `dunstcmd` tool would be awesome!

PS: Maybe, that piece of information could be useful to other users.. Probably it's better to keep it trace in README.md ?

Thanks again,
Alessandro

**Comment by bebehei** [comment]
> PS: Maybe, that piece of information could be useful to other users.. Probably it's better to keep it trace in README.md ?

Well, I consider it rather a hack and not the right solution for this answer.

Also telling more and more ppl about a hack, makes it not very easy to remove it later on and replace it properly.

IMO this should be really implemented in code. But it'll have low priority.

**Comment by WhyNotHugo** [comment]
The man pages explain supported signals which can do this (pause/resume).

If there really anything else that needs implementing here?
