### ISSUE TITLE
Deprecating STATIC_CONFIG and config.h

### ISSUE THREAD

**Issue by tsipinakis** [dunst-project/dunst#414]
As discussed in #371 the static config functionality is a terrible hack that pollutes the global namespace way too much and I don't really know any legitimate uses for it. Additionally the way the file is structured basically guarantees that it breaks with almost every major change as dunst refuses to compile without manually updating the file.

I'm curious, is anyone using this functionality? During the time I've been a maintainer but also from what I've seen looking at the history of the project noone has reported an issue or even commented on using this feature.

As usual if someone wants to use dunst without a configuration option, using `dunst -config /dev/null` should be sufficient.

Issue #412 proposes a possible replacement.

**Comment by fwSmit** [comment]
Implemented by #803
