### ISSUE TITLE
Dunst consumes notifications from Pushbullet

### ISSUE THREAD

**Issue by erikw** [dunst-project/dunst#422]
Hello!

I love dunst, and have used it every day for many many years (2012 I think). Awesome work!

However I have also for many years had an annoying problem, which I've not take the time to report until now unfortunately. Sooo here we go.. :)

If you mirror your phone's notifications to your desktop using Pushbullet, dunst will also pick these up but also consume them. Directly when dunst closes the notification, it disappears from the Pushbullet dialog.

### How to demonstrate:

1. Make sure no dunst is running: `$ killall dunst`.
1. Install Pushbullet android app and login.
1. Install Pushbullet Firefox extension and login.
1.  Go to the app, Hamburber menu > Notification Mirroring > Send a test notification
1. Verify that the notificatin shows up under the Pushbullet icon in Firefox, and that it *stays there*, until manually dismissed.

Now start dunst
1. `$ dunst`
1. Send another test notification from the Pushbullet app.
1. Verify that Dunst shows the notification, and that it shows up under the Pushbullet icon in Firefox like before.
1. Observe now that when dunst closes the notification because of the default timeout, the notification is also removed from Pushbullet!

### Desired behaviour:
The notification should be showed in dunst, but but remain in the Pushbullet firefox extension!

See this image for a visualization of the problem:

![dunst_pusbullet](https://user-images.githubusercontent.com/175286/32147715-f52649a4-bceb-11e7-9fb2-e6c760a6456b.png)

I know that I can ignore Pushbullet notifications in `dunstrc` with:

```ini
[pushbullet]
    summary = "Pushbullet*"
    format = ""
```

but I want both: dunst to show the notification and it to remain in Pushbullet extension.

So is it possible to tell Dunst to not "consume" the notification, only to be a silent receiver of it?

Thanks,

### Installation info
- Version: `Dunst - A customizable and lightweight notification-daemon 1.2.0 (2017-07-12)`
- Install type: `arch pacman`
- Distro and version: ` arch64, up to date`

Firefox: 56
Pushbullet extension: latest

**Comment by bebehei** [comment]
> So is it possible to tell Dunst to not "consume" the notification, only to be a silent receiver of it?

Dunst is a silent receiver of it. It does not instruct the Firefox plugin to eat the notification and it has no API for it. Sadly, this is behavior of your pushbullet app.

**Comment by bebehei** [comment]
> I know that I can ignore Pushbullet notifications in dunstrc with:

You have to tell Pushbullet (or firefox, I don't know what API pushbullet uses), that the notification should not be sent via the native notification daemon.

**Comment by erikw** [comment]
Somehow the Pushbullet extensions knows when dunst stops displaying it at least, as it disappears exactly when dunst times the notification out or I force close it with a keyboard shortcut.

How could this be? :)

**Comment by bebehei** [comment]
> How could this be? :)

Pushbullet/Firefox sees, that the process behind the DBus service `/org/freedesktop/Notifications` died and it does not send its notifications over it anymore. It's not that it's smart. It can't do it anymore and falls back.

**Comment by tsipinakis** [comment]
> Somehow the Pushbullet extensions knows when dunst stops displaying it at least, as it disappears exactly when dunst times the notification out or I force close it with a keyboard shortcut.

As the notification specification mandates, when a notification is closed the notification daemon (in this case dunst) emits a `NotificationClosed` signal with the id of the notification and the close reason, so pushbullet gets a signal and knows if the notification was closed and if it timed out or if it was manually closed.

This doesn't seem to be a problem with dunst but rather a problem with how the pushbullet firefox extension handles that signal.

**Comment by bebehei** [comment]
After reading @tsipinakis answer, I've understood, that I answered completely wrong. Sorry for this.

I have to acknowledge your bugreport. It's very thorough and actually well understanding.

And as also @tsipinakis mentioned: Please go to the Pushbullet authors and ask them kindly to change the behavior of the notifications.

Not sending `NotificationClosed` signals can make some apps hang (I'm looking at you spotify!).

---

@erikw I smell something different: It may be the case, that PB sends these notifications "persistent". Then this issue gets a complete different context. It would be still PB's fault (dunst does not provide persistent functionality (yet?)), but I would understand PB's behavior and it would be consistent.

Could you please run `dbus-monitor path=/org/freedesktop/Notifications,member=Notify` and fire a test notification while dunst is running and paste the output of the command? Thanks in advance.

**Comment by bebehei** [comment]
Like "everyday something new": I've disassembled their [XPI](https://addons.mozilla.org/firefox/downloads/file/509052/type:attachement/pushbullet-335-fx+an.xpi). I was surprised it was just a simple unzip (there was no minification and it wasn't obfuscated, wow!).

My JS skills are very old, but I could figure out the codebits. In `notifier.js`, there is this:

```
    chrome.notifications.onClosed.addListener(function(key, byUser) {
        utils.wrap(function() {
            var notification = pb.notifier.active[key];
            if (notification && byUser) {
                if (notification.onclose) {
                    notification.onclose();
                }

                delete pb.notifier.active[key];
                pb.dispatchEvent('notifications_changed');
            }
        });
    });
```

Looking at this code, the function should work in any browser perfectly (except the `chrome` stuff, but browsers can handle this for some weird reasons). **And they even have a field, if the user did it!!!!!11!eleven!**

Well, a closer look to the Webextension specs [reveals the real bad guy in this scene.](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/onClosed#Browser_compatibility)

> Please go to the Pushbullet authors and ask them kindly to change the behavior of the notifications.

No, they did everything right ;-) We're more basic here. You have to go Firefox first (or even solely?).

**Comment by erikw** [comment]
Wow I love the enthusiasm from you both @bebehei and @tsipinakis!

Very interesting finds you made.


The "chrome" seems to be a [namespace](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#Callbacks_and_the_chrome.*_namespace) that is called "browser" in the Firefox world, but it supports "chrome" as well to being able to run more chrome extensions out-of-the-box, I guess.

@bebehei Hmm so from that last link it says that 

> byUser
    boolean. true if the notification was closed by the user, or false if it was closed by the system. This argument is not supported in Firefox.

So I'm not sure what this means, that the variable has value "undefined" in the above code in Firefox. If so, then we don't go in to the if-statement and do the `notification.onclose()`. Do you suggest that the notification would stay in PB if that `onclose()` is called?


Okay so I went ahead and tried that directly in Chromium 62, and first enable normal desktop notifications by going to

```
chrome://flags/#enable-native-notifications
```

and indeed! In chrome the notification stays in PB even after Dunst has shown it! It could of course be for another reason, and I've not compared the PB source for Firefox and Chrome, but I would guess the code you pasted above is the same.

So hm I guess our hopes are at Firefox to start supporting the `byUser` argument then? :)

**Comment by bebehei** [comment]
> So hm I guess our hopes are at Firefox to start supporting the byUser argument then? :)

These hopes are quite limited: Searching in [mozilla's bugzilla](https://bugzilla.mozilla.org/) for `byuser` does not return any result. I guess, you have to get active by yourself.

**Comment by erikw** [comment]
I notified the Pushbullet guys in their subreddit now:

https://www.reddit.com/r/PushBullet/comments/79r7ct/dont_use_unsupported_byuser_for/

**Comment by bebehei** [comment]
> I notified the Pushbullet guys in their subreddit now

Looking at [pushbullets' release schedule](https://addons.mozilla.org/en-US/firefox/addon/pushbullet/versions/) gives me the feeling, that it might be faster requesting the `byUser` from the Mozilla guys.

**Comment by erikw** [comment]
Wow you are right, that is slow!

I posted this to Firefox's Bugzilla now:

https://bugzilla.mozilla.org/show_bug.cgi?id=1413188

I guess we close this issue here now, as the problem indeed is at either Firefox or Pushbullet's end.
