### ISSUE TITLE
Behaviour of duplicate notifications (again)

### ISSUE THREAD

**Issue by tsipinakis** [dunst-project/dunst#427]
As part of #411 there was a change to the way dunst assigns ids to duplicate notifications, instead of assigning a new id for the merged notifications it re-uses the old one. While that seemed like a good idea at the time of the review it makes much less sense now that I think about it and leaves some open problems on duplicate notifications:

* The [notification spec](https://developer.gnome.org/notification-spec/#commands) states that ids should not be re-used unless all ids have been exhausted
    > The return value is a UINT32 that represent the notification. It is unique, and will not be reused unless a MAXINT number of notifications have been generated.

* Misses actions
    If a new notification is sent and stacked with an existing one, the actions of the first notification are used and the second ones are ignored.
    We should look into merging them (and maybe track for which notification each action belongs to so that we can handle them appropriately)

* Confusion with `CloseNotification` signal
    Previously when dunst returned a new id for each stacked notification only the id of the original notification could be used to close it. Now this is fixed since we return the same id but as mentioned above the notification spec has a note against that and it might confuse some clients.

---

For a proposed solution: Keep all merged in an array inside the original notifications struct (and assign a new id to each one). This will allow us to handle each duplicate notification as a separate one while still merging them into one when displaying them.

The downsides:
* Slightly increased memory usage (which can be trimmed by only storing the actions, id and anything else relevant for the duplicates)
* Complicates the iteration/lookup code for the notifications
    If we need to close a notification by id for example not we don't only need to check all queues but every duplicate notification inside each queue as well.

**Comment by bebehei** [comment]
> The notification spec states that ids should not be re-used unless all ids have been exhausted

Stack duplicates violates the spec heavily. Oh man. What have you done @bebehei.

> Misses actions

Well, how should we do this as best? I actually think, we should do `iter->data = new` and copy some internal fields (like `new->dup_count = old->dup_count`) back. Copying the new fields manually to the new will always miss some fields at some point.

> Slightly increased memory usage

You're absolutely right, but considering how dunst leaked before #421 and #397 (and probably still leaks), this argument renders ridiculous.

> Keep all merged in an array inside the original notifications struct (and assign a new id to each one).
> [...]
> Complicates the iteration/lookup code for the notifications

I would do it slightly different. Close the old notification properly, at the point, when it got stacked.

Why?

- If the client registered some actions, it stops to listen for the old id. The client wouldn't receive any action signals either for the old id. And if it sends actions with the second id, it should listen for this anyway.
- A client does not know, if the notification is stacked. Only [notify osd does merging, too](https://wiki.ubuntu.com/NotifyOSD#merging). And notify-osd requires that you indicate it as the client.

**Comment by tsipinakis** [comment]
> If the client registered some actions, it stops to listen for the old id.

Why would it stop listening on the old id until it receives a `NotificationClosed` signal? On the `ActionInvoked` call we also specify the notification id so multiple notifications with actions can be up from the same client simultaneously without a problem.

**Comment by bebehei** [comment]
>> If the client registered some actions, it stops to listen for the old id.
>
> Why would it stop listening on the old id until it receives a NotificationClosed signal?

Because you can't click on an action, which is not displayed (e.g.: closed). <del>There is no standard for this</del> but all programs do.

From the [notificationClosed signal](https://developer.gnome.org/notification-spec/#signals) docs:

> The ID specified in the signal is invalidated before the signal is sent and may not be used in any further communications with the server.

**Comment by bebehei** [comment]
Example call: notification A (id 1), notification B (id 2), `notification_is_duplicate(A,B) == TRUE`.

```
send(a)
dunst returns id 1
send(b)
{ // stacking
    dunst sends NotificationClosed 1
    dunst returns id 2
}
```

**Comment by tsipinakis** [comment]
>     dunst sends NotificationClosed 1

With what reason? We could use 4 but I would really like to avoid that.

> From the notificationClosed signal docs:

Seems there's some misunderstanding here, I'm talking about the following scenario:

* Notification A arrives with some action, app is listening for a response
* Notification B arrives from the same app with some more actions
* Dunst judges that the 2 notifications are duplicates and merges them, returns the same id.

With the current behaviour we have the contents and actions of notification A displayed. Now the application is listening for actions on 2 notifications with the exact same id **(!)** since none of them has been closed yet and dunst only displays one of them.

**Comment by bebehei** [comment]
> Seems there's some misunderstanding here, I'm talking about the following scenario: [...]

I'm already beyond the ID return value. The scenario you describe is currently handled faulty by dunst. I acknowledge it.  (I developed already a fix for this in my repo.)

I'm already talking about how we handle the merge of the new and old notification, when the notifications get stacked. And there is my point, that we should avoid the merge of both notifications and just immediately send a `NotificationClosed` signal for the old notification at the point where both notifications got stacked.

> With what reason? We could use 4 but I would really like to avoid that.

I meant id=1, I also don't know the best reason integer for it.
