### ISSUE TITLE
Deduplicate Icon structures

### ISSUE THREAD

**Issue by bebehei** [dunst-project/dunst#430]
Sending multiple notifications with the same icon makes dunst saving the icon surface of the icon multiple times.

It would make sense to save the icon surface of the colored layouts in a hash table (see [GHashTable](https://developer.gnome.org/glib/stable/glib-Hash-Tables.html)). This saves memory **and** cputime for all upcoming notifications with the same icon.

It might be a good choice to do the same with the `raw_icon` and hash its data to a short string to have an identifier.

---

This makes only sense **after** the refactorings to `draw.c`.

**Comment by bebehei** [comment]
I've taken now the approach to implement a `GHashTable` for the icons on my own PC. My idea was to use save `GdkPixbuf` icons in the hash table. The hashtable holds only a weak reference onto the pixbuf. When the last notification unrefs its pixbuf, the weak ref callback fires and can remove the entry out of the `GHashTable`. Works well.

My argument from then was: By caching, we can save CPU time, but we buy this by having a higher memory footprint. Deduplication would could fight this. With a `GHashTable` saving a `GdkPixbuf` this would be an easy solution.

But, while inspecting our icon infrastructure now, we don't save any significant cpu time. Our current problem is mainly the complete drawing process. We don't have anything to cache the pixel data anywhere. For every redraw (which happens far more often than creating new notifications), we:

1. read the file from disk
   - maybe we even search the whole icon path before
1. convert the image into a GdkPixbuf
1. scale the pixbuf if necessary
1. Write the png stream into a memory buffer
1. let cairo convert the png data into a surface
1. throw everything out again

In the fix for #571, I'm starting to cache the `GdkPixbuf` together with the notification. Sounds like a good idea and a first step towards my idea above. But it's not radical enough. The most expensive points are actually the steps from `GdkPixbuf` over png stream to `cairo-surface_t`. 

And I'm planning, that after #585, we cache the raw cairo surface data in the notification. This is quite small, because it's already scaled. (For an icon holding 96x96 pixels, it's 37kb.) This is almost nothing.

Introducing complexity with a HashTable isn't worth it.

**Comment by tsipinakis** [comment]
> In the fix for #571, I'm starting to cache the GdkPixbuf together with the notification. Sounds like a good idea and a first step towards my idea above.

The optimal thing would be to cache the `colored_layouts` so the redraw time is minimal, but that would require another partial refactor of the drawing system.

**Comment by bebehei** [comment]
Yes, caching the whole `colored_layout` might make sense and would be the best solution. But the colored layout only contains the scaled image. Dedupping that requires more complexity with almost no benefit.
