### ISSUE TITLE
Left mouse button for clickable actions

### ISSUE THREAD

**Issue by that1communist** [dunst-project/dunst#435]
This should at least be configurable, on my laptop its really annoying to three finger tap them to open something.

i'd do it myself but i don't know C.

I'm pretty sure it'd just be making Button3 into a variable.

Thank you.

**Comment by sistematico** [comment]
#234

**Comment by sistematico** [comment]
#234

**Comment by tsipinakis** [comment]
Closing as a duplicate to #234
