### ISSUE TITLE
progress values > 100

### ISSUE THREAD

**Issue by three-comrades** [dunst-project/dunst#437]
Currently, dunst doesn't show a progress value, [if it is larger than 100](https://github.com/dunst-project/dunst/blob/62e50289f0ead4cc0074b5ed7314302caf72688c/src/dbus.c#L265). It would be nice to change the behavior for two reasons:

- even with percentages, values larger than 100 are used in the wild. For example `pavucontrol` uses percentages > 100%
- the `%n` format specifier doesn't seem to be tied to a unit, so the restriction to 100 seems arbitrary

**Comment by bebehei** [comment]
On the one hand side, I agree with you. I'm also affected of the same <del>`pavucontrol`</del>`pulseaudio-ctl` bug.

But: What's the semantic sense of having 120% progress? Can you explain?

IMHO, `pulseaudio-ctl` should fix this and normalize the progress before sending the notification.

**Comment by bebehei** [comment]
> IMHO, `pulseaudio-ctl` should fix this and normalize the progress before sending the notification.

See graysky2/pulseaudio-ctl#49. Pulseaudio-ctl did it already, but did not calculate the expression.

**Comment by three-comrades** [comment]
In my opinion, there are two points:
- talking about progress: yes, it doesn't make sense to have progress > 100%. But then again, it would make perfectly sense to report total progress instead of percentages  (which was my initial understanding of the purpose of the `%n` specifier) . E.g., the number of files you've copied (out of a total amount)
- more importantly, I think it would make sense to generalize the meaning. Instead of reporting a literal progress, I may want to report/update a system state. And with states > 100% make perfectly sense.

**Comment by tsipinakis** [comment]
I'll have to agree here, having an arbitrary limit on the progress makes no sense, we aren't here to debug other peoples bugs, let's just display the value as-is.

If @bebehei agrees I'll go ahead and change that.

**Comment by bebehei** [comment]
> If @bebehei agrees I'll go ahead and change that.

I actually waited for your answer 😉 . I don't have any valid arguments, so I agree.

Also I'd like to add: The hint sent via notification is actually called `value`. It might also be a good choice to refactor this to make this clear.

**Comment by tsipinakis** [comment]
> The hint sent via notification is actually called value. It might also be a good choice to refactor this to make this clear.

While `value` might be a good name in the notification where there are a few ints - it makes for some very confusing code if it's mixed in with other things.

**Comment by bebehei** [comment]
> Also I'd like to add: The hint sent via notification is actually called `value`. It might also be a good choice to refactor this to make this clear.

I withdraw my statement. In the standard, there is no reference to a hint called `value`. It's just that most people use it. Sticking to `progress` is fine.

**Comment by tsipinakis** [comment]
JFTR, I'm waiting for #428 to implement this since it would conflict currently
