### ISSUE TITLE
Invalid commandline: Invalid byte sequence in conversion input

### ISSUE THREAD

**Issue by seamus-45** [dunst-project/dunst#443]
Hi!
I get this error when invoking dunstify with `--icon='/music/Ascendant/Æthereal Code/cover.jpg'` argument.
It seems UTF problem here.

**Comment by bebehei** [comment]
This is a GLib problem, but not a bug. We use it wrong: https://bugzilla.gnome.org/show_bug.cgi?id=737137

Thank you @seamus-45 for reporting this.

PR incoming.
