### ISSUE TITLE
I don't have any notification on my debian 9.2.

### ISSUE THREAD

**Issue by canel-rom1** [dunst-project/dunst#451]
### Installation info

- Version: `v1.2.0-172-g75fddab`
- Install type: `package (apt) & manuel`
- Distro and version: ` Debian 9.2`

I use dunst on my computer (debian sid) and it runs. Now I want to install it on my laptop (debian 9.2). I installed with apt (1.1.0-2+b1) but it doesn't run. After I compilated it form the source (branch: master and debian) but it's same. For the test, I use send-notify.

If I compare with my computer: I have a running process:
  $ ps -eF | grep dunst
  user    2388     1  0 145708 14944  1 10:12 ?        00:00:00 /usr/bin/dunst
I searched in the systemd if I have a service actif where but no. How systemd started it? 

I don't know how to debug my problem. I don't have log or debug's message.

Thank you for your help.
PS: Sorry for my english, i'm a french user

**Comment by bebehei** [comment]
>  I use send-notify.

You probably want to use `notify-send`?!?

> $ ps -eF | grep dunst
> user 2388 1 0 145708 14944 1 10:12 ? 00:00:00 /usr/bin/dunst

That's obviously apt's installed dunst.

You can get the log output of the current execution via `systemctl status --user dunst`.


Or install it via `make && sudo make install`.

Then **open a new shell** `killall dunst && dunst -print`.

When sending a notification via `notify-send` you can see dunst print out notifications.

Does this work?

>  PS: Sorry for my english, i'm a french user

C'est pas une problème. ;-)

**Comment by canel-rom1** [comment]
- Yes I use notify-send.

- I compiled with the branch master and after:
  $ dunst -print
  Warning: Unknown keyboard shortcut: ctrl+grave
  Name Lost. Is Another notification daemon running?

But i don't have an other notification daemon

**Comment by bebehei** [comment]
>  Name Lost. Is Another notification daemon running?

That's important. See the [FAQs](https://dunst-project.org/faq/#name-lost-is-another-notification-daemon-running)

**Comment by bebehei** [comment]
The transition from "Another daemon running" to "DBus missing completely" is crazy.

I've created a PR to catch the error and print a proper error message.
