### ISSUE TITLE
Cannot find systemd service after make install-service

### ISSUE THREAD

**Issue by febs** [dunst-project/dunst#457]
Hello. I built the code from source and did make install.
That also targets "make install-service", so this was executed:

```
mkdir -p /usr/local/share/dbus-1/services/
install -m644 org.knopwob.dunst.service /usr/local/share/dbus-1/services
install -Dm644 dunst.systemd.service /usr/local/lib/systemd/user/dunst.service
```

Nevertheless, I cannot find dunst in the services list.
`sudo systemctl list-unit-files | grep dunst`

Returns no output even after runnin ` systemctl daemon-reload`

I also tried to install those manually without the "local" prefix with no success.

Am I missing something?

Thanks!

### Installation info

- Version: 1.2.0-non-git (although I built it from the git repo)
- Install type:  manual
- Distro and version: Ubuntu 17.10

**Comment by bebehei** [comment]
> (although I built it from the git repo)

Your git folder [is missing](https://github.com/dunst-project/dunst/blob/b5a48ea13505a926a26e6587d8774c3f6b720332/Makefile#L7). Can you please verify it's there?

> /usr/local/lib/systemd/user/dunst.service

@tsipinakis 

`man systemd.unit` does not list `/usr/local`. According to the [freedesktop systemd specs](https://www.freedesktop.org/software/systemd/man/systemd.html#Directories), we should ignore the prefix and use some pkg-config foo to do determine this:

It turns out, that pkg-config prints very good results of this:

```
sh-4.4$ pkg-config systemd --variable=systemdsystemunitdir
/usr/lib/systemd/system
```

**Comment by tsipinakis** [comment]
Good catch! Thanks for the report.

> we should ignore the prefix and use some pkg-config foo to do determine this

This leaves out 2 issues:

* What do we do with existing users? Should we automatically remove the existing file?

* It's going to cause some permission errors if trying to install to a different directory, e.g. .local/share

**Comment by febs** [comment]
Hello. thanks for the super fast replies.

@bebehei  the .git directory is indeed there. 

Thanks,

**Comment by febs** [comment]
Hem, any hint about how to work around this issue? Thanks :-)

**Comment by bebehei** [comment]
Just a simple copy:
```
sudo cp /usr/{local/,}share/dbus-1/services/org.knopwob.dunst.service
sudo cp /usr/{local/,}lib/systemd/user/dunst.service
```

**Comment by febs** [comment]
Thanks for the reply.
I've actually already done that, although I wasn't aware of that cool shell trick. And it didn't work (and still doesn't). 

The files are in their place:
```
➜  dunst git:(master) ls -l /usr/share/dbus-1/services/*dunst*
-rw-r--r-- 1 root root 106 dic 14 13:26 /usr/share/dbus-1/services/org.knopwob.dunst.service
➜  dunst git:(master) ls -l /usr/lib/systemd/user/dunst.service
-rw-r--r-- 1 root root 230 dic 14 13:26 /usr/lib/systemd/user/dunst.service
```

:thinking:

**Comment by bebehei** [comment]
You have to be sure, that DBus loaded the service file properly. You have at least to restart your dbus session (read: reboot your computer).

Then if problems occur, please show me the bits, which aren't working ;-)

- `systemctl status --user dunst`
- `pidof dunst || dunst`

**Comment by bebehei** [comment]
@tsipinakis 

> - What do we do with existing users? Should we automatically remove the existing file?
> - It's going to cause some permission errors if trying to install to a different directory, e.g. .local/share

So, I found a bug in dbus' pc file. This lead me to compile dbus daemon. And: They're handling it the same like I suggested.

Yes, it fails, when running `./configure --prefix=/tmp/dbus && make && make install`.

I'd suggest to use the variables `DBUS_SESSION_SERVICE_DIR` and `SYSTEMD_USER_UNIT_DIR`, which default to the output of `pkg-config dbus-1 --variable=session_bus_services_dir` and `pkg-config systemd --variable=systemduserunitdir`.

And then install the DBus services and systemd services to these variables and not anymore to the prefix with a hardcoded string.

**Comment by bebehei** [comment]
Ah, great. That should be enough information. Either:

- Uninstall your default notification daemon (If it won't entail the desktop packages)
- Remove the dbus service file from `/usr`
    - `grep -ri org.freedesktop.notifications /usr/share/dbus-1/services` and then delete the file, which gets reported and is not dunst
- [Symlink your dunst dbus service into home, to give the priority to dunst](https://dunst-project.org/faq/#how-to-switch-back-to-notify-osd):
    - `: ${XDG_DATA_HOME:=${HOME}/.local/share}`
    - `mkdir -p "${XDG_DATA_HOME}/dbus-1/services"`
    - `ln -sfT "/usr/share/dbus-1/services/org.knopwob.dunst.service" "${XDG_DATA_HOME}/dbus-1/services/org.freedesktop.Notifications.service"`

Then create your dunstrc in `~/.config/dunst/dunstrc`. You can copy it from the default one. I 

Then kill your previous notification daemon process.

And then start dunst via `notify-send a b`. This should work. If not, dbus probably did not get it right. To resolve this, restart your session please.

**Comment by febs** [comment]
No luck :-(

Didn't uninstall anything, but I removed the entry from /usr/share/dbus-1/services as instructed (I mean, the one which was _not_ dunst, created all the links, ignorantly rebooted everything, no luck. Another dameon runs. :unamused:

**Comment by tsipinakis** [comment]
Can you build master and try again? It should print out the pid of the daemon knowing what it is might help figure out why it's starting.

**Comment by febs** [comment]
I ended up giving up cinnamon and replacing it with i3wm. Now it's working fine. It looks like there was no way to permanently kill cinnamon notification manager and replacing it with dunst... at least not to me.

Thanks for helping!

**Comment by febs** [comment]
I follow up. I am unsure about what happened here (like, installing some gnome packages by accidents and then removing them), and it looks like the problem is back.
```

➜  dunst git:(master) sudo make install-service
install -Dm644 org.knopwob.dunst.service /usr/share/dbus-1/services/org.knopwob.dunst.service
install -Dm644 dunst.systemd.service /usr/lib/systemd/user/dunst.service
➜  dunst git:(master) sudo systemctl status dunst
Unit dunst.service could not be found.
```

**Comment by bebehei** [comment]
dunst is a user service. Therefore you have to use the `--user` flag.

So, use `systemctl status --user dunst.service`. And do **not** execute the `systemctl` with `sudo` in this case.

**Comment by febs** [comment]
Thank you!

The problem though, it still doesn't run.
```

➜  dunst git:(master) systemctl status --user dunst.service
● dunst.service - Dunst notification daemon
   Loaded: loaded (/usr/local/lib/systemd/user/dunst.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-03-01 10:53:45 CET; 3s ago
     Docs: man:dunst(1)
  Process: 2710 ExecStart=/usr/local/bin/dunst (code=exited, status=1/FAILURE)
 Main PID: 2710 (code=exited, status=1/FAILURE)
mar 01 10:53:45 fabio systemd[1638]: Starting Dunst notification daemon...
mar 01 10:53:45 fabio dunst[2710]: CRITICAL: Cannot open X11 display.
mar 01 10:53:45 fabio systemd[1638]: dunst.service: Main process exited, code=exited, status=1/FAILURE
mar 01 10:53:45 fabio systemd[1638]: Failed to start Dunst notification daemon.
mar 01 10:53:45 fabio systemd[1638]: dunst.service: Unit entered failed state.
mar 01 10:53:45 fabio systemd[1638]: dunst.service: Failed with result 'exit-code'.
```

If I run the executable on its own, it just hangs forever.

**Comment by febs** [comment]
Worked around this by running

`systemctl --user import-environment DISPLAY`

before firing up dunst. Just wondering, shouldn't it get the default value for "$DISPLAY" automatically? :thinking:

**Comment by bebehei** [comment]
How do you invoke your session? Somewhere in the session invocation, the `DISPLAY` environment variable has to get set. Sadly, I don't remember, where  the necessary bits are. We had this discussion in some other thread a few months ago.

**Comment by WhyNotHugo** [comment]
You effectively need to run `systemctl --user import-environment DISPLAY` if you want to run any desktop services via systemd.

It's kind of "by design", since you can technically have multiple desktops running (or be running wayland, rather than X).

**Comment by bebehei** [comment]
@febs Is there anything left we can help you here? I'm not getting enlightened here anymore and I believe we can close this one.

**Comment by febs** [comment]
Thank you.
