### ISSUE TITLE
Dunst service not logging. Is that

### ISSUE THREAD

**Issue by febs** [dunst-project/dunst#464]
It seems like I still have some issues with the systemd service :thinking: (reference: #457) 
If I try to see the systemctl logs of dunst, I get nothing:
```
➜  ~ journalctl -u dunst
-- Logs begin at Thu 2017-12-21 11:39:55 CET, end at Fri 2017-12-22 10:18:50 CET. --
-- No entries --
```
Output of dmus-monitor while the notification gets sent: (`dbus-monitor path=/org/freedesktop/Notifications`)

```
method call time=1513935119.507909 sender=:1.153 -> destination=:1.151 serial=6 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; ```
member=GetServerInformation
method call time=1513935119.508531 sender=:1.153 -> destination=:1.151 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string ""
   string "asdf"
   string "asdf10"
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 10000
```

Version of dunst:
1.2.0-non-git (although, again, I just build it from source. Latest git commit is 
4908a75a896f3b1c0db47a8a170e53470d9d84e9

Ubuntu 17.10

I guess I am missing something big once again :thinking:
Thank you!

**Comment by bebehei** [comment]
Dunst won't log anything upon notification. (Unless there are mistakes in the notification content, then it prints warnings).

If you want to have the notifications logged on dunst's STDOUT, use the `-print` option for dunst.

Does dunst run? `systemctl status --user dunst`?

**Comment by febs** [comment]
Yup. So it's a non-issue, lol.
I was trying to understand why some notifications ignore the timeout I set for them (while they are recognized since the colors are matched). I guess dbus-monitor is the way to go? :thinking:

**Comment by maximbaz** [comment]
Just so that you know, since `dunst` is a user service, to see its logs you should pass the `--user` parameter to the `journalctl` tool: `$ journalctl --user -u dunst.service`

**Comment by febs** [comment]
Closing this, thanks
