### ISSUE TITLE
Five calls to notify-send produce six notifications on screen

### ISSUE THREAD

**Issue by dubhater** [dunst-project/dunst#467]
Hi!

Sometimes there are exactly five new messages in my inbox and Thunderbird + GNotifier addon make dunst display something like this:

![2017-12-24-130406_1280x800_scrot](https://user-images.githubusercontent.com/1739488/34326117-37061262-e8ae-11e7-87b2-7702b27119f4.png)

And when those five notifications disappear, then the fifth message appears.

The thing is, if it's okay to display five notifications at the same time, dunst should just display the five messages it received. If five notifications are too many, then it should only display four, the fourth being "(2 more)".

The above picture was generated with the command ``for i in {1..5}; do notify-send asdf "the quick brown fox jumps over the $i lazy dogs"; done``

### Installation info

- Version: 1.2.0, but also tried latest from master
- Install type: "dunst" package from Arch Linux's "community" repository, or "dunst-git" package from AUR
- Distro and version: 64 bit Arch Linux

**Comment by bebehei** [comment]
@tsipinakis The relevant codebits are here:

https://github.com/dunst-project/dunst/blob/5009d444aa4cdba4b02178c07a3675686e0626b5/src/x11/x.c#L1023-L1031

https://github.com/dunst-project/dunst/blob/5009d444aa4cdba4b02178c07a3675686e0626b5/src/x11/x.c#L538-L539

Related: #431 #301

**Comment by bebehei** [comment]
@tsipinakis Also I'd like to add: The xmore layout is always generated from the latest *displayed* message. I'd say this is rather confusing. It would be better to derive it from the first message in the waiting queue.
