### ISSUE TITLE
Dunst not clearing pixbuf if set to NULL

### ISSUE THREAD

**Issue by josswright** [dunst-project/dunst#469]
Using dunst 1.2.0 installed via Arch.

I'm using a notification daemon for mpd called mpd-notification. This displays information, via libnotify, about the current track in mpd when the song or mpd playing state changes. It also shows album art in the notification.

When I pause mpd the notification shows an older image -- I think it's the one from the first album played in that instance of mpd-notification. (When I resume playback the correct current album art is shown, but pausing always goes back to the original image.)

I reported this over at mpd-notification here: https://github.com/eworm-de/mpd-notification/issues/19#issuecomment-355519627 

The author says that there was similar incorrect behaviour in xfce4-notifyd that was fixed recently, and it resulted from the notification daemon not picking up that the notification pixbuf had been set to NULL and clearing appropriately. (More details, and link to the relevant code, in the linked bug.)

**Comment by bebehei** [comment]
This is a libnotify-bug as I have pointed it out in https://github.com/eworm-de/mpd-notification/issues/19#issuecomment-355519627

This can't get solved by dunst.
