### ISSUE TITLE
Dunst crashes if browser variable is invalid

### ISSUE THREAD

**Issue by sambazley** [dunst-project/dunst#476]
No matter what I set the `browser` variable to, Firefox is opened when I open a URL. 

I've tried `browser=xdg-open`, `browser=/usr/bin/xdg-open`, `browser=waterfox`, and `browser=/usr/bin/waterfox`. All of these are ignored.

If I uninstall Firefox, I get the error
```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 129 requests (129 known processed) with 0 events remaining.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 141 requests (141 known processed) with 0 events remaining.
```
and dunst crashes.

### Installation info

- Version: `1.3.0`
- Install type: `Package`
- Distro and version: `Arch Linux`

**Comment by Narrat** [comment]
From your description it isn't clear if you restart dunst after editing the config?

**Comment by bebehei** [comment]
@sambazley Could you please paste the `global` section of your configuration file?

**Comment by bebehei** [comment]
Oh, err. If you click on a notification with a URL and the `browser` option points to something invalid dunst crashes. WOW.

**Comment by sambazley** [comment]
Oh whoops, I missed that I had `browser` set twice, so the `browser` variable _does_ work. It does however still crash if the variable is invalid.
