### ISSUE TITLE
Refactoring x11

### ISSUE THREAD

**Issue by bebehei** [dunst-project/dunst#477]
For scheduled refactoring of the X11 code, what should we pay attention to?

- [add ability to center the notifications](https://github.com/dunst-project/dunst/pull/316)
- [transparent colors (rather than a general transparency)](https://github.com/dunst-project/dunst/issues/289)
- [transparent separator colors](https://github.com/dunst-project/dunst/issues/180)
    - (or maybe use a single window per notification!?)
- [Application name based geometry](https://github.com/dunst-project/dunst/issues/265)
---

@tsipinakis please add your thoughts here, too!

**Comment by bondzula** [comment]
Single windows per notifications would be amazing, I would love to have different notifications size's based on the width needed for that notification, and not get resized when the bigger one comes along.

**Comment by tsipinakis** [comment]
> add ability to center the notifications

I wouldn't put that in the X11 refactor that falls more into the settings redesign (#336 )

---

We should also look for:

* Separate X11 with the rest of the codebase as much as possible (_eyeing those `xctx` accesses in `notification.c`_).

* Decoupling X11 API calls from the pango/cairo drawing functions

**Comment by bebehei** [comment]
> I wouldn't put that in the X11 refactor that falls more into the settings redesign (#336 ), the implementation part of it is pretty straight-forward.

Well, however we should look forward to refactor it in a way, that we can adapt such changes later very easy.

IMHO we should actually now decide, where we want to head for with the graphics stack. This avoids double work.

**Comment by samirettali** [comment]
Implementing the transparency for the separators would be great!

**Comment by bynect** [comment]
tracking this in #1018
