### ISSUE TITLE
Ability to "include" configuration files one in each other.

### ISSUE THREAD

**Issue by febs** [dunst-project/dunst#478]
This is a feature request.

I keep swapping dunst configuration files during the day - if I am working on a critical task, I use a configuration which I call "quiet" where only a subset of **critical** notifications do appear and most of them are muted, when on ordinary activities I swap to a softer configuration which allows more notifications to pop up.

Whenever I want to change something (like, a color) I have to change two files.
It would be a neat feature IMHO if a config file could _include_ other files. This way I could have a common template for colors, and differentiate the two files only by their filters.

**Comment by bebehei** [comment]
Related #357

**Comment by bebehei** [comment]
Related #357

**Comment by knopwob** [comment]
IIRC there was the ability added to read the config file from stdin, so as a workaround you should be able to do something like 
`cat config_part_a config_part_b | dunst -conf - ` (untested).

**Comment by bebehei** [comment]
@febs I've read your bug report again. I have to say, it's much better to use the config via STDIN. It gives you ultimate flexibility.

Also I don't see the worth of such a feature, when you also could use STDIN for it. Implementing this, would require to rework our whole iniparser.

The `-` as  STDIN PR just got merged recently and is also in 1.3.0. If you don't have 1.3.0 available, you can use `-config /dev/stdin` as a fallback anyways.
