### ISSUE TITLE
Fail to find focused screen, when no active window

### ISSUE THREAD

**Issue by bebehei** [dunst-project/dunst#479]
Having multiple screens and dunst set to `follow = keyboard`, it fails to find focus, when there is no window at all. Then it displays the window on the default screen.

### Installation info

- Version: `1.2` and current master
- Distro and version: ArchLinux with i3wm

**Comment by tsipinakis** [comment]
I'd argue that this is intended behaviour from the manpage

> keyboard
> The notifications will be placed on the monitor that contains the window with keyboard focus.

If there are no windows we can't track keyboard focus since there is none.

**Comment by bebehei** [comment]
Well, technically you're right. But it bugged me for the last months. Also because i3 shows me the correct location. I've also traced the sourcecode to understand it. But I didn't get enlighted before opening this issue.

Also the fallback to `XDefaultScreen` wasn't satisfying me. As dunst displayed the notifications on the screen on the left (which is my smaller and therefore secondary screen). But my own configuration had failed there 🙈 and my smaller screen was the primary one.

I understand now the details and I have to say, the way it's handled is actually the best! This issue is invalid.
