### ISSUE TITLE
Please add .service file for DBus activation

### ISSUE THREAD

**Issue by sur5r** [dunst-project/dunst#48]
Currently, it's necessary to start `dunst` manually, e.g. in `~/.xsession`.

Putting the following snippet as `/usr/share/dbus-1/services/dunst.service` results in dunst getting launched via DBus as soon as needed.

```
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/bin/dunst
```

**Comment by blueyed** [comment]
Any ideas why this (stopped(?)) working on Arch Linux for me? (https://github.com/knopwob/dunst/issues/245)
