### ISSUE TITLE
Issue with potentially conflicting patterns for custom notifications

### ISSUE THREAD

**Issue by febs** [dunst-project/dunst#480]
I am trying to get telegram notifications only if the text contains a certain string, and to ignore them otherwise.
This is what I did:

```
#ignore
[rest_of_telegram]
    appname = *elegram*
    format  = ""

#notify
[telegram_emergencies]
    appname = *elegram*
    summary = *EMERGENZE*
    urgency = critical
    format  = "%s "%b""

```
It does not work. I get all telegram notifications.
If I comment out the "emergencies" part, then it works as expected and I don't get _any_ telegram notification.

output of `dbus-monitor path=/org/freedesktop/Notifications`:

> signal time=1515760911.861149 sender=:1.55 -> destination=:1.8 serial=3134 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
>    uint32 1216
>    uint32 1
> method call time=1515760922.284986 sender=:1.8 -> destination=:1.55 serial=2209 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
>    string "Telegram Desktop"
>    uint32 0
>    string ""
>    string "Crupo For the Lulz"
>    string "Pufolino🐔🇻🇮 🐓🇸🇨 4⃣0⃣ 🇮🇹🇨                                                                                                                       
>                   9d 78 4b ff 8d 6b 3d ff 87 69 39 ff 90 76 44 ff 95 7b 4c ff                                                                             
>                   ae 83 51 ff ae 82 51 ff ac 81 54 ff ac 83 57 ff b1 8c 60 ff
>                   db b6 6d 07
>                ]
>             }
>       )
>    ]
>    int32 -1
> signal time=1515760994.894502 sender=:1.55 -> destination=:1.8 serial=3136 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
>    uint32 1217
>    uint32 1
> 
> 

### Installation info

- Version: 1.2.0-non-git [built via git though]
- Install type:  manually
- Distro and version: Ubuntu 17.10

**Comment by tsipinakis** [comment]
I can't seem to reproduce this, can you try the following?:

Run `dunst -p` with both rules and run `dbus-monitor` in parrallel and post both outputs after
* Sending a notification from Telegram that doesn't have `EMERGENZE` in the summary
* Sending one that does

---

What I _was_ able to reproduce with this setup is that the `critical = ...` action isn't applied, will look into this.

---

> Version: 1.2.0-non-git [built via git though]

What's up with this? The `-non-git` suffix shouldn't be used unless either git isn't installed or the .git directory isn't available -.-

**Comment by febs** [comment]
Sorry for the late reply. I just pulled and built the latest master branch, commit  f7cf5b6f5bdccc0 .

dunst -v still returns `1.2.0-non-git`.

I ran dunst -print as instructet and I am monitoring the dbus.

_This time it worked as expected_.

Still, here's what I got for a notification without "EMERGENZE":


```
Warning: 'allow_markup' is deprecated, please use 'markup' instead.                           
Warning: The frame section is deprecated, width has been renamed to frame_width and moved to the global section.
Warning: The frame section is deprecated, color has been renamed to frame_color and moved to the global section.
{
        appname: 'dunst'
        summary: 'startup'
        body: 'dunst is up and running'
        icon: 'dialog-information'
        raw_icon set: false
        category: 
        timeout: 10000
        urgency: LOW
        transient: 0
        formatted: '<b>startup</b>
dunst is up and running'
        fg: #E3C7AF
        bg: #181818
        frame: #383838
        id: 2
        script: (null)
}
skipping notification: Here follows plenty of text without that word included.

```

dbus:


```
signal time=1516029060.546613 sender=org.freedesktop.DBus -> destination=:1.334 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.334"
signal time=1516029060.546633 sender=org.freedesktop.DBus -> destination=:1.334 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.334"
method call time=1516029128.749604 sender=:1.18 -> destination=org.freedesktop.Notifications serial=383 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Google Chrome"
   uint32 0
   string "file:///tmp/.com.google.Chrome.mUqcYB"
   string "Here follows plenty of text without that word included."
   string "Here follows plenty of text without that word included and some more."
   array [
      string "0"
      string "Mark as read"
      string "1"
      string "Delete"
      string "default"
      string ""
   ]
   array [
      dict entry(
         string "urgency"
         variant             uint32 1
      )
      dict entry(
         string "desktop-entry"
         variant             string "google-chrome"
      )
      dict entry(
         string "image_path"
         variant             string "/tmp/.com.google.Chrome.h6q6XD"
      )
      dict entry(
         string "image-path"
         variant             string "/tmp/.com.google.Chrome.h6q6XD"
      )
   ]
   int32 0
signal time=1516029128.750072 sender=:1.333 -> destination=:1.18 serial=5 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 0
   uint32 2
```

For a notification with EMERGENZE in the text I should wait for a message in that group to be delivered (and I can't ask people to do a test since it's a production group). I might create a test group with that string in the name and test, I'll do that ASAP.

Thanks

**Comment by febs** [comment]
Addendum - after a "make clean" I now get "1.3.0-non-git". I got 1.2.0 beforehand. Still, "non-git" is there. Thanks

**Comment by tsipinakis** [comment]
> Addendum - after a "make clean" I now get "1.3.0-non-git".

It's usually a good idea to always run `make clean` before updating dunst, the makefile can do weird things sometimes.


> For a notification with EMERGENZE in the text I should wait for a message in that group to be delivered (and I can't ask people to do a test since it's a production group).

You can test it by faking a notification using dunstify
`dunstify -a "Telegram Desktop" "EMERGENZE Notification" "Dummy notification body"`

**Comment by bebehei** [comment]
> - Version: 1.2.0-non-git [built via git though]
> - Install type:  manually
> - Distro and version: Ubuntu 17.10

This bugs me. Could you please paste the output of `git describe --tags` in your folder?

Also what will happen if you do `make clean && make "VERSION=$(git describe --tags)"`?

**Comment by febs** [comment]
Funny, "dunstify" wasn't compiled with "make" :thinking: .

`git describe --tags` returns `v1.3.0-5-gf7cf5b6`.

after `make clean && make "VERSION=$(git describe --tags)"` I finally build dunst  v1.3.0-5-gf7cf5b6 :astonished: .

"dunstify" doesn't get compiled though.

**Comment by febs** [comment]
BTW, I just pulled  d25404d590 and if I just "make" it I still get the "non-git" version.

My git repository is cloned as a submodule of a bigger project. That could be the reason of this odd behavior?

**Comment by bebehei** [comment]
> My git repository is cloned as a submodule of a bigger project. That could be the reason of this odd behavior?

WTF!? But yeah, that's the "problem".

> "dunstify" doesn't get compiled though.

You have to `make dunstify`

**Comment by febs** [comment]
Well... I can't reproduce the issue anymore. I built some more versions since the issue was opened: maybe it was solved "collaterally" by other changes in the commits.
Or maybe it was something else. If it'll happen again, I now have the instructions to provide full logs from dunst and dbus. Thanks.
