### ISSUE TITLE
Dunst config for root user

### ISSUE THREAD

**Issue by matjaz132** [dunst-project/dunst#490]
When I run dunst as root (sudo) user its not using my config in .config folder. How do I fix this?

**Comment by bebehei** [comment]
- dunst does not create a configuration file by itself. It usually is located in `~/.config/dunst/dunstrc` and has to get placed manually there.
- You may want to take the [current dunstc from the repo](https://github.com/dunst-project/dunst/blob/master/dunstrc).
- Are you sure, you really want to run dunst as the `root` user? If yes, are you sure, dunst is running as the root user?
