### ISSUE TITLE
show_age_threshold does not handle suspend/resume

### ISSUE THREAD

**Issue by blueyed** [dunst-project/dunst#492]
When using `show_age_threshold` the time delta seems to not include time where the computer was suspended.

Relevant code:
https://github.com/dunst-project/dunst/blob/8735c9d3d00faad206eb66d9aa93f7b77787f993/src/notification.c#L514-L515

From `GLib:Date_and_Time_Functions(3)`:
```
   g_get_monotonic_time ()
           gint64              g_get_monotonic_time                (void);

       Queries the system monotonic time, if available.

       On POSIX systems with clock_gettime() and CLOCK_MONOTONIC this call is a very
       shallow wrapper for that. Otherwise, we make a best effort that probably involves
       returning the wall clock time (with at least microsecond accuracy, subject to the
       limitations of the OS kernel).

       It's important to note that POSIX CLOCK_MONOTONIC does not count time spent while
       the machine is suspended.
```

Side note: it would also be good to skip calculating `t_delta` altogether if `show_age_threshold` is not used.

- Version: 1.3.1 (2018-01-30)
- Distro and version: Arch Linux

**Comment by bebehei** [comment]
Well, we traded wall clock time for monotonic time. Either we're affected by DSTs and ill timed hardware clocks or we're not respecting suspends.

Quoting from [the related POSIX docs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_getres.html).
> If the Monotonic Clock option is supported, all implementations shall support a clock_id of CLOCK_MONOTONIC defined in <time.h>. This clock represents the monotonic clock for the system. For this clock, the value returned by clock_gettime() represents the amount of time (in seconds and nanoseconds) since an unspecified point in the past (for example, system start-up time, or the Epoch). This point does not change after system start-up time. The value of the CLOCK_MONOTONIC clock cannot be set via clock_settime(). This function shall fail if it is invoked with a clock_id argument of CLOCK_MONOTONIC.

Linux is the bad candidate here.

@blueyed What's your desired solution actually?

**Comment by blueyed** [comment]
@bebehei 
Thanks for looking into this.
I cannot really suggest something to be done here then - just noticed this (and it's not a big thing after all, but confusing enough for me to look at the code.. ;))

**Comment by tsipinakis** [comment]
I'd say it's a good idea to use `time()` for all user visible strings to prevent problems like this. The easiest solution would be to just store a second timestamp.

**Comment by bebehei** [comment]
What would make wall clock time better?

**Comment by tsipinakis** [comment]
Whoops totally ignored this issue for a few days, sorry!

---

> Side note: it would also be good to skip calculating t_delta altogether if show_age_threshold is not used.

It's a tiny microopt but ideally a compiler should take that out during optimization anyway.

---

I was thinking of storing clock time and displaying it on the notification age in order to show the real age of the notification. The clear disadvantage is that after the computer wakes up from suspend even though the age would show > age limit it still wouldn't time out until the next wakeup.

**Comment by tsipinakis** [comment]
Looking at the actual manpage of `clock_getres` the proper solution to this would be to use `CLOCK_BOOTTIME` which isn't affected by suspends but I'm not sure about the amount of work required to change that.

**Comment by bebehei** [comment]
Just to note down the thoughts from this evening's IRC chat:

It might be best to create a self-written drop-in replacement, which respects `CLOCK_BOOTTIME` on Linux and `CLOCK_MONOTONIC` on others POSIX.

There had been a previous thread in the GLib Bugtracker about solely the docs and the issue that the Linux monotonic clock actually does *not* match POSIX's monotonic. [Their reason](https://bugzilla.gnome.org/show_bug.cgi?id=709466#c3) to stick to `MONOTONIC` and not switch to `BOOTTIME` was the behavior of `poll()`.
