### ISSUE TITLE
dunst disables @ mark key on Japanese keyboard

### ISSUE THREAD

**Issue by danchenka** [dunst-project/dunst#493]
After any notification appears in dunst, the "@" key stops working. (Japanese keyboards have a dedicated key for the "@" mark, rather than using "shift+2", so I'm not sure if this affects other keyboard layouts.)

Once the key goes dead "Super+@" makes the "@" mark for most applications, but not for firefox, possibly others as well.

This doesn't occur with xfce4-notifyd
`killall dunst` returns the key to its proper function.
I was able to reproduce this with fresh Debian installs on two different Lenovo thinkpads with Japanese keyboard layouts (X61 and X200s), but I don't have an external keyboard to try it with.

Output of xev is as follows.

### Before dunst notification:
`KeyPress event, serial 33, synthetic NO, window 0xe00001,
    root 0xb4, subw 0x0, time 7324812, (-1,702), root:(963,706),
    state 0x0, keycode 34 (keysym 0x40, at), same_screen YES,
    XLookupString gives 1 bytes: (40) "@"
    XmbLookupString gives 1 bytes: (40) "@"
    XFilterEvent returns: False`

`KeyRelease event, serial 33, synthetic NO, window 0xe00001,
    root 0xb4, subw 0x0, time 7324884, (-1,702), root:(963,706),
    state 0x0, keycode 34 (keysym 0x40, at), same_screen YES,
    XLookupString gives 1 bytes: (40) "@"
    XFilterEvent returns: False`

### After dunst notification:
`FocusOut event, serial 33, synthetic NO, window 0xe00001,
    mode NotifyGrab, detail NotifyAncestor`

`FocusOut event, serial 33, synthetic NO, window 0xe00001,
    mode NotifyUngrab, detail NotifyPointer`

`FocusIn event, serial 33, synthetic NO, window 0xe00001,
    mode NotifyUngrab, detail NotifyAncestor`

`KeymapNotify event, serial 33, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   `

### Output of `dbus-monitor path=/org/freedesktop/Notifications` in which notification disables "@" key

`method call time=1519722170.400258 sender=:1.255 -> destination=:1.256 serial=6 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
method call time=1519722170.401160 sender=:1.255 -> destination=:1.256 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string ""
   string "dunst bug test"
   string ""
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
signal time=1519722174.396577 sender=:1.256 -> destination=:1.255 serial=5 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 2
   uint32 1`

 

### Installation info

- Version: 1.1.0 (also tried on 1.3.0)
- Install type: `apt-get install dunst`
- Distro and version: Debian Stretch

**Comment by bebehei** [comment]
Dunst is grabbing a few shortcuts to make some actions (close all notifications, close most recent one, pop one from history)

@danchenka What are your shortcut settings in `dunstrc`?

**Comment by danchenka** [comment]
I believe they are still the default settings. I don't think I have ever edited them.

`

    # Shortcuts are specified as [modifier+][modifier+]...key
    # Available modifiers are "ctrl", "mod1" (the alt-key), "mod2",
    # "mod3" and "mod4" (windows-key).
    # Xev might be helpful to find names for keys.

    # Close notification.
    close = ctrl+space

    # Close all notifications.
    close_all = ctrl+shift+space

    # Redisplay last message(s).
    # On the US keyboard layout "grave" is normally above TAB and left
    # of "1".
    history = history = ctrl+grave

    # Context menu.
    context = ctrl+shift+period

`

**Comment by bebehei** [comment]
What happens, when you display a notification and you press the `@` key?

**Comment by danchenka** [comment]
The key stops working immediately, before the notification closes.

**Comment by bebehei** [comment]
I ack, this. Dunst is grabbing the keys, it's configured to do so. It [looks like the `@` key is located on the same key of <code>`</code> (grave)](https://www.win.tue.nl/~aeb/linux/kbd/scancodes-8.html).

According to your configuration, you posted, the `history` keybinding is mapped to `ctrl+grave`. So just move the history keybinding to another key.

PS: You defined `history = history = ctrl+grave`, which is invalid, so dunst will use the default (which is `ctrl+grave`).

> Version: 1.1.0 (also tried on 1.3.0)

PS2: You might want to use `1.3.1`, which fixes a nasty race condition bug during installation.

**Comment by danchenka** [comment]
Thank you very much. 

Since I don't use this shortcut at the moment, I just commented it out, and made a note of the issue so I won't forget it in the event that I ever decide to use it in the future. It now works perfectly.

I'm glad it was such an easy fix. 

PS: Oops. That was just sloppy copying and  pasting after I got distracted while posting.
