### ISSUE TITLE
Display notifications in a stacked manner

### ISSUE THREAD

**Issue by vsr625** [dunst-project/dunst#494]
For some very particular reason, I want the notifications to be displayed in a stacked fashion, that is if there is a notification, and again if a new notification is sent, the new notification should replace/take the place of the old notification in the same place. 
For this, I had set the height in the geometry parameter to 1, set hide_duplicate_count = true and indicate_hidden = no. 
But now, if there is a notification and if a new notification is sent, it isn't displayed until the old notification gets the timeout or dismissed. Is there anyway, such that the stacked behavior is possible.

### Installation info

- Version: `1.3.0`
- Install type: `AUR`
- Distro and version: `Manjaro`

**Comment by bebehei** [comment]
Have you set the `stack_duplicates` setting in dunstrc to `true`?

**Comment by tsipinakis** [comment]
@vsr625 Did you find a solution to your issue? If so it might be worth posting here for others that have the same question.

**Comment by vsr625** [comment]
For my purpose, replacing the existing notification with a new one was suffice, so I followed this answer.
[link](https://askubuntu.com/a/161852).

**Comment by opmorgan** [comment]
the dunstify client, available on aur, also allows you to replace notifications by ID.

**Comment by bebehei** [comment]
Just recently, we introduced a `stack_tag` to dunst. On Arch you have to install `dunst-git`. For further informations then, please consult [my comment in the other thread](https://github.com/dunst-project/dunst/issues/321#issuecomment-437693443).

**Comment by vsr625** [comment]
@bebehei Thank you for looking into this, much appreciated.
