### ISSUE TITLE
Request - Manage multiple X session

### ISSUE THREAD

**Issue by tigerjack** [dunst-project/dunst#495]
I'm trying to get dunst working across multiple X sessions. The problem at the moment is that all the notifications are only displayed in the first session on which I run dbus.
Is it possible to have notifications shown inside the current X session in an effective way? At the moment, if I try to run another instance of dunst, it obviously says

    >dunst
    Cannot acquire 'org.freedesktop.Notifications': Name is acquired by PID 'xxxx'

**Comment by bebehei** [comment]
@tigerjack The notification server is bound to the dbus session and not to the X11 Session. If all notifications from the second session are displayed in the first one, either the second session is not invocated properly or there is something going wrong by accident with your DBus clients (e.g. `DBUS_SESSION_BUS_ADDRESS` pointing to the dbus socket from the first session and not the second).

**Comment by bebehei** [comment]
Googling the net for multiple dbus sessions yielded no pitfalls for me. So, how do you invoke your second X session?

**Comment by tigerjack** [comment]
Hey @bebehei, thanks for your fast response.
I've tried to look at the ``DBUS_SESSION_BUS_ADDRESS`` and in both X sessions it returns
``unix:path=/run/user/1000/bus``. Don't know if it could be the case, but the multiple X sessions are for the same user; could it be the problem?

Regarding the second X session, I first switch to a second virtual terminal with `Ctrl`+`Alt`+`F2`, login as my user and then invoke `startx`, which reload my `.xinitrc` again.

**Comment by bebehei** [comment]
Ok, even I never used multiple sessions before. But I found now the right keywords to google it. And it seems to be easy with startx: You've got to invoke your session via DBus. [See this SO answer](https://askubuntu.com/a/368193). On my system, I can reproduce your issue and I'm able to fix it with this.

I'm not sure, if this is the best way to fix it, but at least it works :tm: .

**Comment by tigerjack** [comment]
@bebehei never do I, I'm just exploring the feasibility of managing multiple x sessions. Btw, your solution lworks perfectly! Thanks for the help, really appreciated.

**Comment by bebehei** [comment]
Glad, I have helped you. If you've got other questions, feel free to ask.
