### ISSUE TITLE
Print version stopped working (-v -version and --version all don't work)

### ISSUE THREAD

**Issue by khamshuayb** [dunst-project/dunst#500]
version: well this is the bug I want to report;)
dunst -v: 
Dunst - A customizable and lightweight notification-daemon

This bug must be introduced in some commit within the last month

git describe --tags:
v1.3.0-53-g4c5c124

**Comment by bebehei** [comment]
@khamshuayb This got merged yesterday. I'm astonished how fast dunst users report this. Thanks for reporting.

The bad commit is 678ea70c88a17162eea3268b37880b85f1d00f7b
