### ISSUE TITLE
Sleep Notifications

### ISSUE THREAD

**Issue by wpovell** [dunst-project/dunst#505]
Is there an easy was to temporarily supress notifications? I would kill dunst, but then many applications (mainly firefox, chrome) default to using their own notifiers. My only thought was to supress all notifications but have a script that selectively resends them if not supressed. Seems hacky though...

### Installation info

- Version:  v1.2.0-213-g65043c0
- Install type: pacman 
- Distro and version: `Linux 4.15.11-1-ARCH`

**Comment by bebehei** [comment]
There's an available hack:

Send a notification with its summary `DUNST_COMMAND_PAUSE` or `DUNST_COMMAND_RESUME`. It's nowhere documented and we clearly don't support it, but it works:tm:. The notifications sent between pause and resume will get delayed but won't get lost.

We're planning to replace it with a proper command line client (see #445). Expect it to get dropped at some point. (But we won't drop it when there is no replacement).

---

> Version: v1.2.0-213-g65043c0

You probably want to rebuild dunst. Just recently, we merged fullscreen detection support. So you can delay/block specific/all notifications via rules when you're in fullscreen.

https://github.com/dunst-project/dunst/blob/aa5ccd7dd75e7c563a2b57e964ab80bbbe73365e/dunstrc#L297-L308

**Comment by wpovell** [comment]
Thanks!

**Comment by bebehei** [comment]
No, that's exactly the problem :joy:

Dunst is in need of a proper command line client, which can handle such a thing.

**Comment by vzaliva** [comment]
`notify-send DUNST_COMMAND_PAUSE` did it for me. Thanks!

**Comment by fwSmit** [comment]
This can now be done with `dunstctl set-paused true` as well. This issue can be closed.
