### ISSUE TITLE
whatsapp notifications are not appearing

### ISSUE THREAD

**Issue by yuceltoluyag** [dunst-project/dunst#506]
Hello, other apps notifications are working fine but WhatsApp notifications can not be displayed

pacman repo installed -> dunst
-v Dunst - A customizable and lightweight notification-daemon 1.3.1 (2018-01-30)
Archlinux 4.14.28-1-lts
DW -> i3 version 4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors

**Comment by tsipinakis** [comment]
Hi,

can you please run the following as a whatsapp notification comes through and post the output?
* Run dunst with the print parameter `dunst -print`
* Run `dbus-monitor`

**Comment by tsipinakis** [comment]
Ping @yuceltoluyag any updates for this?

**Comment by yuceltoluyag** [comment]
I have problems with my settings Sorry :(
