### ISSUE TITLE
Some notifications are not saved in history

### ISSUE THREAD

**Issue by Sweenu** [dunst-project/dunst#508]
For some reason, my notifications coming from kdeconnect don't get saved in history even though I have no special rule set.

Any idea where this behavior could come from and how I could solve that?

### Installation info

- Version: `1.3.0-5-gf7cf5b6`
- Install type: `pacman`
- Distro and version: `4.15.14-1-ARCH`

**Comment by tsipinakis** [comment]
That's probably from #343, there's an internal rule that notifications marked as `transient` by the client are not saved in history. This is a bit confusing as I've mentioned [before](https://github.com/dunst-project/dunst/issues/310#issuecomment-358126293). I've now removed that rule from master.

Sorry for the confusion.

For anyone running the latest release you can add the following in your dunstrc to get around this:

```
[keep-transient]
match_transient = true
history_ignore = false
```

**Comment by Sweenu** [comment]
Thank you! That did it for me.
