### ISSUE TITLE
SVG in notifications results in a double free or corruption

### ISSUE THREAD

**Issue by LightDiscord** [dunst-project/dunst#512]
When I display a notification with a PNG it works but when it is a SVG no notification is displayed. 
In journalctl I have an error:
```
Apr 30 13:52:22 nixos org.freedesktop.Notifications[1132]: double free or corruption (out)
```

### While the notification gets sent:
```
signal time=1525089139.442770 sender=org.freedesktop.DBus -> destination=:1.789 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.789"
signal time=1525089139.442782 sender=org.freedesktop.DBus -> destination=:1.789 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.789"
method call time=1525089140.924184 sender=:1.790 -> destination=:1.788 serial=6 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
method call time=1525089140.924710 sender=:1.790 -> destination=:1.788 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string "/home/arnaud/Documents/papirus-icons/Papirus/64x64/apps/spotify-client.png"
   string "Hello world!"
   string "this is"
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
method call time=1525089142.006995 sender=:1.791 -> destination=:1.788 serial=6 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
method call time=1525089142.007305 sender=:1.791 -> destination=:1.788 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string "/home/arnaud/Documents/papirus-icons/spotify-client.svg"
   string "Hello world!"
   string "this is"
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
```

### Installation info

- Version: 1.3.1
- Install type: [NixOS dunst derivation](https://github.com/NixOS/nixpkgs/blob/7e7477295e1629093a1f23ade37ad0ac91eecf36/pkgs/applications/misc/dunst/default.nix)
- Distro and version: NixOS (18.09pre137749.b5fd3a0bc70 (Jellyfish))

**Comment by bebehei** [comment]
Just recently, I introduced unit tests in the icon loading methods and found [the corresponding bug](https://github.com/dunst-project/dunst/pull/496/commits/2531193a95f8a185dfb3952b5b08b965aabb662d). In parallel somewhere in the gdk libraries the svg loading broke (?!) or it maybe got more strict. Therefore, gdk fails and dunst crashes.

As the fix is already in #496, I don't consider branching creating a special hotfix.

**Comment by bebehei** [comment]
> As the fix is already in #496, I don't consider branching creating a special hotfix.

Oh wait. Stupid thinking of myself. :see_no_evil: 

@tsipinakis We actually should create a hotfix and release `1.3.2` to make it available in downstream distros.

**Comment by bebehei** [comment]
>    string "/home/arnaud/Documents/papirus-icons/spotify-client.svg"

@LightDiscord Out of curiosity, could you please provide this file?

**Comment by LightDiscord** [comment]
Here is my [local](https://transfer.sh/F43Bn/spotify-client.svg) version.
But you can also have it [here](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/spotify-client.svg)

**Comment by tsipinakis** [comment]
I cannot seem to reproduce this with the provided icon. @LightDiscord What version of gdk_pixbuf are you using?

**Comment by LightDiscord** [comment]
According to [this file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gdk-pixbuf/default.nix), i'm using gdk_pixbuf at version 2.36.7

**Comment by tsipinakis** [comment]
> I think we should fix dunst first.

The fix is already in `refactor-drawing` and will land in master (hopefully soon) I'm still thinking it over if it's worth doing another patch release for this one.

In any case, I also expect this to be a bug somewhere in gdk but it's worth looking into IMO (at least finding out the error message it gives out when it fails)

**Comment by tsipinakis** [comment]
Check the logs, there should be an error message on why it failed to load.

**Comment by LightDiscord** [comment]
So much logs in [logs.txt](https://github.com/dunst-project/dunst/files/1968580/logs.txt)

I send a notification with the png then with the svg

**Comment by tsipinakis** [comment]
So many logs when not a single one from the debug output :frowning: 

> access("/home/arnaud/Documents/papirus-icons/spotify-client.svg", R_OK) = 0
> openat(AT_FDCWD, "/home/arnaud/Documents/papirus-icons/spotify-client.svg", O_RDONLY) = 8

That theory is out at least. If you run dunst the same way without the redirects and strace (`./dunst`) is there really no output after sending a notification? (assuming you did `make clean && make debug`)

**Comment by LightDiscord** [comment]
My bad, I forgot the "debug".

```
DEBUG: RUN
DEBUG: XEvent: processing '16'
DEBUG: XEvent: processing '65'
DEBUG: XEvent: Ignored '65'
DEBUG: RUN
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '19'
DEBUG: XEvent: Ignored '19'
DEBUG: XEvent: processing '19'
DEBUG: XEvent: Ignored '19'
DEBUG: XEvent: processing '15'
DEBUG: XEvent: Ignored '15'
DEBUG: XEvent: processing '12'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '12'
DEBUG: XEvent: processing '65'
DEBUG: XEvent: Ignored '65'
DEBUG: XEvent: processing '65'
DEBUG: XEvent: Ignored '65'
DEBUG: XEvent: processing '65'
DEBUG: XEvent: Ignored '65'
DEBUG: RUN
MESSAGE: Couldn't recognize the image file format for file '/home/arnaud/Documents/papirus-icons/spotify-client.svg'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '22'
DEBUG: XEvent: Ignored '22'
DEBUG: XEvent: processing '12'
MESSAGE: Couldn't recognize the image file format for file '/home/arnaud/Documents/papirus-icons/spotify-client.svg'
DEBUG: XEvent: processing '65'
DEBUG: XEvent: Ignored '65'
DEBUG: XEvent: processing '65'
DEBUG: XEvent: Ignored '65'
```

**Comment by tsipinakis** [comment]
I've never used nix before so I have no clue how it works but digging around in their repo looks like `gdk-pixbuf 2.36.12` is available in the staging branch. If it's not much of a bother can you install that and test again to check if it's a library version issue?

---
@bebehei 
> Yes, I also think we should do a patch release

Given that we're in the middle of a big refactor that will probably take a bit before we're ready for another release I'd say I agree. I'll prepare a bugfix release this weekend.

**Comment by LightDiscord** [comment]
> I've never used nix before so I have no clue how it works but digging around in their repo looks like gdk-pixbuf 2.36.12 is available in the staging branch. If it's not much of a bother can you install that (recompile dunst just in case) and test again to check if it's a library version issue?

Doesn't seem to be working either with `gdk-pixbuf 2.36.12`.

**Comment by bebehei** [comment]
> Doesn't seem to be working either with gdk-pixbuf 2.36.12.

I don't want to be the smart ass here, but for me this smelled even before like a subdependency problem and, that it's not gdk-pixbuf2 alone.

The weirdest thing actually: `librsvg` requires `gdk-pixbuf2` (and not the other way around) WTF!?.

@LightDiscord Does [`gdk-pixbuf-query-loaders --update-cache && killall dunst`](https://wiki.gnome.org/Projects/Jhbuild/Issues/gtk%2B) help you and show icons again?

**Comment by LightDiscord** [comment]
Weird, there are no svg related lines when running the command `gdk-pixbuf-query-loaders`

**Comment by LightDiscord** [comment]
Solved!

I export the `GDK_PIXBUF_MODULE_FILE` variable to the loaders.cache generated by librsvg and then run dunst.

**Comment by tsipinakis** [comment]
It might be worth reporting this to nix as well. I doubt you'll be the first one to run into this.
