### ISSUE TITLE
How to change the time length of notifcation?

### ISSUE THREAD

**Issue by divrse** [dunst-project/dunst#513]
When using dunst with i3-gaps, notifications stay on the screen a bit longer than I would like, is there an option in the config file where I can change this? thank you.

**Comment by bebehei** [comment]
`notify-send -t <milliseconds>` or look into the `timeout` parameter of the rules.

For an example dunstrc, see https://github.com/dunst-project/dunst/blob/master/dunstrc

**Comment by divrse** [comment]
@bebehei Thank you appears to work when I change the timeout for low and normal urgency.
