### ISSUE TITLE
Empty format

### ISSUE THREAD

**Issue by jadiah** [dunst-project/dunst#516]
I want to use dunst to show only icons (images), if i leave "format" empy, dunst will skip notifications. I can write to format something like `<b></b>`, but it will add some extra empty pixels to notification.
Make possible to show empty notifications (only with icons).

**Comment by bebehei** [comment]
> but it will add some extra empty pixels to notification.

Do you mean the blank space on the right side of the icon? [0]

![screenshot from 2018-06-11 00-25-20](https://user-images.githubusercontent.com/2073458/41207001-f31de180-6d0d-11e8-99a9-e660188d6f6a.png)

> Make possible to show empty notifications (only with icons).

So you mean, `dunst` should go on and only display icons? Sorry, but I suspect you actually want to misuse dunst for something not notificationish. Could you please clarify your goal?

---

[0] My config: width 300 and shrink no.

**Comment by tsipinakis** [comment]
@jadiah Ping, did this response solve your issue?

**Comment by fwSmit** [comment]
This issue can be closed.
