### ISSUE TITLE
Path in configs to resolve ( ~ )

### ISSUE THREAD

**Issue by freed00m** [dunst-project/dunst#520]
Hi

As I have no idea how the notifiication determines what icon to use, so I would like to managed them in my own folder that sits in my home dir. To make my config universal, the expansion of tilde `~` would be awesome as I would not have to change the config per user. 

Resolving a $HOME variable would also be acceptable.
 
I would like to have  this feature, right now I have to set full path.

- Version: `1.3.2 (2018-05-06)`
- Install type: `package`
- Distro and version: ` 4.17.0-2-MANJARO latest stable `

**Comment by bebehei** [comment]
So, the PR works successfully and also contains tests. 

@freed00m If you want to have a try, you can check it out via:

```
git clone https://github.com/bebehei/dunst
cd dunst
git checkout paths-for-icons
make all test
killall dunst && ./dunst
```

**Comment by freed00m** [comment]
@bebehei I tested it, I works like charms :1st_place_medal: 

All unit tests passed and the tilda is resolved in paths..
