### ISSUE TITLE
dunst 1.3.2 does not display svg

### ISSUE THREAD

**Issue by alezost** [dunst-project/dunst#526]
Hello, 
- I have tried the following svg file: https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/images/icons/hicolor/scalable/apps/emacs.svg

- I use the default dunstrc config, except I set `icon_position = left`

- I use the following command to display icon:

```
notify-send icon -i /tmp/emacs.svg
```

Now, when I run dunst 1.2.0, it displays the svg as expected.  But when I run dunst 1.3.2, it gives the following ouput:

```
Could not load icon: '/tmp/emacs.svg'
Could not load icon: '/tmp/emacs.svg'
Could not load icon: '/tmp/emacs.svg'
```

(this line repeats 3 times)

Does dunst still support svg?

**Comment by tsipinakis** [comment]
We definitely still support svg. I cannot reproduce this on my end.

Can you build from source and try again? This will both tell us if this has been fixed since then somehow and give some more information since we added more detailed error logging for icons.

**Comment by bebehei** [comment]
Have you used the HTML file as an SVG? This is the only way, I can reproduce your error.

```
wget https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/images/icons/hicolor/scalable/apps/emacs.svg
notify-send -i ./emacs.svg a b
```

No Icon and `Could not load icon: './emacs.svg'` as the error message.

**Comment by alezost** [comment]
Maybe the problem is that dunst searches for some libraries in "standard" locations?  I use an unusual distribution ([GuixSD](https://www.gnu.org/software/guix)) and it does not have such standard locations (like `/usr` or `/lib`) at all.

**Comment by bebehei** [comment]
Please verify that your SVG file is valid.

**Comment by tsipinakis** [comment]
I'm also suspecting a gdk-pixbuf loader issue again (see #512), can you post the output of `gdk-pixbuf-query-loaders` and verify that svg is in there?

**Comment by alezost** [comment]
@bebehei, my svg file is valid because when I use dunst 1.2.0 on it, the icon is displayed.

@tsipinakis, here is the output:

```
# GdkPixbuf Image Loader Modules file
# Automatically generated file, do not edit
# Created by gdk-pixbuf-query-loaders from gdk-pixbuf-2.36.12
#
# LoaderDir = /gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders
#
"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so"
"ani" 4 "gdk-pixbuf" "Windows animated cursor" "LGPL"
"application/x-navi-animation" ""
"ani" ""
"RIFF    ACON" "    xxxx    " 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so"
"bmp" 5 "gdk-pixbuf" "BMP" "LGPL"
"image/bmp" "image/x-bmp" "image/x-MS-bmp" ""
"bmp" ""
"BM" "" 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so"
"gif" 4 "gdk-pixbuf" "GIF" "LGPL"
"image/gif" ""
"gif" ""
"GIF8" "" 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.so"
"icns" 4 "gdk-pixbuf" "MacOS X icon" "GPL"
"image/x-icns" ""
"icns" ""
"icns" "" 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.so"
"ico" 5 "gdk-pixbuf" "Windows icon" "LGPL"
"image/x-icon" "image/x-ico" "image/x-win-bitmap" "image/vnd.microsoft.icon" "application/ico" "image/ico" "image/icon" "text/ico" ""
"ico" "cur" ""
"  \001   " "zz znz" 100
"  \002   " "zz znz" 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so"
"jpeg" 5 "gdk-pixbuf" "JPEG" "LGPL"
"image/jpeg" ""
"jpeg" "jpe" "jpg" ""
"\377\330" "" 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so"
"png" 5 "gdk-pixbuf" "PNG" "LGPL"
"image/png" ""
"png" ""
"\211PNG\r\n\032\n" "" 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.so"
"pnm" 4 "gdk-pixbuf" "PNM/PBM/PGM/PPM" "LGPL"
"image/x-portable-anymap" "image/x-portable-bitmap" "image/x-portable-graymap" "image/x-portable-pixmap" ""
"pnm" "pbm" "pgm" "ppm" ""
"P1" "" 100
"P2" "" 100
"P3" "" 100
"P4" "" 100
"P5" "" 100
"P6" "" 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.so"
"qtif" 4 "gdk-pixbuf" "QuickTime" "LGPL"
"image/x-quicktime" "image/qtif" ""
"qtif" "qif" ""
"abcdidsc" "xxxx    " 100
"abcdidat" "xxxx    " 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.so"
"tga" 4 "gdk-pixbuf" "Targa" "LGPL"
"image/x-tga" ""
"tga" "targa" ""
" \001\001" "x  " 100
" \001\t" "x  " 100
"  \002" "xz " 99
"  \003" "xz " 100
"  \n" "xz " 100
"  \v" "xz " 100

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.so"
"tiff" 5 "gdk-pixbuf" "TIFF" "LGPL"
"image/tiff" ""
"tiff" "tif" ""
"MM *" "  z " 100
"II* " "   z" 100
"II* \020   CR\002 " "   z zzz   z" 0

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.so"
"xbm" 4 "gdk-pixbuf" "XBM" "LGPL"
"image/x-xbitmap" ""
"xbm" ""
"#define " "" 100
"/*" "" 50

"/gnu/store/8dyxffqhcq9qyhc9d850bc8kz7c0hr7i-gdk-pixbuf+svg-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so"
"xpm" 4 "gdk-pixbuf" "XPM" "LGPL"
"image/x-xpixmap" ""
"xpm" ""
"/* XPM */" "" 100
```

I guess it means that my gdk-pixbuf does not support svg, right?

**Comment by alezost** [comment]
Now I am pretty sure it is a Guix problem, so I am closing this.
Thank you very much for your support!

**Comment by tsipinakis** [comment]
No problem, please report back when you've solved this for [other people finding this](https://xkcd.com/979/). :)

**Comment by alezost** [comment]
The problem was that dunst in guix was built with gdk-pixbuf that did not have svg support.  I am going to report here when this issue will be fixed on the guix side.

Thanks again for the help!

**Comment by alezost** [comment]
This is fixed in Guix now:
http://git.savannah.gnu.org/cgit/guix.git/commit/?id=e311ef4f87f7ad8db2114e5f89961eea0240893b

**Comment by WammKD** [comment]
It seems obvious to me, now, but this helped me realize why SVGs weren't working for `rofi`, @alezost. `librsvg` was using `gdk-pixbuf`, rather than `gdk-pixbuf+svg`, so this might net us SVGs working wherever `librsvg`'s been used.

**Comment by an4s911** [comment]
> This is fixed in Guix now: http://git.savannah.gnu.org/cgit/guix.git/commit/?id=e311ef4f87f7ad8db2114e5f89961eea0240893b

Please mention how to solve it though.
