### ISSUE TITLE
Sound hint

### ISSUE THREAD

**Issue by kajzersoze** [dunst-project/dunst#529]
Any chance for implementing sound hint ?

For example 
`notify-send "Sound test" --hint=string:sound-file:/path/to/sound.wav`

this works in most notification daemons.

**Comment by gregf** [comment]
I have the following in my dunstrc

dunstrc
```
[play_sound]
summary = "*"
script = ~/bin/alert.sh
```

alert.sh
```
#!/bin/sh
splay /home/gregf/.sounds/beep.mp3
```

As a quick solution.

**Comment by kajzersoze** [comment]
Little tedious but works, thanks!

**Comment by bebehei** [comment]
Well, there is the [`sound-file` hint in the notification spec](https://developer.gnome.org/notification-spec/#hints).

But I think I can speak for us both: We don't want to implement it and neither maintain it.

**Comment by kajzersoze** [comment]
The whole thing is maybe 10 lines of code, max.

Was thinking of making a PR but if there's no interest for it I'm not gonna bother.

**Comment by tsipinakis** [comment]
I'd gladly accept a PR if you want to implement it.

**Comment by kajzersoze** [comment]
I'll try, might take a few days to see how dunst functions.
But basically, it just needs canberra-gtk.h and [ca_gtk_play_for_widget](https://developer.gnome.org/libcanberra/unstable/libcanberra-canberra-gtk.html) function from it. 
Grab filename from the sound-file hint and pass it to that function to play it.

**Comment by tsipinakis** [comment]
I'd propose we just use the infrastructure available with the scripts and let the user provide a command to run, e.g. `sound_cmd = mpv`.

Everyone has at least some one audio player installed and I'd rather avoid adding any more dependencies.

**Comment by kajzersoze** [comment]
Sure, that works just fine, I just didn't know about it, installed dunst yesterday for the first time, must say I like it, the only thing that was confusing was that sound hint thing, not confusing but missing actually. 

Using scripts is fine, that's why I closed this issue once I found out about it.

Playing sound from the code without adding more dependencies is not doable, I think.

**Comment by kajzersoze** [comment]
I'm using `aplay,` part of `alsa-utils`.

IMHO, the best solution would be to take the hint and play it with command specified in `dunstrc`, option to turn sound on or off would also be there.

**Comment by tsipinakis** [comment]
> IMHO, the best solution would be to take the hint and play it with command specified in dunstrc, option to turn sound on or off would also be there.

Sorry if I wasn't clear, that's exactly what I was suggesting :p

**Comment by kajzersoze** [comment]
You was clear, dunno why I said it like that :)

Guess I wanted to say that I would be happy to see that implemented that way :D
