### ISSUE TITLE
Add option to enable a gap between the icon and the notification text

### ISSUE THREAD

**Issue by hamidsafdari** [dunst-project/dunst#543]
The current implementation doesn't seem to have an option to specify some gap between the icon and the notification text. I can set a vertical/horizontal padding but all they do is create space for the overall notification. I don't want any padding around the icon but only between the text and the icon. It would also be nice if the same padding would be applied when there is no icon found.

### Installation info

- Version: `1.3.2`
- Install type: `package manager`
- Distro and version: `Archlinux 4.18.5-arch-1 `

**Comment by blueForestIcarus** [comment]
I'd also like to have this feature

**Comment by fwSmit** [comment]
Closed via #810
