### ISSUE TITLE
Howto

### ISSUE THREAD

**Issue by PhilHudson** [dunst-project/dunst#557]
Your README gives no examples of how to use dunst. You might think that's an absurd thing to say, but... go and have a look. Imagine you're a complete newbie, only barely aware that there are such things as daemons. How do you interact with dunst? 

By trying it I've found that, as I suspected, my scripts' calls to `notify-send` would now use dunst, but... you don't actually explicitly say that anywhere! And I'm someone with something more than a clue about daemons and message buses and high-level IPC/IAC. You also don't address system-wide/per-user service setup, nohup, etc. Your doco is mystifying to anyone who doesn't know as much as you.

Anyway, it looks like dunst will give me what I need, which is `-title` (so I can use `xdotool` to identify unique notifications easily), so thank you very much.

**Comment by bebehei** [comment]
Oh yeah, we could improve heavily. But I'm afraid, writing docs is a hard topic.

But I for myself, never had to access the webpage to start dunst. I've got everything from [the ArchWiki page](https://wiki.archlinux.org/index.php/Dunst). It's not that much, but it was enough to get started.

It would be great, if someone could come up and write "Getting Started" tutorial.

Related #507

**Comment by PhilHudson** [comment]
Thanks for the replies. Thought I should flag it up. I'm content if
you want to close this issue now (though I kind of hope you'll keep it
open).

-- 
Phil Hudson                  http://hudson-it.ddns.net
Pretty Good Privacy (PGP) ID: 0x4E482F85

**Comment by smvoss** [comment]
Came here because of the arch wiki, it specifically calls out:

> There is no need to start or enable dunst; it is called by systemd when programs send notifications through dbus. 

https://wiki.archlinux.org/index.php/Dunst

After digging around here, I got it setup with systemd but I was thrown way down the wrong path. Would have been nice to have a bit of docs so I could tell easier that I did have to actually run it.

**Comment by WhyNotHugo** [comment]
@smvoss What extra steps did you have to take? If properly installed, generally, no extra steps need to be taken (I know I just installed the package on arch, and suddenly "it worked").

**Comment by bebehei** [comment]
@smvoss Could you please do me a favor and do post the output of `grep -r org.freedesktop.Notifications /usr/share/dbus-1/services` and also of `find /usr/share/dbus-1/services | egrep 'dunst|Notifications'` ?

In the service lookup, there are some weird undefined behaviors.

**Comment by Narrat** [comment]
But as already written, writing doc is not an easy task :D 
Depending on your personal setup (full DE or just WM + some extras) make a huge difference. Especially if someone has a full custom xinitrc in use, where the include to ```/etc/X11/xinitrc.d/``` is missing (e.g. no import of DISPLAY, which can cause issues with the notification-daemon in use) or outdated calls for starting the wm still there (like ```exec ck-launch-session dbus-launch openbox-session```).
Should this be covered as an user "error" or should it be written down, etc

**Comment by bebehei** [comment]
During the last years, I've learnt that useful software is actually a big chain of 'and' connections. You could have written the most sophisticated code, but it won't move you forward if the targeted users don't understand it.

And one possibility to fight this is simply documentation. And here at this project, we never had more than a superbig manpage (albeit big, it's not always useful).

So, I'd like to see something like a website and make the dunst manpage solely about the `dunst` executable and its

**Comment by bebehei** [comment]
.... ups hit enter too early ....

----

And this website should cover all about starting techniques, configuration options, tips and tricks, in case of error, etc.

Content-wise, this wouldn't be a problem for me. It would just be a bunch of work documenting everything, but as a profit it would solve exactly this last 'and' concatenation mentioned above.

But my main problem is, I have to start first with wasting thoughts about a documentation framework, a proper template before I can write the first sentence of documentation. And I'd like to spend this time on dunst and not on some meta-details.

If someone is volunteering with documentation, I'd love it. If you think this would be a big deal, writing all the content. We just talk at first about a framework, where we can actually put documentation. Content-wise I will help you!

**Comment by smvoss** [comment]
Sorry, I will get more info but I haven't been at my pc.

My opinion is simple, Rome wasnt built in a day.

I think just a simple example of a full DE setup and an example of a minimal WM setup would be a nice step forward. Don't need huge doc frameworks etc, a small start at the bottom of the read me would work. 

Hell, toss it in the arch wiki and give a link back to it.

**Comment by bebehei** [comment]
Ok, I've started to create docs for dunst. I've chosen readthedocs. It's easy to build and it's tightened strongly to git. You can also build manpages with the underlying sphinx framework, which helps us replacing the superbig `docs/dunst.pod` manpage.

Also this is a duplicate issue. There's already #507, which got reported first. So, I'm going to close this one in favor of #507.

If you guys have any comments, please post them on #507. I'd love to see comments.

**Comment by bebehei** [comment]
Hey guys, I want to move the installation section from the `README.md` into `/docs/installation.rst`. This renders the README almost empty.

I'd love to put into the readme a good set of screenshots. This readme will also be the landing page of the readthedocs project. Are you able to show me your unixporn and make some cool screenshots showing dunst's abilities?


In the meantime, there's already a test project for dunst on readthedocs. I'm pushing regularly on there, see: https://dunsttestproject.readthedocs.io/en/docs/

**Comment by PhilHudson** [comment]
OP here, just come back after a long gap, and wow, doco has really improved a lot. Looks very nice too, which is always a feature to aim for. Congrats and thanks!
