### ISSUE TITLE
Move CI to CircleCI

### ISSUE THREAD

**Issue by bebehei** [dunst-project/dunst#565]
I'd love to move to CircleCI.

- It offers docker container support, so there is no installation process necessary during build.
- You can test indefinitely many distros.
- You can create workflows, with dependencies.
- The current workflow in its current incarnation, is as fast as Travis, **but runs on much more Distros**.
- It's much faster giving negative results (because it tests on a single distro first).
- It's not limited to Ubuntu 14.04 (there is a **beta** for 16.04 in Travis available).
- The test environment are also available locally.
    - Container information is here: https://github.com/bebehei/dunst-docker

A first PR is already done on: bebehei/dunst#1

**Comment by bebehei** [comment]
> (there is a beta for 16.04 in Travis available).

Oh, well I have to revise myself: [They have updated the beta version a few days ago and Ubuntu 16.04 is now broadly available](https://github.com/travis-ci/travis-ci/issues/5821#issuecomment-440899016). But still it's two and a half years since xenial came out!? They're "super pleased to announce" an old distro. And I guess, they have to replace it because their main distro will reach End of Life in half a year.

Also today's half a year after Canonical released Ubuntu 18.04! It would have been a reasonable delay to support now 18.04. For CI, I want to test my software on old systems, of course. But I also need the most recent system to know that it still works there!

**Comment by tsipinakis** [comment]
No objections here, maybe have both running for a while see which fairs better.

**Comment by bebehei** [comment]
While reading [the comments about the current TravisCI aquisition](https://news.ycombinator.com/item?id=18978251), I've got the feeling, we did the absolute right thing here.
