### ISSUE TITLE
Feature request: support XDG Icon Theme Specification

### ISSUE THREAD

**Issue by infokiller** [dunst-project/dunst#570]
AFAIK, right now the only way to specify icons is using the `icon_path` configuration option, which requires to explicitly list the icon directories. This causes the following issues:
1. If you want to use icons from multiple subdirectories, you have to make dunst aware of the subdirectories. For example, to use icons from the `apps`, `devices`, and `places` subdirectories under `/usr/share/icons/hicolor/32x32/`, you can set `icon_path` to `/usr/share/icons/hicolor/32x32/apps/:/usr/share/icons/hicolor/32x32/devices/:/usr/share/icons/hicolor/32x32/places`. Another option is to put one of the top level directories in `icon_path` (such as `/usr/share/icons/hicolor/32x32/`) and then use a specific icon path when calling `notify-send`, for example `notify-send --icon apps/firefox.png`.
2. Dunst will not respect the `index.theme` file, which can specify things like inheriting icons from another theme via the `Inherits` key.

I think it would be better from a user perspective if dunst could respect the `index.theme` file. For example, dunst could have the following new set of configuration options:
- `icon_theme_name` - name of the icon theme subdirectory in `/usr/share/icons` or `$XDG_DATA_DIRS/icons`. For example, `hicolor` or `Adwaita`.
- `icon_preferred_sizes` - list of preferred icon sizes, for example `32x32:64x64:16x16`. Icons will be looked up in this order. For example, the call `notify-send --icon error` may first look for the error icon in `/usr/share/icons/32x32/`, and only if it doesn't find it there it will fall back to searching in `/usr/share/icons/64x64/`, and then optionally in `/usr/share/icons/16x16/`.

## References
- [XDG Icon Theme Specification version 0.13](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) from 2013 (latest version)

**Comment by infokiller** [comment]
Duplicate of #157

**Comment by bebehei** [comment]
Actually, I'd love to see a PR for this! My personal attempts all failed and I've got no time for this now.

So, if you're interested in it, please start with a PR.
