### ISSUE TITLE
If /root/.config/dunst/dunstrc exists it will be preferred to any other

### ISSUE THREAD

**Issue by tsaber** [dunst-project/dunst#578]
I just got behind my problem of being unable to customize the dunst notification colors or framestyle in any way. 
There was a dunstrc existent in my root .config/dunst folder.
Now I don't know if I might have been the one doing this but even so. Is it intended behavior that root dunstrc precedes over any user  dunstrc?

**Comment by bebehei** [comment]
Are you at 35c3? I could help you there directly.

**Comment by bebehei** [comment]
> I just got behind my problem of being unable to customize the dunst notification colors or framestyle in any way.

Which problem?

>  There was a dunstrc existent in my root .config/dunst folder.

Dunst doesn't create a config file by itself.


> Now I don't know if I might have been the one doing this but even so. Is it intended behavior that root dunstrc precedes over any user dunstrc?

Ok. Dunst only reads a single file. It's depending on your XDG's implementation. Ususally it's `~/.config/dunst/dunstrc`. So for root, it's `/root/.config/dunst/dunstrc`. But usually you don't want to run dunst as root.

How are you starting your dbus service? Which user are you running dbus? How are you starting your session?

**Comment by bebehei** [comment]
If you have further questions, please ask them. But I'm going to close this issue.
