### ISSUE TITLE
What are these letters in brackets?

### ISSUE THREAD

**Issue by catzybluphish** [dunst-project/dunst#579]
![dunst](https://user-images.githubusercontent.com/40843060/50538653-23926800-0bbe-11e9-883f-483e0fa99762.png)
They don't appear in Spotify notifications but are else where (gpmdp, firefox, nm-applet).
Here's my [config](https://raw.githubusercontent.com/catzybluphish/Arch-dotfiles/master/.config/dunst/dunstrc)
Cheers!

**Comment by bebehei** [comment]
You've got the `show_indicators` option enabled. Set it to `no` and all the actions will disappear in your notifications.

**Comment by catzybluphish** [comment]
> You've got the `show_indicators` option enabled. Set it to `no` and all the actions will disappear in your notifications.

Thank you!
