### ISSUE TITLE
All notifications prefixed with (A)

### ISSUE THREAD

**Issue by atomheartother** [dunst-project/dunst#599]
Hello!

I can't imagine that this hasn't been described before but I can't seem to find any info about it.  The fact that search engines don't really like the string "(A)" doesn't help... I've had this bug on my setup for the longest time and I can't seem to get rid of it. I didn't mind but I recently reinstalled Arch from scratch and this issue is *still here* so I thought i'd ask here.

Every single notification is prefixed by the string "(A)". I'll use a Discord notification as example but this isn't specific to Discord, it's every single notification:
![1548939524](https://user-images.githubusercontent.com/10134879/52055689-61d5cb00-2560-11e9-8e20-0984846ff823.png)

I've tried reproducing it, however if I use notify-send everything is hunky dory:
`notify-send -t 5000 -a "discord" Someone "dab on the haters"`
![1548939692](https://user-images.githubusercontent.com/10134879/52055820-c3963500-2560-11e9-8336-73a1fb7f4237.png)

Oh yes and when I run `dunst -startup_notification` , the startup notification doesn't have the (A) either.

What I have tried:
- Commenting out parts of my configuration file related to displaying icons, which is where most of my modifications are
- Changing my format to have no variables (`format="test"`)
- Commenting out my entire configuration file
- Using the [example dunstrc](https://dunsttestproject.readthedocs.io/en/docs/getting_started.html#configuring-dunst) file
- Building from source (`master` branch)

**All of these keep the same behavior**. So I'm pretty sure it's not my configuration, it has to be something else, and I'm hoping someone here has seen this before.

### Installation info

- Version: `1.3.2 (2018-05-06)`
- Install type: `Arch Linux package: community/dunst`
- Distro and version: `Arch Linux 4.20-4`

I'm running `i3-wm`, if that could be related in any way.

**Comment by bebehei** [comment]
Set `show_indicators` to false.

**Comment by tsipinakis** [comment]
I was about to say that this is a good opportunity to increase our docs but a quick search for `(A)` in the manpage brings up the relevant section.

> If "show_indicators" is true and a notification has an action, an "(A)" will be prepended to the notification format. Likewise, an "(U)" is preneded to notifications with URLs. It is possible to interact with notifications that have actions regardless of this setting, though it may not be obvious which
       notifications HAVE actions.

@atomheartother Does that answer your question? Any suggestions to improve the docs?

**Comment by atomheartother** [comment]
Don't I feel dumb, I searched all issues here and the documentation online and absolutely forgot you guys had a `man` page. I figured it was something like that though. Sorry for wasting your time, that fixed it of course.

**Comment by tsipinakis** [comment]
No worries, it happens :)

**Comment by atomheartother** [comment]
@tsipinakis Hm well the ["Configuring Dunst" section of the documentation](https://dunsttestproject.readthedocs.io/en/docs/configuration.html) is definitely empty, although I understand it's an open issue (#507) and a WIP. Is anyone currently working on filling that? I'd love to contribute to this awesome project.

**Comment by bebehei** [comment]
This is a regular question. The `(A)` stands for action. So the notification is clickable (and does trigger something in your application). In case for discord, I guess it might open the corresponding chat.

Please keep this issue open. We'll cover this in our docs. We currently start to write some proper docs. And this question has to get answered there, too.
