### ISSUE TITLE
config.mk comment is causing a bad path during make install

### ISSUE THREAD

**Issue by ortango** [dunst-project/dunst#602]
### Installation info

- Version: `v1.3.2-347-gce5721a` (latest git)
- Install type: `manual` (from PKGBUILD)
- Distro and version: `archlinux`

[commit `ce5721a`](https://github.com/dunst-project/dunst/commit/ce5721af731f68ac602d8518c14451216a19a17b#diff-24cd8940f759626a7a0f55b7496baba4R5) in config.mk adds `MANPREFIX ?= ${DATADIR}/man # around for backwards compatibility`. the comment is adding a space, "$DATADIR/man ", and the install of the manpage fails with a bad path. moving the comment fixes the issue. i do not know if this problem is specific to my setup, apologies if it is.

**Comment by tsipinakis** [comment]
Fixed with #600. Wow, that was a really fast response from both of you.
