### ISSUE TITLE
Custom frame_color doesn't work as expected at all times

### ISSUE THREAD

**Issue by quirinux** [dunst-project/dunst#604]
I've got a really weird behaviour when trying to personalize the frame_color for some specific apps

Follow a bit of my dunstrc:

on global section:
```
    frame_width = 2
    frame_color = "#cc241d"
```

on urgency sections
```
[urgency_low]
    background = "#282828"
    foreground = "#ebdbb2"
    frame_color = "#008000"
    timeout = 15

[urgency_normal]
    background = "#282828"
    foreground = "#ebdbb2"
    frame_color = "#0000b2"
    timeout = 15

[urgency_critical]
    background = "#282828"
    foreground = "#ebdbb2"
    frame_color = "#900000"
    timeout = 30
```

On script section
```
[Slack]
        appname = Slack
        new_icon = "/home/quirinux/Pictures/AppIcons/slack.png"
        frame_color = "#e51670"
        frame = "#e51670"

[vpnconnect]
        appname = vpnconnect
        frame_color = "#3CB371"

[Spotify]
        appname = Spotify
        timeout = 5
        frame_color = "#84bd00"

[notification-catcher]
        script = "notification-catcher"
```

Either on Slack and vpnconnect section the frame_color is not changed when triggered, but works perfectly fine on Spotify notification, it gets me buggy.
the last run script is my notification catcher which works fine all the time, I believe it doesn't impact at all, just let it there for the sake of clarity,

It's is easy to reproduce just running:
```
notify-send -t 5000 -a Slack "foo bar"
```

And I got this back from dunst -print
```
{
	appname: 'Slack'
	summary: 'foo bar'
	body: ''
	icon: '/home/quirinux/Pictures/AppIcons/slack.png'
	raw_icon set: false
	category: 
	timeout: 5000
	urgency: NORMAL
	transient: 0
	formatted: '<b>foo bar</b>'
	fg: #ebdbb2
	bg: #282828
	frame: #0000b2
	id: 2
	script: notification-catcher
}
```

So the personalized icon is changed as expected but the frame colour keeps the same as defined on urgency_normal section.

I already tried to create a second slack section, leaving one only for icon change and another just do frame_color, didn't work too. I've tried to use *frame* instead of *frame_color*, nothing again.
 

Any thoughts about how to fix this are more than welcomed.

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.3.2`
- Install type: `nix-pkg compilation`
- Distro and version: ` redhat enterprise 7.5`
- WM: i3gaps

**Comment by tsipinakis** [comment]
> Version: `Dunst - A customizable and lightweight notification-daemon 1.3.2`

There hasn't been a release since we added `frame_color` as a rule setting. You'll have to build from source to use it.


Argh, this is the second similar issue (#596) about unreleased changes recently, there will be a new release in 2 weeks max. Really let the changes pile up this time.

**Comment by quirinux** [comment]
so that might be fixed already, good to know, thanks
dunst is awesome but it lacks documentation and script examples bit I believe I'm able to give a hand with those

thanks a mil
