### ISSUE TITLE
How to dunst with sysvinit?

### ISSUE THREAD

**Issue by p-e-r-s-o-n-a-l-a-c-c-o-u-n-t** [dunst-project/dunst#612]
Minimal devuan (debian without systemd, but with sysvinit) install + basic X (openbox) + dunst and libnotify-bin.

Similar setup on debian (systemd) works out-of-the-box.  I understand that there are fundamental differencies between systemd and sysvinit based systems and what I have gathered for now, sysvinit needs some extra care. Also devuan provides dunst and libnotify-bin in its own repositories, so there should be no conflict. 

Question: How to setup and configure sysvinit (and debian) based minimal X, so it can run/utilize dunst and notify-send?

**Comment by Tonus1** [comment]
Do you launch Dunst at startup? How do you test notifications? 

On Slackware (no systemd crap either), it works out of the box.

**Comment by p-e-r-s-o-n-a-l-a-c-c-o-u-n-t** [comment]
> Do you launch Dunst at startup?

No, I just `apt install dunst libnotify-bin` (and reboot to celebrate)
> How do you test notifications?

notify-send "TEST NOTIFICATION"

BTW [FAQ](https://dunst-project.org/faq/) says that env variable DBUS_SESSION_BUS_ADDRESS must be set, how it is done? `env | grep -i "DBUS_SESSION_BUS_ADDRESS" ` yields nothing, also there was mentioned `gdbus` , which I have no idea what it is, nor do apt.

**Comment by tsipinakis** [comment]
On Debian you need to install the `dbus-user-session` package in order to use dbus. After installing that (and rebooting/relogging) running `notify-send` on the command line should start dunst automatically.

**Comment by p-e-r-s-o-n-a-l-a-c-c-o-u-n-t** [comment]
from debian package search for "dbus":
`dbus-user-session` - simple interprocess messaging system (systemd --user integration)
`dbus-x11`               - simple interprocess messaging system (X11 deps)

`dbus-x11`  did the trick and notifications are working.
thanks!

**Comment by tsipinakis** [comment]
Oh right! `dbus-user-session` is for systemd, `dbus-x11` is the more general one, oops!

Glad you figured it out.
