### ISSUE TITLE
max_icon_size is broken when dynamic width is used

### ISSUE THREAD

**Issue by catzybluphish** [dunst-project/dunst#614]
### Installation info

- Version: `1.4.0 (2019-03-30)`
- Install type: `package`
- Distro and version: `Arch`

The `max_icon_size` setting is broken. Any value will make the icon show at its maximum size. Setting it to 0 will still enable icons. Am I missing something?

**Comment by catzybluphish** [comment]
> It works on my end, can you post your dunstrc and a test case to try and reproduce this?

This is the [dunstrc](http://ix.io/1F2F) I use.
Ever since I updated dunst from the Arch's repos, the icon setting is broken. I've even switched out for the new /usr/share/dunst/dunstrc but that didn't help. All I did was:
1. update dunst
2. change to new dunstrc

**Comment by fwanky** [comment]
Same issue here on arch.

**Comment by tsipinakis** [comment]
Reproduced, the bug comes from c99f715391ab54df9fc6289410da24a62f2ac18f I forgot to check whether the width was 0 so it capped the `max_icon_size` to 0 automatically if dynamic width is used, oops.

@catzybluphish @fwanky Can you build https://github.com/tsipinakis/dunst/commit/dda26bfbe911395ae1d796d3266836af6c2edd78 to confirm if this fixes the issue?

**Comment by catzybluphish** [comment]
> Reproduced, the bug comes from [c99f715](https://github.com/dunst-project/dunst/commit/c99f715391ab54df9fc6289410da24a62f2ac18f) I forgot to check whether the width was 0 so it capped the `max_icon_size` to 0 automatically if dynamic width is used, oops.
> 
> @catzybluphish @fwanky Can you build [tsipinakis@dda26bf](https://github.com/tsipinakis/dunst/commit/dda26bfbe911395ae1d796d3266836af6c2edd78) to confirm if this fixes the issue?

Thanks! It's fixed. While I'm still here, I have a feature suggestion. Since I'm using `geometry = "0x0-20+41"` (dynamic width as you call it), I'd like there to be some space between the icon and text. As you can see in this image:
![2019-04-02-200843_273x112_scrot](https://user-images.githubusercontent.com/40843060/55394689-33d22e80-5583-11e9-9441-5522280ac5bf.png)
The space in between is only as much as my horizontal_padding, and increasing it will add more space to the left of the icon. Is there a way to create a gap between them without setting a fixed width or using padding that also adds space to the right and left?

**Comment by tsipinakis** [comment]
> While I'm still here, I have a feature suggestion [...]

This has been requested before, see #543. The code that handles the layout creation needs some cleanup and proper testing before anything can be changed there.

I'll get around to it someday, but as is usual in open source if you want to help PRs are always welcome.

**Comment by GuessWhatBBQ** [comment]
Replying to @tsipinakis in https://github.com/dunst-project/dunst/issues/614#issuecomment-479386061
Could the space be added according to another parameter in the config file ?

It could be something like 
```icon_text_space = <pixels>```
and be set to 0 (i.e disabled) by default.

I've briefly looked through the render_content function in the draw.c file which I believe is where the position of the text is calculated. The space could be added to text_x alongside the usual h_padding to give the desired result from #543. I'd be ok with having a go although my experience with cairo is null. I'm just curious about whether this would break anything else

**Comment by fwSmit** [comment]
Yes, you will need to add another config variable. I would call it text_icon_padding. I think it's best to default it to 0 and if it's no-zero it overrides the h_padding (not add to it). 
All the drawing is indeed done in draw.c.
