### ISSUE TITLE
Dunst (1.4.0-1)

### ISSUE THREAD

**Issue by Teeffelen** [dunst-project/dunst#615]
Dunst doesn't seem to startup anymore using `dunst &` in my `.xinitrc`. Downgraded to 1.3.2 seems to fix it. It does work after a `pkill dunst` and restarting dunst from a terminal (this method does not reveal any errors).

### Installation info

- Version: `1.4.0-1`
- Install type: `package/pacman`
- Distro and version: `Arch Linux 5.0.5`

**Comment by tsipinakis** [comment]
Are there any errors from dunst in the system log or .xsession-errors?

**Comment by Teeffelen** [comment]
Checking a fresh .xsession-errors does not show any errors. Restarting dunst with the -print option shows the following:
`WARNING: No icon found in path: 'dialog-information'
{
	appname: 'notify-send'
	summary: 'hfkdsaf'
	body: ''
	icon: 'dialog-information'
	raw_icon set: false
	icon_id: '(null)'
	desktop_entry: ''
	category: 
	timeout: 10000
	urgency: NORMAL
	transient: 0
	formatted: 'hfkdsaf'
	fg: #F3F4F5
	bg: #000000
	frame: #888888
	fullscreen: show
	progress: -1
	stack_tag: 
	id: 2
	actions: {}
	script: (null)
}
`
Again, it does work after a restart but something is preventing it from working properly at boot (tried using xinintrc and i3config to boot dunst, which work perfectly on 1.3.2)

**Comment by Teeffelen** [comment]
Wait, I found this using `journalctl -fp err`:
```
-- Reboot --
Apr 01 12:15:07 TP systemd[916]: Failed to start Dunst notification daemon.
Apr 01 12:18:10 TP systemd[916]: Failed to start Dunst notification daemon.
-- Reboot --
Apr 02 15:39:35 TP systemd[887]: Failed to start Dunst notification daemon.
```
(Reboot was me checking if the 1.4.0 version worked at boot, clearly it had an error)

**Comment by Teeffelen** [comment]
You can close this, I got it working by removing all instances of dunst in my i3config and xinitrc... Somehow it starts now at boot without any problems/errors? (I did nothing regarding systemd or systemctl as far as I know?)

I probably had it start dunst twice, causing some problems on the new build, and when I did the pkill dunst I probably killed al instances and then it worked fine when I tried to launch dunst myself because the others were killed...

**Comment by dr3mro** [comment]
Please restore markdown to Dunst again .. this update is very bad

**Comment by BadWolf43** [comment]
No longer use markdown? But why, please restore.

**Comment by tsipinakis** [comment]
@dr3mro @BadWolf43 See #616. Markup was disabled for the summary only.
