### ISSUE TITLE
[Feature Request] Github Notifications

### ISSUE THREAD

**Issue by zero77** [dunst-project/dunst#619]
Can Github notifications support be added to dunst so, every time you get a notification on Github dunst should notify.
Thanks

**Comment by tsipinakis** [comment]
Hi,

Dunst is only the daemon part of the process i.e. the program that displays notification and not the one that generates them.

To fetch notifications from github you'd have to either write or find a addon/client that does so. Look for "Github desktop notifications" on google someone's bound to have written one already.
