### ISSUE TITLE
Set maximum notification height

### ISSUE THREAD

**Issue by ghost** [dunst-project/dunst#625]
Not an issue, question

Is there a way to cut off text instead of displaying all of the text?
It can be quite cumbersome to display a whole stupidly long message :/

**Comment by tsipinakis** [comment]
There isn't currently. The closest thing is the {`DUNST_NOTIF_MAX_CHARS`](https://github.com/dunst-project/dunst/blob/977a7a7ea47f2d86ea3168e609576ebeb0ffa719/src/notification.h#L11) but that's set at compile time and it's there more to prevent a client making dunst hog the CPU by sending a giant notification.


That being said I wouldn't mind adding such a feature with if there is a convincing use-case. Can you go into a bit more detail on what types of notifications you're looking to truncate?

**Comment by beef331** [comment]
The most compelling case for this is when recieving whole code blocks in a single message from discord or other messenger. Takes up the entire 1080p's vertical height.

**Comment by tsipinakis** [comment]
That makes sense. Have you tried using `geometry` and `shrink` to restrict notification size or is there a reason it doesn't work?

**Comment by beef331** [comment]
I honestly have very little idea how to properly customize dunst, but i did try shrink and the geomety.
```
geometry = "300x2-30+20"
shrink = yes
```
Results in 
![image](https://user-images.githubusercontent.com/11792483/69670261-bea2f480-1050-11ea-90a0-ecb28c1082d5.png)

**Comment by tsipinakis** [comment]
You're right, I tried a few combinations and there doesn't seem to be a way to set a hard limit. `word_wrap = no` would achieve this but then you're limited to a single line.

I'd be open to implementing this but in my opinion this should be in the form of a `max_height` and not a character limit, to fit with the plans in #336 , and to avoid variables like font size and spacing.

**Comment by beef331** [comment]
Max height would be a nice solution, I would like it to add a trailing elipsis if at all possible, but that's up to you if you wish.

**Comment by tsipinakis** [comment]
There's already the `ellipsize` setting for adding ellipsis when the notification is truncated (currently only happens when `word_wrap` is off).

So this would ideally work in the same way

**Comment by TRSx80** [comment]
The solution is actually to avoid Discord like the plague, and instead hang out in IRC where (most) people have the sense to instead post a link to a paste. :wink:  :smile:

**Comment by Sh3Rm4n** [comment]
> The solution is actually to avoid Discord like the plague, and instead hang out in IRC where (most) people have the sense to instead post a link to a paste. 😉 😄

Well I do not think that this is a solution, because it is not only discord. kde-connect for example is also a candidate which notification-text includes whole email-texts etc. 

So avoiding such programs just so that Dunst behaves right is the wrong solution.

**Comment by fwSmit** [comment]
@apoorv569 @advilm 
It seems like there is a lot of demand for this feature, so I think we should probably implement it, although it will take some time to do it correctly. I agree with @tsipinakis that the best way to implement this would be to add an option to limit the maximum notification height. This will probably be enabled by default and I think it should include limiting the icon size as well.

**Comment by fwSmit** [comment]
This is implemented by #855
