### ISSUE TITLE
Notification window hidden behind other windows in StumpWM when switching groups

### ISSUE THREAD

**Issue by goose121** [dunst-project/dunst#627]
Version: 1.3.2
Install type: AUR
Distro and version: Artix Linux
Window manager: StumpWM (master branch)
When you switch groups (i.e. workspaces) in StumpWM, the dunst notification window, if it's open, gets buried behind the other windows in the group, and will not raise back above them until the existing window is closed by dismissing all notifications. This seems like it may be tangentially related to #160 (or at least to some of the comments on it), and the corresponding StumpWM issue is https://github.com/stumpwm/stumpwm/issues/469.

**Comment by tsipinakis** [comment]
Thanks for the report!
I'll have to try and setup StumpWM to see what's happening there exactly. I'll report back here when I get some time to do it.

> Version: 1.3.2

In the meantime, can you try installing 1.4.0? (should be in the arch repos already) The fixes that were mentioned in #160 is not included in 1.3.

**Comment by goose121** [comment]
I tried installing 1.4.0, but the behaviour persists.

**Comment by fwsmit** [comment]
It seems this got fixed in stumpwm. Either way, it's not a dunst issue, so I'm closing this.
