### ISSUE TITLE
signal to reload dunstrc

### ISSUE THREAD

**Issue by knopwob** [dunst-project/dunst#63]

**Comment by ferki** [comment]
@knopwob: why not? Is something blocking this?

**Comment by piahoo** [comment]
@knopwob: why not? Is something blocking this?

**Comment by knopwob** [comment]
because the workaround posted above works good enough, IMHO.

@Eizen @tsipinakis  your opinions? Feel free to reopen this issue, if you think otherwise.

**Comment by tsipinakis** [comment]
A workaround has already been mentioned and I don't think reloading the configuration is something that needs to be done that often, so I'm not sure how useful implementing this will be.

That being said, I'd reopen this if there is a use-case that I haven't considered. @piahoo can you elaborate on why you need this feature?

**Comment by luan** [comment]
How exactly does that work around work? That highly depends on how you're starting dunst. I for one do it with a simple: `exec --no-startup-id dunst` on my i3 config. With doesn't get executed when restarting i3 in place or reloading i3.
That makes reloading the dunst config quite annoying.
@tsipinakis

**Comment by Eizen** [comment]
@luan From i3's documentation:
`"if you need a command to run also when restarting i3 you should use the exec_always keyword"`

You could easily use: `exec_always --no-startup-id dunst` as a workaround. Besides for any other use-case one could use a keybind with the previous workaround, in i3 for example: `bindsym $mod+Shift+d --release exec --no-startup-id killall dunst;notify-send foo`.  So i don't really see a valid reason to implement this so far.

**Comment by tsipinakis** [comment]
As @Eizen said. It's expected that you're using the dbus service so that dunst starts automatically when a notification is sent. Is there any reason you're starting dunst manually @luan ?

**Comment by wtfdewuno** [comment]
i know this is old but just for the record && is seemed to be more efficient than the semicolon ; in my case
with the semicolon i had to restart i3 in place(mod+shift+r)  twice for the notify-send notification to show.
needs to be restarted in place twice using semicolon
exec_always --no-startup-id killall dunst;notify-send "i3 & dunst" "rebooted"
and only once using &&
exec_always --no-startup-id killall dunst && notify-send "i3 & dunst" "rebooted"

**Comment by Aeres-u99** [comment]
As a workaround for now I am using `sudo pkill dunst` and then `dunst -config ~/.config/dunst/dunstrc &`

**Comment by aliveupstairs** [comment]
@Aeres-u99 It does not do a great service.
`killall dunst` does not work for me (I don't know what other program is being considered by D-Bus) and the Arch Wiki [says](https://wiki.archlinux.org/index.php/Dunst#Installation):

![Note: It may seem like there's no need to manually start dunst, as it may get autostarted by dbus-daemon when programs send notifications through D-Bus. However, the notification service frequently has multiple daemons installed, and there is no way to know which daemon will be autostarted. The dbus-daemon maintainers explicitly warn against relying on autostart for multiple-provider services.](https://user-images.githubusercontent.com/46059092/74614281-ec12b200-5116-11ea-82b6-aedb9822248d.png)

@tsipinakis One reloads `dunst` every time they change configuration. I think that's often enough.

**Comment by tsipinakis** [comment]
This could be added with #651 , when that's done.

The main problem here was that there was no way to send commands to dunst outside the normal notification API. With that this issue is resolved.

**Comment by tsipinakis** [comment]
> I don't know what other program is being considered by D-Bus

You can find out with:
 `grep -r Notifications /usr/share/dbus-1/services/`

**Comment by LoganDark** [comment]
`notify-send` while Dunst is not open just hangs indefinitely. dbus does not automatically start dunst for me, even though `grep -r Notifications /usr/share/dbus-1/services/` says `./usr/share/dbus-1/services/org.knopwob.dunst.service:Name=org.freedesktop.Notifications`.

**Comment by jdelahunt-wooliesx** [comment]
Furthermore, notification history is lost when dunst is restarted. Reloading config without restarting is highly desireable.

**Comment by flowergardn** [comment]
those who see this issue in search engines later on, a command to reload dunst was implemented in 2024:
https://github.com/dunst-project/dunst/issues/719#issuecomment-2228065455
