### ISSUE TITLE
Display image

### ISSUE THREAD

**Issue by BigfootN** [dunst-project/dunst#631]
Hello,

I would like to know if dunst supports the display of images (album arts to be more specific) ?

Where the path of the image would be sent and the image then displayed ? (not icons)

Something like:

- My dunst version:  `Dunst - A customizable and lightweight notification-daemon 1.4.0 (2019-03-30)`
- Install type: `aur`
- Distribution: `Archlinux`

Thank you very much in advance.

**Comment by tsipinakis** [comment]
Hi,

While the notification spec does list an optional `<img>` html tag it's currently not implemented in dunst. (Although the URL will be included in the context menu). The most common way to get around to it is via icons which you can either send a path for dunst to read, or send the icon itself if you have a file that is being updated.

I'm open to discussion about implementing it though, what are you trying to achieve that can't be solved with the existing icon system?

**Comment by BigfootN** [comment]
Thank you for your quick response.

To answer your question, like I said, I wish to display the album arts/cover of the music playing. I'm thinking something like being able to extract the image from the music path (save it in some temporary place) and pass the path to dunst in order to display it. (Just a thought)

Thank you for your precious help.

**Comment by tsipinakis** [comment]
> I'm thinking something like being able to extract the image from the music path (save it in some temporary place) and pass the path to dunst in order to display it. (Just a thought)

That's definitely doable with icons and some scripting.

With plain `notify-send` you can do `notify-send -i /path/to/icon Summary Body`. However if you're going to be updating the same image in-place it's better to use `dunstify -I` as dunst re-reads the file under some circumstanced and that could also update the icon on older notifications. See #539.

**Comment by BigfootN** [comment]
Hello,

Thank you for your response. I tried to use:

`dunstify -I /path/to/icon/icon.svg "test summary"` (the icon size is `32x32`)

But I only get the notification with `test summary` without the icon.

Thank you very much in advance for any help.

**Comment by tsipinakis** [comment]
You'll have to enable icons in the config, they're off by default. set `icon_position` to `left` or `right` depending on your preference.

**Comment by BigfootN** [comment]
Thank you very much :)
