### ISSUE TITLE
Doesn't work with Chromium

### ISSUE THREAD

**Issue by sarneeh** [dunst-project/dunst#633]
I've been fighting the whole day to make `dunst` work with `chromium` but no success :cry: So I thought that maybe you guys could help me somehow out.

### What's the problem? What's the situation?
- `dunst` generally works
- it displays notifications from `notify-send "test message"`
- it displays notifications from `Firefox`
- unfortunately, in Chromium, the notifications are Chromium-like (not native)

### What I've already checked/tried?
- the above-mentioned tests, like if it works with another browser, or with `notify-send`
- checked `dbus-monitor` for entries, but while running Chromium it doesn't show anything, neither when I trigger a notification in the browser itself
- checked for additional notification-daemons in my system, but only `dunst` was there
- installed chromium from different sources (repository package `chromium-browser`, snap package, `google-chrome-stable` from chrome's website)
- checked fresh install without any extensions etc.
- run chromium with debug logs (also no errors there)
- toggling the `use native notifications` flag in Chromium

The only thing that was suspicious to me is when I've run `chromium-browser` via CLI, I get an error:
```
[9636:9745:0526/130720.964219:ERROR:bus.cc(396)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

(chromium-browser:9636): LIBDBUSMENU-GLIB-WARNING **: 13:07:21.088: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”
```

I'd very appreciate any help and suggestions what could be wrong in my setup as notifications are an important element in my workflow.

### Installation info

- Version: `v1.4.0-6-g264df67`
- Install type: `manually`
- Distro and version: `Ubuntu 18.10 x86_64`

**Comment by tsipinakis** [comment]
Hi!

This is obviously not an issue with dunst as it's something to do with the chromium<-> dbus communication side. But I'd be happy to help you debug it the best I can

Firstly, take a look at a previous discussion in #375 you'll have to do some hacking to get chrome to even attempt to use the native daemon.

> [9636:9745:0526/130720.964219:ERROR:bus.cc(396)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

This looks like there's something up with the bus address, if the issue I linked above doesn't provide any clues check the value of `$DBUS_SESSION_BUS_ADDRESS`, it should be something like `unix:path=/path/to/bus`.

**Comment by sarneeh** [comment]
> This is obviously not an issue with dunst as it's something to do with the chromium<-> dbus communication side. But I'd be happy to help you debug it the best I can

@tsipinakis Thank you very much for wanting to help! I really appreciate that!

> Firstly, take a look at a previous discussion in #375 you'll have to do some hacking to get chrome to even attempt to use the native daemon.

I've just edited my post as I forgot to mention that I've tried already to force Chromium to use native notifications via the flag.

> On second thought, if `notify-send` works there is nothing wrong with dbus on the system side, so it's probably a chromium issue.

I thought about this but I actually can't believe that I'm the only one with this kind of issue as I couldn't find any related problems in the Chromium bug tracker.

> This looks like there's something up with the bus address, if the issue I linked above doesn't provide any clues check the value of `$DBUS_SESSION_BUS_ADDRESS`, it should be something like `unix:path=/path/to/bus`.

That's interesting. I don't have anything under this variable.

**Comment by sarneeh** [comment]
@tsipinakis You are my hero! Exporting a `DBUS_SESSION_BUS_ADDRESS` variable (via `export $(dbus-launch)`) made it work! How can I thank you for this? I literally spent a day debugging this issue! :smile: Thank you!

**Comment by tsipinakis** [comment]
No need, glad I could help! :)

**Comment by isidroas** [comment]
This also worked to me.

When I launch chromium using [dmenu](https://wiki.archlinux.org/title/dmenu), dbus-monitor does not show notifications of chromium.

But when I launch it from the **shell**, which has the variable `DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1001/bus"` (I don't know when it is this set), it works!

Thank you guys! 🍻
