### ISSUE TITLE
Dunstify in crontab

### ISSUE THREAD

**Issue by machinedgod** [dunst-project/dunst#634]
Hi all,
I have a crontab running a custom script, that calls `dunstify` to report some data, and its not working. The error I get is the following:
```
Unable to send notification: Error spawning command line “dbus-launch --autolaunch=9de7c60d640a4de7949cf6ccc0e39832 --binary-syntax --close-stderr”: Child process exited with code 1
```
This is the list of things I've tried:
* making sure that `DISPLAY` env is set up properly, by replacing `dunstify` call with `xmessage` (which works fine)
* searching (DuckDuckGo) for "crontab dunst" (no useful results)
* using `env -i` and gradually introducing variables, to try and get `dunstify` to run (that's how I captured the error)
* using `sudo -u me` (same error as above)
* searched `dunstify.c` code for "Unable to send notification" to try and get some idea of what might be going wrong
* after learning that this is a response to `notify_notification_show`, which I couldn't find, check `#include`, then list symbols from `libnotify.so` (`readelf -s`) and find out this is a libnotify function

This is where I understood that the "problem" I'm having is probably due to libnotify, and maybe I should post there, but I was wondering if you might help me because of what I tried next:
* try searching (DDG) for "libnotify crontab", find a result mentioning Python script using libnotify and cron (https://stackoverflow.com/questions/17278650/python-3-script-using-libnotify-fails-as-cron-job)
* try following accepted answer (add `export` rather than just defining an env for launch)
* try the second part with adding `xhost`

Nothing changes for me, but the person in the SO question commented on the accepted answer, saying that it worked for them. I also tried following the instructions that appeared when I went to submit this issue, ie. monitoring my dbus; nothing showed up.

I am running arch with `xmonad`, `dunstify` works without issues for all scripts that I invoke manually.
Version is 1.4.0-1.

**Comment by tsipinakis** [comment]
Hi, thanks for the detailed report!

I am doing something similar myself, the only thing that was needed was defining `DBUS_SESSION_BUS_ADDRESS` in the cron file, have you tried that?

**Comment by machinedgod** [comment]
I try my best not to waste other people's time :-)

I have not tried previously with `DBUS_SESSION_BUS_ADDRESS`, I wasn't even aware of the existence of this variable. I copied the value from what my shell gives (seems its related to uid, so I guess its OK).
Works like a charm!

Thanks for your help, here's the crontab entry just in case someone stumbles upon here and needs a quick solution:
```
* * * * *  DISPLAY=':0' DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus' $HOME/bin/pwrremind
```
