### ISSUE TITLE
Dunst downstream on Debian

### ISSUE THREAD

**Issue by bebehei** [dunst-project/dunst#635]
On Debian, the dunst package isn't updated to match the 1.4.0. release. As Michael Stapelberg is the current maintainer of the dunst debian package but [actually resigned in the Debian project](https://michael.stapelberg.ch/posts/2019-03-10-debian-winding-down/). I guess someone should embrace the fact and care about the package.

**Comment by tsipinakis** [comment]
Welcome back! :)

Debian testing is currently is freeze so it's normal for sid to lag behind, non-urgent bugfixes have to go through sid first so maintainers usually hold off on new versions in this period. Additionally, Stapelberg hasn't filed any RFAs or orphaned any packages yet.

In any case, I already maintain newsboat in Debian so it'd be logical for me to pick up dunst as well if no-one else steps up. But I'd hold off until after the release of Buster to determine that.

**Comment by tsipinakis** [comment]
Dunst was [orphaned](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930310) and I've marked my intent to adopt it.

I'll package 1.4 and take over the package after the release of buster. I don't think there's any reason to keep this issue open.
