### ISSUE TITLE
Script option with flags

### ISSUE THREAD

**Issue by mattyrc** [dunst-project/dunst#639]
I've created a simple bash script that plays an audio file when a rule matches. The script will play the type of audio file depending on the flag that is called (sound.sh --message, --alert, --email etc). The issue is that it seems I can't pass a flag when calling the script in a rule. For example:
```
[Mail]
appname = Mailnag
script = ~/.scripts/sound.sh --email
```
I've also tried with quotation marks but no luck. Am I doing this wrong or is there no way to run a script with flags?

### Installation info
- Version: `v1.4.0-10-gac94eca`
- Install type: `aur/dunst-git`
- Distro and version: `5.1.15-arch`

**Comment by tsipinakis** [comment]
Flags can't be used because as it's said in the manpage we pass the notification details to the script via the paramaters.

The script will be called like this:
```
./.scripts/sound.sh "appname" "Full summary" "Full body" "/path/to/icon" "urgency"
```

Your best bet would be to do the filtering on the script side based on the appname.

Perhaps we should support some more flexibility here, allowing flags and having the user decide which parameters to pass.

**Comment by mattyrc** [comment]
Oh I see. 

I'm not really sure how to go about doing the filtering from the script as many of my rules are also matched from the summary as the appname is often just a notify-send.

Do you happen to know of any examples that you can point me to for how this could be done?

Thanks

**Comment by tsipinakis** [comment]
Something like this should work for what you're describing:
```bash
#!/bin/bash
appname="$1"
summary="$2"

if [[ "$summary" == *"somestring"* ]]; then
    # do things
fi
```
Add if statements as needed.

**Comment by mattyrc** [comment]
Great. I'll give it a shot tomorrow.

Thank you very much for the help!

**Comment by mattyrc** [comment]
I was able to filter all of my rules through a script like you suggested using the appname, summary or body.

Feel free to close this issue if you'd like.

Thanks again for your help.

**Comment by tsipinakis** [comment]
Happy I could help.

If anyone needs the flag feature mentioned feel free to comment here and I'll re-open this. Or open a new issue entirely.
