### ISSUE TITLE
WhatsApp icons not showing or replaced with 'dialog-information'

### ISSUE THREAD

**Issue by Rahov** [dunst-project/dunst#641]
### Installation info

- Version: `1.4.1-1 (installed on 07-Jul-2019)`
- Install type: `package via pacman`
- Distro and version: `Arch Linux (kernel 4.19.57-1-lts)`
- Desktop Environment: `i3-gaps (4.16.1-1)`

### Issue:

Icons from WhatsApp are ignored or replaced with the 'dialog-information' icon. 
This issue is similar to #394, where the `raw icon set:` was `false` as it is in my case. However, I do not have the `gnome-settings-daemon` package installed.

The information I have up to now is:

- Icons from test websites (e.g. https://www.bennish.net/web-notifications.html) have successfully produced the desired icon.
- Other software on my machine have successfully produced the icon as well, in this case I used Spotify as an example, where the album was being displayed on the notification. 
- Notifications from whatsapp did display normally before installing dunst, however, I'm not sure which package was handling it previously. I would assume it would be part of the i3-gaps package group. 

### Uploads:

- The [dunstrc](https://github.com/Rahov/dunst_issue/blob/master/dunst_config) I'm currently using

#### WhatsApp 
- [output](https://github.com/Rahov/dunst_issue/blob/master/dunst_bus_whatsapp) of `dbus-monitor path=/org/freedesktop/Notifications` for WhatsApp
- [output](https://github.com/Rahov/dunst_issue/blob/master/dunst_print_whatsapp) of `dunst -print -verbosity info -conf .config/dunst/dunstrc1` for WhatsApp

#### Spotify
- [output](https://github.com/Rahov/dunst_issue/blob/master/dunst_bus_spotify) of `dbus-monitor path=/org/freedesktop/Notifications` for Spotify
- [output](https://github.com/Rahov/dunst_issue/blob/master/dunst_print_spotify) of `dunst -print -verbosity info -conf .config/dunst/dunstrc1` for Spotify

**Comment by tsipinakis** [comment]
Huh, for some reason in the spotify output it didn't show the Notify call, that's some unrelated dbus command - weird.
But it doesn't really matter, from the output of the first command looks like firefox is neither giving us a icon file to load nor sending us an icon directly, there is nothing we can do in this case.

Some wild speculation: I'm pretty sure firefox has some built-in notification handling because I remember seeing them when running it without a daemon available, perhaps that's what you were seeing and in that case it selects the website favicon when the website itself doesn't supply an icon to show?

**Comment by Rahov** [comment]
That is a fair point, I've yet to test out if the issue will persist with google-chrome.

In regards to the speculation, I believe you're right based on the fact that discord would not show any notifications, which was why I decided to try out dunst. Previously notifications would show me the profile icon of the sender on whatsapp, which is what I was expecting from dunst as well. 

In any case, thanks for you time. Before I close the issue, would you happen to know what I should be looking into, any lead I can take now would be appreciated. Currently, I'm considering just reinstalling Arch and see if that could solve anything.

**Comment by tsipinakis** [comment]
So, for me the debugging process would be like this:
First uninstall dunst and recreate the old notification you were used to seeing. Using a tool like `xprop` identify which application it is that it's displaying it.

If it's firefox there is nothing else that can be done as that means it's using the icon for its own notifications but is not sending it to other daemons (maybe a fallback). Perhaps research a bit more about how whatapp is sending these notifications and if it's including an icon in them. From the [notification web API](https://developer.mozilla.org/en-US/docs/Web/API/Notification/icon) there's an icon property, if that's set and it isn't showing then there's something along the message chain going wrong.

As you said you should try out a different browser but I would expect it to behave similarly.

PS: Even if this is likely not on dunsts side, I have to say, props for the well researched and thought out report.

**Comment by Rahov** [comment]
Nor problem my dude, thanks for helping out.
