### ISSUE TITLE
Doesn't grab QT system tray message.

### ISSUE THREAD

**Issue by afk-mario** [dunst-project/dunst#642]
Don't really know if this is a QT issue or a dunst issue, but all notifications from [ripcord](https://cancel.fm/ripcord/) are showing up on the system tray instead on using dunst.

Seems to be the same issue described here

https://forum.qt.io/topic/80645/qt-not-using-the-system-notification-daemon

### Installation info

- Version: ` 1.4.1 (2019-07-03)`
- Install type: `pacman`
- Distro and version: ` Arch Linux x86_64 `

**Comment by tsipinakis** [comment]
Is ripcord open source? I can't seem to find the source to analyze what it's doing. In either case dunst uses the standard dbus notification interface. There aren't any alternatives as far as I know.

Could you post the output of `dbus-monitor` while a notification from ripcord goes through?

If it doesn't output anything it probably means it isn't using the standard bus and there isn't much we can do.

**Comment by bebehei** [comment]
ripcord doesn't support libnotify notifications:

https://dev.cancel.fm/tktview?name=8c6b205df0

I guess this can get closed.

**Comment by tsipinakis** [comment]
Something weird is going on here though. From the linked issue

> No, it doesn't. Ripcord uses Qt, and Qt uses the freedesktop/xdg specification over dbus for tray icons and messages. Something is wrong with your Linux desktop configuration.

And the linked code right after directly references the gnome notification spec. So Qt does support sending notifications over the bus?

libnotify should be irrelevant if it has its own dbus implementation.

**Comment by afk-mario** [comment]
I asked Cancel on the discord server and this was the reply, if dunst can't do anything about it then closing this would be alright, just wanted to make sure my config was ok

![image](https://user-images.githubusercontent.com/1025751/61269784-4143ab00-a765-11e9-8537-4078ed4aece9.png)

**Comment by tsipinakis** [comment]
@afk-mario That clears things up thanks!

From a quick google search the spec they mention appears to be [this](https://standards.freedesktop.org/systemtray-spec/systemtray-spec-latest.html).

This is indeed not used by dunst. It looks like a fairly simple and straight forward spec but whether we should support that is up to debate. This is the first time I come across this.

**Comment by bebehei** [comment]
> It looks like a fairly simple and straight forward spec but whether we should support that is up to debate.

I've seen this spec previously (because of another QT bug). Those "balloon messages" are actually messages, which are linked to the trayicon's position. They heavily use the context of the tray icon. The ballon messages were never designed to be a general notification.

It's not our job to implement this. It's the job of the DE's traybar to implement this.

**Comment by tsipinakis** [comment]
That makes sense. I'll close this then.
