### ISSUE TITLE
Cannot connect to DBus.

### ISSUE THREAD

**Issue by unwillexist** [dunst-project/dunst#643]
- Version: Dunst - `A customizable and lightweight notification-daemon 1.4.0 (2019-03-30)`
- Install type: `package`
- Distro and version: ` FreeBSD 12-0 Release`

Dunst doesn't work on my fresh FreeBSD setup. I am getting this output.

```
WARNING: No locale support
WARNING: Unknown keyboard shortcut: 'ctrl+grave'
CRITICAL: Cannot connect to DBus.

```

**Comment by tsipinakis** [comment]
Hi, dunst requires dbus to be installed and the `$DBUS_SESSION_BUS_ADDRESS` variable to be set. You should look at and follow your distributions documentation on setting that up

**Comment by unwillexist** [comment]
Thank you, I just ran doas dbus-uuidgen --ensure and everything worked.

**Comment by tsipinakis** [comment]
No problem, I'm not familiar with BSDs so I apologise for not being able to help you directly.
