### ISSUE TITLE
Add fullscreen as a global option

### ISSUE THREAD

**Issue by ivomac** [dunst-project/dunst#644]
Currently it is possible to change the fullscreen behaviour through rules, but there is no way to change the global behaviour. I am currently using this to use "pushback" for all notifications:
```
[low]
msg_urgency = low
fullscreen = pushback

[normal]
msg_urgency = medium
fullscreen = pushback

[critical]
msg_urgency = critical
fullscreen = pushback
```
it would be nicer to just have a single line in [global]:

```
[global]
fullscreen = pushback
```

**Comment by tsipinakis** [comment]
That's a good idea, there should be a default value for these in the global section.

For now to make your workaround shorter you can use a single rule with no match clause:
```
[pushback_all]
fullscreen = pushback
```

**Comment by ivomac** [comment]
Didn't know that worked! Thanks for the short version.

**Comment by bebehei** [comment]
> That's a good idea, there should be a default value for these in the global section.

Please not. Having rules is the best thing we have. Having "global" configuration options just introduce more complexity while being less flexible. The rules cover every possible configuration case perfectly.

It's just not reallly documented that "order makes a difference".

**Comment by tsipinakis** [comment]
> Having "global" configuration options just introduce more complexity while being less flexible

Interesting that you see it this way. In my mind rules are all about overriding a certain attribute for a specific group, but sometimes like here one wants to change the default value of everything.

The goto would be a section at the top like this:
```
[defaults]
fullscreen = pushback
frame_color = "#..."
```

Given that a lot of these, `frame_color`, `format` etc already do this if placed in the global section, why not expand that to `fullscreen`?

**Comment by bebehei** [comment]
I thought our work was previously directed towards rules. We wanted to improve rules and even want to deprecate such global settings (see #328). A rule without a matcher is effectively a global setting. But in code, it's less complex.

The only point, we have to communicate in the docs: Order makes a difference there.

**Comment by tsipinakis** [comment]
> We wanted to improve rules and even want to deprecate such global settings (see #328). A rule without a matcher is effectively a global setting. But in code, it's less complex.

Indeed but the issue you link is about the `urgency_` sections, not about the global one. What you're suggesting is to split "global" settings like follow, geometry etc and per-notification ones into different sections, right? It does make a lot of sense to do that but currently we don't even have a "proper" issue to track this, no work has been done.

What I'm trying to say is that whatever the state we're trying to move towards, from the user perspective it's currently inconsistent. (why is `frame_color` supported in the global section but `fullscreen` is not?). IMO We should try to keep a consistent state in the config, even if we're planning to change the recommended format in the future.

> The only point, we have to communicate in the docs: Order makes a difference there.

That's true this is indeed missing and should be documented.

**Comment by bebehei** [comment]
>  from the user perspective it's currently inconsistent

Indeed.

> (why is frame_color supported in the global section but fullscreen is not?)

Just because I didn't implement it in my PR. :stuck_out_tongue_closed_eyes:

And I think the actual way to go, is simply deprecating `frame_color` inside the global section. In reality it's a per notification setting and not a global one.

Just see the following code. Do you know how it behaves? After about half a year abstinent, I still know, I've changed it, but I don't know my intention at all.

https://github.com/dunst-project/dunst/blob/6c4eeda43412f0ecd0e38e00069ca47aff4452a8/src/settings.c#L627-L631

The only thing I'm sure about: We have to write it this way, because we have to respect the default and the global settings. Implementing the same with a rule would save 10 settings queries.
