### ISSUE TITLE
Unreadable characters in notifications

### ISSUE THREAD

**Issue by adihrustic** [dunst-project/dunst#648]
### Installation info

- Version: `1.4.1 (2019-07-03)`
- Install type: `package`
- Distro and version: `4.19.62-1-MANJARO`
- Config file: [Link](https://gitlab.com/adihrustic/linux-config/blob/master/homedot/.config/dunst/dunstrc)

### Issue
My dunst notifications have stopped showing regular characters and are instead showing block symbols like this:
![pic](https://i.imgur.com/e4eO8Ie.jpg)

The issues persist regardless of whether I change the current font or not. I'm unsure if the problem lies within dunst itself, but it's the only process with this issues so far.

**Comment by bebehei** [comment]
It looks like your font system is fucked up and it doesn't even have a fallback. I've seen such rectangles, when an emoji or non-ANSI character was attempted to get displayed, but no font with support had been installed.

TBH, I don't see any relation to dunst. Dunst gives pango the font name and pango handles the rest. Are you sure, this font is installed properly on your system?

**Comment by adihrustic** [comment]
Did a clean reinstall of fonts and its working as intended now. I suspect I forgot to kill the dunst process when falling back on preinstalled system fonts.

Closing.

**Comment by progandy** [comment]
Such rectangles might also occur if you try to use bdf bitmap fonts with pango 1.44, This has been fixed in the development version of pango, which will reject such bitmap fonts now.

https://gitlab.gnome.org/GNOME/pango/issues/386
