### ISSUE TITLE
Pass variables as params

### ISSUE THREAD

**Issue by bebehei** [dunst-project/dunst#653]
I think we should pass the flags in the notification script as environment variables.

https://github.com/dunst-project/dunst/blob/53e7f3d16a747a778b7892a175c224d4c558b44e/src/notification.c#L123-L130

Enhancing this, is a PITA and doesn't scale. We also would allow passing flags (#639) and adding new fields would be easy to document and remove later.

It may be also a fix for #645, as you could easily add the desktop_entry field as an environment variable and you could filter it in the script properly.

**Comment by tsipinakis** [comment]
Why the `help wanted` tag?

**Comment by bebehei** [comment]
idk.

**Comment by fwSmit** [comment]
Implemented by #802
