### ISSUE TITLE
Bitmap font error

### ISSUE THREAD

**Issue by edn9** [dunst-project/dunst#654]
Hello, i'm having some troubles with bitmap font, looks like no one is working. (I have tried tewi, gohu, cherry, etc).

![image of the bug](https://i.imgur.com/RYOAnG2.png)

### Installation info

- Version: Dunst - A customizable and lightweight notification-daemon 1.4.1 (2019-07-03)

- Install type: Package, `sudo xbps-install dunst`
- Distro and version: ` Void Linux 4.19.66_1`

**Comment by bebehei** [comment]
Duplicate of #648, see the comment and the linked issue. https://github.com/dunst-project/dunst/issues/648#issuecomment-519951800
