### ISSUE TITLE
Create a Configuration Window

### ISSUE THREAD

**Issue by rosoau** [dunst-project/dunst#664]
Hi
This is not an issue but a suggestion. I use zenity to show and edit dunstrc:

```bash
#!/bin/bash

zenity --window-icon=/usr/share/icons/applications/not.png --text-info --width=700 --height=700 --ok-label="Save Changes" --title="Configure Notifications" --filename=/home/user/.config/dunst/dunstrc --editable > /home/user/.config/dunst/dunstrc-new

if [ -s /home/user/.config/dunst/dunstrc-new  ]
	then
		mv /home/user/.config/dunst/dunstrc-new /home/user/.config/dunst/dunstrc
fi
```

The icon and path is unique for my system, you will have another one
Closing or cancelling the window would produce an empty file: dunstrc-new
and then it would replace the original with a 0 Byte file. That's why we need the if and -s etc. and now this works well. File gets only moved if it has size "-s" but with 0 Byte it gets ignored
![Configure Notifications_027](https://user-images.githubusercontent.com/13397926/66092894-429cab00-e5d1-11e9-97b6-cc5d1cfc01ad.png)

**Comment by rosoau** [comment]
The text on the forum fattened up for some strange reason. I attach the actual file instead
[dunstrc-config.zip](https://github.com/dunst-project/dunst/files/3684110/dunstrc-config.zip)

**Comment by tsipinakis** [comment]
I fixed the formatting for the code you pasted above.

That's useful for someone who's constantly updating their configuration but I suspect most users, like me, use dunst in a "set and forget" way. i.e. Once setup the configuration is rarely updated, if ever.

Additionally, everyone has different preferences in regards to the editor they use or how they edit configuration files, in my opinion there is no need to do something like this when opening the config  with your favorite text editor is only a command away.
