### ISSUE TITLE
SIGCONT / SIGTSTP handling

### ISSUE THREAD

**Issue by mjsir911** [dunst-project/dunst#665]
Hello,

Currently to pause and resume `dunst` is SIGUSR1 (pause) and SIGUSR2 (resume)

I greatly appreciate this feature, but I believe the signals `SIGTSTP` (keyboard stop) and `SIGCONT` would be better suited for this task.

I don't really have a user story for this, but I could imagine tools would be able to take advantage of this more semantically correct signal handling.

Current behaviour of `dunst` is to ignore `SIGTSTP` signals

**Comment by bebehei** [comment]
`SIGUSR*` and `SIGTSTP`/`SIGCONT` signals differ in a simple and easy way.

- `SIGUSR*`: User defined signal, does whatever the process wants to do. If used, always documented. For server daemons, it's most often re-reading the configuration file. We at dunst use it to start/stop _the functionality_ and start/stop displaying notifications.

- `SIGTSTP`/`SIGCONT`: This is necessary for job control. `Ctrl+Z` uses this signal. But all in all, _the process_ stops by getting a signal of the terminal.

So in the semantics differ. We usually don't get spawned in a terminal and dunst has to run all the time. If we really stop the dunst process, many clients may fuck up and run into timeouts until finally DBus will probably start a new dunst instance.

I don't see where the semantics TSTP and CONT are "better suited" for dunst. Also, I'd like to remind you of #445. We plan to implement the functionality by a proper command line control.

**Comment by mjsir911** [comment]
Alright, thanks for your consideration. 

Have a nice day
