### ISSUE TITLE
dunstify --replace broken?

### ISSUE THREAD

**Issue by lampenhauser** [dunst-project/dunst#668]
Dunstify's --replace option does not seem to be working for me. I can't close or replace messages. I tried to check using -r and -p together. In that case it should print the ID i plugged in with the -r option, right?

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.4.1 (2019-07-03)`
- Install type: `package`
- Distro and version: ` manjaro`

**Comment by tsipinakis** [comment]
Just tested it and it works fine on my end, could you be more specific with what's not working?

I did this:
```
dunstify -p Test 123
dunstify -p Test 123456 -r <id returned>
```

**Comment by tsipinakis** [comment]
ping @lampenhauser?
