### ISSUE TITLE
[QUESTION] - Switch to urgent workspaces with dmenu

### ISSUE THREAD

**Issue by marcosnils** [dunst-project/dunst#671]
TL;DR: How to automatically switch to urgent workspace with dunst - dmenu feature.

First of all thanks for taking the time to maintain this project and provide such an amazing tool. I have a question regarding the `dmenu` option for some notifications. Some apps like Slack and Chrome send a notification with an action that allows the WM to focus on the window. When I use dmenu with a `dunst` notification, I get the option to focus the notification window. If I do that and the origin window is in a different workspace, dmenu won't switch to it, it'll just highlight it as urgent.

**Comment by tsipinakis** [comment]
>  If I do that and the origin window is in a different workspace, dmenu won't switch to it, it'll just highlight it as urgent.

I'm curious about what's happening here as well as I've observed the same behaviour. In any case, actions are something the sender is responsible about doing - we only relay the name of the action that was chosen back to the sender.

I'm pretty sure this isn't on the dunst side (unless dmenu is interfering with the workspace switch somehow?)

**Comment by tsipinakis** [comment]
So I also ran into this today, the [solutions mentioned](https://github.com/i3/i3/issues/3860#issuecomment-551406685) in the i3 issue are probably all we're going to get for this. In my case 'focus_on_window_activation` worked just fine.

**Comment by marcosnils** [comment]
Thx @tsipinakis yeah.. it's a shame that we couldn't find anyone else interested on this. I also ended up using a combination of `no_focus` and `focus_on_window_activation`. Thx for closing this.
