### ISSUE TITLE
No icon found warning

### ISSUE THREAD

**Issue by snowman** [dunst-project/dunst#676]
### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.4.1 (2019-07-03)`
- Install type: `sudo pacman -S dunst`
- Distro and version: `Linux USER_NAME 5.4.1-arch1-1 #1 SMP PREEMPT Fri, 29 Nov 2019 13:37:24 +0000 x86_64 GNU/Linux`

### Steps
1. `$ dunst -print`
2. `$ dunstify -i audio-volume-muted "Volume muted"`
3. Output of dunst
```
WARNING: No icon found in path: 'audio-volume-muted'
{
	appname: 'dunstify'
	summary: 'Volume muted'
	body: ''
	icon: 'audio-volume-muted'
	raw_icon set: false
	icon_id: '(null)'
	desktop_entry: ''
	category:
	timeout: 10000
	urgency: NORMAL
	transient: 0
	formatted: 'dunstify
<b>Volume muted</b>'
	fg: #ffffff
	bg: #285577
	frame: #aaaaaa
	fullscreen: show
	progress: -1
	stack_tag:
	id: 3
	actions: {}
	script: (null)
}
```
4. dunstrc settings
```bash
## FILE: $HOME/.config/dunst/dunstrc

icon_path = /usr/share/icons/Adwaita/16x16/status/:/usr/share/icons/Adwaita/16x16/devices/
```
5. check the icon-file existence
```
$ find /usr/share/icons/Adwaita/16x16/status/ -iname "*audio-volume-muted*"
/usr/share/icons/Adwaita/16x16/status/audio-volume-muted-symbolic.symbolic.png
```

**Comment by snowman** [comment]
![2019-12-09-074232_1920x1080_scrot](https://user-images.githubusercontent.com/16096559/70398547-960af980-1a57-11ea-9f0c-878d779bcb87.png)

**Comment by tsipinakis** [comment]
This is a side-effect of the fact that we don't do proper parsing of the icon theme cache but rely on directory searches.

However, for me (on Debian 10), `audio-volume-muted.png` also exists which makes this work as intended. Why doesn't that file exist on Arch?

```
find /usr/share/icons/Adwaita/16x16/ -iname '*audio-volume-muted*'
/usr/share/icons/Adwaita/16x16/status/audio-volume-muted-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/status/audio-volume-muted.png
```

**Comment by snowman** [comment]
Okay, I find out where the bugs come from.

I follow [Dunst - ArchWiki](https://wiki.archlinux.org/index.php/Dunst#Icon_sets), but the `audio-volume-muted` icon do not include in the path `/usr/share/icons/Adwaita/16x16/status/`.

```bash

➜ find /usr/share/icons/Adwaita/16x16 -iname '*audio-volume-muted*'
/usr/share/icons/Adwaita/16x16/legacy/audio-volume-muted.png
/usr/share/icons/Adwaita/16x16/status/audio-volume-muted-symbolic.symbolic.png
```

so in your `.dunstrc` config put those lines instead:
```bash
icon_path = /usr/share/icons/Adwaita/16x16/status/:/usr/share/icons/Adwaita/16x16/devices/:/usr/share/icons/Adwaita/16x16/legacy/
```
