### ISSUE TITLE
Icon won't display

### ISSUE THREAD

**Issue by indeedwatson** [dunst-project/dunst#677]
```
[cordless]
    appname = cordless
    format = "%i %s: %b"
    icon = /usr/share/icons/Paper/48x48/apps/discord.png
```

The app is [cordless](https://github.com/Bios-Marcel/cordless), a terminal client for Discord. Is the matching failing because it's a terminal program?

**Comment by tsipinakis** [comment]
>    icon = /usr/share/icons/Paper/48x48/apps/discord.png

Should be `new_icon`, one of the many pitfalls of our inconsistent rule naming :/ .

PS: %i is the icon path, not the icon itself. To show the icon set `icon_position` to `left` or `right`.

**Comment by indeedwatson** [comment]
> one of the many pitfalls of our inconsistent rule naming :/ 

:/ indeed! What's the logic?

Sadly still doesn't seem to work with `new_icon`.

**Comment by tsipinakis** [comment]
> What's the logic?

`icon` is for matching notifications that use a specific icon `new_icon` is to override it. #349 Is an attempt to make it more consistent but there hasn't been any progress on it, yet.

---

My own test case works, i.e.
On `1.4.1` with the default dunstrc with
```
[cordless]
    appname = cordless
    format = "%i %s: %b"
    new_icon = /usr/share/icons/Paper/48x48/apps/discord.png
```
Test notification sent with `notify-send -a cordless Test`.

Can you try the `notify-send` call yourself? If it still doesn't work please run dunst with `dunst -config {your config} -print` and post the output when cordless sends a notification.

**Comment by indeedwatson** [comment]
`dunst -config {your config} -print`

This was very helpful for debugging, turns out I had to use `summary = Cordless*` instead of `appname`. Thank you.
