### ISSUE TITLE
Wrong markup reference url in man page

### ISSUE THREAD

**Issue by Tonus1** [dunst-project/dunst#679]
In the man page, the url for the markup reference no longer exist.
The good one might be :
[https://developer.gnome.org/pygtk/stable/pango-markup-language.html](https://developer.gnome.org/pygtk/stable/pango-markup-language.html)

### Installation info

- Version: Dunst - A customizable and lightweight notification-daemon 1.4.1 (2019-07-03)
- Install type: compile from source (SlackBuild from [slackbuids.org](slackbuids.org))
- Distro and version: Slackware-current from jan. 7

**Comment by tsipinakis** [comment]
Has been fixed in master, the working link is https://developer.gnome.org/pango/stable/pango-Markup.html.
