### ISSUE TITLE
A specific app will not respect the timeout option

### ISSUE THREAD

**Issue by matcharles** [dunst-project/dunst#681]
Hello, I don't know how it works behind the scenes, but dunst will respect my timeout set at 10 seconds for all the apps I have except deepin screenshot. Do you think I should contact them or is there a way I could modify the dunstrc to add something specific for this app? Thanks a lot!

**Comment by tsipinakis** [comment]
Oh sorry for the delay, I missed this one.

It's possible that the application "cheats" the timeout by sending a `NotificationClose` message to forcefully close it regardless of what the server does.

To confirm this is indeed on Deepins side, could you post the output of `dbus-monitor` as a notification from deepin is sent and times outs?

If it's indeed the case sadly dunst doesn't have a way to tell it to ignore close signals from other programs - so it'll have to be fixed on Deepins' side if there isn't a proper reason for implementing timeouts like this.

**Comment by matcharles** [comment]
No worries at all, thanks for your time!

Actually I meant that the notification will not clear after 10s, rather it stays there until I click it manually. All other apps will clear after 10s.

Here is the output of the command. I clicked manually at the bold time.

`matt@KALEL ~ $ dbus-monitor
signal time=1579271382.950995 sender=org.freedesktop.DBus -> destination=:1.62 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.62"
signal time=1579271382.951014 sender=org.freedesktop.DBus -> destination=:1.62 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.62"
method call time=1579271392.304291 sender=:1.63 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1579271392.304306 sender=org.freedesktop.DBus -> destination=:1.63 serial=1 reply_serial=1
   string ":1.63"
signal time=1579271392.304316 sender=org.freedesktop.DBus -> destination=(null destination) serial=5 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.63"
   string ""
   string ":1.63"
signal time=1579271392.304330 sender=org.freedesktop.DBus -> destination=:1.63 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.63"
method call time=1579271392.304494 sender=:1.63 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RequestName
   string "com.deepin.Screenshot"
   uint32 4
signal time=1579271392.304505 sender=org.freedesktop.DBus -> destination=(null destination) serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "com.deepin.Screenshot"
   string ""
   string ":1.63"
signal time=1579271392.304518 sender=org.freedesktop.DBus -> destination=:1.63 serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string "com.deepin.Screenshot"
method return time=1579271392.304526 sender=org.freedesktop.DBus -> destination=:1.63 serial=4 reply_serial=2
   uint32 1
method call time=1579271392.336381 sender=:1.63 -> destination=org.freedesktop.DBus serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus',arg1=''"
method call time=1579271392.336426 sender=:1.63 -> destination=org.freedesktop.DBus serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameHasOwner
   string "org.a11y.Bus"
method return time=1579271392.336435 sender=org.freedesktop.DBus -> destination=:1.63 serial=5 reply_serial=4
   boolean true
method call time=1579271392.336509 sender=:1.63 -> destination=org.freedesktop.DBus serial=5 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus'"
method call time=1579271392.336563 sender=:1.63 -> destination=org.freedesktop.DBus serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.a11y.Bus"
method return time=1579271392.336570 sender=org.freedesktop.DBus -> destination=:1.63 serial=6 reply_serial=6
   string ":1.9"
method call time=1579271392.336659 sender=:1.63 -> destination=org.a11y.Bus serial=7 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "ScreenReaderEnabled"
method return time=1579271392.336861 sender=:1.9 -> destination=:1.63 serial=10 reply_serial=7
   variant       boolean false
method call time=1579271392.396825 sender=:1.63 -> destination=org.freedesktop.DBus serial=8 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='com.deepin.dde.ControlCenter'"
method call time=1579271392.396862 sender=:1.63 -> destination=org.freedesktop.DBus serial=9 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "com.deepin.dde.ControlCenter"
error time=1579271392.396871 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=9
   string "Could not get owner of name 'com.deepin.dde.ControlCenter': no such name"
method call time=1579271392.396972 sender=:1.63 -> destination=org.freedesktop.DBus serial=10 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='com.deepin.dde.ControlCenter',path='/com/deepin/dde/ControlCenter',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'"
method call time=1579271392.396992 sender=:1.63 -> destination=org.freedesktop.DBus serial=11 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='com.deepin.dde.ControlCenter'"
method call time=1579271392.397036 sender=:1.63 -> destination=org.freedesktop.DBus serial=12 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "com.deepin.dde.ControlCenter"
error time=1579271392.397045 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=12
   string "Could not get owner of name 'com.deepin.dde.ControlCenter': no such name"
method call time=1579271392.397125 sender=:1.63 -> destination=org.freedesktop.DBus serial=13 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method call time=1579271392.397177 sender=:1.63 -> destination=org.freedesktop.DBus serial=14 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Notifications"
error time=1579271392.397185 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=14
   string "Could not get owner of name 'org.freedesktop.Notifications': no such name"
method call time=1579271392.397247 sender=:1.63 -> destination=org.freedesktop.DBus serial=15 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.Notifications',path='/org/freedesktop/Notifications',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'"
method call time=1579271392.397266 sender=:1.63 -> destination=org.freedesktop.DBus serial=16 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method call time=1579271392.397295 sender=:1.63 -> destination=org.freedesktop.DBus serial=17 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Notifications"
error time=1579271392.397306 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=17
   string "Could not get owner of name 'org.freedesktop.Notifications': no such name"
signal time=1579271392.397427 sender=org.freedesktop.DBus -> destination=org.freedesktop.systemd1 serial=27 path=/org/freedesktop/DBus; interface=org.freedesktop.systemd1.Activator; member=ActivationRequest
   string "dunst.service"
method call time=1579271392.397435 sender=:1.63 -> destination=org.freedesktop.Notifications serial=18 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=CloseNotification
   uint32 0
method call time=1579271392.397454 sender=:1.63 -> destination=org.freedesktop.DBus serial=19 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='com.deepin.daemon.Zone'"
method call time=1579271392.397485 sender=:1.63 -> destination=org.freedesktop.DBus serial=20 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "com.deepin.daemon.Zone"
error time=1579271392.397493 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=20
   string "Could not get owner of name 'com.deepin.daemon.Zone': no such name"
method call time=1579271392.397569 sender=:1.63 -> destination=org.freedesktop.DBus serial=21 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='com.deepin.daemon.Zone',path='/com/deepin/daemon/Zone',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'"
method call time=1579271392.397600 sender=:1.63 -> destination=org.freedesktop.DBus serial=22 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='com.deepin.daemon.Zone'"
method call time=1579271392.397635 sender=:1.63 -> destination=org.freedesktop.DBus serial=23 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "com.deepin.daemon.Zone"
error time=1579271392.397644 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=23
   string "Could not get owner of name 'com.deepin.daemon.Zone': no such name"
method call time=1579271392.397918 sender=:1.0 -> destination=org.freedesktop.DBus serial=14 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method return time=1579271392.397926 sender=org.freedesktop.DBus -> destination=:1.0 serial=28 reply_serial=14
method call time=1579271392.397947 sender=:1.0 -> destination=org.freedesktop.DBus serial=15 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Notifications"
error time=1579271392.397955 sender=org.freedesktop.DBus -> destination=:1.0 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=15
   string "Could not get owner of name 'org.freedesktop.Notifications': no such name"
method call time=1579271392.407830 sender=:1.64 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1579271392.407850 sender=org.freedesktop.DBus -> destination=:1.64 serial=1 reply_serial=1
   string ":1.64"
signal time=1579271392.407867 sender=org.freedesktop.DBus -> destination=(null destination) serial=7 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.64"
   string ""
   string ":1.64"
signal time=1579271392.407895 sender=org.freedesktop.DBus -> destination=:1.64 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.64"
method call time=1579271392.410305 sender=:1.64 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RequestName
   string "org.freedesktop.Notifications"
   uint32 0
signal time=1579271392.410324 sender=org.freedesktop.DBus -> destination=(null destination) serial=30 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.Notifications"
   string ""
   string ":1.64"
signal time=1579271392.410343 sender=org.freedesktop.DBus -> destination=:1.64 serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string "org.freedesktop.Notifications"
method return time=1579271392.410354 sender=org.freedesktop.DBus -> destination=:1.64 serial=4 reply_serial=2
   uint32 1
method return time=1579271392.410582 sender=:1.64 -> destination=:1.63 serial=3 reply_serial=18
method call time=1579271397.363993 sender=:1.63 -> destination=com.deepin.dde.Notification serial=24 path=/com/deepin/dde/Notification; interface=org.freedesktop.DBus.Introspectable; member=Introspect
error time=1579271397.364012 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=24
   string "The name com.deepin.dde.Notification was not provided by any .service files"
method call time=1579271397.364096 sender=:1.63 -> destination=org.freedesktop.DBus serial=25 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='com.deepin.dde.Notification'"
method call time=1579271397.364157 sender=:1.63 -> destination=org.freedesktop.DBus serial=26 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "com.deepin.dde.Notification"
error time=1579271397.364171 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=26
   string "Could not get owner of name 'com.deepin.dde.Notification': no such name"
method call time=1579271397.364443 sender=:1.63 -> destination=org.freedesktop.Notifications serial=27 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Deepin Screenshot"
   uint32 0
   string "deepin-screenshot"
   string ""
   string "Picture has been saved to /home/matt/downloads/DeepinScreenshot_select-area_20200117092957.png"
   array [
   ]
   array [
   ]
   int32 0
method call time=1579271397.364502 sender=:1.63 -> destination=org.freedesktop.DBus serial=28 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='com.deepin.dde.Notification'"
method call time=1579271397.364570 sender=:1.63 -> destination=org.freedesktop.DBus serial=29 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.DBus'"
error time=1579271397.364590 sender=org.freedesktop.DBus -> destination=:1.63 error_name=org.freedesktop.DBus.Error.MatchRuleNotFound reply_serial=29
   string "The given match rule wasn't found and can't be removed"
method return time=1579271397.367472 sender=:1.64 -> destination=:1.63 serial=4 reply_serial=27
   uint32 2
method call time=1579271397.373558 sender=:1.63 -> destination=org.freedesktop.DBus serial=30 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus',arg1=''"
method call time=1579271397.373587 sender=:1.63 -> destination=org.freedesktop.DBus serial=31 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus'"
signal time=1579271397.373824 sender=org.freedesktop.DBus -> destination=:1.63 serial=8 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string "com.deepin.Screenshot"
signal time=1579271397.373844 sender=org.freedesktop.DBus -> destination=(null destination) serial=9 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "com.deepin.Screenshot"
   string ":1.63"
   string ""
signal time=1579271397.373893 sender=org.freedesktop.DBus -> destination=:1.63 serial=10 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.63"
signal time=1579271397.373904 sender=org.freedesktop.DBus -> destination=(null destination) serial=11 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.63"
   string ":1.63"
   string ""
**signal time=1579271413.067337** sender=:1.64 -> destination=:1.63 serial=5 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 2
   uint32 2
error time=1579271413.067357 sender=org.freedesktop.DBus -> destination=:1.64 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=5
   string "The name :1.63 was not provided by any .service files"
^C`

**Comment by tsipinakis** [comment]
(I fixed the formatting of your last comment)

> Actually I meant that the notification will not clear after 10s, rather it stays there until I click it manually. All other apps will clear after 10s.

Oh! That's a much different issue then, and the log you posted it confirms it. Deeping specifically asks for the notification to not time out. In which case you can set a rule to override it by adding this to the end of the `dunstrc`:
```
[deepin-override-timeout]
appname = "Deepin Screensot"
timeout = 10
```
I'm not familiar with Deepin but you may need to use `appname = "Deepin*"` if it uses different appnames.

**Comment by matcharles** [comment]
It works!!!! Thanks so much, this had been bothering for such a long time. You're the best!!
