### ISSUE TITLE
BUG: CANT OPEN DUNST

### ISSUE THREAD

**Issue by darkmachineweb** [dunst-project/dunst#685]
![image](https://user-images.githubusercontent.com/60662297/73938438-5bb2c100-490f-11ea-8d49-f8cc5190da09.png)
CRITICAL: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'gnome-shell' with PID '21141'.

**Comment by tsipinakis** [comment]
This message is telling you that another notification daemon is running and has control of the notification address, it's not possible to run 2 notification servers at the same time.

In this case it looks like you're using GNOME which has its own notification server, if you want to use dunst you'll have to somehow disable that. I'm not familiar with GNOME so I'm not sure if it's possible

**Comment by darkmachineweb** [comment]
@tsipinakis  thanks
