### ISSUE TITLE
Markup not having any effect

### ISSUE THREAD

**Issue by markmarsella** [dunst-project/dunst#686]
Using markup in the format config or in the body (Tried with markup set to full/strip/no) doesn't change the font in the notification (although tags are gone).  

Tried various fonts but no joy.

e.g.

`dunstify "Summary" "<b>Expect bold text</b> <i>Expect italics here</i>"`

Result is 
![2020-02-10-23:51:25](https://user-images.githubusercontent.com/51721976/74201094-9c3c7280-4c60-11ea-840d-92f58c58dfdf.png)

### Installation info

- Version: 1.4.1 
- Install type: Package
- Distro and version: Arch Linux
- Window Manager: bspwm

**Comment by kushraj** [comment]
this test command is working perfectly in my system ( Output is as expected )
might be a problem in your dunst config I guess,can you post it

**Comment by markmarsella** [comment]
Sorry I've moved to Gnome, thanks though
