### ISSUE TITLE
Is it possible to save recent notification into the file?

### ISSUE THREAD

**Issue by pwittchen** [dunst-project/dunst#688]
Hi,

I would like to save recent notification and information, which program send a notification into the file.
Is it possible? How can I do it?

Regards,
Piotr

**Comment by tsipinakis** [comment]
What would be the usecase for that?

There is no 'proper' way to do it via the config. But you can hack your way around that by telling dunst to print all notifications (`dunst -print`) and redirect that to a file.

**Comment by pwittchen** [comment]
Ok, I no longer need this. :-)

I'm using Spotify for listening to the music and Spotify sends notification whenever song is changed. I wanted to log information about the last song and display it in the i3 WM status bar.

I solved it via the following config in `dunstrc` file:

```
[spotify]
    appname = Spotify
    urgency = normal
    script  = ~/.scripts/spotify_log.sh
```

`spotify_log.sh` is my custom script, which reads information about the song.
Whenever Spotify sends a notification, I save information about the current song to the file and that's what I wanted.
