### ISSUE TITLE
Allow for multiple actions per mouse event

### ISSUE THREAD

**Issue by mkrasnitski** [dunst-project/dunst#690]
I'd like to request a feature to allow for users to specify a list of actions to perform for each mouse event (left, middle, and right click). To fit with INI formatting, it would be a comma-separated list, and the actions would be executed in-order left to right as listed. 

My use case for this is that I want my left click to perform an action/bring up the context menu, and then also close the current notification. As I have it configured right now, left clicking on a notification performs the action and then leaves it on the screen, which to me feels unnatural.

**Comment by tsipinakis** [comment]
I agree this would be useful, I'm not sure when I'll get around to this, but if someone wants to work on it I'm open to PRs.

**Comment by mkrasnitski** [comment]
I'm planning on starting work on a PR for this, and was wondering what the best way to run the test suite provided in `test` would be? Is the best way simply to compile each test and run it individually?

**Comment by tsipinakis** [comment]
You can run the test suite with `make test && ./test/test`

**Comment by biopsin** [comment]
This is interesting as I don't use statusbar or dock. 
Toying with the idea using dunst as a dock for iconified windows is very appealing.
Testing scrot to dump a 128x128 thumbnail with wmctrl to iconify/restore window.
