### ISSUE TITLE
request: enable per-notification font configuration

### ISSUE THREAD

**Issue by dicktyr** [dunst-project/dunst#691]
sometimes one needs to change the font for a given notification
or ideally for part(s) of a given notification
in particular to support monospace when necessary

this could be done using hints to change font for the whole notification
or better by supporting the `tt` and `span` tags in full Pango markup

**Comment by tsipinakis** [comment]
We pass the markup directly to pango to parse, so this should be achievable with `<span font_desc="new font">`

Keep in mind the first part of the notification (summary) doesn't support markup due to limitations in the notification spec.

**Comment by dicktyr** [comment]
my apologies
documentation suggested a limited subset
and I did indeed neglect to test the body (rather than summary)
thank you
