### ISSUE TITLE
Don't start notification timeout until mouse/keyboard is moved/pressed?

### ISSUE THREAD

**Issue by levihb** [dunst-project/dunst#696]
This is a feature request to not start the timeout until the mouse or keyboard are next activated. Sometimes I go out for half an hour, or just nip out to the bathroom, and when I come back have missed notifications. Having the notifications stay until I next input something would be great, as it'd stay up when I'm not here, but disappear when I am.

**Comment by tsipinakis** [comment]
Have you looked into the [`idle_threshold`](https://github.com/dunst-project/dunst/blob/master/dunstrc#L80-L85) setting?

**Comment by levihb** [comment]
@tsipinakis oh wow sorry, I looked all over but must have read/skipped over it somehow. That's exactly what I want, sorry for wasting your time.

I blame it on the self-isolation, losing my mind.
