### ISSUE TITLE
dunst is running but no notification 

### ISSUE THREAD

**Issue by ahmadsiddeeq0** [dunst-project/dunst#698]
dunst is running but no notification what so ever it only send notification manualy with notify-send "notificatin test" 
???

### Installation info

- Version:  1.3.2
- Install type: package
- Distro and version: debian 10 (buster)

**Comment by tsipinakis** [comment]
Uh, can you be more specific? What's the problem exactly? If notify-send is working it means dunst is running and should be able receive notifications from any program that can send them.

**Comment by ahmadsiddeeq0** [comment]
@tsipinakis yes notify-send is working and dunst is working but i dont receive any notifications

**Comment by bebehei** [comment]
Ok, what does `systemctl --user status dunst` tell you?

**Comment by ahmadsiddeeq0** [comment]
it is active and runung but no notificaion comes to me

**Comment by bebehei** [comment]
Ok, well. This doesn't bring anyone further. Please paste the full output.

For the future: If requested, do this always, please don't just paraphrase the output. There might be more information in such command requests. @tsipinakis and me maintained this program for the last two years (@tsipinakis even longer) and for this time, every changed line either got reviewed or was written by one of us. If there are bugs (I bet there are :wink: ), we're the ones who will kill those probably in the fastest manner. To do this, we need your help to help you. Please provide exact information. Otherwise we can't help you so easily (or maybe at all).

In the status output there is more information than "it's up and running". So, please paste it.

**Comment by ahmadsiddeeq0** [comment]
$systemctl --user status dunst
● dunst.service - Dunst notification daemon
   Loaded: loaded (/usr/lib/systemd/user/dunst.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-03-30 16:04:33 +03; 9s ago
     Docs: man:dunst(1)
 Main PID: 32570 (dunst)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dunst.service
           └─32570 /usr/bin/dunst

**Comment by bebehei** [comment]
>    Active: active (running) since Mon 2020-03-30 16:04:33 +03; 9s ago

Have you just started your session or is it running for a longer time?

Ok and what does the following `dbus-send` call tell you?
```
 dbus-send --session --dest=org.freedesktop.Notifications --print-reply /org/freedesktop/Notifications org.freedesktop.Notifications.GetServerInformation
```

**Comment by tsipinakis** [comment]
I guess the basic question here is: Given that notify-send works, what program are you expecting a notification from that isn't arriving?

**Comment by ahmadsiddeeq0** [comment]
@tsipinakis surf, nnn, nano , and system over all (battery low or full , cpu is hot .. etc)

**Comment by ahmadsiddeeq0** [comment]
@bebehei 
$dbus-send --session --dest=org.freedesktop.Notifications --print-reply /org/freedesktop/Notifications org.freedesktop.Notifications.GetServerInformation
method return time=1585582491.551982 sender=:1.300 -> destination=:1.352 serial=58 reply_serial=2
   string "dunst"
   string "knopwob"
   string "1.3.2 (2018-05-06)"
   string "1.2"

**Comment by tsipinakis** [comment]
> surf, nnn, nano , and system over all (battery low or full , cpu is hot .. etc)

Um, none of these programs send notification by default. Dunst is just the server, i.e. the part the displays the notifications. We can't show one for something we have no knowledge happened.

For system events you can write a script that checks the battery status, cpu etc and call it periodically, or even better someone must have already written one somewhere if you look around github.

For the rest, it's up to them to add support for notifications if they want.

**Comment by ahmadsiddeeq0** [comment]
@tsipinakis 
ok so which program is support by default ?

**Comment by tsipinakis** [comment]
>  ok so which program is supported by default ?

There is no 'supported by default' or a list of programs. Notifications are based on a specific specification, any program can choose to use it to send one.
The biggest example is browsers which allow websites to send desktop notifications, you can test it [here](https://www.bennish.net/web-notifications.html). Any decent web messaging/email service should support desktop notifications.

**Comment by ahmadsiddeeq0** [comment]
when i press show :


Notification #1 queued for display
Notification #1 errored

**Comment by tsipinakis** [comment]
Did you click `Authorize` first? You need to give permissions to send notifications.

**Comment by ahmadsiddeeq0** [comment]
when i give the permission it uses chroms's default notification

**Comment by tsipinakis** [comment]
Chrome has been a bit tricky, take a look at #633, maybe that's the issue?

**Comment by ahmadsiddeeq0** [comment]
oh yesterday night i was uploading my website via ftp using filezilla when it finishes upload dunset send me a notification !!!! 
it only worked with filezilla but it worked 

maybe my programs seems not to support dunset.

thank you for helping 

and sorry for taking your time
