### ISSUE TITLE
Allow toggle paused status via dunstctl

### ISSUE THREAD

**Issue by mrossinek** [dunst-project/dunst#709]
### Feature Idea

I just started taking a look at `dunstctl` from #651 since I have been waiting for the PR to be merged.
I would like to be able to simply toggle the paused state of dunst with a single command. Since I think this would also be useful to other users I think it would be an easy addition to the `dunstctl` shell script.

If you like, I am happy to implement this myself and open a PR. If so, which approach would you like:
- add another argument option to `set-running` e.g. `toggle`
- set this as the default when calling `dunstctl set-running` without additional arguments
- add a new command entirely

If you do not agree that this should be integrated into `dunstctl` directly I will opt to write a wrapper myself, I just wanted to put this out there.

**Comment by tsipinakis** [comment]
I agree this would be useful (and been requested before as an addition to the `DUNST_COMMAND_...` hacks if I remember right). 

> If you like, I am happy to implement this myself and open a PR.

If you have the time to work on it, please do!

> If so, which approach would you like:

I'd prefer `dunstctl set-running toggle`, it's best to be explicit here in my opinion.

**Comment by mrossinek** [comment]
@tsipinakis Okay will do. I will fix #710 too, while I'm at it.

**Comment by tsipinakis** [comment]
Thank you! If you have any questions or get stuck somewhere feel free to ask.
