### ISSUE TITLE
Different notification sounds for different programs.

### ISSUE THREAD

**Issue by chhajedji** [dunst-project/dunst#714]
Is there a way to set different attributes for different types of notifications? Attributes like timeout, default priority, notification sound for programs having same `instance`/`class`/`name` or something.

### Installation info

- Version: `v1.4.1-8-g9e29406`
- Install type: `apt install`
- Distro and version: ` Ubuntu 20.04`

If a similar thread exists please refer it here. 

Thanks in advance.

**Comment by tsipinakis** [comment]
There are rules, see [here](https://github.com/dunst-project/dunst/blob/master/docs/dunst.pod#rules) and [here](https://github.com/dunst-project/dunst/blob/master/dunstrc#L310).

However, dunst has no knowledge of the program that sent the notification so it cannot match on window attributes, the only option is to match with what data is sent with the notification.

**Comment by tsipinakis** [comment]
Dunst will print all attributes of a notification if ran with `dunst -print`, can be useful for debugging rules.

**Comment by chhajedji** [comment]
Oh thanks, This is something useful for me. One more query is I don't see any direct approach to change notification sound (or mute) for a specific `rule`. So is there any hack or something to do so?

**Comment by tsipinakis** [comment]
I assume you've used the `script` option to set the notification sound, if so you can change the script from a rule. And apparently this isn't documented in the manpage!

**Comment by chhajedji** [comment]
Okay, that helped.

Thanks for your quick support. :)
