### ISSUE TITLE
can't send notifications when run as a cronjob

### ISSUE THREAD

**Issue by sleeperzjf** [dunst-project/dunst#718]
I have writed a shell scropt with `notify-send 'something'` in it and if I run it manually, I get notification.
But if I run it scheduled as  a cronjob, it doesn't send noifications anymore.
And all my other notifications work flawlessly. 
I redirect the output of the shell script to a text file when run as a cronjob, it doesn't report any bug.
So, why?

**Comment by tsipinakis** [comment]
`notify-send` needs the session bus address to send the notification, a similar question is answered in the [FAQ about sudo](https://dunst-project.org/faq/#sending-notifications-from-another-user-root).

Long story short, you need something like this at the top of the crontab:
```crontab
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
```

**Comment by sleeperzjf** [comment]
That works! Thank you!!
