### ISSUE TITLE
Separator-color won't change

### ISSUE THREAD

**Issue by vinicius507** [dunst-project/dunst#721]
I saw that in the last week transparency support was added to all color hexes and then built dunst from source. But then, when I try to change separator color, even without while using only #RGB and not #RGBA it won't change.

**Comment by tsipinakis** [comment]
Hi! Can you provide an example config (full dunstrc preferred) reproducing this?
From what I observe it appears it's working correctly.
I tried
`separator_color = "#ff0000"` -> red separator
`separator_color = "#00ff00"` -> blue separator

Just to be sure: You are killing/restarting dunst between config changes, right?

**Comment by vinicius507** [comment]
Yes, I'm killing dunst between config changes. I found the problem, I was forgetting to add " around the color hex. Thanks for the attention, though.

But then I found that picom shadows are rendered as if all notifications are one entity(what I understood they are), is there any way to render each notification in it's own "window"?

**Comment by tsipinakis** [comment]
Whoops, sorry this one slipped through.

> But then I found that picom shadows are rendered as if all notifications are one entity(what I understood they are), is there any way to render each notification in it's own "window"?

Not currently, there is multi-window handling internally but no-ones implemented separate window per notification yet.

I'll close this issue as it's resolved, but feel free to open a new one about having multiple windows per notification. I was under the impression there was one already but I can't find it.

**Comment by vinicius507** [comment]
Sure will do, thank you for your attention!
