### ISSUE TITLE
Separate Window per Notification

### ISSUE THREAD

**Issue by vinicius507** [dunst-project/dunst#723]
I use picom as a window as a window compositor. When multiple notifications appear it considers all of them as a single window and renders shadows for all of them together, as if they were a single window(which from other issues I understood it's because externally they essentially are).

It'd be great if, by default or by choice, we'd be able to have separate windows for notifications.

Thanks for the attention.

**Comment by mortezadadgar** [comment]
yeah it would be great!

**Comment by flipflop133** [comment]
Most awaited feature!

**Comment by catthou** [comment]
Any word on this?

**Comment by fwSmit** [comment]
It's gonna take a while for it to be implemented, but I'm planning to add it. It's not very easy to add and there's just a bunch of other things I'm adding first (see the milestones).

**Comment by Delected** [comment]
Quick search brought me here. It is unfortunate that this feature is not yet available, but I'm very glad that it's being considered!

**Comment by NotMurPh** [comment]
Any update's on this 🫠 ?

**Comment by mortezadadgar** [comment]
it's already merged with https://github.com/dunst-project/dunst/pull/1053, this issue can be closed

**Comment by fwsmit** [comment]
That PR is implemented with a single window and using transparent colour for the gaps. This means that clicking in the blank space does not go to the window below it. Other things like blurring might also not work as expected. So this issue still stands

**Comment by bynect** [comment]
Same as #1018
