### ISSUE TITLE
dunst not showing notifications consistently

### ISSUE THREAD

**Issue by j1nxie** [dunst-project/dunst#725]
dunst doesn't seem to send notifications consistently. I have Discord and Caprine (a Facebook Messenger Electron app) in my background, and sometimes they send notifications with their associated notification sounds, sometimes they will not, even if I am not focused on that window. Other notifications such as Spotify's seem to show up normally whenever there's a song change though.

### Installation info

- Version: `1.4.1`
- Install type: `package`
- Distro and version: `Arch Linux x86_64`

**Comment by tsipinakis** [comment]
Dunst does not have support for playing notification sounds natively (unless you added a script for that yourself), the sounds are being played from the app directly. From this, my immediate assumption is that the other programs aren't sending the notifications at all.

To verify please post the output of `dbus-monitor path=/org/freedesktop/Notifications` as a notification that you expected to be sent isn't. This will print out all commands sent to the notification bus.

**Comment by j1nxie** [comment]
After running `dbus-monitor path=/org/freedesktop/Notifications` it seemed like the apps themselves are inconsistent in their notifications, as somehow Discord didn't send me notifications quite a lot of the times.

A bit of investigation from my side made me realize that apparently changing desktops in `bspwm` (I have Discord on another desktop separate from my other desktops) doesn't unfocus the application,  which makes it not show whatever message notifications of the channel that I am on, since it still thinks I'm focused on its window.
