### ISSUE TITLE
Notifications with transparent RGBA backgrounds show previous notification when replaced

### ISSUE THREAD

**Issue by epeery** [dunst-project/dunst#728]
### Notification with background color #ffffff50
![image1](https://user-images.githubusercontent.com/15280524/85907410-5d5a2400-b7df-11ea-974c-1aa620997211.png)
### Notification after being replaced by notification with same ID
![image2](https://user-images.githubusercontent.com/15280524/85907419-621ed800-b7df-11ea-87be-89ebd13fbb01.png)

As a temporary workaround I have made my scripts manually remove the previous notification before creating a new one but this doesn't work for applications like Spotify.

**Comment by tsipinakis** [comment]
Hi, thanks for the report. As I said in another issue I'm unavailable these days so I'll look into this in depth in a week or two.

I have a hunch that this is related to ed3db5048cad7f6e26b9eb6e619a53c6348dbcc4, I reverted that as it caused some flickering on redraws but it may have caused this as a side effect.

Quick test: Can you build 7735c9a4f60ef8cd645a39a98557c8950d0fa9ec (its parent) and try to reproduce it? If it works, please also try ed3db5048cad7f6e26b9eb6e619a53c6348dbcc4 to verify that it is indeed the broken commit.

**Comment by epeery** [comment]
Good thinking! The issue goes away with 7735c9a. I'll use this commit for now. Thanks!

**Comment by epeery** [comment]
Almost forgot to mention, I built ed3db50 and that is indeed the commit that caused the issue.

**Comment by progandy** [comment]
Instead of XClearWindow, maybe try setting either ```CAIRO_OPERATOR_SOURCE```, or ```CAIRO_OPERATOR_CLEAR``` with [cairo_set_operator](https://www.cairographics.org/manual/cairo-cairo-t.html#cairo_set_operator)

**Comment by tsipinakis** [comment]
Should be fixed now @epeery. Apparently `XClearWindow` works without the `XFlush` calls. I checked the docs and it doesn't seem to prod about flushing after using that function, so it should work in every case now.

I'm not sure why I removed both calls in the first place, this should have been my first course of action, but either way, it's fixed.

**Comment by epeery** [comment]
Glad to hear it. Thanks for being so on top of this.
