### ISSUE TITLE
Context menu not selectable

### ISSUE THREAD

**Issue by chensun-hep** [dunst-project/dunst#737]
I'm able to invoke the context menu by Ctrl-Shift-period. However, I'm not able to select any options there. For example, if I send a notification through 

`dunstify --action="replyAction,reply" --action="closeAction,close" "Message received"`

I can see the two options in the context menu, but I cannot select either of them. In the end my dunstify gets 1 due to timeout. I'm not sure if there's something I'm missing. I'm running EXWM if that's relevant. 

### Installation info

- Version: ` Dunst - A customizable and lightweight notification-daemon v1.4.1-118-g0de8610`
- Install type: `manually`
- Distro and version: ` Ubuntu 20.04`

**Comment by tsipinakis** [comment]
If you're using the default menu (`dmenu`) then it doesn't support using the mouse, use the keyboard arrows and enter to select.
You can change the program used to display the menu in the config.

**Comment by chensun-hep** [comment]
indeed i'm using dmenu. i understand that it doesn't support mouse click yet but it seems not to respond to my keyboard arrows either. Any suggestions where I should start to debug? Thanks.

**Comment by tsipinakis** [comment]
Huh, that's weird it works on my end. Does simply enter to select the first action work?

**Comment by chensun-hep** [comment]
no it doesn't.  it seems pressing any key leads dmenu being closed.

**Comment by tsipinakis** [comment]
Try running dmenu without dunst: `echo -e "option1\noption2" | dmenu`, see if that works.

If not, I'd raise an issue with the dmenu devs, I'm not sure how to debug this.

**Comment by chensun-hep** [comment]
Indeed, that gives me segfault. I'll open an issue there.

**Comment by tsipinakis** [comment]
I'll close this then as it's not dunst related - please do update this if you find a solution though, for future readers.
