### ISSUE TITLE
Issue with rgba

### ISSUE THREAD

**Issue by dj-bauer** [dunst-project/dunst#739]
I am currently trying to get rgba working, but it does only show a mostly vibrant color.
For example a background of  ```#ffffff50``` gives me a vibrant yellow.

I use the latest git commit (c01f81b)
I run Arch linux with dwm and picom active as transparency manager.
What am I doing wrong?

**Comment by tsipinakis** [comment]
Can you please be more specific? Doing what you mentioned above works on my side (Debian unstable, picom).

The following would help:
* A full dunstrc example
* Output of `dbus-monitor path=/org/freedesktop/Notifications` as the notification is sent through
* A screenshot of the problem.

**Comment by dj-bauer** [comment]
It just magically started working. Propably some wrong environment variables. I cannot reproduce the error as well.

**Comment by tsipinakis** [comment]
I just realized `#ffff50` (the color you used minus the first 2 digits) is a vibrant yellow, so you most likely used an older version of dunst that didn't support transparency.

**Comment by MaximeWack** [comment]
I seems like commit c01f81b breaks transparency when the border width is 0 (see #750)
