### ISSUE TITLE
Dunst in a virtual machine

### ISSUE THREAD

**Issue by sleeperzjf** [dunst-project/dunst#740]
I installed `manjaro` in `VMware`, how should I use `dunst`?
Right now when I run `notify-send "something"`, nothing happened.

**Comment by tsipinakis** [comment]
Have you tried running `dunst` manually? Is dbus running?

**Comment by sleeperzjf** [comment]
If I run `dunst` manually, it works.

**Comment by sleeperzjf** [comment]
Oh, maybe it's my `dwm` problem, I use `dwm` to start `dunst`, but it doesn't work.
After I put it into `.xprofile`, it works fine.
But I also use `dwm` to set my wallpaper, and that works fine, weird.
