### ISSUE TITLE
IOS style notifications

### ISSUE THREAD

**Issue by Iss-in** [dunst-project/dunst#741]
Hi, It will be a good addition from aesthetic viewpoint to have an ios like design for notifications.

```

Old Design

┌───────────────────────────────────┐ 
| - - - - -    - - - - - - - - - - - -  
| - Image -    - - - - content - - - - 
| - - - - -    - - - - - - - - - - - - 
|
|                         -time-passed-
└───────────────────────────────────┘ 

New Design

┌──────────────────────────────────────┐ 
| --app-icon-app-name--      -time-passed-   
|                                        
| - - - - -    - - - - - - - - - - - -    
| - Image -    - - - - content - - - - 
| - - - - -    - - - - - - - - - - - - 
└──────────────────────────────────────┘
```
I want to implement this, but I cant figure out how to get information(name) about the app/process sending the notification for drawing the app-icon .
can you suggest me a way to implement this

**Comment by tsipinakis** [comment]
That seems like a good idea but I'm having trouble seeing how this can be implemented without adding a lot of code complexity (at least, bar a refactor on the drawing code).

Some ideas on ow to find the icon:
* Search in `icon_path` for the appname
* Somehow read/parse the `.desktop` file that's sent along with the notification (`desktop-entry` hint) and look for the icon field.

**Comment by kushraj** [comment]
So after a bit of playing around with cairo, I was able to produce this [
![2020-08-03_10-07-23](https://user-images.githubusercontent.com/36916613/89146512-91103280-d571-11ea-919f-486add86fc65.png)
](url) 
I hope this should be good enough, albeit code part is still a mess :P 
There may or may not be a app info provided with every notification , so in the later case should I fall back to old style or add a default icon/name for every such instance ?

**Comment by tsipinakis** [comment]
>  I hope this should be good enough, albeit code part is still a mess :P

That's my big worry about merging this. Plus the drawing code is entirely untested as it's impossible to write tests for in the current scheme, so testing that existing stuff doesn't break should be a priority.

>  There may or may not be an app info provided with every notification , so in the later case should I fall back to old style or add a default icon/name for every such instance ?

My take here would be to fall back to a default value, consistency is best in these cases in my opinion (plus, it would nudge users to report bugs in applications that don't provide an icon).

**Comment by kushraj** [comment]
so I am pretty much done with it, last thing I am unable to decide is the foreground color of titlebar ( app-name + elapsed time )
Should I default them both to same color of either of body or summary or add another color setting in dunstrc for this titlebar ?
And should I add an optional background color for it as well ?

**Comment by tsipinakis** [comment]
> Should I default them both to same color of either of body or summary or add another color setting in dunstrc for this titlebar
> And should I add an optional background color for it as well which could fall back to original bg color if not defined ?

Best to default to the default text color, and existing background IMO, lets not add extra settings until they are requested/needed.

**Comment by kushraj** [comment]
cool, That should be all, Including the default color setting, I'm also keeping the app icon size, height and font size of titlebar constant regardless of config options . Is it alright ?

**Comment by tsipinakis** [comment]
That's fine, these details can always be changed later.

**Comment by ProgrammingLife** [comment]
Had that already implemented in dunst?

**Comment by fwSmit** [comment]
I do remember seeing a PR that wasn't merged, but I can't find it now. It hasn't been implemented in dunst yet

**Comment by bynect** [comment]
Was this implemented in the end? Either way I would say that this can be closed as there are more options to customize the layout now

**Comment by bynect** [comment]
> I don't think it has been implemented. But I do think it's nice to think about if the default layout of Dunst can be improved

Well, that's for sure. I was thinking of making a meta issue with all the aesthetic related changes summarized

**Comment by fwsmit** [comment]
Sure, I'll close this issue then if there are no immediate plans to implement it.
