### ISSUE TITLE
[i3-gaps] Transparency issue with rounded corners?

### ISSUE THREAD

**Issue by aendeavor** [dunst-project/dunst#746]
### Description

When RGBA colors are defined for backgrounds and rounded corners are enabled, rounded corners appear, though the base color (without transparency, i.e. RGB) fills the frame at the corner and makes the frame square.

### Installation info

- Version `1.5.0 (2020-07-23)`
- Install type `manually`
- Distro and version `Ubuntu 20.04 LTS`
- Further information: I am using `i3-gaps` _without_ a desktop environment.

### Workaround

If you are using picom (version `vgit-44b49`, [this fork](https://github.com/ibhagwan/picom)), you can enable `corner-radius = X;` to "fix" this.

**Comment by tsipinakis** [comment]
I can't seem to reproduce what you're describing, perhaps I misunderstood something in the reproduction steps. Could you post your dunstrc and a screenshot to help debugging?

**Comment by aendeavor** [comment]
It may be my mistake, or I may have read something wrong.

My dunstrc:
```
[global]
  geometry = "300+1600+48"
  frame_color = "#FFFFFF00"
  corner_radius = 70
  shrink = false
  follow = none
  monitor = 0
  
  format = "%s\n%b" # or "%s\n%b"
  font = Roboto Medium 11
  padding = 30
  line_height = 5
  alignment = center
  word_wrap = true
  ignore_newline = false
  
  transparency = 0
  separator_color = "#FFFFFF00"
  
  idle_threshold = 0
  show_age_threshold = -1
  
  sticky_history = false
  allow_markup = true
  markup = full
  indicate_hidden = false
  sort = yes
  show_indicators = true
  stack_duplicates = false
  hide_duplicates_count = true
  startup_notification = false
  
  browser = "/usr/bin/firefox"

[urgency_low]
    background = "#FFFFFF00"
    foreground = "#FFFFFF"
    timeout = 5

[urgency_normal]
    background = "#FFFFFF00"
    foreground = "#FFFFFF"
    timeout = 7

[urgency_critical]
    background = "#FFFFFF00"
    foreground = "#FFFFFF"
    timeout = 9
```

When I set the `frame_color` option, I can't seem to get any rounded corners (strangely enough), and when I comment it out, the rounded corners are there, but the problem I mentioned arises.

It may have to do with my setup as well?

**Comment by tsipinakis** [comment]
Are you sure this is the correct dunstrc? All the background colors in this config have a 0 in the alpha field i.e. fully transparent/invisible background. It doesn't appear to match your screenshot.

**Comment by aendeavor** [comment]
A bit misleading, I admit, but this is the correct `dunstrc`. As I mentioned, when having `frame_color` set to any value, the frame has **no** rounded corners, but when disabling it, you get what you see in the picture. So what I am using right now is (notice the comment for `frame_color`):

``` CONF
[global]
  geometry = "300+1600+48"
  #frame_color = "#FFFFFF00"
  corner_radius = 7
  shrink = false
  ...
```

Now, rounded corners work. I use picom to "force" the cutting and rounding of the corners - I therefore would not even need the rounded corners feature of dunst.

**Comment by aendeavor** [comment]
I solved the issue. The reason is most likely the compositor, and not a bug in dunst, where `_NET_WM_WINDOW_OPACITY` is set twice during the application opacity rules. It works like a charm without a compositor.

Therefore, it's perfectly fine to use the compositor in the end to adjust the border radius, like I mentioned.

**Comment by MaximeWack** [comment]
Rounded corners worked in 1.4.1 with bspwm + picom, so I consider this a regression.

I dug a little deeper, and found that commit c01f81b is the culprit, and not compositor detection.  
Reverting this commit alone fixes round corners on the latest version.

I also think the commit doesn't implement division by zero correctly, as `(h + (w - r) * 2)` can be zero with values of `r` and `w` that are equal, and not only all equal to zero.  
Also, as it was the case for me, `w` (`settings.frame_width` in the caller) equal to zero is a valid case and doesn't cause a division by zero.^

I will submit a PR with a fix very shortly. :-)
