### ISSUE TITLE
[Solved] no shadows with xcompmgr > v1.1.8

### ISSUE THREAD

**Issue by biopsin** [dunst-project/dunst#749]
Heya, 
did a dunst update to latest v.1.5.0, and it seems new 'compositior detection' rutine don't play with xcompmgr. There are no more shadows under notifications. I run a stripped down xcompmgr with subtle shadows only, so I guess this means move on? :D

**Comment by aendeavor** [comment]
Very similar problem to mine, see #745.

**Comment by biopsin** [comment]
Installation info

    Version 1.5.0 (+ patch https://github.com/dunst-project/dunst/pull/750)
    Install type manually
    Distro and version Voidlinux (5.4.57)
    Further information: I am using pekwm.

Tested with "Fix possible division by zero in radius calculation" but it did not take..

**Comment by tsipinakis** [comment]
@biopsin Can you please provide your configurations(s) and steps to reproduce? I can't really offer much help without being able to debug.

**Comment by biopsin** [comment]
Sorry should have been more verbose. 
I'm using a single monitor.
// [dunstrc](https://p.teknik.io/Simple/6DX9c)
// $ xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55

Being running smooth since I patched dunst 1.4.2 with https://github.com/dunst-project/dunst/pull/705

I will try debug it myself when I have the time, 
maybe compare stuff to the unmaintained compton if it works too..

Anyways appreciate the time and effort you put into dunst :+1: 

dunst-1.5.0 / gtk+-2.24.32 / libnotify-0.7.9
xcompmgr-1.1.8 / libXcomposite-0.4.5 / libXdamage-1.1.5 / libXext-1.3.4

**Comment by biopsin** [comment]
Yup, it's this commit https://github.com/dunst-project/dunst/commit/d3f6c055902d9723c4b46acb943fd75fd142f2ee
where shadows brake. Gonna check some stuff in xcompmgr, I think I know where it is..
