### ISSUE TITLE
How to make notifications appear from the bottom up?

### ISSUE THREAD

**Issue by Scupake** [dunst-project/dunst#752]
- Version: `1.5.0`
- Install type: `Package`
- Distro and version: ` Arch`
Here's how it currently looks on my setup: 
![Screenshot_20 08 12_15 09 05](https://user-images.githubusercontent.com/61241021/90032442-e654ee00-dcad-11ea-9148-e196cdb57bb0.png)
I want to notifications to go from the bottom up, and I can't figure out how to do that so all new notifications start appearing off-screen

**Comment by tsipinakis** [comment]
Hi,

To achieve that you can set the `y` part of geometry to a negative value so the anchor point is at the bottom of the screen.
e.g. `geometry = "300x5-30-20"`

**Comment by Scupake** [comment]
It works. Thank you!
