### ISSUE TITLE
Provide an option to apply Xorg scaling factor to the window geometry?

### ISSUE THREAD

**Issue by asrcpq** [dunst-project/dunst#754]
I want to have consistent size of dunst notification window when switching between multiple monitors with different resolution and different dpi scaling level. I have a laptop with FHD builtin display and when I connect it to an external UHD monitor(with Xft.dpi doubled) I always find the notification window too narrow.

**Comment by frebib** [comment]
This is still a problem, please re-open this issue. dunst will dynamically redraw when the DPI changes, but the geometry is not updated. Restarting in that case seems overkill, especially when most of the work is already done live

**Comment by tsipinakis** [comment]
Hm, I agree handling this would be useful. There is some dpi handling but it doesn't extend to the window dimensions.

**Comment by fwSmit** [comment]
@frebib @asrcpq  Is anyone still wanting this feature and willing to test it? I could pretty easily implement this (for integer scaling factors), since it's implemented for wayland now already.

**Comment by frebib** [comment]
Yes, I'd very much like this and am willing to run experimental builds. Notifications are at most a luxury for me anyway :)

**Comment by fwsmit** [comment]
This is implemented by #890
