### ISSUE TITLE
monitor=1 overrides follow=keyboard|mouse

### ISSUE THREAD

**Issue by ecnerwala** [dunst-project/dunst#755]
When the configuration file includes
```
monitor = 1
follow = keyboard
```
dunst always opens notifications on monitor 1. This seems to match what's written at https://github.com/dunst-project/dunst/blob/master/src/x11/screen.c#L307, which checks for a nonzero monitor number first.

However, the man pages say
```
follow (values: [none/mouse/keyboard] default: none)
Defines where the notifications should be placed in a multi-monitor setup. All values except none override the monitor setting.
```
which seems to imply that follow=keyboard should work regardless of the monitor setting. The default dunstrc also says
```
    # If this option is set to mouse or keyboard, the monitor option
    # will be ignored.
```

Could we change either the documentation or the behavior so that they match?

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.5.0 (2020-07-23)`
- Install type: `package`
- Distro and version: `Archlinux`

**Comment by tsipinakis** [comment]
Thanks for the report, `monitor` will now be ignored if `follow_mode != none`.
