### ISSUE TITLE
No max width option?

### ISSUE THREAD

**Issue by OctaveLarose** [dunst-project/dunst#759]
As far as I know, there's no way to specify you want a variable width for every notification BUT with a cap ; I'd like for it to automatically expand to the longest message displayed (so just like when you specify a width of 0) but giving it a maximum so it doesn't end up taking half my screen at times.

If this feature is already present, I can't find it, but please do correct me if I'm wrong.

**Comment by rddunphy** [comment]
I think you're looking for the `shrink` option - with this turned on the maximum width is the width specified by `geometry`:

```
# Shrink window if it's smaller than the width.  Will be ignored if
# width is 0.
shrink = yes
```

**Comment by OctaveLarose** [comment]
That would be it, my bad! I don't know how I missed that. Here's hoping someone makes the same mistake in the future and stumbles upon this thread, then
