### ISSUE TITLE
Spacebar binding error

### ISSUE THREAD

**Issue by herod2k** [dunst-project/dunst#761]
Dunst is keybinded (wrongly) to the spacebar, my configuration is setup is:
close = ctrl+space
close_all = ctrl+shift+space

But when I receive a notification and I just push the spacebar (without ctrl or ctrl + shift) I close the notification popup. This is causing problems, because:
- I'm closing involuntary the popup
- I'm losing the spaces when I'm writing and I receive notifications.

My WM (BSPWM) doesn't have any other keybinding to the spacebar.

### Installation info

- Version: `1.5.0`
- Install type: `package`
- Distro and version: ` Archlinux`
- WM: BSPWM

**Comment by tsipinakis** [comment]
Huh, that's the default as well I'm not sure what's going on there, can't reproduce on my side.

On the other hand, I don't think this is worth the effort to fix it. I've been planning to deprecate/remove the internal keyboard shortcut support in dunst and this is another reason to rush it a bit more.

From 1.5 and onwards dunst ships with `dunstctl` that you can use to bind these commands to shortcuts with your WMs config.
Specifically for `close` and `close_all` it's `dunstctl close` and `dunstctl close-all`

**Comment by herod2k** [comment]
I didn't know about dunstctl I'll use that. What is the correct way to disable the standard keyboard shortcuts? Do I just comment them?

**Comment by tsipinakis** [comment]
> What is the correct way to disable the standard keyboard shortcuts? Do I just comment them?

Set them to `none` or comment them, either should work.
