### ISSUE TITLE
Hide notifications temporarily, mainly during screenshare.

### ISSUE THREAD

**Issue by chhajedji** [dunst-project/dunst#763]
### What I want to achieve

Stop notifications temporarily from popping up and then resume them later. All notifications during this time should be popped up when I resume notifications. I can do `pgrep dunst | xargs kill` to stop and then later manually restart it, but then I lose all my notifications in the mid time. Mainly helpful when doing a screenshare. 

Is there any way to achieve this behavior? Please help.

### Installation info

- Version: `v1.4.1-8-g9e29406`
- Install type: `apt install dunst`
- Distro and version: ` Kubuntu 20.04`

**Comment by AlexBocken** [comment]
You can use `notify-send "DUNST_COMMAND_TOGGLE"` to toggle the display of notifications. Received notifications during the pause will be displayed afterwards.

The other options are:
``` 
DUNST_COMMAND_PAUSE
DUNST_COMMAND_RESUME
```

**Comment by chhajedji** [comment]
Oh thanks, that helps :smile:

**Comment by Narrat** [comment]
And with the latest dunst release (1.5.0) there is a dedicated command/helper script for such cases: `dunstctl`

**Comment by AlexBocken** [comment]
Ah nice! Thanks, I didn't know that one either. Now I can finally check for current status!
