### ISSUE TITLE
Update dependencies for Fedora

### ISSUE THREAD

**Issue by maxiimilian** [dunst-project/dunst#764]
I would like to update the dependencies for Fedora in the wiki but I don't know how to do it. I can't push to the wiki repository and I don't know how to open a pull request for the wiki. Could somebody please tell me how to do it or just add this to the page:

```
dbus-devel libX11-devel libXrandr-devel glib2-devel pango-devel gtk3-devel libxdg-basedir-devel libXScrnSaver-devel libnotify-devel
```

I added `libnotify-devel` because dunst would not compile otherwise and also switched `gtk2-devel` to `gtk3-devel`. The "outdated" note is not required anymore.

**Comment by tsipinakis** [comment]
The wiki was set to restricted access for some reason, it used to be open and I'm not sure when that changed. Either way it's open now, feel free to push/edit in browser.

**Comment by maxiimilian** [comment]
Done. Thank you :)
