### ISSUE TITLE
DBus PropertiesChanged signal not being emitted for `paused ` property

### ISSUE THREAD

**Issue by ammgws** [dunst-project/dunst#765]
I want to monitor changes to `dunst`'s pause state in real time using D-Bus. According to the output of `busctl --user introspect org.freedesktop.Notifications /org/freedesktop/Notifications org.dunstproject.cmd0`, the `paused` property should emit a PropertiesChanged signal (assuming that's what `emits-change` in the below output means), however there appears to be no signal generated when monitoring the bus and running `dunstctl set-paused toggle`. Am I going mad or is there actually not meant to be a signal emitted when it's changed?

Introspection of the interface showing the `paused` property:
```
> busctl --user introspect org.freedesktop.Notifications /org/freedesktop/Notifications org.dunstproject.cmd0
NAME                   TYPE      SIGNATURE RESULT/VALUE FLAGS
.ContextMenuCall       method    -         -            -
.NotificationAction    method    i         -            -
.NotificationCloseAll  method    -         -            -
.NotificationCloseLast method    -         -            -
.NotificationShow      method    -         -            -
.Ping                  method    -         -            -
.paused                property  b         false        emits-change writable
```

Monitoring the bus while spamming `dunstctl set-paused toggle`:
```
>busctl --user monitor org.freedesktop.Notifications
Monitoring bus message stream.
‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=2
  Sender=:1.361  Destination=org.freedesktop.Notifications  Path=/org/freedesktop/Notifications  Interface=org.freedesktop.DBus.Properties  Member=Get
  UniqueName=:1.361
  MESSAGE "ss" {
          STRING "org.dunstproject.cmd0";
          STRING "paused";
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1 Cookie=46  ReplyCookie=2
  Sender=:1.303  Destination=:1.361
  UniqueName=:1.303
  MESSAGE "v" {
          VARIANT "b" {
                  BOOLEAN true;
          };
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=2
  Sender=:1.362  Destination=org.freedesktop.Notifications  Path=/org/freedesktop/Notifications  Interface=org.freedesktop.DBus.Properties  Member=Set
  UniqueName=:1.362
  MESSAGE "ssv" {
          STRING "org.dunstproject.cmd0";
          STRING "paused";
          VARIANT "b" {
                  BOOLEAN false;
          };
  };
```

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.5.0 (2020-07-23)`
- Install type: `package`
- Distro and version: `Arch`

**Comment by tsipinakis** [comment]
You're right, there is no signal emitted even though it's marked that it should be in the interface.

This is probably an artifact from the initial dunstctl implementation where a `monitor` command was planned to continuously check the paused status but if I remember right was scrapped due to some difficulties in implementing it.

I'd accept a PR adding that if anyone wants to work on it.

PS: Be mindful that there's no guarantee of backwards compatibility on the dbus interface, use the raw commands at your own risk :)
