### ISSUE TITLE
Tell scripts everything you know

### ISSUE THREAD

**Issue by jbash** [dunst-project/dunst#767]
It would be nice for a script to get access to *everything* duntst knows about a notification. My immediate use for this would be to be able to play different sounds for notifications with different categories. Having to guess from the appname isn't ideal. Obviously there are many other possible uses.

Ideally this would include both all the notification's attributes as originally provided to dunst, *and* all of the attributes as subsequently modified by rules. I could imagine it also being useful for a script to know the results of various decisions dunst had made about whether and how to display the notification.

I would suggest passing this stuff via environment variables as described in #653. I don't think it completely obviates #639; the two could be useful together. Another possibility would be to provide all of these things as %-expansions in the script line, but that might be harder to use.

**Comment by fwSmit** [comment]
Maybe it's better to give the script a notification ID and make sure all the neccesary variables are available through dunstctl.
This will probably be more work though.

**Comment by fwSmit** [comment]
@jbash The PR linked above passes info about the notification via environment variables. The variables are listed in [the man page](https://github.com/dunst-project/dunst/pull/802/files#diff-c1889f7158a4cace6e494b1a7c64687b91444308ffe24007ca16e40436e0321e). It would be a bit harder to provide the variables as they were before modified by rules, so they aren't included. Are there any specific use cases you have that would benefit from more variables being provided via environment variables?

**Comment by jbash** [comment]
I don't have any specific use case that would need the unrewritten variables. One can always just not rewrite them. Thanks.

**Comment by fwSmit** [comment]
Okay cool, I'll close this issue then.
