### ISSUE TITLE
notify-send DUNST_COMMAND_PAUSE no longer working

### ISSUE THREAD

**Issue by kidsil** [dunst-project/dunst#783]
Recently dunst's pause/resume feature stopped working.
When running  `notify-send DUNST_COMMAND_PAUSE`
It simply shows the prompt:
![image](https://user-images.githubusercontent.com/154950/100257939-c5f02d00-2f46-11eb-8a30-d3a96486446e.png)

The exact same command worked before (pausing dunst), but is no longer working.

### Installation info

- Version: `1.3.0 (2018-01-05)`
- Install type: `apt-get`
- Distro and version: `Ubuntu 18.04.5 LTS `

**Comment by kidsil** [comment]
After running: `systemctl restart --user dunst.service`
twice (odd, I know), it started working again.

**Comment by bebehei** [comment]
FYI: In 1.5.0 we've introduced dunstctl. Doing the same. (But without an in-band message).
