### ISSUE TITLE
Action handler for a desktop notification defined by Firefox itself does not work

### ISSUE THREAD

**Issue by piroor** [dunst-project/dunst#786]
### Steps to reproduce

1. Install Firefox and Dunst.
2. Install [Tree Style Tab](https://addons.mozilla.org/firefox/addon/tree-style-tab/) addon to Firefox.
3. On the TST's sidebar, right click on a tab item and choose "Bookmark this Tab".
4. Then a desktop notification appears with a message: "Failed to get permissions to create bookmarks. Please click here to grant extra permissions."
5. Click the notification.

### Actual result

Nothing happen and the notification is just closed.

### Expected result

Notification is closed and the options page of the TST addon is opened with a new tab, because the click action is handled by the listener defined by the TST addon.

### Installation info

- Version: 1.5.0
- Install type: package
- Distro and version: ArchLinux installed at 2020-11-30

----

TST addon registers a click event listener via [this API provided by Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/onClicked). Firefox registers its own action handler for a desktop notification at [this line](https://searchfox.org/mozilla-central/rev/168c45a7acc44e9904cfd4eebcb9eb080e05699c/toolkit/system/gnome/nsAlertsIconListener.cpp#48), and the action handler calls the listener registered by the TST addon. When Dunst is running something happens and this chain looks to be broken. Any known solution? Or, is this a unsolvable restriction of the combination Firefox and Dunst?

**Comment by fwSmit** [comment]
Dunst doesn't handle actions via clicking the notification. You have to press a keyboard shortcut, by default that is Ctrl+alt+c. This will open dmenu and ask what action you want to perform. On my system it opened a tab with the relevant TST setting, so it seemed to work as intended.

**Comment by piroor** [comment]
Thank you for a quick response. After I install the `dmenu` package I've successfully shown the menu as an alternate for a click action.

I've looked the [FAQ](https://dunst-project.org/faq/) but I couldn't see any topic about click actions on the notification. The [top page](https://dunst-project.org/) also just says "The mouse can be used too - left-click to dismiss a notification, or right-click to dismiss them all." On the other hand, some softwares shows notification with a message "click here to do something" because click actions on notifications is used for various reactions like TST does. So newcomers like me may be confused from the difference of the basic strategy.

I think a FAQ topic about that point will helpful for people like me. How about this idea? If it is OK I'll create a pull request for https://github.com/dunst-project/dunst-project.org/blob/master/content/faq.md .

**Comment by tsipinakis** [comment]
Adding a FAQ is a good idea, feel free to make a PR. Additionally, if there's a `default` action or there's only one action on the notification you can middle click to trigger that without dmenu. (If there isn't a default, dmenu will open).

You can also customize the mouse behaviour in the config via the `mouse_{left,middle,right}_click` settings.

**Comment by piroor** [comment]
Thank you for very helpful information! Middle click works as you told, and finally the setting `mouse_left_click = do_action, close_current` helped me to use a behavior like other platforms. I've created a PR #17 adding these information to the FAQ.

**Comment by fwSmit** [comment]
I think this can be closed then @tsipinakis

**Comment by piroor** [comment]
Oops, sorry I forgot to close this. Thanks again!
