### ISSUE TITLE
dunst -print output not accepted by tee?

### ISSUE THREAD

**Issue by Barbarossa93** [dunst-project/dunst#787]
I'm not sure if this is a bug and I'm probably missing something but I sincerely wasn't sure. I'm trying to log the output of `dunst -print` into a file using the full command `dunst -print | tee /tmp/dunstlog`. My goal is to be able to parse the file to output in rofi to create a sort of notification center. Unfortunately, the command with dunst and tee never output the notification events to the file. It's only after I kill the process do the notifications get released to tee. It seems like `tee` is unable to accept the output of `dunst -print` while its running? I'm not sure what the problem would be since the man page specifies that the `-print` flag prints to stdout.

### Installation info

- Version: `1.5`
- Install type: `package`
- Distro and version: ` Arch`

**Comment by tsipinakis** [comment]
My hunch is this is because of buffering. In the terminal stdout is flushed on every newline, but if you redirect it to a file it's buffered until the system feels like flushing it to the file.
Dunst _can_ specify that the output shouldn't be buffered but I don't see the point in that. If your intend is to create a notification log you can try using a script that dumps all the information to a file instead.

**Comment by Barbarossa93** [comment]
Looks like you're right! I used `expect`'s unbuffer command and ta-da! Its writing output to tee in real time. I suppose I could do it so that dunst is killed and then restarted every time I wanted to look at the log but that seems grotesque to me. One last thing, is the `-print` output a particular format? It looks similar to json but `jq` doesn't like it the way it is

**Comment by tsipinakis** [comment]
> Looks like you're right! I used expect's unbuffer command and ta-da! Its writing output to tee in real time.

Glad that's solved, I'll close this then.

> I suppose I could do it so that dunst is killed and then restarted every time I wanted to look at the log but that seems grotesque to me

As I said, as long as you just want to log the appname, summary and body you can make your own logger using the `script` setting in whatever format you prefer.

> One last thing, is the -print output a particular format? It looks similar to json but jq doesn't like it the way it is

Indeed that's not valid JSON, I'm not sure why it's the way it is it was like that before I took on the project and left it as-is.

**Comment by Barbarossa93** [comment]
Oh wow, I didn't realize I could use dunst rules for scripts! That's amazing! The only thing problem I have is how can I make a rule be ubiquitous for all notifications? My understanding of the man page is that the notification has to match something specifically when my goal is to capture all notifications. Can I simply do:
```
[log_notifs]
    script = ~/parse_dunst_notifs.sh
```
Or do I need to be more specific such as:
```
[log_notifs]
    appname = *
    script = ~/parse_dubst_notifs.sh
```

**Comment by tsipinakis** [comment]
The first one should work, if there's no matching rule all notifications match it.

**Comment by Barbarossa93** [comment]
Awesome. Thank you!!
