### ISSUE TITLE
wttr.io output not rendering properly

### ISSUE THREAD

**Issue by alrayyes** [dunst-project/dunst#789]
I have the following fonts setup in my config:

```
font = JoyPixels 10, Hack Nerd Font Mono 10
```

I've tried JetBrains/Hack Nerd Font/Hack Mono as well.

When printing wttr.io output (```notify-send Weather "$(curl -4 "wttr.in/")"```) the output in dunst in garbled. Running the same curl command wit the same fonts in st (```echo "$(curl -4 "wttr.in/")"```) gives the expected results.

Notify-sending emojis works without issues.

**Comment by tsipinakis** [comment]
When you say garbled what do you mean? Can you post a screenshot?

**Comment by alrayyes** [comment]
Silly of me to forget that, sorry. Here you go.

![screenshot](https://user-images.githubusercontent.com/511318/101154190-b13a2600-3625-11eb-90dc-bdb58c659403.png)

**Comment by tsipinakis** [comment]
Looks like wttr uses terminal color codes, which dunst doesn't support. It needs to be in [markup](https://developer.gnome.org/pygtk/stable/pango-markup-language.html) form to be correctly displayed by dunst.

**Comment by alrayyes** [comment]
Ah, of course. Fixed it with ```notify-send "$(curl -4 wttr.in/amsterdam?T)"``` to disable ansi. Thanks a bunch!
