### ISSUE TITLE
With CJK characters in title, body message with less than 3 characters doesn't appear in notification

### ISSUE THREAD

**Issue by nathanielevan** [dunst-project/dunst#790]
Hi, it seems that if I have a Chinese/Japanese/Korean character in the notification title, each line of the body won't show up in the notification if it has less than 3 characters. So for example if I do this:
![2020-12-10-235739](https://user-images.githubusercontent.com/9361126/101803862-9135c580-3b43-11eb-994b-76f074a6410a.png)
This is the notification that appears on my screen:
![2020-12-10-235804](https://user-images.githubusercontent.com/9361126/101803925-a27ed200-3b43-11eb-8278-c78abf23d3df.png)
But if I run this command:
![2020-12-11-000114](https://user-images.githubusercontent.com/9361126/101804331-0bfee080-3b44-11eb-8da4-dddf76baf132.png)
This is what shows up:
![2020-12-11-000111](https://user-images.githubusercontent.com/9361126/101804344-10c39480-3b44-11eb-8b4f-da0f556d943f.png)
As you can see, in the second scenario, the last line of the body appears in the notification, but not in the first scenario. I could replicate this with both a single-line and a multi-line body message, in each individual line in the multi-line message.

I use this in my notification script for spotifyd [here](https://github.com/nathanielevan/dotfiles/blob/master/.local/bin/spotifyd-notif) that runs in every song change; the idea is to display the song title in bold, followed by the name of the artist and the album title, each in a single line.

### Installation info

- Version: `1.5.0`
- Install type: `package`
- Distro and version: ` Arch Linux`

**Comment by erikarvstedt** [comment]
This bug also appears with single-line bodies.\
Here's a minimal example:

```
notify-send "あ" "a"
```
Output:
```
あ

```

Interestingly, repeating the command
```
notify-send "あ" "a"
notify-send "あ" "a"
```
fixes the output:
```
(1) あ
a
```

`notify-send "あ" "abc"` also works correctly.

Here's @nathanielevan's original example: `notify-send "あげない" "tricot\n12"`

**Comment by fwSmit** [comment]
Thanks for the minimal reproduction, I was able to reproduce it. I poked around a bit and logged some things, but to me this seems like an issue with [pango](https://gitlab.gnome.org/GNOME/pango). That library does all the rendering of text.

**Comment by fwSmit** [comment]
This is indeed a pango bug. It's fixed in the current master, so I'm closing this.
