### ISSUE TITLE
Number of unread messages

### ISSUE THREAD

**Issue by ritze** [dunst-project/dunst#792]
Currently it's not possible to get the number of unread messages when dunst is paused or messages were not closed actively.

The number of unread messages could be used to be shown in a status bar or somewhere else, like other notification services already do.

The primary scope would be when dunst is paused, because you need to focus on a task. To not miss unread messages, you can easily check, if any message were queued since you paused dunst.

**Comment by tsipinakis** [comment]
That's a good idea, however 'unread' needs to be defined more precisely.
Dunst has 3 queues `waiting`, `displayed` and `history`.
`waiting` being a notification that has arrived but hasn't been shown yet (either on standby because of no space, or dunst is paused)
`displayed` being the notifications currently being shown.

In your opinion should `unread` be `waiting+displayed` or just the number in the waiting queue?

**Comment by ritze** [comment]
That's a good point. I let this detail open, since I'm not familiar how dunst manages the notifications.

Why not just adding options for all three? E.g. `dunstctl history-num`, `dunstctl waiting-num`, and `dunstctl missed-num` (for displayed notifications which were not actively "clocked" away). Or just printing all three by calling one command:

```
$ dunstctl status
              Waiting: 0
  Currently displayed: 3
              History: 13
```

This would be the same behavior like for other systemd commands (e.g. `networkctl status`). The disadvantage with one command to show all stats would be that you have to write additional logic around your script, which you use to forward this information.

**Comment by tsipinakis** [comment]
The formatting can be done directly in `dunstctl` so adding all of the above would not be that big a problem.

If anyone wants to work on this there's already the `queues_length_{waiting,displayed,history}` functions and all that's needed is to add the interfaces to [dbus.c](https://github.com/dunst-project/dunst/blob/master/src/dbus.c#L82)

**Comment by fwSmit** [comment]
#793 is merged, so I'll close this issue
