### ISSUE TITLE
Flush stdout while using the -print flag.

### ISSUE THREAD

**Issue by vlnx** [dunst-project/dunst#794]
Running release v1.5.0.

```patch
diff --git a/src/notification.c b/src/notification.c
index 1c18db4..a9e9e63 100644
--- a/src/notification.c
+++ b/src/notification.c
@@ -97,6 +97,7 @@ void notification_print(const struct notification *n)
                 printf("\n");
         }
         printf("}\n");
+        fflush(stdout);
 }

 /* see notification.h */
```

When stdout is redirected to a file, fflush is needed.

**Comment by tsipinakis** [comment]
If this is about redirecting the `-print` output to a file IMO that's the wrong way to do it, see #787 for an alternative (and better) approach.

I'll push this patch either way since the changes are minimal.
