### ISSUE TITLE
Move default config to /etc/xdg/dunst/dunstrc

### ISSUE THREAD

**Issue by fwSmit** [dunst-project/dunst#795]
Currently the dunst config is installed in `/usr/share/dunst/dunstrc`. This is not used by default by dunst, which results in users having to copy the dunstrc to `~/.config/dunst/dunstrc` before being able to use dunst properly.
Dunst doesn't search in `/usr/share/dunst/dunstrc` for config files. It only searches `/etc/xdg/dunst/dunstrc` and `/etc/xdg/dunstrc` for system wide config files. It would be easier for new users if the default config is used if it isn't overridden by a user config file.

Another thing that's worth considering is to let the user config not override the system wide config, but add to it. So if you have a setting that's not defined in the user config, the system wide setting is used. This way we can get rid of the default definitions in `config.h`. Sometimes it's forgotten to add a default setting to both config.h and the default dunstrc.

Edit: see #198 for an old reference to something similar

**Comment by tsipinakis** [comment]
The config is already installed there in the Debian package (which I manage) so I guess it makes sense to update it globally. However I'm not sure about getting rid of `config.h` as that means dunst will now error when run without a config in that place. Some hardcoded defaults are needed in any case.

**Comment by fwSmit** [comment]
> The config is already installed there in the Debian package (which I manage) so I guess it makes sense to update it globally. 

Yeah I noticed. The archlinux package just uses make install, so if we update the makefile, it will work correctly.

> However I'm not sure about getting rid of `config.h` as that means dunst will now error when run without a config in that place. Some hardcoded defaults are needed in any case.

I'm fine with that, but I think we should update it then once with the current default config. The current settings are not very nice looking.
But should we add new settings every time in config.h? Otherwise we can add a comment to just leave it like it is.

**Comment by tsipinakis** [comment]
I just remembered there's #414 open, so that's already planned to do whenever we decide to bump the major version. I'm just hesitant because I don't know if there's anyone actually using config.h for configuration.

On the other hand, there's been a [warning](https://github.com/dunst-project/dunst/blob/master/config.mk#L50) if dunst is built with `STATIC_CONFIG` for years now and and no-one has complained thus far.
