### ISSUE TITLE
fullscreen = "delay" or "pushback" not working in xmonad

### ISSUE THREAD

**Issue by toniz4** [dunst-project/dunst#801]
using fullscreen = "delay" or "pushback" doesn't work on xmonad, i'm using it like this:
```
[script]
	summary = "*"
	fullscreen = "delay"
	script = notifysound.sh
```
Under dwm it worked as expected.

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.4.1 (2019-07-03)`
- Install type: `package`
- Distro and version: `gentoo`

**Comment by fwSmit** [comment]
> Using fullscreen = "delay" or "pushback" doesn't work on xmonad

What is the behaviour you get instead?

If it works under dwm, it's probably an issue with xmonad not telling dunst if it's fullscreen.

**Comment by toniz4** [comment]
I just get the notification on top of the fullscreen window.
Checking with xprop i can see `_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN`, that would mean that xmonad is reporting a fullscreen window?

**Comment by fwSmit** [comment]
If that window is focused that should be good. Could try to compile and run this branch https://github.com/fwSmit/dunst/tree/fullscreen-debug. It add a debug log for fullscreen. Build and run with:
```
make
./dunst -verbosity debug
```
Does it report fullscreen as 1?

**Comment by toniz4** [comment]
Yup:
```
INFO: System is running X11
DEBUG: RUN
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Ignoring '65'
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Ignoring '18'
DEBUG: XEvent: Ignoring '18'
DEBUG: XEvent: Ignoring '18'
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Ignoring '19'
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 1
DEBUG: RUN
DEBUG: Focused window fullscreen: 1
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 1
DEBUG: XEvent: Ignoring '18'
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 1
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 1
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 1
DEBUG: XEvent: Ignoring '19'
DEBUG: XEvent: Ignoring '19'
DEBUG: XEvent: Ignoring '19'
DEBUG: XEvent: Ignoring '18'
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: RUN
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
DEBUG: XEvent: Ignoring '19'
DEBUG: XEvent: Checking for active screen changes
DEBUG: Focused window fullscreen: 0
```
This is switching from a workspace with mpv in fullscreen.

**Comment by bebehei** [comment]
The occurences of `RUN` are always bound to a change in `Focused window fullscreen`. I don't see any `RUN` triggered by a notification.

Have you sent a notification in the meantime while creating this logfile?


Do you use stack tags, so that the incoming notification actually gets merged?

**Comment by toniz4** [comment]
updating to 1.5.0 apparently solved the issue, thanks for your time!
