### ISSUE TITLE
Dunst script option doesn't provide image path from spotify's notifications

### ISSUE THREAD

**Issue by Barbarossa93** [dunst-project/dunst#804]
When using a script accepting arguments from dunst's script option, the icon path of spotify notifications isn't included. I would expect there to be a path provided since I can see album art in the actual dunst notification. I know it's not an issue with the script since I can get icons for other notifications, specifically when I send a notification with a specified image.

I apologize if this is a problem on spotify's end; it's not clear to me where the problem is stemming.

### Installation info

- Version: `1.5.0`
- Install type: `package`
- Distro and version: ` Arch`

**Comment by bebehei** [comment]
Spotify's notification uses a raw image. This is binary data, sent over the wire. (In comparison: The icons are just text strings, which get resolved then by dunst after receiving the notification.)

We can't provide the binary data in a meaningful way to a script.

**Comment by bebehei** [comment]
See here:

https://github.com/dunst-project/dunst/blob/0e6997b6fcb9bb89c961597123945bc0075445c9/src/notification.c#L105-L143

IIRC spotify, doesn't send an iconname, which then results in an empty parameter in your script. (Which is absolutely fine, the `icon` parameter is optional in the notification spec)

**Comment by Barbarossa93** [comment]
Oh bummer, figured it was something on their end.  Thanks for the quick response! I assume this is unfixable so I'll go ahead and close this.

**Comment by fwSmit** [comment]
If you really want all icons to be usable by scripts, you could add something like
```diff
diff --git a/src/draw.c b/src/draw.c
index bb70b1c..2f9e1fc 100644
--- a/src/draw.c
+++ b/src/draw.c
@@ -311,6 +311,8 @@ static struct colored_layout *layout_init_shared(cairo_t *c, const struct notifi
 
         if (settings.icon_position != ICON_OFF && n->icon) {
                 cl->icon = gdk_pixbuf_to_cairo_surface(n->icon);
+                GError * error = NULL;
+                gdk_pixbuf_save(n->icon, "/tmp/dunst_icon.jpg", "jpeg", &error, NULL);
         } else {
                 cl->icon = NULL;
         }
```
and make your script use `/tmp/dunst_icon.jpg` if it doesn't get an icon via arguments. If you make the icon name the app name, it would even work for multiple notifications at the same time.
