### ISSUE TITLE
release 1.5.1?

### ISSUE THREAD

**Issue by domenkozar** [dunst-project/dunst#805]
In 1.5.0 middle click is broken, which makes dunst hard to use with notifications that require actions. I'd like to switch back to using it once it's in my OS.

**Comment by tsipinakis** [comment]
Next release will be 1.6 which is blocked by #781. After I merge this (this weekend if everything goes smoothly), I'll wait a week or two for any bugs to be reported by master users then I'll release 1.6.

**Comment by domenkozar** [comment]
:pray:
