### ISSUE TITLE
Force send spotify notifications with icon

### ISSUE THREAD

**Issue by salil-sudo** [dunst-project/dunst#806]
When a new song is played in spotify, I get a notification via dunst. But sometimes I want to know the song info in the middle of the song. Hence I made a small script like this:
`dunstify "$(spotifycli --song)" "$(spotifycli --artist)"
`
The script uses spotifycli and is called via a keybinding. The problem is, it doesnt show any album artwork ( because I am not asking it show). I wanted to know how can I ask it show this info with album artwork. And is there a better way to get song info in the middle of the song?

### Installation info

- Version: `1.5.0-1`
- Install type: `pacman`
- Distro and version: `ArcoLinux`

**Comment by fwSmit** [comment]
There has been an issue about this earlier, see #804. There I provided a hacky patch for saving images sent via notifications (see https://github.com/dunst-project/dunst/issues/804#issuecomment-756697382). You could improve a bit on that patch and use that. This will probably never be included in dunst. 
Another solution we could try to extend `dunstctl`'s history-pop functionality, where you can replay old notifications, to include a command to "pop" a specific notification. This way you could replay the old spotify notification. Does that sound like a good solution to you? This way you don't have to query the music information via some command.

**Comment by salil-sudo** [comment]
That sounds like an excellent workaround. There is one very tiny issue with this. Sometimes I refresh my desktop, which changes the current wallpaper. I use pywal to color everything (including dunst). To make sure dunst gets the color of current wallpaper, I kill it  and start it again with new set of colors. Now, killing dunst removes notification history (or thats what I assume). Is there any way to kill dunst without erasing history ?

**Comment by fwSmit** [comment]
> That sounds like an excellent workaround.

Cool, then I'll work on that some time soon (probably in two weeks, but maybe earlier).

> Is there any way to kill dunst without erasing history?

No, not yet, but I do want to implement config reloading.

**Comment by salil-sudo** [comment]
Thanks ! Closing this

**Comment by fwSmit** [comment]
It's not yet implemented, so I'm reopening :)

**Comment by salil-sudo** [comment]
Ah nice. Let me know when it happens :)

**Comment by fwSmit** [comment]
@salil-sudo I've implemented the feature. Could you test if it works for you?

**Comment by fwSmit** [comment]
You can use it with `dunstctl history-pop _ID_`

**Comment by salil-sudo** [comment]
Thanks for the update. How can I obtain the notification ID of last spotify notification ?

**Comment by fwSmit** [comment]
The notification ID can be obtained from the variable `DUNST_ID` from a script. Make sure to activate that script only for spotify notifications. So put something like this in your dunstrc:
```
[spotify]
appid = "spotify"
script = ~/.local/bin/spotify-save-id.sh
```

**Comment by salil-sudo** [comment]
I am still a bit confused. How do I print the notification ID of any notification? Is it with `-p` flag or something ?

**Comment by fwSmit** [comment]
Dunst sets the environment variable `DUNST_ID` to the notification id before calling a script. You can use that information from a script and save it in some file to use it later for reopening the notification.

`~/.local/bin/spotify-save-id.sh`
```
#!/bin/sh
echo "icon: $DUNST_ID" > /tmp/spotify-id
```

`dunstrc`
```
[spotify]
appid = "spotify"
script = ~/.local/bin/spotify-save-id.sh
```

You can reopen the notification with `dunstctl history-pop $(cat /tmp/spotify-id)` if everything works

**Comment by salil-sudo** [comment]
I thought so. But I am not seeing any environmental variable called `DUNST_ID`. Either it doesnt exist or its empty

**Comment by fwSmit** [comment]
With the latest release of Dunst you won't, but with the linked brach you should have that environment variable available from a script **launched by Dunst**

**Comment by salil-sudo** [comment]
Not sure whats happening. I removed the latest release. Installed the master branch from the source. `$DUNST_ID` is empty even after using the script mentioned above

**Comment by fwSmit** [comment]
Could you send your dunstrc?
You can try any of the other environment variables to see if they are set. https://github.com/dunst-project/dunst/pull/802/files#diff-c1889f7158a4cace6e494b1a7c64687b91444308ffe24007ca16e40436e0321e
Some of the variables are also passes as arguments to the script, as mentioned in the above documentation. Unfortunately the id isn't one of them, but you can try if those work.

**Comment by salil-sudo** [comment]
[dunstrc.txt](https://github.com/dunst-project/dunst/files/6004891/dunstrc.txt)
here is my dunstrc

**Comment by fwSmit** [comment]
I don't know if the appid of spotify notifications is actually "spotify". Also, appid isn't correct, my bad. It actually should be apname. So try `appname = "*"`.

**Comment by salil-sudo** [comment]
Tried with appname. `DUNST_ID` is still empty and all the other variable in the documentations also dont exist

**Comment by fwSmit** [comment]
And does the script get any arguments passed to it?

**Comment by salil-sudo** [comment]
No it doesnt

**Comment by fwSmit** [comment]
We decided [here](https://github.com/dunst-project/dunst/pull/823#discussion_r584118151) that the history-pop feature isn't the right solution and should not be added to dunst. Take a look at the first comment in this thread for the other solution.
