### ISSUE TITLE
Multi-action on click event

### ISSUE THREAD

**Issue by cephox** [dunst-project/dunst#807]
It would be nice if you can trigger multiple custom actions when clicking a notification

### Installation info

- Version: `1.5.0 (2020-07-23)`
- Install type: `package`
- Distro and version: `Arch Linux 5.10.7-arch1-1`

**Comment by tsipinakis** [comment]
Dmenu doesn't support multiple options to be selected at the same time sadly. However, you can remove the `close_current` action from `mouse_middle_click` and this prevent the notification from closing allowing you to trigger as many actions as you want.
