### ISSUE TITLE
Notfifications not leaving even though it is configured to do so in configs on SwayWM.

### ISSUE THREAD

**Issue by LiterallyJohnny** [dunst-project/dunst#808]
I used Dunst on i3wm and it worked completely fine. I decided to give Wayland and SwayWM a shot today, and I noticed that notifications pop up don't leave, and the notifications show up on top of each other instead of new notifications positioning itself above the last notification.

I am unable to make the notifications go away unless I spam `xkill` on it, which for some reason kills all of my other tabs before it gets rid of the notifications.

I start Dunst on SwayWM startup using `exec dunst &`, which is also how I started it on i3wm.

**Configs:**

- [SwayWM configs](https://github.com/LiterallyJohnny/Dotfiles/blob/main/configs/sway/config)
- [i3wm configs](https://github.com/LiterallyJohnny/Dotfiles/blob/main/configs/i3/config)
- [Dunst configs](https://github.com/LiterallyJohnny/Dotfiles/blob/main/configs/dunst/dunstrc)

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.5.0 (2020-07-23)`
- Install type: `Installed from Arch package from official repo.`
- Distro and version: `Arch Linux (Rollilng Release)`

**Comment by LiterallyJohnny** [comment]
Now that I think about it, I don't recall seeing any mention about Wayland support in Dunst's ArchWiki page. Does Dunst even support Wayland?

**Comment by tsipinakis** [comment]
> Does Dunst even support Wayland?

It does as of [4 days ago](https://github.com/dunst-project/dunst/commit/77bfbc4f7ff0a0ace6a7c9f0d9823ca3ca0fe3fd) :). 1.5 is running via XWayland. Can you try building from master and see if that fixes your issue?

**Comment by LiterallyJohnny** [comment]
This is weird. It shows notifications, but it looks like it's one of my programs. I'll try to explain it as best as I can.

The notifications pop up, and they do stack up on top of each other. However, the notifications do not go away and I am unable to close them. I right-clicked on one (my binding for close notif) and I got a Firefox dialog instead.

I used `xprop` and clicked on it the notification, and this is the output:

```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 56623109, 56623110
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3600004
WM_CLIENT_LEADER(WINDOW): window id # 0x3600001
_NET_WM_PID(CARDINAL) = 8859
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "lj-laptop"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 450 by 95
		program specified maximum size: 8192 by 8192
		program specified base size: 450 by 95
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "Navigator", "Nightly"
WM_ICON_NAME(COMPOUND_TEXT) = "Playing a Game - Quizizz — Firefox Nightly"
_NET_WM_ICON_NAME(UTF8_STRING) = "Playing a Game - Quizizz — Firefox Nightly"
WM_NAME(COMPOUND_TEXT) = "Playing a Game - Quizizz — Firefox Nightly"
_NET_WM_NAME(UTF8_STRING) = "Playing a Game - Quizizz — Firefox Nightly"
```

It's showing up as one of the programs I have open. I don't understand why, but it explains why using `xkill` and clicking on it closes my other tabs.

Do you know what could be causing this? I'm going to restart when I get the chance, I'm in class right now doing a quiz so I can't quite reboot right now.

If rebooting doesn't fix it, I'll go and build it from master and see if that fixes the issue.

**Comment by tsipinakis** [comment]
> _NET_WM_NAME(UTF8_STRING) = "Playing a Game - Quizizz — Firefox Nightly"

That's a notification from firefox, not dunst. If firefox can't find an active notification daemon it displays the notifications on its own.
You've probably misconfigured dbus in some way.

**Comment by LiterallyJohnny** [comment]
That's not a notification from Firefox though, that's why I'm confused. I used `notify-send "Test" and then used` `xprop` and clicked on the notification.

I'm trying to figure out why it's showing Firefox when I sent the notication from the terminal with `notify-send`.

**Comment by fwSmit** [comment]
> That's not a notification from Firefox though, that's why I'm confused. I used `notify-send "Test" and then used` `xprop` and clicked on the notification.
> 
> I'm trying to figure out why it's showing Firefox when I sent the notication from the terminal with `notify-send`.

xprop only works in X, or in wayland programs that are using xwayland. The current dunst master branch will use wayland, so xprop won't work on it. Firefox uses xwayland by default.

> > _NET_WM_NAME(UTF8_STRING) = "Playing a Game - Quizizz — Firefox Nightly"
> 
> That's a notification from firefox, not dunst. If firefox can't find an active notification daemon it displays the notifications on its own.
> You've probably misconfigured dbus in some way.

Don't think it's a firefox _notification_, since notifications shouldn't have `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL` iirc. 

To test if your dbus is configured correctly, what does `dunstctl debug` say?

**Comment by LiterallyJohnny** [comment]
My apologies for the late response. I switched to a different notification program (Mako), which is designed specifically for Wayland.
