### ISSUE TITLE
Bringing back old notifications stops actions from working.

### ISSUE THREAD

**Issue by sevensidedmarble** [dunst-project/dunst#815]
Apologies if this has been talked about before, but I couldn't find an answer on Google.

If you bring back an old notification with the shortcut (for me its like ctrl+` which I think is the default) and then hit the combo to bring up the actions in dmenu (which also by default I believe is ctrl+shift+.), the actions never seem to actually *do* anything on old notifications. They work just fine if I haven't closed the notification, but bringing back an old one and performing an action on it never seems to actually launch my browser.

EDIT: Based on this: https://github.com/dunst-project/dunst/pull/699/files this actually seems to be a feature, but why? Sometimes I get a lot of notifications and I don't necessarily want to deal with them all at once. I'd really like to be able to run actions on past notifications.

**Comment by fwSmit** [comment]
IIRC, the application has to keep listening for actions and it stops listening once dunst signals the notification is closed.
I think the linked PR only makes sure no expired actions are used.

**Comment by tsipinakis** [comment]
That's correct. Applications stop listening for actions when a notification is closed, so they can't be triggered. The linked PR only makes it so that actions are deleted/don't show up when you recall a notification for exactly this reason.

**Comment by fwSmit** [comment]
Yep, then the only solution would be to not send a notification closed event, and hope the application won't time out. This won't be desirable for most users, but you could add an option for it.

**Comment by sevensidedmarble** [comment]
Would this be doable in Dunst then as an option?

**Comment by fwSmit** [comment]
I don't think it will be hard to implement, but I won't implement it myself in the near future. You can take a stab at it though.

**Comment by tsipinakis** [comment]
I don't think implementing something like this is a good idea however. It goes directly against the [spec](https://developer.gnome.org/notification-spec/). Additionally, it might not even work as some clients close the notifications themselves, or might just stop listening after a timeout.

**Comment by sevensidedmarble** [comment]
Couldn't dunst just keep enough info about the notification in memory to perform actions even after the notification is removed? I realize that goes against the specs but it would be very useful.

**Comment by tsipinakis** [comment]
> Couldn't dunst just keep enough info about the notification in memory to perform actions even after the notification is removed

That's the problem, an action isn't something dunst does, it's something the program that sent the notification does.

A simple notification exchange goes like this:
Sender: Sends notification message with a list of actions (e.g. 'open tab')
Dunst: Replies with acknowledgement and notification id e.g. 5.
(some time later)
Dunst: Sends a message to the sender that the user requested the 'open tab' action on notification 5
Sender then performs all the steps to do that

Then either sender sends a message to dunst to close the notification, at which point the sender stops listening for actions
Or, the user closes the notification themselves and dunst sends a notification to the sender that notification 5 was closed, making it stop listening for actions.

The solution proposed would only solve the second case and will be very flaky on whether it works.

**Comment by fwSmit** [comment]
Yeah maybe you're right. It's sad, thought that there's no real good alternative to this

**Comment by sevensidedmarble** [comment]
So it might be flaky if Dunst had a flag to not actually send the notification close signal because the notification itself might close (because of a timeout something) on its own?

**Comment by fwSmit** [comment]
Yes, it might cause more confusion from users than what it's worth
