### ISSUE TITLE
fedora mate compiz mouse click does not close window

### ISSUE THREAD

**Issue by garberw** [dunst-project/dunst#817]
I am using dunst on compiz window manager with mate desktop environment on fedora linux.  have a problem:  can not click on notification window to close it.  works in mate/marco and mate/metacity.
fedora install of dunst by package/rpm has files

/usr/bin/dunst
/usr/lib/.build-id
/usr/lib/.build-id/0a
/usr/lib/.build-id/0a/505690ae9acc70e137c1ad1fd269333dde0880
/usr/lib/systemd/user/dunst.service
/usr/share/dbus-1/services/org.knopwob.dunst.service
/usr/share/doc/dunst
/usr/share/doc/dunst/AUTHORS
/usr/share/doc/dunst/CHANGELOG.md
/usr/share/doc/dunst/LICENSE
/usr/share/doc/dunst/README.md
/usr/share/doc/dunst/RELEASE_NOTES
/usr/share/dunst
/usr/share/dunst/dunstrc
/usr/share/man/man1/dunst.1.gz

I am not sure how to get the two services to work, I have already tried 
systemctl enable --user dunst
eventually I just added dunst to the startup-applications for the desktop.

journalctl -b -p3
Feb 08 17:11:25 electron.localdomain dbus-broker-launch[1751]: Ignoring duplicate name 'org.freedesktop.Notifications' in service file '/usr/share//dbus-1/services/org.knopwob.dunst.service'
Feb 08 17:11:25 electron.localdomain dbus-broker-launch[1751]: Ignoring duplicate name 'org.freedesktop.Notifications' in service file '/usr/share//dbus-1/services/org.kde.plasma.Notifications.service'
Feb 08 17:11:25 electron.localdomain dbus-broker-launch[1751]: Ignoring duplicate name 'org.freedesktop.FileManager1' in service file '/usr/share//dbus-1/services/org.mate.freedesktop.FileManager1.service'
Feb 08 17:11:26 electron.localdomain cupsd[1521]: [CGI] ippfind (PID 1660) stopped with status 1!
Feb 08 17:11:26 electron.localdomain cupsd[1521]: [cups-deviced] PID 1649 (driverless) stopped with status 1!
Feb 08 17:11:28 electron.localdomain pulseaudio[1923]: module-rescue-stream is obsolete and should no longer be loaded. Please remove it from your configuration.
Feb 08 17:11:39 electron.localdomain gdm-password][2301]: gkr-pam: unable to locate daemon control file
Feb 08 17:11:42 electron.localdomain dbus-broker-launch[2416]: Ignoring duplicate name 'org.freedesktop.Notifications' in service file '/usr/share//dbus-1/services/org.knopwob.dunst.service'
Feb 08 17:11:42 electron.localdomain dbus-broker-launch[2416]: Ignoring duplicate name 'org.freedesktop.Notifications' in service file '/usr/share//dbus-1/services/org.kde.plasma.Notifications.service'
Feb 08 17:11:42 electron.localdomain dbus-broker-launch[2416]: Ignoring duplicate name 'org.freedesktop.FileManager1' in service file '/usr/share//dbus-1/services/org.mate.freedesktop.FileManager1.service'
Feb 08 17:12:09 electron.localdomain pulseaudio[2672]: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

it looks like there are multiple notification daemons running but I am not sure which services to disable; help?

### Installation info

- Version: `1.4.1`
- Install type: `package`
- Distro and version: `fedora 32 `

**Comment by garberw** [comment]
garberw@electron> echo $DISPLAY
:0

**Comment by garberw** [comment]
I cleaned up all the excess services I think with this script:


#!/bin/bash                                                                                         

# this script is only for documentation purposes                                                    

DIR="/usr/share/dbus-1/services"
DISABLER=".garberw.disabled"
SERVICE1="${DIR}/org.freedesktop.mate.Notifications.service"
SERVICE2="${DIR}/org.kde.plasma.Notifications.service"

# this is how we get the list of notification services                                              
# do not remove these comments                                                                      
#### $ grep org.freedesktop.Notifications "${DIR}/*.service*                                        
#### /usr/share/dbus-1/services/org.freedesktop.mate.Notifications.service:Name=org.freedesktop.Not\
ifications                                                                                          
#### /usr/share/dbus-1/services/org.kde.plasma.Notifications.service:Name=org.freedesktop.Notificat\
ions                                                                                                
#### /usr/share/dbus-1/services/org.kde.plasma.Notifications.service:Exec=/usr/bin/plasma_waitforna\
me org.freedesktop.Notifications                                                                    
#### /usr/share/dbus-1/services/org.knopwob.dunst.service:Name=org.freedesktop.Notifications        

# do not disable this one                                                                           
# if this one is active dunst will be active                                                        
#### /usr/share/dbus-1/services/org.knopwob.dunst.service                                           

# remove comments below to disable the services and run the script                                  
#    mv "${SERVICE1}" "${SERVICE1}${DISABLER}"                                                      
#    mv "${SERVICE2}" "${SERVICE2}${DISABLER}"                                                      

# eee eof

**Comment by garberw** [comment]
<pre><code>
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
{
        appname: 'notify-send'
        summary: 'GARBAGE'
        body: ''
        icon: 'dialog-information'
        raw_icon set: false
        icon_id: 'dialog-information'
        desktop_entry: ''
        category: 
        timeout: 0
        urgency: NORMAL
        transient: 0
        formatted: '<b>GARBAGE</b>'
        fg: #FF7F50
        bg: #FFFFFF
        frame: #aaaaaa
        fullscreen: show
        progress: -1
        stack_tag: 
        id: 2
        actions: {}
        script: (null)
}
DEBUG: RUN
WARNING: BadAccess (attempt to access private resource denied)
WARNING: Unable to grab mouse button(s).
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Ignoring '65'
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Ignoring '19'
DEBUG: XEvent: Ignoring '19'
</pre></code>

**Comment by fwSmit** [comment]
There's no need to move any of the dbus service files. The only thing you need to do is link org.freedesktop.Notifications.service to org.knopwob.dunst.service. You might need to restart for this to take effect. Dunst will now automatically be started by dbus.
As for notification windows not closing correctly, could you try the master branch of dunst to see if it's still not working there?

**Comment by garberw** [comment]
upgraded to master branch (see below); still get same WARNING; any help please?  I know this is due to a possible incompatibility with compiz window manager not in marco or metacity (I tried them all).  regards.
</code></pre>
garberw@electron> wg-Compiz-Marco-Metacity.sh
(c) compiz or (m) marco (e) metacity (s) show current > s
choosing show current
press enter to continue >
Name: compiz
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF
done; res=0
garberw@electron> which dunst
/usr/local/bin/dunst
garberw@electron> dunst -v
Dunst - A customizable and lightweight notification-daemon v1.5.0-87-g814e620
garberw@electron> ps aux | grep dunst
garberw     3011  0.4  0.0 538960 19264 ?        Ssl  07:51   0:00 /usr/local/bin/dunst
garberw     3286  0.0  0.0 221436   852 pts/1    S+   07:52   0:00 grep --color=auto dunst
garberw@electron> kill 3011
garberw@electron> dunst -print
{
        appname: 'notify-send'
        summary: 'Good morning :-)'
        body: ''
        icon: 'dialog-information'
        raw_icon set: false
        icon_id: 'dialog-information'
        desktop_entry: ''
        category:
        timeout: 0
        urgency: NORMAL
        transient: 0
        formatted: '<b>Good morning :-)</b>'
        fg: #FF7F50
        bg: #FFFFFF
        highlight: #1745d1
        frame: #aaaaaa
        fullscreen: show
        progress: -1
        stack_tag:
        id: 2
        actions: {}
        script_count: 0
}
WARNING: BadAccess (attempt to access private resource denied)
WARNING: Unable to grab mouse button(s).
^Cgarberw@electron>
</code></pre>

**Comment by garberw** [comment]
here is the dump of the dbus during a command:
<pre><code>
garberw@electron> notify-send "WELCOME"
</code></pre>
output resulting ...
<pre><code>
garberw@electron> dbus-monitor path=/org/freedesktop/Notifications
signal time=1612906181.867486 sender=org.freedesktop.DBus -> destination=:1.102 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.102"
signal time=1612906181.867504 sender=org.freedesktop.DBus -> destination=:1.102 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.102"
method call time=1612906203.580355 sender=:1.103 -> destination=:1.94 serial=6 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
method call time=1612906203.581004 sender=:1.103 -> destination=:1.94 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string ""
   string "WELCOME"
   string ""
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
^C
garberw@electron> 
</code></pre>

**Comment by garberw** [comment]
another <B>separate</B> bug; dunst tries to start before X11; apparently something sent a message before X11 started; maybe could queue messages until after X11 starts
<pre><code>
garberw@electron> cat journalctl_-b_after_boot.log
Feb 09 13:19:58 electron.localdomain systemd[2310]: Created slice session.slice.
Feb 09 13:19:58 electron.localdomain dunst[2324]: CRITICAL: Cannot open X11 display.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Starting D-Bus User Message Bus...
Feb 09 13:19:58 electron.localdomain systemd[2310]: dunst.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 13:19:58 electron.localdomain systemd[2310]: dunst.service: Failed with result 'exit-code'.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Failed to start Dunst notification daemon.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Reached target Main User Target.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.kde.baloorunner.service' is not named after the D-Bus name 'org.kde.runners.baloo'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/gnome-vfs-daemon.service' is not named after the D-Bus name 'org.gnome.GnomeVFS.Daemon'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.kde.activitymanager.service' is not named after the D-Bus name 'org.kde.ActivityManager'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.kde.kscreen.service' is not named after the D-Bus name 'org.kde.KScreen'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/sealert.service' is not named after the D-Bus name 'org.fedoraproject.Setroubleshootd'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/imsettings-daemon.service' is not named after the D-Bus name 'com.redhat.imsettings'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.mate.panel.applet.SoftupdApplet.service' is not named after the D-Bus name 'org.mate.panel.applet.SoftupdAppletFactory'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.mate.freedesktop.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Started D-Bus User Message Bus.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Startup finished in 157ms.
Feb 09 13:19:58 electron.localdomain dbus-broker-lau[2330]: Ready
Feb 09 13:19:58 electron.localdomain gdm-password][2293]: gkr-pam: gnome-keyring-daemon started properly and unlocked keyring
Feb 09 13:19:58 electron.localdomain audit[2293]: USER_START pid=2293 uid=0 auid=1000 ses=2 subj=system_u:system_r:xdm_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,pam_selinux,pam_keyinit,pam_namespace,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_gnome_keyring,pam_umask acct="garb>
Feb 09 13:20:00 electron.localdomain kernel: rfkill: input handler enabled
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: (--) Log file renamed from "/home/garberw/.local/share/xorg/Xorg.pid-2347.log" to "/home/garberw/.local/share/xorg/Xorg.0.log"
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: X.Org X Server 1.20.10
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: X Protocol Version 11, Revision 0
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: Build Operating System:  5.7.11-200.fc32.x86_64
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: Current Operating System: Linux electron.localdomain 5.10.13-200.fc33.x86_64 #1 SMP Thu Feb 4 14:54:51 UTC 2021 x86_64
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: Kernel command line: BOOT_IMAGE=(hd0,gpt1)/vmlinuz-5.10.13-200.fc33.x86_64 root=/dev/mapper/main-root ro rd.lvm.lv=main/root rd.lvm.lv=main/00 rhgb quiet
garberw@electron>
</code></pre>

**Comment by garberw** [comment]
another <B>separate</B> bug.  icon paths need to be updated for different desktop environments.  for mate desktop envir.
in dunstrc use ...    
<pre><code>
 icon_path = /usr/share/icons/mate/16x16/status/:/usr/share/icons/mate/16x16/devices/:/usr/share/icons/mate/16x16/apps:/usr/share/icons/hicolor/16x16/apps
</code></pre>
what else needs to be added to this?

**Comment by fwSmit** [comment]
So if I understand it correctly, this issue is caused by an incompatibility from compiz?

Could you open two separate issues for the things you mentioned above, to keep the discussion clean?

**Comment by garberw** [comment]
I moved the queston about icons to <A>https://github.com/dunst-project/dunst/issues/822</A> and I moved the question about messages before start of X to <A>https://github.com/dunst-project/dunst/issues/821</A>

**Comment by fwSmit** [comment]
Thank you for reporting all those issues, I'll look at them soon. For this issue, I would suggest reporting it to compiz, as it seems like an issue on their side. The reason why you're not able to close the notification is because dunst is unable to get input from the X server (probably because of compiz), as you can see in the logs
```
WARNING: BadAccess (attempt to access private resource denied)
WARNING: Unable to grab mouse button(s).
```

**Comment by garberw** [comment]
Thank you :-) moving to compiz wiki/blog.  Yes I believe it may not get any messages from mouse buttons although <pre><code>$ xwininfo</pre></code>and<pre><code>$ xev -id WINDOWID</pre></code> show it is getting messages.

**Comment by garberw** [comment]
put back metacity; give up on compiz; compiz is not under development; <b>compiz translates mouse buttons as seen on line 1539 of</b><pre><code>compiz/src/display.c</code></pre>Unlike marco, metacity does not have annoying feature that it uses mouse location to determine focus; after exiting one program focus returns to previously focused window; also dunst closes window when you click on it;
