### ISSUE TITLE
dunst called before start of X11; MINOR bug and error message

### ISSUE THREAD

**Issue by garberw** [dunst-project/dunst#821]
dunst tries to start before X11; apparently something sent a message before X11 started; maybe could queue messages until after X11 starts.  <pre><code>garberw@electron> cat journalctl_-b_after_boot.log
Feb 09 13:19:58 electron.localdomain systemd[2310]: Created slice session.slice.
Feb 09 13:19:58 electron.localdomain dunst[2324]: CRITICAL: Cannot open X11 display.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Starting D-Bus User Message Bus...
Feb 09 13:19:58 electron.localdomain systemd[2310]: dunst.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 13:19:58 electron.localdomain systemd[2310]: dunst.service: Failed with result 'exit-code'.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Failed to start Dunst notification daemon.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Reached target Main User Target.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.kde.baloorunner.service' is not named after the D-Bus name 'org.kde.runners.baloo'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/gnome-vfs-daemon.service' is not named after the D-Bus name 'org.gnome.GnomeVFS.Daemon'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.kde.activitymanager.service' is not named after the D-Bus name 'org.kde.ActivityManager'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.kde.kscreen.service' is not named after the D-Bus name 'org.kde.KScreen'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/sealert.service' is not named after the D-Bus name 'org.fedoraproject.Setroubleshootd'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/imsettings-daemon.service' is not named after the D-Bus name 'com.redhat.imsettings'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.mate.panel.applet.SoftupdApplet.service' is not named after the D-Bus name 'org.mate.panel.applet.SoftupdAppletFactory'.
Feb 09 13:19:58 electron.localdomain dbus-broker-launch[2330]: Service file '/usr/share//dbus-1/services/org.mate.freedesktop.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Started D-Bus User Message Bus.
Feb 09 13:19:58 electron.localdomain systemd[2310]: Startup finished in 157ms.
Feb 09 13:19:58 electron.localdomain dbus-broker-lau[2330]: Ready
Feb 09 13:19:58 electron.localdomain gdm-password][2293]: gkr-pam: gnome-keyring-daemon started properly and unlocked keyring
Feb 09 13:19:58 electron.localdomain audit[2293]: USER_START pid=2293 uid=0 auid=1000 ses=2 subj=system_u:system_r:xdm_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,pam_selinux,pam_keyinit,pam_namespace,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_gnome_keyring,pam_umask acct="garb>
Feb 09 13:20:00 electron.localdomain kernel: rfkill: input handler enabled
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: (--) Log file renamed from "/home/garberw/.local/share/xorg/Xorg.pid-2347.log" to "/home/garberw/.local/share/xorg/Xorg.0.log"
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: X.Org X Server 1.20.10
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: X Protocol Version 11, Revision 0
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: Build Operating System:  5.7.11-200.fc32.x86_64
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: Current Operating System: Linux electron.localdomain 5.10.13-200.fc33.x86_64 #1 SMP Thu Feb 4 14:54:51 UTC 2021 x86_64
Feb 09 13:20:00 electron.localdomain /usr/libexec/gdm-x-session[2347]: Kernel command line: BOOT_IMAGE=(hd0,gpt1)/vmlinuz-5.10.13-200.fc33.x86_64 root=/dev/mapper/main-root ro rd.lvm.lv=main/root rd.lvm.lv=main/00 rhgb quiet
garberw@electron></code></pre>

### Installation info

- Version: `v1.5.0-87-g814e620`
- Install type: `manual`
- Distro and version: ` fedora32`

**Comment by fwSmit** [comment]
Looking at the systemd unit, it seems like there should be an dependency on the graphical session, not only an PartOf line.
The relevant systemd documentation can be found [here](https://www.freedesktop.org/software/systemd/man/systemd.unit.html).

> PartOf=
>    Configures dependencies similar to Requires=, but limited to stopping and restarting of units. When systemd stops or restarts the units listed here, the action is propagated to this unit. Note that this is a one-way dependency — changes to this unit do not affect the listed units.
>    When PartOf=b.service is used on a.service, this dependency will show as ConsistsOf=a.service in property listing of b.service. ConsistsOf= dependency cannot be specified directly.

It seems like PartOf only influences stopping and restarting, not starting.

[This](https://github.com/emersion/mako/blob/master/contrib/systemd/mako.service.in) is mako's systemd unit file. They add
```
After=graphical-session.target
```
to make sure the unit is started after the graphical session. Could you try adding that as well (with `systemd edit --full dunst.service` I think)

**Comment by garberw** [comment]
I could not figure out "systemd edit --full dunst.service" so I manually edited as follows then rebooted 
<pre><code>garberw@electron> cd /usr/lib/systemd/user
garberw@electron> ls dunst.service*
dunst.service  dunst.service.garberw.orig
garberw@electron> cat dunst.service
[Unit]
Description=Dunst notification daemon
Documentation=man:dunst(1)
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=dbus
BusName=org.freedesktop.Notifications
ExecStart=/usr/bin/dunst
garberw@electron> </code></pre>That error persisted.

**Comment by fwSmit** [comment]
I believe you have to run `sytemctl daemon-reload` after editing manually, but maybe rebooting works as well.
Maybe you have to add this as well
```
[Install]
WantedBy=graphical-session.target
```

**Comment by garberw** [comment]
that did not fix it either.  dunst still appears in log before X11 I think.

**Comment by garberw** [comment]
yes !!!! I updated by <pre><code>cd /usr/lib/systemd/user/
mv dunst.service dunst.service.disabled
systemctl daemon-reload</code></pre>and created a desktop envoironment (gnome or mate or kde etc.) autostart-on-login file.  This works and you can use the desktop environment "startup preferences" in mate to turn it on or off which is convenient.  This also solves<A>https://github.com/dunst-project/dunst/issues/820</A>.

**Comment by fwSmit** [comment]
Couldn't reproduce this issue by the way. I added
```
[Install]
WantedBy=graphical-session.target
```
 because of a warning from systemd.

**Comment by garberw** [comment]
My mistake.  A former install left this "systemd --user" file lying around.  Removing it removed this bug.  In the end I left the (non-user) systemd service as the means of starting dunst.  <pre><code>garberw@electron> pwd
/home/garberw/.config/systemd/user/default.target.wants
garberw@electron> ls -l
dunst.systemd -> /usr/lib/systemd/user/dunst.service</code></pre>For more on this approach by using systemd --user services, see a good reference <a>https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg</a> but I do not recommend it.

**Comment by garberw** [comment]
yes thank you
