### ISSUE TITLE
MINOR issue; icon paths need to be adjusted for different desktop environments

### ISSUE THREAD

**Issue by garberw** [dunst-project/dunst#822]
icon paths need to be updated for different desktop environments. for mate desktop environment in dunstrc use ...
<pre><code>icon_path = /usr/share/icons/mate/16x16/status/:/usr/share/icons/mate/16x16/devices/:/usr/share/icons/mate/16x16/apps:/usr/share/icons/hicolor/16x16/apps</code></pre>what else needs to be added to this?

### Installation info

- Version: `v1.5.0-87-g814e620`
- Install type: `manually`
- Distro and version: ` fedora 32`

**Comment by fwSmit** [comment]
Currently we leave it up to users to change the icon_path to something sensible for their desktop environment. We could improve this by adding some more icon sets to the default icon_path. I'm open to adding more suggestions for icon paths.
Also, to make sure the icon_path doesn't get too long, we could make the icon_path recursive. So you only need to add `/usr/share/icons/mate/16x16/` and get all the 16x16 icons.

**Comment by garberw** [comment]
if it is recursive that would probably solve the problem in general.  the first posting is an adequate solution in my specific case.  thank you :-)

**Comment by fwSmit** [comment]
I don't think we would want `/usr/share/icons/` to be the default icon path if it's recursive, since you would get inconsistently sized 
icons, depending on the theme.
Also apparently we should add the hicolor theme as a fallback according to the spec: https:// standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

**Comment by garberw** [comment]
yes it seems hicolor is closest to what we want :-)

**Comment by fwSmit** [comment]
I've added a few commits, because the default setting wasn't working. Let me know if it works now :)

**Comment by fwsmit** [comment]
The fix has now been merged. You can set an icon theme with `icon_theme = mate, hicolor`
