### ISSUE TITLE
Space at line 40 causes make to output an error.

### ISSUE THREAD

**Issue by hackedWifi** [dunst-project/dunst#824]
Trying to compiled from source causes an error with make at line 40 due to an extra space. 
```
ifeq (,${DATA_DIR_WAYLAND_PROTOCOLS})
	$(warning "Failed to query $(PKG_CONFIG) for package 'wayland-protocols'!")
endif
endif
```
I fixed that by removing the extra space.
So, I based on the README.md WAYLAND=1 SYSTEMD=1 means no support for it.
```
SYSTEMD=(0|1): Enable/Disable the systemd unit. (Default: detected via pkg-config)
WAYLAND=(0|1): Enable/Disable wayland support. (Default: 1)
```
` make WAYLAND=1 SYSTEMD=1` produces the following error
```
Makefile:40: "Failed to query pkg-config for package 'wayland-protocols'!"
Package wayland-client was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-client.pc'
to the PKG_CONFIG_PATH environment variable
Package 'wayland-client', required by 'virtual:world', not found
Package wayland-client was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-client.pc'
to the PKG_CONFIG_PATH environment variable
Package 'wayland-client', required by 'virtual:world', not found
Makefile:49: *** "pkg-config failed!".  Stop.
```
make runs fine with `make WAYLAND=0 SYSTEMD=0`

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon v1.5.0-87-g814e620
`
- Install type: `compiled from source`
- Distro and version: ` kernel 5.4.92-gentoo `

**Comment by fwSmit** [comment]
Good catch, I'll fix that one.

> So, I based on the README.md WAYLAND=1 SYSTEMD=1 means no support for it.

No, WAYLAND=0 and SYSTEMD=0 means to disable them. We should probably flip around the wording.

> make runs fine with make WAYLAND=1 SYSTEMD=1

Do you mean WAYLAND=0?

**Comment by hackedWifi** [comment]
> Good catch, I'll fix that one.
> 
> > So, I based on the README.md WAYLAND=1 SYSTEMD=1 means no support for it.
> 
> No, WAYLAND=0 and SYSTEMD=0 means to disable them. We should probably flip around the wording.
> 
> > make runs fine with make WAYLAND=1 SYSTEMD=1
> 
> Do you mean WAYLAND=0?

Yes, you are correct. I noticed the pull request that fixes the indent and the wording in the README.md
Thank you.
