### ISSUE TITLE
Toggling pause status doesn't display window until next update

### ISSUE THREAD

**Issue by tsipinakis** [dunst-project/dunst#827]
Steps to reproduce:
* Start dunst
* `dunstctl set-paused true`
* `notify-send test`
* `dunstctl set-paused false`

The notification will not appear until the window focus changes.

We already call `wake_up()` when changing pause status so I can't find an obvious cause here. This needs some more investigating.

### Installation info

- Version: 167d7dd
- Install type: manually
- Distro and version: ` Debian Buster`

**Comment by fwSmit** [comment]
I couldn't reproduce on wayland, but I could when forcing xwayland. So it's probably somewhere in src/x11/*.
Btw, I changed `set-pause` to `set-paused` in your comment. I assume you ran the correct command.

**Comment by tsipinakis** [comment]
>  I assume you ran the correct command
Indeed, typo. Fixed.

Calling `wake_up()` twice appears to work. Weird. Additionally `notify-send DUNST_COMMAND_PAUSE && notify-send Test1 && notify-send DUNST_COMMAND_RESUME` also appears to work. Weird.

**Comment by tsipinakis** [comment]
I've narrowed this down to being because we call `cairo_paint` (in `x_display_surface`) before `x_win_show` if I place a `x_win_show()` call before that it works.
Perhaps e09e29968afef7c40604cccad47e6f62e47e32bd was wrong and it only works because we redraw pretty frequently?

**Comment by fwSmit** [comment]
> I've narrowed this down to being because we call `cairo_paint` (in `x_display_surface`) before `x_win_show` if I place a `x_win_show()` call before that it works.
> Perhaps [e09e299](https://github.com/dunst-project/dunst/commit/e09e29968afef7c40604cccad47e6f62e47e32bd) was wrong and it only works because we redraw pretty frequently?

According to that theory it will also break if you don't send a notification in a while.
I'm thinking that maybe it goes wrong at the pause already. Since it's called async (I think) it might leave the buffer in a weird state.

**Comment by sukima** [comment]
> Additionally `notify-send DUNST_COMMAND_PAUSE && notify-send Test1 && notify-send DUNST_COMMAND_RESUME` also appears to work.

**Thank you** @tsipinakis This saved my i3lock setup. I'm stuck on dunst v1.5.0 (thanks Ubuntu), Could not find any mention of those commands in the man pages. 🙇
