### ISSUE TITLE
Script is not being run when dunst is started from dbus

### ISSUE THREAD

**Issue by fwSmit** [dunst-project/dunst#828]
To reproduce:

- Make sure your dunstrc contains something that triggers a script.
I tested with the following script
```sh
#!/bin/sh
echo "something" >> /tmp/dunst_log
```
- Then run the following
```sh
pkill dunst
notify-send "Trigger script"
```
A notification from dunst appears.

I would expect a line of text to appear in /tmp/dunst_log as well, but nothing was appended.
This only happens when dunst is started with dbus.

### Installation info

- Version: `v1.5.0-87-g814e620`
- Install type: `AUR`
- Distro and version: `Arch linux`

**Comment by tsipinakis** [comment]
What path are you using for the script? Perhaps dbus starts dunst with a different working directory?

**Comment by fwSmit** [comment]
Oh good point, I should use an absolute path for scripts. It's probably good to recommend that in general
