### ISSUE TITLE
Maximum amount of lines

### ISSUE THREAD

**Issue by advilm** [dunst-project/dunst#829]
Feature request: I would like a way to limit the amount of lines that dunst can display in a notification. I only use dunst for a quick preview which I can use to jump to an unread notification and I don't need more than a few lines displayed. It gets annoying when someone sends a large message.

### Installation info

- Version: `1.5.0 (2020-07-23)`
- Install type: `package`
- Distro and version: ` Arch Linux`

**Comment by fwSmit** [comment]
Most programs that send notifications already don't send the whole message of it's very long. What program are you using that sends such long notifications?

**Comment by advilm** [comment]
Discord

**Comment by fwSmit** [comment]
I don't this feature should be included in dunst. Clients like discord should send messages with a reasonable length. My email client doesn't send the entire email as a notification either.

**Comment by fwSmit** [comment]
It seems like the same issue was posted earlier in #625. Let's continue the conversation there
