### ISSUE TITLE
1.6.1 fails to start on wayland compositors without zwlr_layer_shell_v1 support

### ISSUE THREAD

**Issue by alebastr** [dunst-project/dunst#833]
The new wayland code works fine on sway, wayfire and other wlroots-based compositors (and probably recent kwin as it supports layer-shell). Thanks a lot for implementing this feature!
However on a compositors without the required protocol support (weston, gnome) dunst fails to start with error message about missing protocols.

Steps to reproduce:
1. Start weston with [xwayland support enabled in weston.ini](https://wayland.freedesktop.org/xserver.html#heading_toc_j_5)
2. `systemctl --user import-envronment DISPLAY WAYLAND_DISPLAY`
3. `systemctl --user start dunst`
4. The same result is reproducible when running `dunst` from the terminal. Deleting `WAYLAND_DISPLAY` env variable allows `dunst` to start in X11 mode

Expected behavior:
`dunst` fails to register required wayland interfaces and falls back to X11 backend.

Actual results: 
```
Feb 21 15:51:54 localhost.localdomain systemd[987]: Starting Dunst notification daemon...
Feb 21 15:51:54 localhost.localdomain dunst[13765]: ERROR: compositor doesn't support zwlr_layer_shell_v1
Feb 21 15:51:54 localhost.localdomain systemd-coredump[13769]: Process 13765 (dunst) of user 1000 dumped core.

                                                               Stack trace of thread 13765:
                                                               #0  0x00007f8340559913 g_logv (libglib-2.0.so.0 + 0x5b913)
                                                               #1  0x00007f8340559b83 g_log (libglib-2.0.so.0 + 0x5bb83)
                                                               #2  0x00005632bd9e0ebe wl_init (dunst + 0x14ebe)
                                                               #3  0x00005632bd9d8633 main (dunst + 0xc633)
                                                               #4  0x00007f834034b1e2 __libc_start_main (libc.so.6 + 0x281e2)
                                                               #5  0x00005632bd9d8cee _start (dunst + 0xccee)
```

### Installation info

- Version: `1.6.1`
- Install type: package (found while preparing update for Fedora)
- Distro and version: ` Fedora 33`

**Comment by fwSmit** [comment]
Thanks for the report. I didn't think of adding the fallback. I will fix it soon. A workaround for now would be to set 'force_xwayland = true' in the dunstrc.

**Comment by fwSmit** [comment]
#834 should fix this issue.
