### ISSUE TITLE
Config options for progress bar color

### ISSUE THREAD

**Issue by FollieHiyuki** [dunst-project/dunst#835]
I think this is not raised yet.

**Comment by fwSmit** [comment]
You can use the highlight color for that. Currently it's only used for the progress bar color.
I called it highlight, because other small elements might also use this color in the future

**Comment by FollieHiyuki** [comment]
Thanks for the quick response. Close then.
I kept searching the man page for a wrong word, hence couldn't find the option ;)

**Comment by RedDofamine** [comment]
For dumbs like me:
# white color for bar
highlight = "#ffffff"

**Comment by DimaGashko** [comment]
I mean... Border color (frame-color is not enough)? "Foreground" (background of empty bar)
