### ISSUE TITLE
Wayland HiDPI Font Scaling Blurriness

### ISSUE THREAD

**Issue by adamcstephens** [dunst-project/dunst#836]
When scaling my HiDPI screens in Wayland, the text is blurry. The font is the same between dunst and the terminal/waybar.

I'm happy to try any tweaking or configuration ideas. Setting `GDK_SCALE=2` didn't seem to make a difference.

Monitor (scaling=1.3)
![dunst-monitor](https://user-images.githubusercontent.com/2071575/109251554-b12b6b80-77b9-11eb-904c-ac27e585734c.png)

Laptop screen (scaling=2)
![dunst-laptop](https://user-images.githubusercontent.com/2071575/109251577-b8eb1000-77b9-11eb-95ab-700cfd076b52.png)

### Installation info

- Version: `1.6.1`
- Install type: `modified Debian package`
- Distro and version: `Debian Bullseye`

**Comment by fwSmit** [comment]
Currently hidpi is not implemented by the dundt wayland code. The surface is now scaled up by your compositor.
I don't know if the hidpi situation was better on 
Xorg, but you can try falling back to it with `force_xwayland = true` in your dunstrc until it's implemented in our wayland code.

**Comment by bebehei** [comment]
What is missing here to implement scaling inside dunst on wayland? I've bought a 4k-screen today and found myself having the same issue.

If I remember correctly, on Xorg you could set `Xft.dpi` in the `Xresources` to something higher than 96 to implement scaling. (which worked, but was quite clumsy).

**Comment by fwSmit** [comment]
We currently do nothing with the scaling factor we get from wayland. We should pass that value I believe to both Cairo and pango. I'll have to look into it a bit more to give detailed information.
