### ISSUE TITLE
Disabled Sorting Order Is Not Honored While Dunst Is Paused

### ISSUE THREAD

**Issue by S-u-b** [dunst-project/dunst#838]
I have the "sort" option set to false within the Dunst configuration, which currently sorts notifications in the following, vertically stacked, order:
**10
9
8
7
6
5
4
3
2
1**

When generated as follows:
**notify-send 1
notify-send 2
notify-send 3
notify-send 4
notify-send 5
notify-send 6
notify-send 7
notify-send 8
notify-send 9
notify-send 10**

However, when pausing Dunst, the notification order seems`*` to change back to the default behavior, as if the "sort" option was set to true, where the ordering of the numbered notifications shown above is reversed (_1..10 top to bottom, rather than 10..1_), but only while Dunst is paused.  For example, the following:
**notify-send 1
notify-send 2
notify-send 3
notify-send 4
dunstctl set-paused true
notify-send 5
notify-send 6
dunstctl set-paused false
notify-send 7
notify-send 8
dunstctl set-paused true
notify-send 9
notify-send 10
dunstctl set-paused false**

Generates:
**8
7
4
3
2
1
5
6
9
10**

But the expected results were that it would show the notifications in the same order, whether or not Dunst is being paused/unpaused, ie:
**10
9
8
7
6
5
4
3
2
1**

Looking through the issue history, I found past bug reports related to the sort option:
[#Add option to always sort messages chronologically based on when they arrived? · Issue #301](https://github.com/dunst-project/dunst/issues/301)
[#Queue handling with settings.sort · Issue #431](https://github.com/dunst-project/dunst/issues/431)

But I don't think they're directly related to this bug, as they don't reference the sorting behavior while Dunst is paused.

`*` Also, it's worth noting that the urgency of the notification doesn't seem to impact the ordering when the "sort" config option is disabled, but it definitely does when this option is enabled, and seems to behave as described while Dunst is either paused or unpaused.

### Installation info

- Version: Dunst - A customizable and lightweight notification-daemon v1.6.1
- Install type: manual, from source
- Distro and version: Xorg using Linux distro

**Comment by fwSmit** [comment]
I was able to reproduce this issue. It seems like the notifications appear at the bottom of the list when they're added during pausing.
I suspect it will also happen if you set `fullscreen=pushback` in a rule in your dunstrc. I'm not able to test that currently though.

**Comment by fwSmit** [comment]
With a bit of a delay, I have a fix for you. Firstly, the setting name `sort` is a bit confusing since the notifications are still sorted when it's set to false. It should actually be named `sort_urgency`, since it determines if the notifications are sorted based on urgency. When `sort` is set to false, the notifications are sorted based on ID, which is in most cases the same as sorting based on time.

**Comment by S-u-b** [comment]
@fwSmit: thank you, and sorry for my belated follow-up! I think this does fix the underlying issue and now has Dunst produce the notifications in the ascending sorting order that it was likely meant to originally, reversing the descending sorting order behavior of the notifications that you used to see when disabling the sort option.

Although the change may break some people's current [expectations](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) of how this poorly named "sort" option works when disabled, and including it in a stable release should probably be held off on until the sorting order can be made configurable too?  I've submitted a new feature request asking for just that:
#845 Feature Request: Configurable Notification Sorting Order (Ascending / Descending / Random?)

**Comment by fwSmit** [comment]
Thank you for your thoughtful response, I will look into those issues.
