### ISSUE TITLE
Installation fails without XScreenSaver

### ISSUE THREAD

**Issue by IonicsTheRealOne** [dunst-project/dunst#839]
Not all systems use **XScreenSaver**, like I am using **i3lock** with **xsslock**. Does **XScreenSaver** really have to be a requirement?

The Arch package is not up-to-date so I had to install dunst manually, following the documentation.
```
cd dunst
make
```
Terminates with fatal error:
```
cc -o src/dbus.o -c src/dbus.c -D_DEFAULT_SOURCE -DVERSION=\"v1.6.1-13-g3acffdb\"  -g --std=gnu99 -pedantic -Wall -Wno-overlength-strings -Os  -DENABLE_WAYLAND  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -pthread  -MMD -MP
In file included from src/settings.h:13,
                 from src/dbus.c:14:
src/x11/x.h:10:10: fatal error: X11/extensions/scrnsaver.h: No such file or directory
   10 | #include <X11/extensions/scrnsaver.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:83: src/dbus.o] Error 1
```

I apologize if I am missing something.

### Installation info

- Version: 1.6.1
- Install type: manually
- Distro and version: Arch Linux

**Comment by tsipinakis** [comment]
We use the XScreenSaver extension in order to check the user idle status so yes, it's a hard dependency.

**Comment by Narrat** [comment]
On Arch the whole xscreensaver package isn't needed. The package libxss offers this library.
If you want to update a package from the repositories, I would suggest the program asp. This allows the retrieval of the dunst PKGBUILD, which you can use to update the package.

**Comment by IonicsTheRealOne** [comment]
Reinstalling libxss and the other required packages fixed it. For some reason many X11/extensions/*.h files were missing, even if the packages were installed. Thank you, highly appreciated.
