### ISSUE TITLE
CRITICAL: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'naughty' with PID '480597'.

### ISSUE THREAD

**Issue by Henryws** [dunst-project/dunst#841]
I have awesomewm installed and I've removed all traces of naughty in rc.lua and dunst keeps saying that it can't acquire org.freedesktop.notifications

rc.lua: https://paste.ubuntu.com/p/pbK5FM8p4C/

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon v1.6.1-13-g3acffdb`
- Install type: `aur`
- Distro and version: `Arch Linux`

**Comment by fwSmit** [comment]
You'll also have to autostart Dunst with your window manager.

**Comment by Henryws** [comment]
It says this now:
`WARNING: BadAccess (attempt to access private resource denied)
WARNING: BadAccess (attempt to access private resource denied)
WARNING: Unable to grab key 'ctrl+grave'.
CRITICAL: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'naughty' with PID '5030'.`

**Comment by Henryws** [comment]
I fixed it by putting: `local old_dbus = dbus
dbus = nil
local naughty = require("naughty")
dbus = old_dbus` and `package.loaded["naughty.dbus"] = {}
` in my rc.lua

**Comment by fwSmit** [comment]
> I fixed it by putting: `local old_dbus = dbus dbus = nil local naughty = require("naughty") dbus = old_dbus` and `package.loaded["naughty.dbus"] = {} ` in my rc.lua

That's a bit of a hack. I think just removing the `naughty = require("naughty")`  would do the trick as well.
