### ISSUE TITLE
Make separator area unreceptive to mouse action

### ISSUE THREAD

**Issue by Iss-in** [dunst-project/dunst#842]
Currently Separator is counted as a part of notification above it and any click on this area will be interpreted as mouse click action on that notification. 

It will be in better practice to render that part of area as unresponsive to any mouse action. will it be possible ?

**Comment by fwSmit** [comment]
Yes, it's definitely possible, but it will take some effort in calculating the right position.
Another thing that could be improved is that on wayland, the rounded corners are still part of the notification.

**Comment by Iss-in** [comment]
thanks a lot, this was minor but important fix
