### ISSUE TITLE
[Feature Request] Logging

### ISSUE THREAD

**Issue by seniorm0ment** [dunst-project/dunst#843]
Requesting the ability to output all notifications to a log, to easily refer back to the notifications. Basically a history of notifications in a txt file.

The user could set basic things, such as auto purge after X amount of time/days/weeks/months/etc to keep the file small, log location, timestamps,  as well as a basic whitelist/blacklist. For example if you don't want it logging messages from certain programs (maybe sensitive info).

This log would allow users to refer back to notifications they miss or click away, it would also allow scripting opportunities, for example a live log on another monitor to keep open, or for other applications to grab from or pipe into other scripts, etc.

It'd be minimal, and I think it would be a nice feature.

**Comment by tsipinakis** [comment]
This has been asked before but my opinion remains the same: I am against implementing this for privacy reasons, it's too easy to enable it and forget that it's actually enabled.

If someone really wants this for some reason, all notification information can be passed to scripts, you can implement a custom logger by piping all script variables to a file.

**Comment by fwSmit** [comment]
If you want to see notifications you missed, take a look at dunstctl's history-pop feature. Another thing that's somewhat relevant is `dunst -print`.

**Comment by fwSmit** [comment]
> This has been asked before but my opinion remains the same: I am against implementing this for privacy reasons, it's too easy to enable it and forget that it's actually enabled.

I don't entirely agree about the privacy part. If someone can run commands on someone's user they can access all the notifications anyways with dbus-monitor. If you set the permissions of the log file to 640 not much risk is added. I still don't think that notification logging should be implemented though.
What could be better is the debug logging. That would maybe help solve #757.

**Comment by fwSmit** [comment]
@grravity  you haven't mentioned your use case, but can you work with the solutions mentioned in the above comments?

**Comment by grravity** [comment]
I haven't had a chance to look at it yet, however I can't say I entirely understand the privacy concerns around it. It would be disabled by default, and if the user chooses to enable it they should assume responsibility.
I just don't see the reason not to implement it, again optional off by default.

However I'll look at the print and history pop more when I get some time.

**Comment by fwSmit** [comment]
> I can't say I entirely understand the privacy concerns around it. It would be disabled by default, and if the user chooses to enable it they should assume responsibility.
> I just don't see the reason not to implement it, again optional off by default.

Yeah, I don't share the same privacy concerns either, especially when the log files are rotated often. That said, it takes some effort to implement this and I don't see what is missing from the current possibilities. Let me know when you had the time to look at it, and if something is missing from the current options.

**Comment by fwSmit** [comment]
Closing this, as we likely don't need changes to this
