### ISSUE TITLE
Feature Request: Configurable Notification Sorting Order (Ascending / Descending / Random?)

### ISSUE THREAD

**Issue by S-u-b** [dunst-project/dunst#845]
This request is related to the following bug report:
#838 Disabled Sorting Order Is Not Honored While Dunst Is Paused

Lets call the new global option being made available to control this behavior: "sort_order" (_or go with whatever you prefer_).  Once implemented, generating notifications as follows:
`notify-send 1`
`notify-send 2`
`notify-send 3`
`notify-send 4`
`notify-send -u low 1`
`notify-send -u low 2`
`notify-send -u low 3`
`notify-send -u low 4`
`notify-send -u critical 1`
`notify-send -u critical 2`
`notify-send -u critical 3`
`notify-send -u critical 4`

Would produce these notification results (_when using the default "true" value for the "sort", or more aptly named: "sort_urgency", option; a "false" value would simply make Dunst not group the notifications by urgency at all_):

* when **sort_order** in the dunstrc configuration is set to **ascending**:
1 (_critical_)
2 (_critical_)
3 (_critical_)
4 (_critical_)
1
2
3
4
1 (_low_)
2 (_low_)
3 (_low_)
4 (_low_)

* when **sort_order** in the dunstrc configuration is set to **descending**:
4 (_low_)
3 (_low_)
2 (_low_)
1 (_low_)
4
3
2
1
4 (_critical_)
3 (_critical_)
2 (_critical_)
1 (_critical_)

* when **sort_order** in the dunstrc configuration is set to **random** (_results may actually vary; I'm also not strongly attached to getting this particular setting choice, so I'd be fine with you deciding that it's too much of a gimmick and not implementing it_):
1 (_low_)
4 (_low_)
3 (_low_)
2 (_low_)
1
4
2
3
3 (_critical_)
1 (_critical_)
2 (_critical_)
4 (_critical_)

**Comment by fwSmit** [comment]
Thank you for the clear feature request. I agree we should add an setting `sort_order` with the options of descending or ascending (random isn't useful I think), and rename `sort` to `sort_urgency` (and add a deprecation warning message for the old name).

**Comment by fwSmit** [comment]
There is also one thing I would like to change internally. Currently the notifications are sorted based on their ID, which is almost, but not exactly the same as ordering based on their time. For I will change that to sorting based on their arival time (which is not updated when the notification is updated). There's also the option of sorting based on their update time, which we maybe could add later.

**Comment by S-u-b** [comment]
> Thank you for the clear feature request. I agree we should add an setting `sort_order` with the options of descending or ascending (random isn't useful I think), and rename `sort` to `sort_urgency` (and add a deprecation warning message for the old name).
> Edit: I just noticed that my interpretation of ascending is different from yours. I would say that ascending means higher urgency, the more you go down the list. Is there a better name for those options?

I think that this sort ordering could then perhaps be applied to both options, which would yield the following combinations (_based on my original `notify-send ...` command examples_):


**1\)**
sort_order -> ascending (_"lowest id or oldest arrival/update time" -> "highest id or newest arrival/update time"_)
+
sort_urgency -> ascending (_low -> normal -> critical_)
\=
1 (_low_)
2 (_low_)
3 (_low_)
4 (_low_)
1
2
3
4
1 (_critical_)
2 (_critical_)
3 (_critical_)
4 (_critical_)

**2\)**
sort_order -> ascending (_"lowest id or oldest arrival/update time" -> "highest id or newest arrival/update time"_)
+
sort_urgency -> descending (_critical -> normal -> low_)
\=
1 (_critical_)
2 (_critical_)
3 (_critical_)
4 (_critical_)
1
2
3
4
1 (_low_)
2 (_low_)
3 (_low_)
4 (_low_)

**3\)**
sort_order -> descending (_"highest id or newest arrival/update time" -> "lowest id or oldest arrival/update time"_)
+
sort_urgency -> ascending (_low -> normal -> critical_)
\=
4 (_low_)
3 (_low_)
2 (_low_)
1 (_low_)
4
3
2
1
4 (_critical_)
3 (_critical_)
2 (_critical_)
1 (_critical_)

**4\)**
sort_order -> descending (_"highest id or newest arrival/update time" -> "lowest id or oldest arrival/update time"_)
+
sort_urgency -> descending (_critical -> normal -> low_)
\=
4 (_critical_)
3 (_critical_)
2 (_critical_)
1 (_critical_)
4
3
2
1
4 (_low_)
3 (_low_)
2 (_low_)
1 (_low_)


Also, for those who don't care to group the notifications by urgency at all, the sort_urgency option should probably take an additional "none" value, so that it produces the same behavior that the original sort option used to produce when it was set to "false"?  This would provide 2 additional sort_order / sort_urgency combinations (_the notifications only *appear* to be grouped by urgency because of the order in which the `notify-send ...` commands were run, but should no longer really appear at fixed points in the overall list of notifications_):

**1\)**
sort_order -> ascending (_"lowest id or oldest arrival/update time" -> "highest id or newest arrival/update time"_)
+
sort_urgency -> none
\=
1
2
3
4
1 (_low_)
2 (_low_)
3 (_low_)
4 (_low_)
1 (_critical_)
2 (_critical_)
3 (_critical_)
4 (_critical_)

**2\)**
sort_order -> descending (_"highest id or newest arrival/update time" -> "lowest id or oldest arrival/update time"_)
+
sort_urgency -> none
\=
4 (_critical_)
3 (_critical_)
2 (_critical_)
1 (_critical_)
4 (_low_)
3 (_low_)
2 (_low_)
1 (_low_)
4
3
2
1


Making what the notification sorting is based on (_ie id, arrival time, update time, etc_) configurable too sounds like a good idea to me :slightly_smiling_face:, and will likely help close out past issue requests asking for this, but I'm content with the current id based sorting.

In any case, feel free to implement these changes as you best see fit.

**Comment by fwSmit** [comment]
Ref: #206
