### ISSUE TITLE
Cannot make test file with the same name as source file

### ISSUE THREAD

**Issue by fwSmit** [dunst-project/dunst#850]
I recently tried adding tests for settings and draw, but when I make a file called `test/draw.c` or `test/settings.c` it wont link.
``` sh
make test
...
/usr/bin/ld: src/x11/x.o: warning: relocation against `win' in read-only section `.text'
/usr/bin/ld: test/dunst.o: in function `run':
/home/friso/git-repos/dunst/test/../src/dunst.c:69: undefined reference to `output'
/usr/bin/ld: /home/friso/git-repos/dunst/test/../src/dunst.c:70: undefined reference to `output'
/usr/bin/ld: /home/friso/git-repos/dunst/test/../src/dunst.c:78: undefined reference to `draw'
/usr/bin/ld: /home/friso/git-repos/dunst/test/../src/dunst.c:79: undefined reference to `output'
/usr/bin/ld: /home/friso/git-repos/dunst/test/../src/dunst.c:79: undefined reference to `win'
/usr/bin/ld: /home/friso/git-repos/dunst/test/../src/dunst.c:81: undefined reference to `output'
/usr/bin/ld: /home/friso/git-repos/dunst/test/../src/dunst.c:81: undefined reference to `win'
/usr/bin/ld: test/dunst.o: in function `dunst_main':
/home/friso/git-repos/dunst/test/../src/dunst.c:183: undefined reference to `draw_setup'
/usr/bin/ld: test/dunst.o: in function `teardown':
/home/friso/git-repos/dunst/test/../src/dunst.c:136: undefined reference to `draw_deinit'
/usr/bin/ld: src/x11/x.o: in function `x_mainloop_fd_dispatch':
/home/friso/git-repos/dunst/src/x11/x.c:292: undefined reference to `draw'
/usr/bin/ld: /home/friso/git-repos/dunst/src/x11/x.c:375: undefined reference to `draw'
/usr/bin/ld: src/x11/x.o: in function `x_win_corners_shape':
/home/friso/git-repos/dunst/src/x11/x.c:114: undefined reference to `draw_rounded_rect'
/usr/bin/ld: src/x11/x.o: in function `x_win_get_context':
/home/friso/git-repos/dunst/src/x11/x.c:184: undefined reference to `win'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make: *** [Makefile:123: test/test] Error 1
```

Adding `int output` to `test/draw.c` gets rid of the warning that output is not defined, suggesting that `test/draw.c` is included over `src/draw.c`.

EDIT: a workaround is adding
```
#include "../draw.c"
```
but I still consider this a bug.

**Comment by bebehei** [comment]
I'm not able to understand your point fully.

But the error-message you're seeing is:


```
/usr/bin/ld: /home/friso/git-repos/dunst/test/../src/dunst.c:70: undefined reference to `output'
```

This is in the linker phase, so your whole code is already built. It's just that your object is missing now the symbol `output`. Usually there is another compilation unit, which is not linked into the final object. Some things like `-L`/`-l` are missing.

**Comment by bebehei** [comment]
It might be because of [Makefile line 123](https://github.com/dunst-project/dunst/blob/3acffdb194de931bc9f21145a4a895371a93e2da/Makefile#L123). There the objects are explicitly filtered out. But this is just a wild guess.

**Comment by fwSmit** [comment]
> I'm not able to understand your point fully.
> 
> But the error-message you're seeing is:
> 
> ```
> /usr/bin/ld: /home/friso/git-repos/dunst/test/../src/dunst.c:70: undefined reference to `output'
> ```
> 
> This is in the linker phase, so your whole code is already built. It's just that your object is missing now the symbol `output`. Usually there is another compilation unit, which is not linked into the final object. Some things like `-L`/`-l` are missing.

What I think is happening is that instead of including src/draw.c,  test/draw.c is included in source files. That explains what the include in the test file makes a difference. Just running make Dunst still works, so it might be that line indeed

**Comment by fwSmit** [comment]
> It might be because of [Makefile line 123](https://github.com/dunst-project/dunst/blob/3acffdb194de931bc9f21145a4a895371a93e2da/Makefile#L123). There the objects are explicitly filtered out. But this is just a wild guess.

I've looked more into it, and it seems that is indeed the line. It makes sure that instead of `src/draw.c`, `test/draw.c` is being compiled. This is because the test files always include their respective source file. If they were both compiled you would get a multiple definition error. I think we can leave it this way, because in release these files are not being included, so there is no chance of accidentally using a test object.
