### ISSUE TITLE
KeePassXC and Ripcord notifications show in tray instead of Dunst

### ISSUE THREAD

**Issue by txtsd** [dunst-project/dunst#852]
Whenever [KeePassXC](https://github.com/keepassxreboot/keepassxc/) and [Ripcord](https://cancel.fm/ripcord/) send a notification, they are not caught and shown in Dunst. Instead, they show up in the system tray as notification balloons.
Other Qt apps like qBittorrent show native notifications with Dunst correctly.

### Screenshots
![](https://0x0.st/-TRA.png)
![](https://0x0.st/-TRm.png)

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.5.0 (2020-07-23)`
- Install type: `package`
- Distro and version: `Arch Linux`

**Comment by fwSmit** [comment]
This is most likely an issue with KeePass and ripcord. If they don't send notifications over dbus according to the notification spec, Dunst can't see them. You'll have to open an issue there, or use a workaround. After a quick search I found this, which may help for ripcord https://github.com/efskap/discord-notify.

**Comment by txtsd** [comment]
@phoerious Does KeePassXC do dbus correctly?

**Comment by fwSmit** [comment]
> @phoerious Does KeePassXC do dbus correctly?

Or more precisely, does it follow the [notification spec](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html) on linux?

**Comment by bebehei** [comment]
I can confirm, that KeePassXC uses the notification spec and works with dunst flawlessly. If you have QT balloons, this mostly has the reason, that you've started keepassxc before starting dunst and keepassxc wanted to create a notification, but failing to find `org.freedesktop.Notification` DBus-Interface. (likewise for any other app).

**Comment by bebehei** [comment]
So, to test it: Restart KeepassXC after session login and test it again. This should work then.

**Comment by txtsd** [comment]
Just restarted KeePassXC and tried it. I still get the tray balloon.
![](https://0x0.st/-Tht.png)

Are there any logs I could provide that would help find what's happening?

**Comment by fwSmit** [comment]
> I can confirm, that KeePassXC uses the notification spec and works with dunst flawlessly. If you have QT balloons, this mostly has the reason, that you've started keepassxc before starting dunst and keepassxc wanted to create a notification, but failing to find `org.freedesktop.Notification` DBus-Interface. (likewise for any other app).

Most apps will try to send a notification, and it dunst isn't already started dunst will be autostarted by dbus.

**Comment by bebehei** [comment]
> Most apps will try to send a notification, and it dunst isn't already started dunst will be autostarted by dbus.

This is true. Sorry for the hiccup.

According to this issue in keepassxc (https://github.com/keepassxreboot/keepassxc/issues/4073), there should also be linux support. This might be some sort of QT problem then.

**Comment by fwSmit** [comment]
> Are there any logs I could provide that would help find what's happening?

You can try to `pkill dunst` and start dunst with debug logs: `dunst -print`. This way dunst will print all notifications it receives. If you don't see any notifications, it's either that your setup is incorrect, or there's something wrong with keepass/ripcord.

**Comment by txtsd** [comment]
Looking through the FAQ:
My `gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/Dbus --method org.freedesktop.DBus.ListNames` lists  `(['org.freedesktop.DBus', 'org.freedesktop.Notifications', ':1.228', 'org.keepassxc.KeePassXC.MainWindow', ':1.8', ':1.229', ':1.9', 'org.Nemo', 'org.freedesktop.systemd1', 'org.gtk.vfs.mountpoint_14172', 'org.gtk.vfs.Daemon', 'org.pulseaudio.Server', 'org.gtk.vfs.mountpoint_14159', ':1.80', ':1.82', ':1.60', ':1.83', ':1.61', ':1.84', ':1.62', 'org.gtk.vfs.UDisks2VolumeMonitor', 'org.a11y.Bus', ':1.63', ':1.20', ':1.64', 'org.gnome.Identity', ':1.21', ':1.65', ':1.88', ':1.66', ':1.252', ':1.89', ':1.67', ':1.68', 'net.lutris.Lutris', 'ca.desrt.dconf', 'org.freedesktop.FileManager1', 'org.PulseAudio1', 'org.gtk.vfs.mountpoint_http', 'org.gtk.vfs.GoaVolumeMonitor', ':1.90', ':1.91', ':1.92', 'org.eclipse.swt.BiglyBT', 'org.gnome.OnlineAccounts', ':1.71', ':1.94', 'com.feralinteractive.GameMode', ':1.51', 'org.gtk.vfs.Metadata', ':1.96', ':1.74', 'org.etherdream.KeyledsService', ':1.98', ':1.76', ':1.54', 'org.gtk.vfs.mountpoint_dnssd', ':1.77', ':1.55', ':1.186', ':1.164', ':1.56', ':1.0', ':1.13', ':1.57', ':1.1', ':1.14', ':1.58', ':1.189', 'org.freedesktop.secrets', ':1.15', ':1.59', 'org.gtk.vfs.MTPVolumeMonitor', ':1.3', ':1.246', ':1.4', ':1.17', ':1.247', ':1.104', ':1.5', ':1.18', ':1.105', ':1.6'],)`
So it looks like I have another notification daemon running? I don't see how though.

These are the only packges I have installed with the word notification in their name or description:
```
λ pacman -Qs notification
[sudo] password for txtsd: 
local/dunst 1.5.0-1
    Customizable and lightweight notification-daemon
local/libevent 2.1.12-1
    An event notification library
local/libnotify 0.7.9-1
    Library for sending desktop notifications
local/networkd-notify-git r15.ae26ffb-1
    Desktop notification integration for systemd-networkd
local/startup-notification 0.12-7
    Monitor and display application startup
```

**Comment by fwSmit** [comment]
In what way is dunst started? If you use systemd
, then stop the service and the pkill.
Dunst will not start if another notification daemon is running.

**Comment by txtsd** [comment]
I don't use systemd to start it. I start it by including it in my `~/.config/openbox/autostart`.

**Comment by fwSmit** [comment]
> I don't use systemd to start it. I start it by including it at the beginning of my `~/.config/openbox/autostart`.

Then look at what starts dunst again, since dunst doesn't start by itself (dbus can start it when an application sends a notification).

>  lists  'org.freedesktop.Notifications'

This means a notification daemon is running, but you say dunst is still running.

Make sure the environment keepass and ripcord are running have access to dbus (DBUS_SESSION_BUS_ADDRESS should be set in that environment).

**Comment by txtsd** [comment]
KeePassXC is launched from the same file.

I'll report again the next time I reboot, with the `dunst` entry taken out of my autostart file.

**Comment by txtsd** [comment]
Okay this time `dunst` was not explicitly started, however, the `gdbus` output still lists `org.freedesktop.Notifications`.

**Comment by fwSmit** [comment]
> Okay this time `dunst` was not explicitly started (it still launched itself), however, the `gdbus` output still lists `org.freedesktop.Notifications`.

There is nothing weird about that. That just mean a notification daemon is running, which is dunst in this case. It probably got started through dbus

**Comment by txtsd** [comment]
idk how to debug this then.
KeePassXC devs claim everything is normal and they see native notifications, not tray balloons, and yet I get tray balloons.

**Comment by fwSmit** [comment]
Can you try to reproduce it on a clean system. Or otherwise make clear steps for me to reproduce

**Comment by rijenkii** [comment]
Had the same problem for about a year now with KeePassXC, will try to reproduce on a clean system.

**Comment by rijenkii** [comment]
I have reproduced it on a clean system, but it seems that it really is not a dunst problem: I was able to reproduce it with xfce4-notifyd also.

<details>
<summary>dunst</summary>
<img src="https://user-images.githubusercontent.com/5338332/122162853-6cc5f780-ce9e-11eb-80dc-59962929b782.png">
</details>

<details>
<summary>xfce4-notifyd</summary>
<img src="https://user-images.githubusercontent.com/5338332/122162868-751e3280-ce9e-11eb-8ea0-a8a4d1ae0540.png">
</details>

**Comment by fwSmit** [comment]
Thank you for reproducing. Have you tried reproducing it with the newest version of qt? If the issue lies there it might be fixed already

**Comment by rijenkii** [comment]
I am not sure how to do that. KeePassXC says that it uses `Qt 5.15.2`, which AFAIK is the latest Qt5 version.
![image](https://user-images.githubusercontent.com/5338332/122165964-2cb54380-cea3-11eb-92bf-24563e696bca.png)
