### ISSUE TITLE
config file (~/.config/dunst/dunstrc) does not cofigure dunst

### ISSUE THREAD

**Issue by TruncatedDinosour** [dunst-project/dunst#863]
### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon v1.6.1-15-gf2017eb`
- Install type: `manual`
- Distro and version: `arch linux, 5.12.1-arch1-1 `

### Issue
I compiled and installed dunst using these commands:
```shell
git clone https://github.com/dunst-project/dunst
cd dunst
make
sudo make clean install
# needed to create the dir because it did not exist
mkdir -p ~/.config/dunst
cp /etc/dunst/dunstrc ~/.config/dunst/dunstrc
reboot
```
and after rebooting i tested it with
```shell
notify-send "This is a test"
```
and it seems to work, but then i tried changing something in the config
and it did not work, I don't understand why.

**Comment by fwSmit** [comment]
Reboot is not needed. Are you sure you're using Dunst? Try `pkill dusnt; dunst.` for reloading the. config.

**Comment by TruncatedDinosour** [comment]
> Reboot is not needed. Are you sure you're using Dunst? Try `pkill dusnt; dunst.` for reloading the. config.
yes, i am sure, i tried reloading the config file, i literally cloned this repository and installed it manually, still doesn't work

**Comment by TruncatedDinosour** [comment]
sorry i accidentally closed the issue

**Comment by fwSmit** [comment]
Could you try https://github.com/fwsmit/dunst/tree/log-config and send the debug output? It should tell you what config path is used.

**Comment by TruncatedDinosour** [comment]
Oops, forgot to update y'all, dunst works when i download it from the [AUR](https://aur.archlinux.org/packages/dunst-git/)
