### ISSUE TITLE
Duplicate command-line arguments

### ISSUE THREAD

**Issue by freak532486** [dunst-project/dunst#868]
The command-line argument `-lh` is used both for setting the line height of the notification and for setting the low urgency hightlight color. The line height seems to take precedence.

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.6.1 (2021-02-21)`
- Install type: `package`
- Distro and version: `Archlinux (Rolling Release)`

**Comment by fwsmit** [comment]
These command line options are removed, so it's not an issue anymore. The
