### ISSUE TITLE
No context menu for action + url

### ISSUE THREAD

**Issue by jzbor** [dunst-project/dunst#872]
Hi,
My problem is that if I send a notification with exactly one URL and one action I don't get prompted a context menu to decide whether I want to execute the action or open the URL.

You can recreate this problem with this command (dest is an absolute file path and filename the name of a picture in that directory):
```sh
dunstify -a Screenshot -i "$dest/$filename" "Successfully taken screenshot" "file://$dest/$filename https://github.com" \
                --action "$FILEMANAGER $dest,open" | sh 2> /dev/null
```

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.6.1 (2021-02-21)`
- Install type: `Arch Repositories`
- Distro and version: ` Arch Linux x86_64`

**Comment by fwSmit** [comment]
I'm not entirely sure how it worked in 1.6.1, but this isn't a problem anymore on master. Now there's a separate `open_url` mouse action, which opens the url or context menu if there's multiple url's. There's also `context` which always opens the context menu. See the man page for all possible mouse actions.
Does this solve your problem?

**Comment by jzbor** [comment]
Yes I think that solves my problem. Thank you!
