### ISSUE TITLE
[Question] Is it possible to display the application icon next to the notification?

### ISSUE THREAD

**Issue by gabomontero89** [dunst-project/dunst#873]
Sometimes it is confusing to know where the notification comes from.

Any help will be appreciated.
Regards.

**Comment by fwSmit** [comment]
It's possible, but you'll have to do it for each application with a rule. For example (you'll have to change the appname and icon to something that works)
`~/.config/dunst/dunsrc`
```
[discord]
appname="discord"
icon=/usr/share/icons/hicolor/discord
```

**Comment by fwSmit** [comment]
Closing, as the question is answered

**Comment by gabomontero89** [comment]
> It's possible, but you'll have to do it for each application with a rule. For example (you'll have to change the appname and icon to something that works)
> `~/.config/dunst/dunsrc`
> 
> ```
> [discord]
> appname="discord"
> icon=/usr/share/icons/hicolor/discord
> ```

Thanks @fwSmit
