### ISSUE TITLE
Dunst fails to start

### ISSUE THREAD

**Issue by Davincible** [dunst-project/dunst#876]
I am unable to get dunst to work, with the error `CRITICAL: Cannot connect to DBus`.

`echo $DBUS_SESSION_BUS_ADDRESS` returns `unix:abstract=/tmp/dbus-rNWolXwjpm,guid=7a5e040db55a404965b9d5f660cae7e6`

I am running Manjaro 5.12 with i3-gaps and dunst v1.5.0 (2020-07-23)

**Comment by fwSmit** [comment]
Does the error also occur when starting+ dunst from the command line?

**Comment by Davincible** [comment]
Actually only from the command line, systemd status shows no errors, however I can't notify-send or dunstify anything, the latter fails with a dbus error

**Comment by fwSmit** [comment]
Is this reproducible on a clean manjaro install? It seems like you have done something weird to your dbus setup.
You can also try to see if another notification daemon works.

**Comment by Davincible** [comment]
Not sure, could be possible. I installed manjaro with KDE, but I am trying to move away from that now. What daemon(s) should I try?

**Comment by fwSmit** [comment]
You can try undoing that rename and see if the KDE one works. Otherwise try xfce4-notifyd or any other standalone notification daemon listed here https://wiki.archlinux.org/title/Desktop_notifications

**Comment by bebehei** [comment]
You can run `dunstctl debug` to see, if there are any other running DBus Daemons.

**Comment by Davincible** [comment]
Will try one of the other once.

@bebehei that only prints out `dunst is not running.`

**Comment by bebehei** [comment]
Well then, use d-feet and look at your session bus. There you find, which daemon occupies `org.freedesktop.Notifications`

**Comment by Davincible** [comment]
I have no such file on my system, only `/usr/share/dbus-1/services/org.kde.plasma.Notifications.service(.disabled)`. Is that the problem then?

**Comment by fwSmit** [comment]
It shouldn't be a problem. It's only used for autostarting the notification daemon. What bebehei means is the dbus interface called `org.freedesktop.Notifications`. Take a look at https://dunst-project.org/faq/#name-lost-is-another-notification-daemon-running for how to see if it is occupied.

**Comment by Davincible** [comment]
After a lot of digging I found out the problem was that I had symlinked my .xinitrc to my .xsession because I switched to lightdm and thought that was needed, but as a result the dbus got messed up. After deleting that symlink (and switching back to sddm), my dbus env var gets set to a proper `/run` path
