### ISSUE TITLE
feature request: ability to scroll long notifications

### ISSUE THREAD

**Issue by treeshateorcs** [dunst-project/dunst#878]
is there any way to scroll notifications that won't fit on the screen (vertically). there's not much software that produces such long notifications, but i have one example, and it's https://github.com/soimort/translate-shell, if there's no way to do it, consider this a feature request. i did search google before creating this issue, the project's name is almost ungoogleable, and there was nothing sensible in the output

here's a screenshot
![here's a screenshot](https://user-images.githubusercontent.com/60894565/122577667-590fc200-d053-11eb-9450-536ed75f8d35.png)

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.6.1 (2021-02-21)`
- Install type: `package`
- Distro and version: `archlinux rolling release `

**Comment by fwSmit** [comment]
Unfortunately implementing a scrollbar is not realistic for Dunst, since it doesn't use a gui toolkit. Alternatives include making this specific notification a bit wider using rules or running a script that can take the notification text and show it in another program that does have a scroll bar.

**Comment by treeshateorcs** [comment]
okay thanks for the heads up
