### ISSUE TITLE
Feature request : workspace specific notification

### ISSUE THREAD

**Issue by kushraj** [dunst-project/dunst#880]
Is there a way to make dunst exclude a desktop from showing notification ?

use case: while playing games on a specific desktop , notifications interrupt the experience. 
disabling the notifications is not an option if you are multitasking.

 only way to deal with them is to use a keyboard shortcut or switch to another workspace and click on them.
can this be considered ?

**Comment by fwSmit** [comment]
You can skip or delay notifications while fullscreen. Would that be enough for you?

You could also make a script that ties into the i3 API (or whatever wm you are using) and pauses Dunst when you are on a specific workspace.

The last thing I can think of is to make the shortcut that switches to a workspace also execute the pause command

I don't know how one would implement it for specific workspaces and it wouldn't work on wayland.

**Comment by kushraj** [comment]
thnx for the suggestion, 

> You can skip or delay notifications while fullscreen

this could work for me, how to implement this ? others wont work so well as I switch between workspaces too often

**Comment by fwSmit** [comment]
> thnx for the suggestion,
> 
> > You can skip or delay notifications while fullscreen
> 
> this could work for me, how to implement this ? 

```
[foo] 
fullscreen = pushback
```

> others wont work so well as I switch between workspaces too often

I'm not sure if you understand it. The others should work even if you switch very often. It happens automatically.

**Comment by progandy** [comment]
> You could also make a script that ties into the i3 API (or whatever wm you are using) and pauses Dunst when you are on a specific workspace.

Here is a bash script that should pause dunst while the workspace named "3" is focused in i3 (needs the jq tool)
```
#!/bin/bash
paused=0
pause_ws="3"
while read name ; do 
	if [[ "$paused" == "1" && "$name" != "$pause_ws" ]]; then
		paused=0
		dunstctl set-paused false
	elif [[ "$paused" == "0" && "$name" == "$pause_ws" ]]; then
		paused=1
		dunstctl set-paused true
	fi
done < <( i3-msg -t subscribe -m '[ "workspace" ]' | jq -r --unbuffered ".current.name" )
```

Also, "paused" means notifications are collected and displayed later when dunst is resumed.

**Comment by kushraj** [comment]
thanks, this worked exactly as I wanted. closing now
