### ISSUE TITLE
Multiple issues: context menu doesn't work, closed notifications not removed from history

### ISSUE THREAD

**Issue by jakec-dev** [dunst-project/dunst#887]
`dunstctl context` in terminal doesn't do anything. No menu's pop up, no errors are received in terminal. Literally nothing happens.

Setting `mouse-right-click = context_all` in the config file causes an error:
`WARNING: Unknown mouse action value: 'context_all'`
The same error occurs when using `mouse-right-click = context`

Setting `mouse-right-click = close_current` doesn't remove the notification from history. As far as I can tell from reading the documentation, there is no way to dismiss notifications from history. 

Maybe I'm confused about how dunst works, but I really can't figure out how to 1) view a list of all unread notifications (i.e. notifications that haven't been closed by the user), and 2) remove dismissed notifications from history. There isn't any documentation on the context menu so I'm just guessing that's the menu that displays your unread notifications? Would it be possible to add some documentation around this?

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.6.1 (2021-02-21)`
- Install type: `sudo pacman -S dunst`
- Distro and version: `Arch Linux v 1.4 (latest release) `

**Comment by fwSmit** [comment]
Context and context_all were added after the release of 1.6.1.

To answer your questions :
1) Is not possible
2) Is not possible either.
You're welcome to add a skip_history rule to solve the second problem though.

The context menu is for executing actions, similar to do_action. Only the context option always opens the context menu I believe. I'm not sure how you are aware of this unreleased option, yet can't find documentation about it :) . The context menu is documented in the actions section of the man page.

**Comment by jakec-dev** [comment]
I'm not sure where I found the info on context. Perhaps from stackoverflow or similar while searching for a solution to my issue.

I've tried searching for `skip_history` in the repo but couldn't find any information on it. Are you able to link me to where I can find it please?

**Comment by fwSmit** [comment]
> I'm not sure where I found the info on context. Perhaps from stackoverflow or similar while searching for a solution to my issue.
> 
> I've tried searching for `skip_history` in the repo but couldn't find any information on it. Are you able to link me to where I can find it please?

Skip_history doesn't exist yet. It was only a suggested addition to Dunst
