### ISSUE TITLE
History-pop shortcut don't work

### ISSUE THREAD

**Issue by Wisehh** [dunst-project/dunst#893]
Hi

I would like to report an error that my dunst has been having for a couple of weeks (but I had not had time to detail it until now)

Before the shortcut 'ctrl + grave' worked perfectly to see the last closed notifications. However some time ago this shortcut did not work, so I did some tests

- I checked that the config files were ok
- I made sure that no other program was using the command.
- I witnessed the bug with the development version and the stable one (dunst and dunst-git, from Arch repositories)
- I tried using my hotkey daemon to compare results

What I got was that when I tried to bind any shortcut to the history-pop action FROM the dunst file, this shortcut didn't work (I tried ctrl + grave, ctrl + space, and even ctrl + a, just by trying any combination). With that I ruled out that it was some other program 'stealing' my shortcut, since for example the action 'close' linked to ctrl + space, worked perfectly.

Then I tried adding the 'dunstctl history-pop' command to sxhkd with ctrl + grave, and this time it did work, as did all the other actions.

I tried using dunstctl debug in case there was something useful there, but its only output was the dunst version.

Could I have forgotten something? Any other information that I can add, I remain available

(Oh, and by the way, thanks for Dunst, it's amazing!)

### Installation info

- Version:  1.6.1 (stable) and 1.6.1-95-g6d41d1c (aur)
- Install type: package with pacman and paru
- Distro and version: Arch Linux

**Comment by Narrat** [comment]
Well, the global hotkeys of dunst were deprecated and got removed.
As you noticed, or already did, configuring a hotkey daemon or via the X window manager or Wayland compositor using dunstctl is the way to go :)

**Comment by fwSmit** [comment]
The built in shortcuts were indeed removed (in #803). As narrat noted, you can replace them by adding shortcuts to you window manager, desktop environment, etc. and letting those shortcuts call `dunstctl` commands.

**Comment by Wisehh** [comment]
Oh! I was not aware that it was a relegated feature. Thanks to both for the clarification; I admit that I found it a bit strange to have access to shortcuts through configuration and also through dunsctl with hotkey daemons.

I proceed to close the issue, and thank you again!
