### ISSUE TITLE
GLib-WARNING on ArcoLinux

### ISSUE THREAD

**Issue by CSpencerND** [dunst-project/dunst#897]
I'm using a hotkey that switches a keyboard layout and it also should `notify-send` to show me when the layout changes. I originally did it on Ubuntu and it worked as expected. I recently switched to ArcoLinux and now I get this error.
```
(notify-send:49917): GLib-WARNING **: 15:37:21.324: In call to g_spawn_sync(), exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.
```
I tried it with `dunstify` and also got an error.
```
(dunstify:144348): GLib-WARNING **: 00:39:11.901: In call to g_spawn_sync(), exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.
Unable to send notification: Error spawning command line “dbus-launch --autolaunch=bb1318e4bd0540a588696afd911edc96 --binary-syntax --close-stderr”: Child process killed by signal 48

```
The program I'm using that configures the keyboard (`kmonad`) has to run as root (it grabs the keyboard and makes a `uinput` device to stand in it's place), so I tried prepending `su <my-username>` to the `notify-send` or the `dunstify` command to make sure my user is getting the notification and it no longer produces the error message but I still don't get the notification. 

Notifications work fine in all other use cases.

I opened an issue over on their repo but we haven't been able to figure it out so I figured I should ask here.  Sorry if this is long winded. I wanted to make sure I was thorough. 

### Installation info

- Version: `1.6.1 (2021-02-21)`
- Install type: `pacman`
- Distro and version: ` ArcoLinux`

**Comment by bebehei** [comment]
According to the logged message, this seems to be a problem inside of libnotify and its use of glib.

---

Also in respect of this logline:

```
Unable to send notification: Error spawning command line “dbus-launch --autolaunch=bb1318e4bd0540a588696afd911edc96 --binary-syntax --close-stderr”: Child process killed by signal 48
```

I'd assume you've got some DBus-related problems. Are you able to start DBus? Will `dbus-monitor path=/org/freedesktop/Notifications` show some output like this?

```
signal time=1629625790.220438 sender=org.freedesktop.DBus -> destination=:1.27 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.27"
signal time=1629625790.220524 sender=org.freedesktop.DBus -> destination=:1.27 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.27"
```

**Comment by CSpencerND** [comment]
dbus-monitor path=/org/freedesktop/Notifications
```
signal time=1629676602.258837 sender=org.freedesktop.DBus -> destination=:1.1819 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.1819"
signal time=1629676602.258887 sender=org.freedesktop.DBus -> destination=:1.1819 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.1819"
```

**Comment by bebehei** [comment]
Ok, have you tried to this from the FAQs? [Sending notifications from another user (root)](https://dunst-project.org/faq/#sending-notifications-from-another-user-root)

**Comment by CSpencerND** [comment]
> Ok, have you tried to this from the FAQs? [Sending notifications from another user (root)](https://dunst-project.org/faq/#sending-notifications-from-another-user-root)

Yes. It gives me the exact same error.

**Comment by CSpencerND** [comment]
I got it figured out. There's nothing wrong with libnotify or anything. I had to make a `input` and `uinput` group and a `udev` rule so I can run the app without sudo. Everything works as expected now.
