### ISSUE TITLE
Opening angle bracket "<" breaks rendering

### ISSUE THREAD

**Issue by pvonmoradi** [dunst-project/dunst#900]
`notify-send  "title"  "We <3 dunst"` shows up as:  

![image](https://user-images.githubusercontent.com/1058151/132224981-c97cc72d-fefd-4264-bbf9-b413a85de8fb.png)

`notify-send  "title"  "We <3> dunst"`:  

![image](https://user-images.githubusercontent.com/1058151/132225032-4c4525ea-b4a1-408c-a2a0-104530fe368e.png)

Even a mere `notify-send  "title"  "We < dunst"` shows up cut off at <.

I have activated markup support in my dunstrc, but I think dunst should ignore these strings because they are incomplete and do not collide with supported tags (b, i, s, u).
### Installation info
- Version: `v1.6.1`
- Install type: `manual`
- Distro and version: `Xubuntu 18.04+i3-gaps `

**Comment by LamprosPitsillos** [comment]
Pretty sure this is caused by the markup setting in the config
```
    # Possible values are:
    # full: Allow a small subset of html markup in notifications:
    #        <b>bold</b>
    #        <i>italic</i>
    #        <s>strikethrough</s>
    #        <u>underline</u>
    #
    #        For a complete reference see
    #        <https://developer.gnome.org/pango/stable/pango-Markup.html>.
    #
    # strip: This setting is provided for compatibility with some broken
    #        clients that send markup even though it's not enabled on the
    #        server. Dunst will try to strip the markup but the parsing is
    #        simplistic so using this option outside of matching rules for
    #        specific applications *IS GREATLY DISCOURAGED*.
    #
    # no:    Disable markup parsing, incoming notifications will be treated as
    #        plain text. Dunst will not advertise that it has the body-markup
    #        capability if this is set as a global setting.
    #
    # It's important to note that markup inside the format option will be parsed
    # regardless of what this is set to.
    markup = full

```
Turning this to no should fix it but it is still a problem... 

`notify-send "title" "We \<3 dunst"` doesn't fix it also.

**Comment by fwSmit** [comment]
If you're using markup=full, the markup is completely handled by pango, so you should report a bug there. If you use markup=strip you can see there's a warning in the documentation that it's not perfect and this would not be considered a bug.
Either way, I believe this issue can be closed on our side.

**Comment by LamprosPitsillos** [comment]
[Link to the issues page of pango](https://gitlab.gnome.org/GNOME/pango/-/issues?scope=all&state=opened&search=%3C)

**Comment by fwSmit** [comment]
I created a pango issue [here](https://gitlab.gnome.org/GNOME/pango/-/issues/612)

**Comment by fwSmit** [comment]
Turns out, this is not a pango bug, but intended behaviour It's just plain xml. We should encode `<` with `&lt;` and to prevent accidental encodings, replace `&` with `&amp;`.

**Comment by pvonmoradi** [comment]
@fwSmit You mean dunst should respect HTML entities? It seems pango is not implementing [all html entities](https://dev.w3.org/html5/html-author/charref). I didn't find relevant info on what chars to escape in [pango docs](https://docs.gtk.org/Pango).  

So at this point, I think out best bet is `sed`ing &lt; for <

**Comment by fwSmit** [comment]
> @fwSmit You mean dunst should respect HTML entities? It seems pango is not implementing [all html entities](https://dev.w3.org/html5/html-author/charref). I didn't find relevant info on what chars to escape in [pango docs](https://docs.gtk.org/Pango).  

The docs aren't clear on this, but at least & and < have to be encoded. I think I'll encode ", ' and > too just to be safe. 


> So at this point, I think our best bet is `sed`ing `<` with `&lt;` before piping the string to `notify-send`

No I'll implement it inside of dunst. Then it won't matter what is passed via notify-send

**Comment by fwSmit** [comment]
I wasn't entirely correct here. Since you're allowed to put markup in the notification body, we can't just escape all markup symbols. The right solution is indeed to make sure you escape any markup symbols you want to send.
We can, however improve the way incorrect notifications are handled. Too much of the notification is stripped away, resulting in what you've noticed

**Comment by fwSmit** [comment]
@pvonmoradi I've created a PR (#914) that works around this issue. Keep in mind, however that it's still better to escape the `<` symbols with `&lt;`.
