### ISSUE TITLE
Letters between parenthesis before title.

### ISSUE THREAD

**Issue by samoht9277** [dunst-project/dunst#902]
- Version: `1.6.1 (2021-02-21)`
- Install type: `pacman -S dunst`
- Distro and version: ` Arch, 5.13.13-arch1-1`

Description:
It happens whenever i get a discord notification, mainly, but not on spotify for example.
I suspect this is not an error, but a debug feature maybe? Is it possible to disable it?

Image: 
![image](https://user-images.githubusercontent.com/53660242/132773396-5ec123f2-6626-435e-8b9a-e8c47b8e5733.png)
see `(A)`

[dbus-monitor output](https://pastebin.com/XDBaGqkG)

**Comment by fwSmit** [comment]
That letter is an indication that there's an action available for the notification (namely going to the message). You can activate the action by `dunstctl action` or middle clicking on the notification. It's not possible to remove that letter from the formatting I believe.
