### ISSUE TITLE
Trouble with application specific notifications

### ISSUE THREAD

**Issue by Tuuuukka** [dunst-project/dunst#905]
### Installation info

- Version: `1.6.1`
- Install type: `pacman -S dunst`
- Distro and version: `Linux manjaro 5.10.52-3-rt47-MANJARO `

### My problem

I'm having trouble with catching notifications from Slack. My goal is to style them a bit differently to make them stand out more. With e.g. Spotify this works nicely, I have this in my `dunstrc`:

```
[spotify]
    appname = Spotify
    format = "My custom formatting for Spotify notifications"
```

If I try this with Slack, it doesn't work:

```
[slack]
    appname = Slack
    summary = Slack Notification
    format = "My custom formatting for Slack notifications"
```

I've also tried `desktop_entry` instead of `appname`, but nothing changes. Slack notifications still go with the global styling etc. This is what I get when sending a test notification from Slack:

```
dunst -print
{
	appname: 'Slack'
	summary: '[XXXXX] from Slackbot'
	body: 'What do you know, it works?'
	icon: 'dialog-information'
	raw_icon set: false
	icon_id: 'dialog-information'
	desktop_entry: 'Slack'
	category: 
	timeout: 10000
	urgency: NORMAL
	transient: 0
	formatted: '<b>[XXXXX] from Slackbot</b><span font_desc='Fira Code Nerd Font 2'>

</span><span font_desc='Fira Code Nerd Font 11'>What do you know, it works?</span>'
	fg: #fbf1c7
	bg: #282828E6
	highlight: #1745d1
	frame: #282828E6
	fullscreen: show
	progress: -1
	stack_tag: 
	id: 2
	actions: {
		"default": "View"
	}
	script_count: 0
}
```

So what is it that I'm missing?

**Comment by fwSmit** [comment]
```
[slack]
    appname = Slack
    summary = Slack Notification
    format = "My custom formatting for Slack notifications"
```
You match here for the notification with appname "Slack" and summary "Slack Notification". If you remove that it should match the notification.
Currently it's not possible to change summary of the notification, except by overriding the notification with a new one.

**Comment by fwSmit** [comment]
Subscribe to #899 if you want to get updates about changing the summary and other properties (don't expect it soon though).
