### ISSUE TITLE
Very strange issue with script and notification , might be unrelated...

### ISSUE THREAD

**Issue by LamprosPitsillos** [dunst-project/dunst#911]
While calling my script through qtile (mouse-callback and via the run promt) the pango markup in the notification just vanishes... I just cant wrap my head around how this is possible. The same script , just called through qtile.

[My issue on Qtile](https://github.com/qtile/qtile/issues/2800)
### Video showing what i mean
https://user-images.githubusercontent.com/61395246/133853664-0cf16441-87de-4b06-9029-14d98ac36a7d.mp4
### My script
```bash
#!/bin/sh

day="$(date +'%A')"
calendar="$(cal --color=always |\
		sed -r 's#\[7m(.*)\[27m#<b><i><big>\1</big></i></b>#' |\
		sed -r 's/$/ /g')"
# echo -n "$calendar"
weather="$(curl -s wttr.in/Crete\?format=4)"
notify-send "$day" "\n<big>$calendar</big>\n\n$weather" -i weather_few_cloud

```
### Dbus log
[dbus.txt](https://github.com/dunst-project/dunst/files/7188439/dbus.txt)

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.6.1 (2021-02-21)`
- Install type: `AUR`
- Distro and version: `Artix Linux x86_64  `

**Comment by fwSmit** [comment]
What is the most minimal script that still reproduces this bug?

**Comment by LamprosPitsillos** [comment]
https://user-images.githubusercontent.com/61395246/133880701-74decbc3-1732-4907-9054-91655ce75481.mp4

Again more weirdness... 
I git cloned `Qtile` and started it up with `xephyr` , the script that is provided in the repo.
But the bug wasn't present... Same config , same script , same everything...
So sadly this isn't reproducible i guess...

I just cant wrap my head around how is this possible, what could be the problem...

**Comment by LamprosPitsillos** [comment]
I figured out how to fix this, but not why this was a problem in the first place, any explanation would be welcomed. Please check out the post on Qtile repo for more info ( linked at the top of my issue )
