### ISSUE TITLE
Unknown mouse action value: 'context'

### ISSUE THREAD

**Issue by MithicSpirit** [dunst-project/dunst#916]
Setting any of the `mouse_*_click` variables in the `[global]` section to `context` causes the error `Unknown mouse action value: 'context'`. Although this doesn't result in a crash, the context menu does not work.

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon v1.6.1-117-g82c8c06`
- Install type: `dunst-git` in the AUR
- Distro and version: Arch Linux (rolling)

**Comment by fwSmit** [comment]
Thank you for the notice. I've fixed it in #918.
