### ISSUE TITLE
incorrect wrapping with shrink enabled with an image

### ISSUE THREAD

**Issue by wael444** [dunst-project/dunst#920]
shrink disabled, 256x64
![image](https://user-images.githubusercontent.com/47404953/134750383-32eb1579-96f0-41b8-b394-1c18b4c2fc5e.png)
![image](https://user-images.githubusercontent.com/47404953/134750400-06209496-af68-40e2-ad1d-da48cd19ffd5.png)

shrink enabled
![image](https://user-images.githubusercontent.com/47404953/134750449-64e03024-d70b-4c49-baa6-432edd579b60.png)
![image](https://user-images.githubusercontent.com/47404953/134750495-1a0f070c-1719-49af-acd7-94ee96550efa.png)

sorry if i'm not being clear enough.

### Installation info

- Version: `1.6.1 (2021-02-21)`
- Install type: `pacman`
- Distro and version: `Arch Linux 5.14.6 `

**Comment by fwSmit** [comment]
In #855 those settings were reworked and this issue should be fixed. Do you mind trying the newest commit to see if it was fixed?

**Comment by wael444** [comment]
shrink doesn't function anymore
![image](https://user-images.githubusercontent.com/47404953/135080665-4a89d0be-12fa-4744-8d96-58b9835d98d5.png)
or did i do something wrong?

**Comment by fwSmit** [comment]
> shrink doesn't function anymore or did i do something wrong?

`shrink` is replaced by the `width` setting. You can set a minimum and maximum: `(min, max)`, for example `(0, 400)`.

**Comment by wael444** [comment]
> `shrink` is replaced by the `width` setting. You can set a minimum and maximum: `(min, max)`, for example `(0, 400)`.

~~i should have read the config~~

using default [dunstrc](https://github.com/dunst-project/dunst/blob/master/dunstrc) also gives these
```
WARNING: Setting notification_height in section global doesn't exist
WARNING: Setting startup_notification in section global doesn't exist
WARNING: Setting verbosity in section global doesn't exist
```
the default dunstrc should be updated to this i suppose, thanks for the fix!

**Comment by fwSmit** [comment]
> > `shrink` is replaced by the `width` setting. You can set a minimum and maximum: `(min, max)`, for example `(0, 400)`.
> 
> ~i should have read the config~
> 
> using default [dunstrc](https://github.com/dunst-project/dunst/blob/master/dunstrc) also gives these
> 
> ```
> WARNING: Setting notification_height in section global doesn't exist
> WARNING: Setting startup_notification in section global doesn't exist
> WARNING: Setting verbosity in section global doesn't exist
> ```
> 
> the default dunstrc should be updated to this i suppose, thanks for the fix!

Yes good point. I'll update the dunstrc.
