### ISSUE TITLE
I'm getting two notifications from mpd

### ISSUE THREAD

**Issue by Rashad-707** [dunst-project/dunst#923]
I'm getting duplicate notification from mpd when song change, one from script I have that send notification according to format I want with the song cover as an icon, but the other with a different format and without a cover only music icon. 
How can i know its source if there is a script sending it, or just there was an update so dunst send mpd notification by itself, and how to disable it

**Comment by fwSmit** [comment]
> I'm getting duplicate notification from mpd when song change, one from script I have that send notification according to format I want with the song cover as an icon, but the other with a different format and without a cover only music icon. How can i know its source if there is a script sending it

There isn't a definite way, but `dunst -print` should give you more information.

> or just there was an update so dunst send mpd notification by itself, and how to disable it

There isn't such a functionality in dunst.

**Comment by fwSmit** [comment]
Closing this as this doesn't seem to be a dunst bug
