### ISSUE TITLE
Documentation on not displaying notifications

### ISSUE THREAD

**Issue by MithicSpirit** [dunst-project/dunst#925]
The sample `dunstrc` states that, to prevent a notification from being displayed, `format` should be set to `""`. However, doing so has no effect and creates the output `WARNING: Cannot set empty value for setting format`. I suspect that this is old behavior that has not been updated in the sample configuration yet.

### Installation info

- Version: `v1.6.1-139-ge973cf8`
- Install type: AUR package `dunst-git`
- Distro and version: Arch (rolling)

**Comment by fwSmit** [comment]
Thank you for noticing this. This behaviour has indeed been changed by #803. The right way to skip a notification is `skip_display = true`. I've updated the dunstrc.
