### ISSUE TITLE
seperator seperate?

### ISSUE THREAD

**Issue by wael444** [dunst-project/dunst#929]
default behavior:
![image](https://user-images.githubusercontent.com/47404953/135763589-76c7b848-96bb-470c-bf38-4be2ee6c2d42.png)

what i would appreciate: 
![image](https://user-images.githubusercontent.com/47404953/135763645-16b8bc27-4224-4d8b-bf3b-2efba76f5f26.png)

i assume this would be already possible but i can't seem to find it, sorry if it __is__ and i'm just blind.

**Comment by fwSmit** [comment]
You can make the separator height really big and make it transparent

**Comment by wael444** [comment]
> You can make the separator height really big and **make it transparent**

this is what i was looking for. how?

**Comment by fwSmit** [comment]
Take a look at the COLORS section in the man page

**Comment by wael444** [comment]
RGBA support with transparency colors... I SHOULD REALLY READ THE MAN PAGE MORE OFTEN.

**Comment by RedDofamine** [comment]
> 

Just set color as = "#00000000" where last 00 is your transparency
00 00 00 00 (hex) -> 255 255 255 255 (dec)
r    g   b   a
