### ISSUE TITLE
dunstctl does not recognize /usr/local/bin/dunst

### ISSUE THREAD

**Issue by tim042849** [dunst-project/dunst#932]
* dunst 1.6.1 and dunstctl and installed on my ubuntu 21.04 system via make. Both are at /usr/local/bin.
* Yet when I run dunstctl debug I get an error message that says that dunstctl is finding the older version, which 
* is at /usr/bin. The default path for executables is /usr/local/bin. How can this be resolved so that dunstctl finds
* the dunst at /usr/local/bin? `Thanks`
Error message:
```
dunst version: 1.4.1
Dunst controlling interface not available. Is the version too old?
```

### Installation info

- Version: `<!-- output of dunst -v -->`
- Dunst - A customizable and lightweight notification-daemon 1.6.1 (2021-02-21)
- Install type: `<!-- [package|manually|...] -->`
- Installed via make, compiled and sudo make install
- Distro and version: ` `
- 1.6.1

**Comment by tim042849** [comment]
Yes
```
which -a dunst
/usr/local/bin/dunst
/usr/bin/dunst
/bin/dunst
```
Thanks for the reply

**Comment by fwSmit** [comment]
DBus may start /usr/bin/dunst. So try `pkill dunst; dunst&; dunstctl version;`

**Comment by tim042849** [comment]
/usr/bin/dunst no longer exists. I uninstalled the distro package. Nevertheless, the code above eliminated the error message.
I was at that time in mate. I logged out and went into i3. 
Screen dump follows:
```
dunstctl debug
dunst version: MATE
Dunst controlling interface not available. Is the version too old?
tim@mini:~$ dunst &
[1] 1535141
tim@mini:~$ CRITICAL: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'Notification Daemon' with PID '1535089'.
^C
[1]+  Exit 1                  dunst
tim@mini:~$ kill 1535089
bash: kill: (1535089) - No such process
tim@mini:~$ kill 1535089
bash: kill: (1535089) - No such process
tim@mini:~$ dunst &
[1] 1535267
tim@mini:~$ dunstctl debug
dunst version: 1.6.1
```
I think we are on the right track, but since I retired my linux IQ has diminished. Thanks for the help, greatly appreciated.

**Comment by fwSmit** [comment]
How is dunst started on your system?

**Comment by tim042849** [comment]
With i3 is was using 
`exec --no-startup-id dbus-launch /usr/local/bin/dunst --config ~/.config/dunst/dunstrc`
Now I have changed that to
`exec --no-startup-id dunst --config ~/.config/dunst/dunstrc`
**Now** `dunstctl debug`
Gives me 
`dunst version: 1.6.1`
So that looks good. I will be unable to respond until tomorrow or hours later today, probably. I really appreciate the help.
cheers

**Comment by tim042849** [comment]
It appears that this issue has been solved. I look forward to using a good product that is clearly well-supported. Closing now.
