### ISSUE TITLE
Dunst cannot be configured through command line arguments

### ISSUE THREAD

**Issue by exorcist365** [dunst-project/dunst#940]
Why have you removed this, it was one of the most useful functionalities of this program????

**Comment by aleksfadini** [comment]
Please bring back shortcuts and command line arguments

**Comment by fwSmit** [comment]
> @fwSmit would be good to mention this in the README, don't you think? I can make a PR.

True. A PR would be appreciated :)

**Comment by fwSmit** [comment]
For clarity, I'm considering re-adding the command line options in a slightly different from. They would be with double dashes (`--`). It shouldn't be too complicated, it's just something I haven't gotten to.

**Comment by marcelofern** [comment]
For the record, this is a script I was using to change dunst colors based on the pywal theme. This isn't working anymore:
```sh
#!/bin/sh

# source wal colors.
source ~/.cache/wal/colors.sh

pkill --exact dunst
dunst \
    -config=~/.config/dunst/dunstrc \
    -frame_width 1 \
    -lb $color0 \
    -lf $color7 \
    -lfr $color3 \
    -cb $color0 \
    -cf $color7 \
    -cfr $color3 \
    -nb $color0 \
    -nf $color7 \
    -nfr $color3 &
```

**Comment by aleksfadini** [comment]
> For the record, this is a script I was using to change dunst colors based on the pywal theme. This isn't working anymore:
> 
> ```shell
> #!/bin/sh
> 
> # source wal colors.
> source ~/.cache/wal/colors.sh
> 
> pkill --exact dunst
> dunst \
>     -config=~/.config/dunst/dunstrc \
>     -frame_width 1 \
>     -lb $color0 \
>     -lf $color7 \
>     -lfr $color3 \
>     -cb $color0 \
>     -cf $color7 \
>     -cfr $color3 \
>     -nb $color0 \
>     -nf $color7 \
>     -nfr $color3 &
> ```

Would like to know what is a workaround for this, since it stopped working.

**Comment by marcelofern** [comment]
@aleksfadini my understanding is that there is no workaround. @fwSmit your feedback on this would be appreciated.

I've created a script to manually change `dunstrc` based on pywal colors, but it is by no means a better solution, it is not even a good solution at all. However, at the time I am writing this I couln't find a better replacement:

```sh
#!/bin/sh

# source wal colors.
source ~/.cache/wal/colors.sh

DUNST_FILE=~/.config/dunst/dunstrc

# update dunst based on pywal colors.
sed -i '/background = /s/.*/background = "'$color0'"/' $DUNST_FILE
sed -i '/foreground = /s/.*/foreground = "'$color7'"/' $DUNST_FILE
sed -i '/frame_color = /s/.*/frame_color = "'$color3'"/' $DUNST_FILE
```

**Comment by fwsmit** [comment]
You're almost at the workaround I think is best. Instead of overwriting the existing dunstrc, you should generate one based on a template. Then you should start Dunst with the generated config.
There's already a script that does exactly what you want here: https://github.com/dunst-project/dunst/blob/master/contrib/dunst_xr_theme_changer.sh

**Comment by aleksfadini** [comment]
> Is there a way to do this in a more elegant way? The above feels like a dirty hack.

@marcelofern thank you for posting that. could you edit the post or reply with a link to your dunstrc for clarity? For some reason I'm having trouble with colors since command line options were removed.

**Comment by BeyondMagic** [comment]
> Luckily this problem is already solved by https://github.com/dunst-project/dunst/blob/master/contrib/dunst_xr_theme_changer.sh. Just run the script and change your config location to ~/.config/dusnt/dunstrc_xr_colors. As always, every time you change the config, you need to restart dunst.

It seems a hell of a downgrade to rely on an external script for a functionality that was already *implemented* on dunst itself.

**Comment by aleksfadini** [comment]
@BeyondMagic thank you for explaining this. We still can't understand why such a function was removed.

**Comment by zlice** [comment]
just throwing my hat in the ring. broke today on me and has the ugly midnight default colors.

**Comment by fwsmit** [comment]
Drop-in files have been implemented in #997, so this should solve the underlying issue of needing to generate the entire dunstrc. The solutions mentioned above should work without any issues. I'll go ahead and close this issue.

**Comment by zlice** [comment]
So there won't be a `--` implemented ?

I don't want another file. As petty as it is, it's just one more thing to copy between machines if I'm setting something new up or changing something.

**Comment by fwsmit** [comment]
> So there won't be a -- implemented ?

There might be some time. If someone wants to submit a PR that'd be great. 

> I don't want another file. As petty as it is, it's just one more thing to copy between machines if I'm setting something new up or changing something.

I get where you're coming from. It's just not something that bothers me in my setup, as I'm using a dotfiles repo with a dotfiles manager. So it's easy to copy dotfiles around. If you have a different setup it might be easier to use command line arguments.
Anyways, I'll probably get to the command line arguments some time, but I don't consider it a bug right now, since the alternative of drop-ins are there now.

**Comment by vzaliva** [comment]
I used to do `notify-send DUNST_COMMAND_PAUSE` to pause notifications. The use case is when I share my screen and doing a presentation.  How can I do this now?

**Comment by Narrat** [comment]
You can use `dunstctl` which should come with your dunst installation :)
See `man dunstctl`. There is a section about `is-paused`, `set-paused`, `get-paused` and `set-pause-level`

**Comment by fedang** [comment]
for future reference, this will _not_ be added back. 
all configuration of dunst should be done with dunstctl or dunstrc files.
if you need dynamic changes you can add drop-ins and `dunstctl reload`
