### ISSUE TITLE
Notification window wrongly sized

### ISSUE THREAD

**Issue by vpont** [dunst-project/dunst#950]
- Version: `Dunst - A customizable and lightweight notification-daemon v1.7.0-15-g1d7bfbe`
- Install type: `manually`
- Distro and version: ` Arch Linux`

For some reason and with a combination of a few config values and the Iosevka Nerd Font results with the notification window being wrongly sized:
![Screenshot](https://i.postimg.cc/N0RZH7tr/2021-10-25-104159-2560x1440-scrot.png)

You can reproduce it by changing only the following settings:
```
width = (300, 500)
frame_width = 0
font = Iosevka Nerd Font Mono 11
```
And this test notification:
```
dunstify "This is a notification with a long long line

Test"
```

**Comment by fwSmit** [comment]
Maybe @vincentbernat wants to take a look at this?

**Comment by pawel-szopinski** [comment]
I also have similar issue. It does not happen to all notifications, and sometimes even the exact same popup (same content) is  displayed correctly and another time not. 

You can also notice that border widths are not identical on all sides (this also happens randomly).

My xft.dpi is 154 (which means fractional scaling of 1.6) and screen resolution is 3072x1920.

Relevant settings in dunstrc:
width = (0, 300)
height = 1800
scale = 0
frame_width = 2

Here's the screenshot:
![gscreenshot_2021-05-22-160805](https://user-images.githubusercontent.com/25465830/139922731-fed86767-2f3f-443f-bd7d-26ad42ac49a8.png)

**Comment by fwsmit** [comment]
I've posted a PR that might solve this issue. Could you test if this works?

**Comment by fwsmit** [comment]
I also noticed that trying to close notifications with the mouse doesn't work quite well on x11 when scaled. Do you experience the same issue?

**Comment by vpont** [comment]
It looks like it's working!

![screenshot](https://i.imgur.com/4bLbiSa.png)

**Comment by vpont** [comment]
> I also noticed that trying to close notifications with the mouse doesn't work quite well on x11 when scaled. Do you experience the same issue? Edit: I've also posted a fix for that. Would be nice if you could test that as well.

It was working fine before the fix for me.

**Comment by fwsmit** [comment]
> It was working fine before the fix for me.

Is it still working with the fix? 

Before the fix I was able to close notifications with the mouse, but the intersection calculation was as if the notifications were unscaled. So if you have 2 notifications and click on the bottom part of the top notification, the bottom one would close.

**Comment by vpont** [comment]
> Before the fix I was able to close notifications with the mouse, but the intersection calculation was as if the notifications were unscaled. So if you have 2 notifications and click on the bottom part of the top notification, the bottom one would close.

I see, yes, I could reproduce that behaviour. It's fixed now.

**Comment by fwsmit** [comment]
Thanks. I'll close this issue now

**Comment by yoarch** [comment]
> Right, with `scale = 2` the issue is not there anymore.

Fixed the problem too.
