### ISSUE TITLE
No "fit to screen width" notification width option since 1.7.0

### ISSUE THREAD

**Issue by milaq** [dunst-project/dunst#951]
Hi all and thanks to the project maintainers for the awesome work on dunst!

Since the deprecation of `geometry` (which came with no futher warning btw - would have been nice to keep it for a version or two to not set *all* configs on fire) there is no option to have the notification width to fill the screen horizontally.
With `geometry` , there was the option to omit the width to fill the screen ("If the width is omitted but the height is given ("-geometry x2"), the message window expands over the whole screen [...]").

I tried setting an arbitrarily high `width` but that leads to the notification bleeding into the next screen (X11) in multi-monitor setups even though correctly centering the notification text.
Is there any new setting that I overlooked?

**Comment by milaq** [comment]
Hey again

sorry for the delay, I was pretty involved with RL recently.

As a first fix I implemented #973 to fix the notification bleeding into other screens.
This was most probably introduced with 208b967c37d82aa7eb072aa6a54a710a7dd16c51.
For now under X11 it works as before if one sets the width to an arbitrarily high value, say `10000`.

What needs to be done would be a range setting as you described, i.e. `(0,)`.
I took a quick look at the settings parsing code in `option_parser.c` and `settings.c`. An implementation of omitting the value would need adjustments in the length struct and int parsing, as a null value is evaluated as `-1` automatically. This then goes haywire with the min/max logic in the notfication width calculation in `draw.c`.

But for now, maybe the clamp width fix should be sufficient for most cases.
What I deem more important would be the correct implementation of `get_active_screen` under Wayland.

I'll have a look at the parsing logic once I have a tad more free time :)

**Comment by fwsmit** [comment]
> Hey again
> 
> sorry for the delay, I was pretty involved with RL recently.
> 
> As a first fix I implemented #973 to fix the notification bleeding into other screens. This was most probably introduced with [208b967](https://github.com/dunst-project/dunst/commit/208b967c37d82aa7eb072aa6a54a710a7dd16c51). For now under X11 it works as before if one sets the width to an arbitrarily high value, say `10000`.

Thank you! 

> 
> What needs to be done would be a range setting as you described, i.e. `(0,)`. I took a quick look at the settings parsing code in `option_parser.c` and `settings.c`. An implementation of omitting the value would need adjustments in the length struct and int parsing, as a null value is evaluated as `-1` automatically. This then goes haywire with the min/max logic in the notfication width calculation in `draw.c`.

Actually, `(0, )` or even `(,)` will result in a range of 0-INT_MAX. We only don't have a way to signal that you want a constant width of INT_MAX (up until the width of your screen).

**Comment by milaq** [comment]
I thought about using `-1` too but that would exclude negative values for a `length` setting in future usages, right?

**Comment by fwsmit** [comment]
Fixed by #973
