### ISSUE TITLE
Micro stutters during video games

### ISSUE THREAD

**Issue by fuzunspm** [dunst-project/dunst#962]
Hi,

I don't know how to debug this so I'm creating an issue. While video gaming (does not matter which game it's) notifications are causing micro stutters. I have a very basic configuration of dunst, just the text no icon or anything

Regards

### Installation info

- Version: 1.7.0 (2021-10-19)
- Install type: pacman
- Distro and version: Latest and updated Arch Linux

**Comment by fwSmit** [comment]
This is most likely not fixable by Dunst. Instead its a problem of your window manager or graphics drivers

**Comment by fwsmit** [comment]
Closing, as there is no actionable info
