### ISSUE TITLE
Click box wrong when using DPI scaling on X11

### ISSUE THREAD

**Issue by nikola-kocic** [dunst-project/dunst#966]
When DPI scaling is used on X11, notification cannot be dismissed when clicked on the lower part of it.
Downgrading to v1.7.0 fixes the issue, so the issue was probably introduced in the [input: make border or separator unresponsive to clicks](https://github.com/dunst-project/dunst/commit/9d0464df5546eb288383a544cf817d43f3a9084a#diff-4fdb31943fd145fd3cb67fd6bd0f7ce3e30f0887de4c3ab05e06fb5102d823c3) commit.

### How to reproduce
1. Change (or add) `Xft.dpi` to `192` in `${HOME}/.Xresources` (the line should look like this: `Xft.dpi: 192`)
2. Log out
3. Log in to the X11 session
4. Create a notification (e.g. `notify-send test`)
5. Try to click on the lower part of the notification to dismiss (it doesn't work)

### Installation info

- Version: `1.7.1 (2021-11-01)`
- Install type: `package`
- Distro and version: ` Latest and updated Arch Linux`

**Comment by fwsmit** [comment]
I already found this issue when investigating another issue and fixed it in #965. The mouse position does not scale automatically with the scale like it does on wayland. So I manually applied that there.
