### ISSUE TITLE
Which parameters can be set through urgency?

### ISSUE THREAD

**Issue by indeedwatson** [dunst-project/dunst#967]
Based on default config, a few parameters can be overridden through the urgency feature. However, it's not clear which. For example I can't change the origin or the timeout through urgency. There seems to be no documentation in the man pages about urgency, it's not even clear to me what it is for.

Is there simply no way to have different notifications show up in different places on the screen?

**Comment by indeedwatson** [comment]
nevermind, i found it online https://dunst-project.org/documentation/

it begs the question tho why my local man pages don't display this information

**Comment by fwsmit** [comment]
What distro are you using?
