### ISSUE TITLE
Can not remove border

### ISSUE THREAD

**Issue by tkkcc** [dunst-project/dunst#969]
### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.7.1 (2021-11-01)`
- Install type: `package`
- Distro and version: `archlinux`

```txt
[global]
    origin=top-center
    offset=0x0
    font=monospace 18
    alignment=center
    max_icon_size=0
```
With above `dunstrc`, and `dunstify 22222`, I got this

![image](https://user-images.githubusercontent.com/17373509/140889372-610e8274-e37d-4dcf-851f-c600e3e04583.png)

Here the border and padding is what I want to remove, but I have no way to do this, as `border` and `padding` both default to zero.

The same config for 1.6.1 gives me:
![image](https://user-images.githubusercontent.com/17373509/140907504-fcc3b56f-617c-42eb-802c-72ab33608e5b.png)
which is less padding and borderless.

**Comment by fwsmit** [comment]
What happens if you manually set the border and padding to 0?

**Comment by tkkcc** [comment]
Actually there is no `border` option, my mistake. After I set `padding=0` and `horizontal_padding=0`(both default to zero in `man 5 dunst`), the appearance is closer to 1.6.1, but border is still. 
![image](https://user-images.githubusercontent.com/17373509/141233085-024bd361-6368-4745-9767-751ac6ded120.png)

**Comment by fwsmit** [comment]
You're looking for the `frame_width` variable. The default might have changed in a recent version. I've updated the default values in the man page.
