### ISSUE TITLE
Elapsed time (age) configuration

### ISSUE THREAD

**Issue by aksr** [dunst-project/dunst#97]
Hi knopwob,
**Thank you** for dunst.
Since _almost_ everything in dunst is configurable, 
it would nice if  elapsed time (_age_) color is configurable.
The thing that bothers me now is that, elapsed time looks like a part of the body of notification, mainly because it's the **same** color. I think its _optional_ position should be defined in format (for example: **_%t**_). I'm not sure if it's possible to implement.
Also, it would be nice if parentheses where configurable (with/without them or to change them to something else ( **[ ] { }** etc.), this, also would be definable in format..
**_Gradition of the elapsed time**_ would also be nice (for example: _green <60s, yellow >60s, red >500s_ or something like that).

Thank you.

**Comment by bynect** [comment]
maybe an age_threshold_format can be added to customize it ?

Also somewhat related to #509
