### ISSUE TITLE
Making the deprecation of `[shortcuts]` for dunstctl more informative

### ISSUE THREAD

**Issue by zaeph** [dunst-project/dunst#974]
Hi folks,

With the recent deprecation of `[shortcuts]`, I had to go fishing for information to figure out what had changed.  The manual for `dunst` does not mention the words “shortcut” or “bind” anymore, and the closest we get to informing the user is with the deprecation message.

https://github.com/dunst-project/dunst/blob/master/src/utils.c#L357-L360

https://github.com/dunst-project/dunst/blob/master/src/option_parser.c#L435-L438

Could we turn the elements in `deprecated_sections` into `{ name, info }` arrays where `info` points you to a relevant manual, and modify `save_settings` accordingly?

I'm not sure how much energy we want to put into making informative deprecation; but if I run into it, others are likely to do the same, and it'd be a shame to get them started on the wrong foot with `dunstctl`.

Thanks for your work on the recent iterations!

**Comment by fwsmit** [comment]
I agree that it could be more clear. It's not so hard to implement a custom message. What do you think the deprecation message should say?
I can also add a message in the man page about recent deprecations.

**Comment by zaeph** [comment]
Sorry for having you do this; I originally wanted to PR, but I'm not familiar enough with C to make anything robust.

In my attempt, I added the following line between `WARNING: Section shortcuts is deprecated.` and `Ignoring` (i.e. the value of `info` in the array I proposed):
```
Acting on notifications has been moved to its own utility.  For more information, see the manual for dunstctl.
```

For the `dunst` manual, we could append the following section to the `Miscellaneous` section:
> Dunst used to provide shortcuts to act on notifications via key-bindings, but it has now been moved to its own utility.  For more information, see the manual for dunstctl(1).

Thank you for taking care of this!

**Comment by fwsmit** [comment]
Thanks, I've implemented in a quick and dirty way.

**Comment by amithm7** [comment]
Is this removal or deprecation of `[shortcuts]` config?

Although I welcome this change, if this is removal, shouldn't it have been in v2.0.0 and not v1.7.0 since it's not backwards compatible.

**Comment by fwsmit** [comment]
You can set shortcuts in the global section
