### ISSUE TITLE
Notification text cut up on some settings

### ISSUE THREAD

**Issue by Tokariew** [dunst-project/dunst#975]
### Installation info

- Version: `1.7.1`
- Install type: `package`
- Distro and version: `Fedora 35 `

For some notification, dunst cut off some height of the last line of text. For example such as from it:
`dunstify 'FeedMe' 'synchronize complete: 561 unread article(s), including 0 new article(s).'`

Minimal config to reproduce:
```
[global]
width = (0, 300)
font = Fira Code 14
icon_position = left
min_icon_size = 32
max_icon_size = 32
```
Minimum icon set is set up so, the problem is reproducible.
And screenshot with error:
![feedme_fail](https://i.imgur.com/pYRaJIU.png)

Changing width to something greater will fix it, but probably some other notification text will be cut up…

**Comment by fwsmit** [comment]
Hi, this issue should be fixed in https://github.com/dunst-project/dunst/pull/965.

**Comment by Tokariew** [comment]
yes, #965 fix this issue
