### ISSUE TITLE
Notifications are really big despite no conifg changes

### ISSUE THREAD

**Issue by Peter-Crawley** [dunst-project/dunst#976]
![image](https://user-images.githubusercontent.com/49043380/141681921-1a258137-c0bc-4108-ba35-d0562209ef2f.png)

There config is whatever the default config is, I can not find any reason for this to occur.

### Installation info

- Version: 1.7.1
- Install type: Pacman
- Distro and version: Arch Linux

**Comment by fwsmit** [comment]
Are you using X11 or Wayland?
If you're using X11, this is likely because of your screen DPI. Dpi scaling was implemented in #890. You can change the DPI with `xrandr --dpi 96`. This will result in a scale of 1. Alternatively you can set `scale = 1` in your dunstrc.

**Comment by Peter-Crawley** [comment]
I tried the command you sent, this seems to have fixed the issue.
Thanks.
