### ISSUE TITLE
shortcut/dunstctl/windows manager

### ISSUE THREAD

**Issue by jas01** [dunst-project/dunst#979]
Really sorry to create a issue, when it's not really a issue. 
Don't hesitate to close/delete this issue.
I try the freenode but it's not working.., don't see any mailing-list so...

Well I'm trying to understand how to use dunstctl in a window_manager (i3 for me). I find a little annoying to do that in a shell

What's the best way to use it ? Do you create a shortcut in the window_manager to launch dunstctl ?

**Comment by fwsmit** [comment]
> Do you create a shortcut in the window_manager to launch dunstctl ?

Yes

**Comment by jas01** [comment]
> > Do you create a shortcut in the window_manager to launch dunstctl ?
> 
> Yes

Thanks you
