### ISSUE TITLE
`close_current` does not work `mouse_left_click` since Dunst 1.7.0

### ISSUE THREAD

**Issue by jwflory** [dunst-project/dunst#980]
## Installation info

- Version: `1.7.1`
- Install type: `package`
- Distro and version: `Fedora Linux 35`
- DE: `i3 version 4.20 (2021-10-19)` (no compositor)

Since upgrading to v1.7.0 and updating my Dunst config file to be compatible with new changes, a left-click from the mouse does not close a notification from the screen. However, a right-click does work (as well as closing all the notifications on the screen). I manually set `mouse_left_click = close_current` in my `dunstrc`, but I did not change any mouse control settings when updating my config file for being compatible with 1.7.0. Most of what I changed to update was geometry settings.

I wasn't sure how best to reproduce this error or make it easier to debug. Let me know if I can provide more context.

## Config

```cfg
# See dunst(5) and /etc/dunst/dunstrc for all configuration options

[global]
	### Display ###
	monitor = 0
	follow = mouse
	indicate_hidden = yes
	transparency = 0
	separator_height = 2
	padding = 8
	horizontal_padding = 8
	text_icon_padding = 0
	frame_width = 3
	frame_color = "#6600cc"
	separator_color = frame
	sort = yes
	idle_threshold = 120


	### Geometry ###
	width = (0, 650)
	height = 400
	origin = bottom-right
	# Offset from the origin
	offset = 7x56
	scale = 0
	notification_limit = 5


	### Progress bar ###
	# Turn on the progess bar. It appears when a progress hint is passed with
	# for example dunstify -h int:value:12
	progress_bar = true

	# Set the progress bar height. This includes the frame, so make sure
	# it's at least twice as big as the frame width.
	progress_bar_height = 10

	# Set the frame width of the progress bar
	progress_bar_frame_width = 1

	# Set the minimum width for the progress bar
	progress_bar_min_width = 150

	# Set the maximum width for the progress bar
	progress_bar_max_width = 300


	### Text ###
	font = Cantarell 10
	line_height = 0
	markup = full
	alignment = left
	vertical_alignment = center
	show_age_threshold = 60
	ellipsize = middle
	ignore_newline = no
	stack_duplicates = true
	hide_duplicate_count = false
	show_indicators = yes

	# The format of the message.  Possible variables are:
	#   %a  appname
	#   %s  summary
	#   %b  body
	#   %i  iconname (including its path)
	#   %I  iconname (without its path)
	#   %p  progress value if set ([  0%] to [100%]) or nothing
	#   %n  progress value if set without any extra characters
	#   %%  Literal %
	# Markup is allowed
	format = "<b>%s</b>\n%b"


	### Icons ###
	icon_position = left
	min_icon_size = 0
	max_icon_size = 64
	icon_path = /usr/share/icons/gnome/256x256/status/:/usr/share/icons/gnome/256x256/devices/


	### History ###
	sticky_history = yes
	history_length = 20


	### Misc/Advanced ###
	dmenu = /usr/bin/dmenu -p dunst:
	browser = /usr/bin/xdg-open
	always_run_script = true
	title = Dunst
	class = Dunst

	# Define the corner radius of the notification window in pixel size.
	corner_radius = 25


	### Mouse controls
	mouse_left_click = close_current
	mouse_middle_click = do_action
	mouse_right_click = close_all


# Experimental features that may or may not work correctly. Do not expect them to have consistent behaviour.
[experimental]
	# Calculate the dpi to use on a per-monitor basis.
	# If this setting is enabled the Xft.dpi value will be ignored and instead dunst will attempt to calculate an
	# appropriate dpi value for each monitor using the resolution and physical size. This might be useful in setups
	# where there are multiple screens with very different dpi values.
	per_monitor_dpi = true


[urgency_low]
	background = "#222222"
	foreground = "#888888"
	timeout = 10
	# Icon for notifications with low urgency, uncomment to enable
	#icon = /path/to/icon

[urgency_normal]
	background = "#285577"
	foreground = "#ffffff"
	timeout = 10
	# Icon for notifications with normal urgency, uncomment to enable
	#icon = /path/to/icon

[urgency_critical]
	background = "#900000"
	foreground = "#ffffff"
	frame_color = "#ff0000"
	timeout = 0
	# Icon for notifications with critical urgency, uncomment to enable
	#icon = /path/to/icon

# vim: ft=cfg
```

**Comment by biopsin** [comment]
Nope no issue here on 1.7.1, could you possibly test something like
`mouse_left_click = do_action, close_current`

**Comment by jwflory** [comment]
@biopsin I tried changing `mouse_left_click` to that, and no change. While trying this, I also found that `do_action` is not working for me anymore either, with both `mouse_left_click` and `mouse_middle_click`. 🤔 

However, I did change `mouse_left_click` to `close_all` and that _did_ collapse notifications. So it seems to be an issue with `do_action` and `close_current` behavior specifically.

**Comment by fwsmit** [comment]
Could you try the latest commit? Some X11 hidpi fixes were merged after 1.7.1

**Comment by biopsin** [comment]
@jwflory after some testing I can confirm some actions dont while spesified with -A do, but I agree something is broken here.

**Comment by jwflory** [comment]
Latest commit does fix this issue for me! 👍🏻 I highly recommend creating a bugfix release for the Linux distros to pick up for their system packages.

**Comment by biopsin** [comment]
Weird, even after updating to latest commit and reloading dunst, it still wont open
`dunstify "TIME" "<a href=\"https://time.is\"></a>\nOPEN BROWSER"`
And my earlier post is wrong as i have codeblock after -A , so I did not notice anything wrong at the time.

**Comment by fwsmit** [comment]
> Weird, even after updating to latest commit and reloading dunst, it still wont open `dunstify "TIME" "<a href=\"https://time.is\"></a>\nOPEN BROWSER"` And my earlier post is wrong as i have codeblock after -A , so I did not notice anything wrong at the time.

Make sure you have `xdg-open` installed or set `browser` to your preferred browser.

**Comment by mmirus** [comment]
Thank you for all your work! Would it be possible to tag a bugfix release so that the fix for this makes it to packages?

**Comment by fwsmit** [comment]
Yes, I'll release one when I have time

**Comment by fwsmit** [comment]
Dunst v1.7.2 is released

**Comment by mmirus** [comment]
Thank you very much!

**Comment by jwflory** [comment]
Thanks for getting this all resolved! 🎉
