### ISSUE TITLE
Add possibility to send a notification without a summary

### ISSUE THREAD

**Issue by isak102** [dunst-project/dunst#982]
As far as I know there's no possibility to send a notification without a title (or summary as it's called) and I find this very weird since you can't use HTML formatting on the summary but you can on the body, so being forced to have a title when you want to do some HTML formatting on the notification seems counter intuitive. Is it possible to add this feature in the future? Thanks :)

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.7.1 (2021-11-01)`
- Install type: `package`
- Distro and version: `ArchLinux 5.15.2-arch1-1`

**Comment by m-bartlett** [comment]
An alternative to achieve this is to make a rule that omits the summary for the sort of notification you like.

For example in your dunstrc:
```ini
[my_rule]
    category="my_category"   # Match criteria
    format="%b"  # only show body (%b) and not summary (%s)
```

Then (after reloading dunst) you can do:
```
$ notify-send -c my_category "this summary won't be shown!" "this body will be shown"
```
and get:

![image](https://user-images.githubusercontent.com/85039141/142802063-ee55a40f-0ed2-40fb-b47a-213a5baaf885.png)

You can also put a similar `format=...` entry in the `[global]` section if you want that by default. This doesn't absolve the need to provide a summary in any tools that use libnotify (e.g. `notify-send`, `dunstify`) but it at least makes the summary content negligible.

**Comment by fwsmit** [comment]
> An alternative to achieve this is to make a rule that omits the summary for the sort of notification you like.

Seems like a good solution.

> You can also put a similar `format=...` entry in the `[global]` section if you want that by default. This doesn't absolve the need to provide a summary in any tools that use libnotify (e.g. `notify-send`, `dunstify`) but it at least makes the summary content negligible.

If that's a big problem you can circumvent this by creating a shell alias or something.

I'll close this issue as there is a good solution
