### ISSUE TITLE
HiDPI issue with clicking on notifications

### ISSUE THREAD

**Issue by mattfbacon** [dunst-project/dunst#986]
The cursor position is recognized as twice as low as it actually is when I have 2x scaling (192 DPI). That is, the first notification can only be clicked in its top half, while clicking the bottom half will click the next notification. This effect continues as more notifications stack, resulting in me having to click half as low as the notification actually is.

This seems to be a regression because I didn't use to have this issue even with HiDPI.

### Installation info

- Version: `1.7.1`
- Install type: `Package`
- Distro and version: Arch Linux

**Comment by fwsmit** [comment]
This is fixed in master. Unfortunately I haven't had the time to make a release

**Comment by fwsmit** [comment]
The fix is released in v1.7.2
