### ISSUE TITLE
Default follow value is not working

### ISSUE THREAD

**Issue by DusanLesan** [dunst-project/dunst#990]
I have issue when removing follow entry or commenting it out like `# follow = keyboard`. The documentation states: 
> follow (values: [none/mouse/keyboard] default: none)

The default does not seem to work. The app behaves like using `follow = keyboard` when there is no follow value. 
Please fix the dafault = none

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.7.1 (2021-11-01)`
- Install type: `package`
- Distro and version: `arch 5.15.5-arch1-1`

**Comment by fwsmit** [comment]
Can you describe what not works when you comment this part out.
I also need a bit more info, namely your desktop environment and a minimal dunstrc needed for replication

**Comment by DusanLesan** [comment]
@fwsmit When I comment out the follow entry, the dunst will not behave like it is using default value.
I am using dwm
Minimal dunstrc to reproduce:
```
[global]
    monitor = 0
```
Since the default value for follow is `none`, the below dunstrc should behave exactly the same as above one:
```
[global]
    monitor = 0
    follow = none
```
The `none` value is default and including it was not required before. Since I am commenting out entries from a script to get default behavior, I would like to have default value working.

**Comment by fwsmit** [comment]
It seems like the default value now is `mouse`. I changed it back to `none`, since that was the default in v1.6.1. The commit is now in master (3a40b5e9f54323553ee5be73224e61027549ae45).
Thank you for your bug report
