### ISSUE TITLE
Bring  back keybindings in dunstrc

### ISSUE THREAD

**Issue by saevarb** [dunst-project/dunst#993]
Hello.

After upgrading my system, I discovered that dunst had changed significantly right under me and that I now need `dunstctl` to control it. 
When it was possible to configure the keybindings to close popups inside dunstrc, those keybindings would also work in all sorts of other contexts. I used ctrl-space, and I also used this to start auto-completion in emacs. No issues with these overlapping generally -- in fact it's really quite useful.

The current situation means that I now need to my WM to invoke `dunstctl` which means that it eats the keybinding and I can't use it for anything else, so I'd have to pick a new keybinding.

What would be required to bring back passive listening to keybindings as it was, and what is the reason this functionality was removed? 

I also tried looking through the commit history to find the right place to fork dunst so that I don't have to bother with these changes that have zero use for me, but it wasn't very clear to me which one would be best to choose. Is there a specific commit you recommend?

**Comment by Narrat** [comment]
The removal was done with https://github.com/dunst-project/dunst/pull/803
As for the reasons: see for example this [comment](https://github.com/dunst-project/dunst/issues/940#issuecomment-950305620)

**Comment by fwsmit** [comment]
Thanks for answering, narrat. To exactly mimic the old behaviour, you can also do something like this: https://github.com/dunst-project/dunst/issues/978#issuecomment-970142969
