### ISSUE TITLE
Disable Dunst icons

### ISSUE THREAD

**Issue by huyhoang8398** [dunst-project/dunst#995]
Cannot disable icon with `icon_position = off`

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.7.2 (2021-11-30)`
- Install type: `pacman package`
- Distro and version: ` Archlinux 5.15.6-arch2-1`

**Comment by fwsmit** [comment]
Could you send your dunstrc?

**Comment by fwsmit** [comment]
Turns out, I accidentally patched out that behaviour. It's fixed in #996.
