### ISSUE TITLE
Lack of documentation for breaking geometry change in 1.7.0

### ISSUE THREAD

**Issue by Juraci** [dunst-project/dunst#999]
### Issue description

In the `1.7.0` release there was a breaking change that made `geometry` related configurations stop working.

```
- geometry has been replaced by origin, width, height, offset and
notification_height. This allows for more flexible geometry settings. (#855)
```

There is no example in the release notes (or any other place) on how the user should migrate an existing configuration to the new format while keeping the same settings.

I can understand breaking changes on the APIs, but I wish there was some documentation to help the users migrate to the newer configuration for those of us that do not work with Dunst on a daily basis as it might not be so obvious.  

### Installation info

- Version: `1.7.1`
- Install type: `package`
- Window manager / Desktop environment: `i3 gaps`

<details>
<summary>Minimal dunstrc</summary>

```ini
# Dunstrc here
```
</details>

**Comment by fwsmit** [comment]
I agree this could have been more extensive. What do you think is the best way to fix it now, though? Should the release notes be improved or the man page maybe?

**Comment by Juraci** [comment]
@fwsmit I think either the release notes and/or the man page are good options. A short note on how to migrate from the old config to the new and where each old param should go in the new format will suffice.

**Comment by fwsmit** [comment]
I've added a note about it on the man page: 8855f77291e7e6ece59afdcbb6dca578a2718032

**Comment by fwsmit** [comment]
Does that suffice? Obviously, people won't see it in dunst until the next releaes or until they read the release notes.

**Comment by Juraci** [comment]
@fwsmit I think that should be enough, people having this problem might arrive in this issue which contains the link. 

Thank you for that.

**Comment by vincentbernat** [comment]
I don't remember what `height` was supposed to be with the geometry notation, but it seemed it was a number of lines. Now, it is a number of pixels. However, trying again with an old version, it seems that height was a minimal height and not a maximum one? Now, this is a maximum one and the notification is truncated and the icon is not centered anymore. Maybe `height = 0` should be infinite?
